ROADMAP.md
=> docs(*): add ROADMAP.md

README.md
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
=> docs(README): Add SMI Traffic Metrics status

README.md, docs/development_guide.md
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
=> docs(README): Fix broken links

docs/development_guide.md
Updates the Helm section in the development guide.
=> docs/development_guide: update Helm chart guide

docs/patterns/certificates.md
Update relative paths for wiki links
=> docs(patterns/certificates): update relative paths for wiki links

cmd/cli/mesh.go
=> fix typo unique

demo/reset-counters.sh, docs/example/README.md, scripts/port-forward-all.sh
Run the commands in background and wait on them instead.
=> scripts/demo: remove dependency on GNU parallel

README.md
=> remove check refs in README

README.md
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
=> docs(README): Add projects of inspiration

demo/README.md
Adds prerequisite for linux or WSL2 base with gcc
=> docs(demo/readme): update OS requirements for demo

cmd/cli/env.go, cmd/cli/mesh.go, cmd/cli/mesh_delete.go, cmd/cli/namespace.go, cmd/cli/namespace_add.go, cmd/cli/namespace_list.go, cmd/cli/namespace_remove.go, cmd/cli/version.go, pkg/cli/environment.go
+ give proper attribution to helm project
+ update namespace flag description
+ use cobra instead of helm require pkg
=>  ref(*): update env related files 

.github/pull_request_template.md
Adds a pull request template to make pull request descriptions
more consistent and to help understand their scope.
=> github/template: add pull request template

README.md
=> ref(README): update attribution section

cmd/cli/install.go, cmd/cli/install_test.go
Fixes #1441
No. This code just uses the client-go API
=> fix(osm/cli): Fail when namespace already contains osm-controller

docs/development_guide.md
This PR removes colloquialism from the dev doc.
=> docs: Remove colloquialism from dev doc

scripts/port-forward-bookstore-ui-v2.sh
the Pod of bookstore-v2 working on port 80
no
=> the Pod of bookstore-v2 working on port 80

cmd/cli/dashboard.go, cmd/cli/namespace_add.go, cmd/cli/namespace_remove.go, cmd/cli/namespace_test.go, pkg/certificate/providers/tresor/debugger_test.go, pkg/certificate/providers/vault/debugger_test.go, pkg/envoy/ads/stream.go, pkg/envoy/cds/response_test.go, pkg/envoy/lds/listener_test.go, pkg/envoy/proxy.go, pkg/envoy/xdsutil.go, pkg/metricsstore/metricstore.go
Fix typos which are mentioned in  https://goreportcard.com/report/github.com/openservicemesh/osm
no
=> Closes #1407 :  FIX commonly misspelled English Words.

docs/example/README.md
- Added git clone instructions to manual demo script.
@phillipgibson : as promised.
**No**
=> Updated manual demo

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/improvement---feature-request.md, .github/pull_request_template.md
Resolves #1479 
Resolves #1480 
Resolves #1481 
=> chore(*): update issue/PR templates

charts/osm/templates/osm-configmap.yaml, charts/osm/values.yaml, pkg/configurator/client.go, pkg/configurator/client_test.go, pkg/configurator/fake.go, pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/configurator/types.go, pkg/constants/constants.go, pkg/injector/config_test.go, pkg/injector/patch.go, pkg/injector/sidecar.go
Set Envoy sidecar log-level via OSM ConfigMap. Resolve #1232 
No
=> feat(pkg/*): Set Envoy sidecar log-evel via configMap

docs/patterns/ingress.md
Add Gloo integration docs for Ingress+OSM
=> Add Gloo Gateway to Ingress documentation

pkg/catalog/ingress_test.go, pkg/catalog/routes_test.go
Formats the files using `gofmt -s`
`No`
=> catalog: gofmt simplify

cmd/osm-controller/osm-controller.go
Uses osm-controller as the component name where applicable.
`No`
=> cmd/osm-controller: use osm-controller as the component name

charts/osm/Chart.yaml, charts/osm/values.yaml, cmd/cli/install.go
Update versions for release v0.3.0
=> chore(*): prep for v0.3.0 release

docs/patterns/ingress.md
Just a typo fixture
- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? no
=> fix typo in docs/patterns/ingress.md

README.md
Add statement of support
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
=> docs(README): Add support statements

charts/osm/Chart.yaml, charts/osm/templates/grafana-deployment.yaml, charts/osm/templates/prometheus-deployment.yaml, charts/osm/templates/zipkin-deployment.yaml, charts/osm/values.yaml
* change ImagePullPolicy on all Deployments to IfNotPresent
* remove default imagePullSecrets, user can add imagePullSecrets
manually if required
Thanks @stefanprodan for pointing these bits out!
=> fix(*): update chart values and metadata

pkg/envoy/proxy.go
Delete unused methon on the Proxy struct.
=> envoy: Delete unused GetService

pkg/logger/logger.go
Small refactor to simplify the instantiation of new Zerolog loggers.
- Other                  [ x ]
=> logger: Simplify logger instantiation

charts/osm/templates/osm-deployment.yaml, charts/osm/values.yaml, cmd/cli/install.go, cmd/cli/install_test.go
=> ref(cmd/cli): update imagePullSecret value

pkg/endpoint/providers/kube/client_test.go
=> kube/test: fix spelling

pkg/catalog/service.go, pkg/envoy/rds/response.go, pkg/envoy/route/config.go
This PR removes empty slice allocations.
---
- Control Plane          [ x ]
=> Remove empty slice allocations

charts/osm/Chart.yaml, charts/osm/README.md
This PR updates the OSM Chart README.md file in order to describe the latest chart values and defaults.
+ generated using https://github.com/norwoodj/helm-docs
+ also updates the chart description
=> chore(charts): update osm chart README

pkg/kubernetes/util_test.go
=> ref(pkg/kubernetes): rm import comment

pkg/featureflags/featureflags_test.go, pkg/featureflags/suite_test.go
Partially addresses: #1489
Increase test coverage for pkg/featureflags
No
=> test(featureflags): Add featureflags test

pkg/namespace/client.go, pkg/namespace/client_test.go, pkg/namespace/suite_test.go, pkg/smi/client_test.go
Add tests for pkg/controller
Partially addresses: #1489 
No
=> test(pkg/namespace): Add tests for namespace controller

charts/osm/grafana/dashboards/osm-mesh-envoy-details.json
- Number and list of Namespaces on the mesh
- Number and list of Services on the mesh
- Number and list of Pods on the mesh
- Envoy:
- Malloc data
- Heap (virt mem) data
- Physical (RSS?) mem data
- CPU consumption on Envoy containers
No
=> Add Mesh & Envoy Details dashboard

pkg/envoy/route/config.go
* removed unused constants
* update case for constants to match comment
=> ref(pkg/envoy/route): clean up constants

pkg/featureflags/featureflags.go, pkg/metricsstore/types.go
=> ref(*): cleanup unused log variables

demo/cmd/common/books.go
Use random URLs when testing egress to avoid throttling
No
=> test: Use random URLs for testing egress

.env.example, charts/osm/values.yaml, cmd/cli/install.go, cmd/cli/install_test.go, demo/run-osm-demo.sh
Disable Grafana by default.
Partially address #1599 
No
=> feat(grafana): Disable Grafana by default

charts/osm/README.md, docs/development_guide.md, docs/patterns/observability.md
Forgot to edit documentation in my previous PR for decoupling Grafana from Prometheus, so doing that here. 
=> Documentation for Prometheus and Grafana installation flags

demo/clean-kubernetes.sh
Run kubectl in parallel and wait for all of them to return.
`--wait` [waits for resources to be gone](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands)
No
=> Speedup cleanup

pkg/catalog/endpoint.go, pkg/catalog/errors.go, pkg/endpoint/providers/kube/client.go, pkg/endpoint/providers/kube/client_test.go, pkg/endpoint/providers/kube/errors.go, pkg/endpoint/providers/kube/fake.go, pkg/endpoint/types.go
Due to a hard dependency, we leaked some of the implementation
details to catalog.
We have recently fixed some of the constraints that forced this
implementation, and now can be decoupled and resolved.
No
=> Moving GetResolvableEndpoints to Providers

cmd/cli/metrics_test.go
Improves test coverage by testing enable/disable
metrics commands against resulting metrics scraping
annotations configured on pods.
Part of #1016
`No`
=> cli/metrics: test metrics annotations on pods

cmd/cli/namespace_add.go, cmd/cli/namespace_test.go
Please describe the motivation for this PR and provide enough information so that others can review it.
Refer to #1727 
No
=> Fix when enableSidecarInjection=false, the annotation is not removed.

charts/osm/Chart.yaml, charts/osm/values.yaml, cmd/cli/install.go
Updates the chart and container image versions used as a
part of v0.4.0 release.
=> charts: update chart and image version for v0.4.0 release (#1748)

charts/osm/Chart.yaml, charts/osm/values.yaml
* fixes installation of osm if you're just using helm
* certficateManager -> cerificateManager
=> fix(chart): fix certificateManager value

.github/pull_request_template.md
Updates the PR template and also adds a new area to track
performance improvements.
`No`
=> Update pull request template to split tests and CI checkbox

docs/release_guide.md
=> docs/release_guide: update release guide to reflect latest process

pkg/catalog/ingress_test.go, pkg/certificate/providers/certmanager/certificate_manager_test.go, pkg/certificate/providers/tresor/certificate_manager_test.go, pkg/configurator/client_test.go, pkg/envoy/ads/response_test.go, pkg/envoy/rds/response_test.go, pkg/smi/client_test.go
PR for issue: https://github.com/openservicemesh/osm/issues/1707
PR as part of the Hacktoberfest :)
- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? **no**
=> tests: use Ginkgo api for fatal error reporting

CODE_OF_CONDUCT.md, README.md
Relevant to https://github.com/openservicemesh/osm/issues/1730
Not applicable
=> Update code of conduct

go.mod, pkg/catalog/routes_test.go
Refactor ginkgo tests to use Go test and testify
No
=> test(routes): Convert ginkgo tests to go test

.github/workflows/release-chart.yml
**Description**: Backporting #1802 to the release-v0.4 branch
No
=> fix(release): update chart release tag match (release-v0.4 backport)

demo/deploy-smi-policies.sh, demo/reset-counters.sh, demo/reset.sh, scripts/port-forward-bookbuyer-ui.sh, scripts/port-forward-bookstore-ui-v1.sh, scripts/port-forward-bookstore-ui-v2.sh, scripts/port-forward-bookthief-ui.sh
Running the demo today I ran into a few scripts that needed fixing.  This PR addresses these.
=> demo: Fixes

ROADMAP.md
Update ROADMAP.md with latest information
-->
- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? NO
=> ref(ROADMAP): update ROADMAP with latest info

.github/ISSUE_TEMPLATE/improvement---feature-request.md
**Description**: Labels listed in issue/PR templates are case sensitive. This change updates the "improvement / feature request" label with the correct casing so the label is added for new issues.
- Other                  [X] (repo maintenance) …
=> fix(issue template): update label name

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go
Updating references to 0.4.2 on charts, install and values
=> Update refs to v0.4.2

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go
=> Update to v0.4.2

pkg/tests/fixtures.go
Fixes comment typo for Bookstore v2 service name
No
=> test(fixtures): Fix typo

go.sum
=> Go-tidy fix

cmd/cli/dashboard.go
In favor of error returns and stdout for logging.
Addresses #1848
No
=> cli/dashboard: Amending use of fatals and log

cmd/cli/dashboard.go
Simplifies channel receiving by removing an unnecessary select
on the channel.
`No`
=> cli/dashboard: remove unnecessary select on channel

tests/e2e/e2e_certmanager_test.go
https://github.com/openservicemesh/osm/issues/1880
=> (e2e, CI) Skip cert-manager

charts/osm/templates/fluentbit-configmap.yaml, docs/patterns/observability/logs.md
**Description**: Updates the Fluent Bit regex to filter more strictly on key/value pair for log level
No
=> fix(logs): Update Fluent Bit regex to filter log level

charts/osm/Chart.yaml, charts/osm/values.yaml, cmd/cli/install.go
**Description**: Update tags for release v0.5.0-rc.1
=> Updates tags in charts

tests/e2e/e2e_pod_client_server_test.go
This PR contains a tiny refactors of `e2e_pod_client_server_test.go` to carve out a function `setupSource()`, which creates the source pod.
This introduced a boolean flag, which controls whether we create a Kubernetes Service for the source pod (or not).
No functional code changes in this PR (except for the addition of `if withKubernetesService {`)
This is a step forward towards making an end to end test for https://github.com/openservicemesh/osm/pull/1932 and https://github.com/openservicemesh/osm/issues/1946
--- …
=> e2e: Carve out a helper function creating a source mesh participant

pkg/endpoint/providers/kube/client.go
This PR removes the call to `IsMonitoredNamespace()` and does some small refactoring to add clarity.
We know that `IsMonitoredNamespace()` is costly.  We don't need to call this fn here because the Pod and the ServiceAccount are in the same namespace.  The call for `GetServicesForServiceAccount(serviceAccount)` assumes here that `serviceAccount` has already been vetted as one being in a OSM-watched namespace.
- Performance …
=> endpoints: Refactor GetServicesForServiceAccount() to remove call to IsMonitoredNamespace and add clarity

.env.example, cmd/osm-controller/osm-controller.go, cmd/osm-controller/osm-controller_test.go, demo/run-osm-demo.sh, pkg/constants/constants.go, pkg/debugger/certificate.go, pkg/debugger/certificate_test.go, pkg/debugger/envoy.go, pkg/debugger/feature_flags.go, pkg/debugger/index.go, pkg/debugger/mock_debugger.go, pkg/debugger/namespace.go, pkg/debugger/namespace_test.go, pkg/debugger/policy.go, pkg/debugger/policy_test.go, pkg/debugger/port_forward.go, pkg/debugger/proxy.go, pkg/debugger/server.go, pkg/debugger/server_test.go, pkg/debugger/types.go, pkg/debugger/xds.go, pkg/httpserver/debugger.go, pkg/httpserver/debugger_test.go, pkg/httpserver/httpserver.go, pkg/httpserver/httpserver_test.go, scripts/port-forward-osm-debug.sh
Automate enableDebugServer to turn on/off debug server when ConfigMap is updated 
and resolves #1740
- New Functionality      [X ]
No
=> feat(osm/*) Automate enableDebugServer feature

pkg/envoy/proxy.go, pkg/envoy/xdsutil.go
Fixes linting issues caught by golint related to exported functions
not having comments.
`No`
=> envoy: fix linting issue related to exported function without comment

tests/scenarios/helpers.go
This PR improves some of the comments in the recently added test scenario.
=> tests/scenarios: Better comments

pkg/envoy/ads/stream.go
While debugging an issue with discovery requests for specific
resources not being responded to by the controller, adding
the resource names to the logs helped identify the potential
problem. Adding additional info to the logs will aid debugging. …
=> envoy/ads: add requested resource names to logs

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go
**Description**: This change updates tag references to v0.5.0 and updates the chart README.md with the latest values.
No
=> Cut v0.5.0

.golangci.yml, ci/cmd/maestro/kubernetes_tools.go, demo/cmd/common/books.go, pkg/cli/chart_source.go, pkg/health/health.go, tests/e2e/common.go
Enabling errCheck on the repository
Fixes : #2041 
=> Linter: Enabling errCheck Linter

charts/osm/Chart.yaml, charts/osm/values.yaml, cmd/cli/install.go, cmd/cli/install_test.go, go.mod, go.sum
**Description**: Follow-up from the v0.5.0 release to update the version refs to the new tag.
No
=> update tags to 0.5.0

charts/osm/templates/fluentbit-configmap.yaml, charts/osm/templates/mutatingwebhook.yaml, charts/osm/templates/osm-deployment.yaml, charts/osm/values.schema.json, charts/osm/values.yaml
Parameterize additional chart values
=> Chart changes with additional configurations

charts/osm/templates/fluentbit-configmap.yaml
One of the tests for fluent-bit that ran after I merged my previous chart to main failed, and I realized that I had a minor spelling error. 
=> Corrected Spelling in fluentbit configmap

charts/osm/templates/osm-service.yaml, tests/e2e/common.go, tests/e2e/e2e_debug_server_test.go
Adds e2e testing for enableDebugServer feature
and resolves #1910 
No
=> test(*): Add e2e test for enableDebugServer

pkg/envoy/lds/inmesh.go
Add more speficic comments for each field in the filter chain
match. The existing comment is incorrect with regards to
how the SNI is configured.
`No`
=> envoy/lds: add comments for specific filter chain match criteria

pkg/logger/logger.go
logger pretty printing not working.
=> fix logger pretty printing

CONTRIBUTING.md
Updated contributing.md with DCO guidance for contributors. Will be removing previous CLA agreement in branch rules.
=> Updated CONTRIBUTING.md from CLA to DCO

pkg/envoy/lds/rbac.go
This change uses the RBAC policy builder added by commit f20c7b58
to generate the policies. No functional change introduced apart
from additional error checking due to usage of a new api. …
=> envoy/lds: use rbac policy builder

charts/osm/README.md, charts/osm/templates/fluentbit-configmap.yaml, charts/osm/templates/osm-deployment.yaml, charts/osm/values.schema.json, charts/osm/values.yaml
**Description**: Updates Fluent Bit related values in charts and schema for cleanliness and clarity
No, no.
=> chore(fluentbit): Update and clean up Fluent Bit values and schema

pkg/envoy/lds/inmesh.go, pkg/envoy/lds/inmesh_test.go, pkg/envoy/lds/response.go, pkg/envoy/lds/response_test.go, pkg/envoy/xdsutil.go
Refactors code used to build the inbound HTTP filter chain
in preparation to support TCP filter chain.
Part of #1521
`No`
=> envoy/lds: refactor inbound filter chain building

pkg/trafficpolicy/trafficpolicy.go, pkg/trafficpolicy/trafficpolicy_test.go, pkg/trafficpolicy/types.go
This PR begins a stream of PRs for adding methods related to working with the new inbound/outbound traffic policy structs
* part of #2034
=> feat(*): add rules on inbound traffic policy

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go
=> Update chart tags and readme for 0.6.0

pkg/catalog/routes.go, pkg/envoy/cds/response.go
=> ref(pkg/envoy/cds): use proxy identity to build outbound services

pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/tests/fixtures.go
addresses https://github.com/openservicemesh/osm/pull/2173#discussion_r539468262
=> ref(pkg/catalog): add ListMeshServices method 

pkg/trafficpolicy/trafficpolicy.go, pkg/trafficpolicy/trafficpolicy_test.go
part of #2034
Signed-off-by: Michelle Noorali <michellemolu@gmail.com>
=> feat(*): add functions for merging traffic policies

pkg/trafficpolicy/trafficpolicy.go, pkg/trafficpolicy/trafficpolicy_test.go
* adds functions that help build new traffic policy
related objects
* part of #2034
reference #2187 to see how these will be used
=> feat(pkg/trafficpolicy): add constructor funcs

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go
=> release: update chart for v0.6.0

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go
=> release: update versions for release 0.6.0

pkg/injector/metrics.go
This PR fixes a misspelled word by removing it (it is redundant).
---
=> Fixing typo (removing word) from error log message

pkg/health/health.go
**Description**: Fixes a typo in liveness probe log messaging
no, no
=> fix(pkg): fix typo in health.go

pkg/envoy/lds/inmesh.go
Not so efficient after all, as we introduce ordering for deterministic endpoint
output to not have to juggle values in tests.
No
=> Changing linear search function to mapset

.gitignore
Removing duplicate lines from the .gitignore file
---
=> Remove duplicate lines from .gitignore

docs/release_guide.md
This change removes any confusing verbiage from the release guide about
the PR to update version refs on the main branch.
No
=> docs(release): clarify version update PR

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go
**Description**: Update versions in chart for v0.6.1 release
no, no
=> release: bump versions for 0.6.1 release

pkg/debugger/envoy.go, pkg/debugger/port_forward.go, pkg/envoy/ads/grpc.go
**Description**: Resolves #2313 
=> logging: change podIPs to UIDs in logs

pkg/injector/webhook.go
=> logging: remove raw object from logs

pkg/envoy/sds/response.go
=> logging: remove SANs from logs

CONTRIBUTING.md
Updates the contributing guide to reflect the updated pull request and 
review workflow.
Resolves #2347
Documentation …
=> contributing: update guide to reflect new pull request workflow

pkg/envoy/lds/ingress.go
This PR has a tiny tweak for an error message.
=> lds/ingress: Tweak error log message for clarity

pkg/catalog/routes.go
Minuscule change to the verbiage of a Trace log line
No functional code changes!
---
=> catalog: Tweak verbiage of log line

pkg/catalog/routes.go, pkg/catalog/routes_test.go
Added clarification to a log line.
Deleted an unused function
---
=> catalog: Small tweak verbiage of log line; Delete unused function

docs/troubleshooting/upgrade.md
Adds upgrade troubleshooting guide
No
=> docs(upgrade): Add upgrade troubleshooting guide

docs/content/docs/osm_config_map.md, docs/upgrade_guide.md
This documentation makes it easier for users to know how to create an override values file when performing an upgrade. …
=> docs(upgrade): Document mapping of ConfigMap and values file

docs/upgrade_guide.md
Helm upgrade does not install CRDs at all, so they. need to be manually created.
No
=> docs(upgrade): Include steps to recreate CRDs

pkg/configurator/validating_webhook.go, pkg/configurator/validating_webhook_test.go
Adds checks in the validating webhook to ensure the value
for the `outbound_ip_range_exclusion_list` field is as
expected.
Part of #2344
Examples:
```
kubectl patch ConfigMap osm-config -n osm-system -p '{"data":{"outbound_ip_range_exclusion_list":"54.164.234.192/32"}}' --type=merge
configmap/osm-config patched
```
```
$ kubectl patch ConfigMap osm-config -n osm-system -p '{"data":{"outbound_ip_range_exclusion_list":"54.164.234.192/32ss"}}' --type=merge
Error from server (
outbound_ip_range_exclusion_list: must be a list of valid IP addresses of the form a.b.c.d/x): admission webhook "osm-config-webhook.k8s.io" denied the request: 
outbound_ip_range_exclusion_list: must be a list of valid IP addresses of the form a.b.c.d/x
```
Signed-off-by: Shashank Ram …
=> configurator: validate outbound IP exclusion field

charts/osm/README.md, charts/osm/templates/osm-deployment.yaml, charts/osm/values.schema.json, charts/osm/values.yaml
This PR parameterizes the resource configuration for the osm-controller and will allow a user to customize these properties of the osm controller for their environment. …
=> feat(charts/): parameterize resource configuration

docs/example/README.md
Signed-off-by: Rita Zhang <rita.z.zhang@gmail.com>
update `kubectl create` to `kubectl apply`
move permissive mode up as it needs to be set to `false` to see traffic flowing thru …
=> fix(docs/example/README.md): fix apply and move permissivemode

tests/e2e/e2e_tcp_client_server_test.go
=> tests/e2e: fix log message

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go
=> Update readme and tags for 0.7.0-rc.1

docs/content/docs/patterns/observability/metrics.md
=> docs(metrics): fix broken link in metrics.md

cmd/osm-controller/osm-controller.go, pkg/injector/types.go
Removes an unused option added during initial
development.
`No`
=> injector: remove unused option

docs/content/docs/troubleshooting/_index.md, docs/content/docs/troubleshooting/uninstall.md, docs/content/docs/troubleshooting/upgrade.md
Moves upgrade troubleshooting guide to the new docs directory
No
=> docs(troubleshoot): Move upgrade troubleshooting guide

docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v1.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml
This PR updates the image versions on the manual demo manifests
=> chore(docs): update manual demo manifest images

.github/workflows/release-chart.yml, docs/content/docs/release_guide.md
Cherry-pick a127c1e1c07d432dc7ff055c425e03b21f265212 (#2447)
Updating release guide
No
=> docs(release): add patch release instructions (backport to v0.7)

docs/example/manifests/apps/bookstore.yaml
=> ref(docs): rm unnecessary label from bookstore manifest

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v1.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml, scripts/release-notes.sh
=> Update versions to v0.7.0

docs/content/docs/release_guide.md
This change adds the demo manifests to the list of locations to update
hardcoded versions to the release guide.
No
=> docs(release): update image tags in demo manifests

charts/osm/README.md
Regenerate with `make chart-readme`
No
=> fix(chart): regenerate chart README.md

docs/content/docs/patterns/observability/logs.md
**Description**: Updates logs.md to include format for basic auth under outbound proxy setup.
no, no
=> docs(logs): update for basic auth proxy support

charts/osm/README.md, charts/osm/values.yaml
**Description**: Fix typos and discrepancies in chart values and descriptions
=> chart(fluentbit): fix typos in comments and readme

docs/content/docs/patterns/observability/logs.md
**Description**: Updates old link to latest version of fluent bit docs
=> docs(logs): update old link

pkg/catalog/routes_test.go
This PR adds a test case to `TestBuildOutboundPermissiveModePolicies` ensuring that it builds outbound policies even when the proxy doesn't have any services …
=> test(pkg/catalog/routes_test.go) : Add a test scenario for outbound policies in permissive mode

experimental/routes_refactor/demo/README.md
Fix environment variable reference for CTR_TAG.
`No`
=> experimental/routesV2: fix typo in README

cmd/cli/install.go
=> cli(install): fix typo in flag description

docs/content/docs/patterns/observability/tracing.md
References language from https://www.jaegertracing.io/docs/1.21/#about
=> docs(tracing): add tracing.md for byo jaeger

cmd/cli/mesh_upgrade.go
This change modifies the `osm mesh upgrade --help` text to clarify how
manual edits to resources are handled.
No
=> docs(upgrade): update upgrade CLI docs to clarify manual edits

README.md
The link to Installation Guide is broken. Updated to correct location of (docs/content/docs/installation_guide.md)
Update link to install guide
=> Update link to Installation Guide

pkg/featureflags/featureflags_test.go
-->
- Control Plane          [ X]
- CLI Tool               [X ]
=> tests(pkg/featureflags): test WASMStats flag

pkg/catalog/mock_catalog.go, pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/catalog/service.go, pkg/catalog/service_test.go, pkg/catalog/types.go, pkg/envoy/cds/response.go, pkg/trafficpolicy/trafficpolicy.go, pkg/trafficpolicy/trafficpolicy_test.go
=> feat(*): implement traffic split v1alpha2 w/ routes refactor

go.mod, go.sum, pkg/envoy/cds/cluster_test.go, pkg/envoy/cds/response_test.go
* convert response_test.go to use go testing framework
* add test in cluster_test.go for getPrometheusCluster
=> tests(pkg/envoy/cds): update cds tests

cmd/cli/osm.go, cmd/osm-controller/osm-controller.go, cmd/osm-injector/osm-injector.go
Adds package comments.
Part of #1038
`No`
=> cmd/*: add package comments

pkg/httpserver/httpserver_test.go
Increasing test coverage of `pkg/httpserver` from 20% to 80%
=> httpserver: Adding tests

pkg/health/health_test.go
=> pkg/health: Increase test coverage

.github/workflows/automerge.yml, CONTRIBUTING.md, docs/developer/automerge.md, scripts/status-checker.sh
Adds automerge pull request feature and closes #2393 
- New Functionality      [ X]
No
=> feat(*): Add automerge bot, generate token script, and  markdown for automerge action

demo/run-osm-demo.sh
This change fixes the demo script to accept optional arguments passed
through to `osm install`.
No
=> fix(demo): fix optional args

charts/osm/README.md, charts/osm/values.yaml
Fixes #2558
This increases the default memory limits of the injector and the controller so that they are less likely to crash. …
=> fix(injector): Increase memory for controller and injector

.env.example
Updates .env.example description of the BOOKTHIEF_EXPECTED_RESPONSE_CODE to match the changes from #1725
No
=> docs(demo env): Update expected bookthief response code

docs/content/docs/onboard_services.md, docs/content/docs/patterns/_index.md, docs/content/docs/patterns/observability/_index.md, docs/example/README.md
**Description**: References Jaeger docs and corrects documentation of defaults
- Metrics                [x]
no, no
=> docs(observability): update docs for prometheus, grafana, jaeger changes

docs/content/docs/patterns/ingress.md
Updates the ingress documentation examples and adds
notes around experimental features.
Part of #2115
`No`
=> docs/ingress: update examples and add note for HTTPS

pkg/envoy/xdsutil_test.go
This PR adds a test for `GetLocalClusterNameForServiceCluster()`
=> pkg/envoy: Test GetLocalClusterNameForServiceCluster()

pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/catalog/service.go, pkg/catalog/service_test.go
This PR build inbound routes with virtual hosts pointing to the apex
service a for an upstream service that is referenced in a traffic split.
Corresponding unit tests have been added.
I have tested these changes locally by enabling routes v2 on the traffic split e2e tests and they pass for all  traffic split scenarios
Fixes #2545
- …
=> feat(routesv2) : Build inbound routes for traffic split apex services

docs/content/docs/patterns/observability/logs.md
**Description**: Instructs users on properly setting Helm chart values
no, no
=> docs(logs): update doc to explicitly set chart values

docs/content/docs/install/manual_demo.md
Fixes merge conflicts in the doc.
`No`
=> docs/manual_demo: fix merge conflicts

DESIGN.md, docs/content/docs/design_concepts/interfaces.md, pkg/catalog/ingress.go, pkg/catalog/ingress_test.go, pkg/catalog/mock_catalog_generated.go, pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/catalog/types.go, pkg/tests/fixtures.go
This PR removes code that is no longer used after migration to routes v2
Part of #2397
=> chore(routesv2): Remove unused code

docs/content/docs/HA/_index.md, docs/content/docs/design_concepts/osm_components_interactions/_index.md, docs/content/docs/install/manual_demo/_index.md, docs/content/docs/patterns/observability/_index.md, docs/content/docs/scale/_index.md
Based on feedback from @shashankram in https://github.com/openservicemesh/osm/pull/2636#discussion_r584001615 I'm trying a relative link style to see if it shows up correctly on both the website and the github repo.
=> Adjusting links for use on repo and website

README.md, docs/README.md
- After the fixes in https://github.com/openservicemesh/osm/pull/2647 there was one broken link in the main README.
- I'm clarifying in the docs README what needs to happen for embedded images to work correctly.
=> Clarifications for links

pkg/envoy/route/route_config_test.go
-->
- Control Plane          [ X]
=> tests(pkg/envoy/route): add unit tests for clusterWeightByName

cmd/cli/mesh_upgrade_test.go, pkg/catalog/fake.go, pkg/catalog/helpers_test.go, pkg/catalog/ingress_test.go, pkg/catalog/routes_test.go, pkg/catalog/service_test.go, pkg/catalog/xds_certificates_test.go, pkg/certificate/providers/config_test.go, pkg/configurator/client.go, pkg/configurator/validating_webhook_test.go, pkg/endpoint/providers/kube/client_test.go, pkg/envoy/rds/response_test.go, pkg/kubernetes/event_handlers_test.go, tests/e2e/e2e_trafficsplit_same_sa_test.go, tests/scenarios/traffic_split_with_apex_service_test.go, tests/scenarios/traffic_split_with_zero_weight_test.go
This PR removes duplicate imports across the codebase. No functional changes
=> chore(*): Remove duplicate imports

ci/cmd/maestro/types.go, demo/cmd/common/const.go, pkg/envoy/xdsutil.go, pkg/health/health.go, pkg/injector/types.go, pkg/tests/fixtures.go
Remove unused variables from the code base
=> chore(*): Remove unused variables

ROADMAP.md
Typo fix as noted in https://github.com/openservicemesh/osm/issues/2444.
=> Typo correction

docs/content/docs/tasks_usage/metrics.md
While this isn't how we probably want to store such videos, this is the shortest path to fixing the broken link. We also will want to decide:
=> Correcting broken link

tests/framework/common.go
None of the tests we currently have should be seeing pod restarts.
This is put in place to rule out unwanted restart issues, but other
tests implementing restarts should be put in place.
- Control Plane          [x ]
- Tests                  [ x]
No
=> e2e: Add pod restart checks and Fail tests if seen by default

cmd/cli/mesh_upgrade.go, cmd/cli/mesh_upgrade_test.go
This change modifies how `osm mesh upgrade` handles values so that
upgrades can succeed when the new chart adds new required values.
Currently, values for the new release are computed as:
1. Old chart defaults, overridden by
2. Old release overrides, overridden by
3. New release overrides
With this change, values are computed as:
1. New chart defaults, overridden by
2. Old chart defaults, overridden by
3. Old release overrides, overridden by
4. New release overrides
Fixes #2659
- Security …
=> fix(cli): Handle new required values in upgrade

cmd/cli/mesh_upgrade.go, tests/e2e/e2e_upgrade_test.go
This change updates the CRD versions in the upgrade e2e test to the
versions needed for v0.7.0.
No
=> fix(e2e): Update upgrade test with new CRD versions

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v1.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml
=> release(v0.8.0): update charts and tags for v0.8.0-rc.1

.golangci.yml
Removes ignore rule for non-existent path.
`No`
=> golangci: remove rule for non-existent path

tests/e2e/README.md, tests/e2e/e2e_fluentbit_deployment_test.go, tests/e2e/e2e_fluentbit_output_test.go
**Description**: Updates contexts for Fluent Bit e2es to clarify their purpose
no
=> tests(fluentbit): differentiate contexts for fluentbit e2es

pkg/smi/client_test.go
Adds a unit test for the GetTCPRoute() method.
Resolves #2686
`No`
=> pkg/smi: add unit test for GetTCPRoute

docs/content/docs/install/manual_demo/_index.md
+ reorganize install lines so they're more clear
+ rewording
No
=> ref(docs): update manual demo

docs/content/docs/install/uninstallation_guide.md, docs/content/docs/troubleshooting/uninstall/_index.md
Fixes https://github.com/openservicemesh/osm/issues/2451
=> Fixing links

pkg/envoy/lds/inmesh_test.go
Adds a unit test for the function that builds the
outbound TCP filter. This test will be further
updated when TCP traffic splitting is introduced.
Resolves #2696
- Does this change contain code from or inspired by another project? If so, did you notify …
=> envoy/lds: add unit test for outbound TCP filter

demo/cmd/tcp-client/tcp-client.go, demo/cmd/tcp-echo-server/tcp-echo-server.go
And setting log level to Debug.
No
=> tcp-client/serv: move all logging to log

tests/framework/common.go
No positive effect seen.
- CI System              [x]
No
=> e2e: envoy log lvl back to debug

tests/framework/common.go
Adds collection of envoy configs on the test:
"config_dump", "clusters", "certs", "listeners", "ready" and "stats".
format:
```
/tmp/test-<id>/envoy_configs
| <namespace_podName>/
| "config_dump.txt"
| "certs.txt"
| "listeners.txt"
...
```
No
=> e2e: Add envoy config collection to e2e

demo/join-namespaces.sh, demo/unjoin-namespaces.sh, docs/content/docs/install/manual_demo/_index.md, docs/content/docs/patterns/observability/tracing.md, docs/content/docs/tasks_usage/egress.md, docs/content/docs/tasks_usage/ingress.md
Refactor `kubectl edit` commands to `osm mesh upgrade`  plus small markdown formatting fix
and resolves #2504
=> ref(*): Update docs to use "osm mesh upgrade" + small markdown fix

pkg/envoy/route/route_config_test.go
Improve test coverage for clusterWeightByName.Less()
Fixes : https://github.com/openservicemesh/osm/issues/2695 
- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?`no`
=> test(pkg/envoy/route) : Test clusterWeightByName.Less()

charts/osm/README.md, charts/osm/templates/_helpers.tpl, charts/osm/templates/osm-configmap.yaml, charts/osm/values.yaml
**Description**: Resolves #2585 
no
=> fix(chart): template jaeger address to use osm.namespace value

.github/ISSUE_TEMPLATE/documentation.md
**Description**: Update to match all other issue templates that have heading lines in bold
=> chore(docs): fix documentation gh issue template

pkg/service/service_test.go
Add tests for service package
Fixes: #2688 
=> test(pkg/service): Add tests for service package

cmd/cli/install.go
This change disables the behavior of `helm install --atomic` by default
for `osm install`, making it possible to debug failures without having
to reinstall. A new `osm install --atomic` flag enables the old
behavior.
Fixes #2508 …
=> fix(install): disable atomic by default

pkg/configurator/methods_test.go
Added unit tests for UseHTTPSIngress(), IsPrivilegedInitContainer() and added disable check for IsDebugServerEnabled() unit test and resolves #2716 + #2715 
No
=> tests(pkg/configurator): add unit tests to pkg/configurator

docs/content/docs/install/manual_demo/_index.md
This change updates a relative link in the manual demo to one of the
YAML manifests to an absolute link to GitHub like the other manifest
links.
No
=> fix(demo): update relative link in manual demo

docs/content/docs/install/manual_demo/_index.md, docs/content/docs/install/uninstallation_guide.md
This change adds cleanup steps to the manual demo that describe how to
remove the resources created for the demo.
Fixes #2812
No
=> docs(demo): add cleanup steps to manual demo

.github/pull_request_template.md
Add demo checkbox to pull request template. Changes may occur in the demo for usability, etc. so these may not necessarily fall into "CI System" …
=> Add demo checkbox to pull request template

pkg/envoy/lds/inmesh_test.go
Adds a unit test for the function that builds the outbound
TCP filter chain.
Resolves #2697 …
=> envoy/lds: add unit test for outbound TCP filter chain

pkg/envoy/proxy_test.go
Adds to unit test for GetLastSentNonce() and resolves #2712
No
=> test(pkg/envoy): add to test for GetLastSentNonce()

docs/content/docs/dev_guide/_index.md
Fix links to design docs and installation in development guide.
=> Fix links in development guide

pkg/catalog/xds_certificates.go
The key is known, no need to walk the map.
No
=> xds_cert: Fix walk on map

README.md
This change updates the table of supported SMI resource versions to include individual kinds and their full CRD name.
Fixes #2862
No
=> docs(readme): update supported SMI table

docs/content/docs/troubleshooting/traffic/_index.md, docs/content/docs/troubleshooting/traffic/permissive_traffic_policy_mode.md
Adds a basic troubleshooting guide for permissive mode.
Part of #2855
`No`
=> docs/troubleshooting: add guide for permissive mode

cmd/osm-controller/osm-controller.go
=> osm-controller: Fix small typos in comment

pkg/envoy/proxy_test.go
Add unit test for GetIP() and resolves #2709 
No
=> test(pkg/envoy): add coverage for GetIP

docs/content/docs/tasks_usage/ingress.md
Clearly document how to install nginx controller for examples
Partially addresses  #2827 
No
=> docs(ingress): Document how to install nginx ingress controller

.mergify.yml
Allows Mergify to automerge for main and release branch and autorebases based on automerge and autorebase label based on the yaml rules.
Currently does not automerge for paths-ignore.
- New Functionality      [ X]
- Does this change contain code from …
=> feat(*): Mergify yaml for autorebase and automerge

docs/content/docs/tasks_usage/traffic_management/egress.md
Documents egress usage with a sample demo
as per #2869.
`No`
=> docs/egress: document demo and envoy config

docs/content/docs/troubleshooting/traffic/_index.md, docs/content/docs/troubleshooting/traffic/egress.md
Adds a troubleshooting guide for egress.
Part of #2869
`No`
=> docs/troubleshooting: add guide for egress

tests/e2e/e2e_http_ingress_test.go
This change updates the HTTP ingress e2e test to only install the nginx
ingress controller service as NodePort on kind clusters and LoadBalancer
elsewhere. On kind, test requests are made against `localhost` and for
other clusters against the load balancer ingress IP or hostname of the
nginx service.
Fixes #2835
Please answer …
=> fix(e2e): fix HTTP ingress e2e on non-kind

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml
=> chore(release): update versions for v0.8.0

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml
=> chore(release): update versions for v0.8 in main

docs/config.toml
=> docs(release): Update version dropdown for docs site

docs/content/docs/tasks_usage/traffic_management/_index.md, docs/content/docs/tasks_usage/traffic_management/iptables_redirection.md, docs/content/docs/tasks_usage/traffic_management/permissive_traffic_policy_mode.md
Documents iptables based traffic redirection along
with dynamic IP range exclusions. Adds a sample
demo to the document to understand the feature.
Also updates the title styling in the permissive mode
doc for consistency.
Part of #2884 …
=> docs/traffic_management: iptables redirection

pkg/envoy/ads/response.go, pkg/envoy/ads/response_test.go, pkg/envoy/ads/stream.go
Different code paths are using different functions to generate xDS proto
underneath. In order for future improvements to catch and be able to validate
the configurations we send, this commit refactors the `sendAllResponses` to
be able to take any arbitrary xDS TypeURIs, and be reusable for all current
uses in `stream.go` (`DiscoveryRequest` trigger, dispatch trigger or SDS
cert rotated trigger).
From xDS perspective, this commit should not incur in any functional change.
No
=> ADS: generalize `sendAllResponses` to accomodate any TypeURI

docs/content/docs/release_guide.md
**Description**: Fixes text wrapping that was making it difficult to copy-paste the url suffix
no
=> chore(release): fix typo and text wrapping in release guide

pkg/envoy/ads/response.go, pkg/envoy/ads/response_test.go
There is a bug where the upstream service's service cert that
is referenced in the corresponding inbound filter chain for
the service is not programmed when there is a request to push
all secrets via XDS. Without this, it has been observed that
in certain environments the secrets often don't transition
from warming to active. As a result, mTLS is broken when
such a situation occurs.
This change programs the upsteam service's service cert
as a part of the request to provision all secrets associated
with the proxy.
This change does not address other potential XDS problems,
such as the one pertaining to XDS DiscoveryRequest with
an empty TypeUrl.
Potentially addresses #2749
- …
=> envoy/ads: program upsteam's service cert when making all secrets

.mergify.yml
Specified to use rebase method for updating PR branch for merge action.
- New Functionality      [X ]
No
=> feat(*): Add rebase to automerge action

cmd/cli/namespace_add.go
- CLI Tool               [ X]
No
=> ref(*): update osm namespace add description

pkg/envoy/ads/grpc.go, pkg/envoy/ads/response.go, pkg/envoy/ads/stream.go, pkg/envoy/types.go
=> xds: handle wildcard TypeURI

DESIGN.md
Signed-off-by: aisuko <urakiny@gmail.com>
=> Fixed the broken address of the design document

.github/workflows/main.yml
This change configures CI to additionally push images with the git SHA
tag on each push to release branches like for pushes to main.
No
=> feat(ci): push images for each push to release branches

docs/content/docs/tasks_usage/namespace_monitoring.md
=> docs(*): add osm namespace monitoring doc

docs/content/docs/tasks_usage/metrics.md
- reformatting / re-organizing
- modified wording
-->
=> ref(docs/observability): updated observability docs

.github/workflows/main.yml
=> fix(ci): fix missing paren

docs/content/docs/troubleshooting/traffic/_index.md, docs/content/docs/troubleshooting/traffic/iptables_redirection.md
Adds a troubleshooting guide related to iptables
redirection.
Part of #2884
`No`
=> docs/troubleshooting: add iptables doc

CONTRIBUTING.md
Adds a section for documentation.
Part of #2453
`No`
=> contributing guide: add section for docs

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml
=> chore(release): update charts and tags for v0.8.1-rc.1

pkg/envoy/xdsutil_test.go
Adds additional unit test for UnmarshalSDSCert and resolves #2714
No
=> test(pkg/envoy): add test for UnmarshalSDSCert

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml
=> chore(release): update charts and tags for v0.8.1-rc.2

docs/content/docs/tasks_usage/container_startup.md
=> docs: document potential container startup issues

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml
=> chore(release): update charts and tags for v0.8.1

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml
=> chore(release): update chart and tags for v0.8.2

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml
=> chore(release): update versions in main

pkg/envoy/xdsutil_test.go
Adds unit test for pbStringValue() and resolves #2708
No
=> test(pkg/envoy): add test for pbStringValue()

docs/content/docs/tasks_usage/metrics.md, docs/content/docs/troubleshooting/observability/_index.md, docs/content/docs/troubleshooting/observability/grafana.md
This change adds a troubleshooting guide for OSM's automatically
deployed Grafana instance.
Fixes #2873
No
=> docs(metrics): add Grafana troubleshooting

docs/content/docs/troubleshooting/observability/grafana.md
This change simplifies instructions in the Grafana troubleshooting guide
for checking and modifying data source settings to ensure Grafana can
communicate with Prometheus.
Follow-up from #2992 …
=> docs(metrics): simplify Grafana TSG data source check

pkg/envoy/ads/health_test.go
Add test for GetID() and resolves #2699
- Does this change contain code from or inspired by another project? No. If so, did you notify the maintainers and provide attribution? N/A.
=> test(pkg/envoy/ads): add test for GetID()

pkg/kubernetes/types_test.go
Add EventType.String() test and resolves #2690
- Does this change contain code from or inspired by another project? No. If so, did you notify the maintainers and provide attribution? N/A
=> test(pkg/kubernetes): add EventType.String() test

docs/content/docs/patterns/_index.md
=> ref(docs): rm empty patterns directory

docs/content/docs/osm_config_map.md, docs/content/docs/troubleshooting/cli/mesh_upgrade.md, docs/content/docs/troubleshooting/osm_configmap.md
Documentation for `osm-config`
No
=> docs(docs/content/docs): add configmap doc

docs/content/docs/install/manual_demo/_index.md
Corrected typo in documentation for the manual demo
- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? No additional code.
=> correct typo

charts/osm/README.md, charts/osm/templates/osm-deployment.yaml, charts/osm/templates/osm-injector-deployment.yaml, charts/osm/values.schema.json, charts/osm/values.yaml
Signed-off-by: Rita Zhang <rita.z.zhang@gmail.com>
Fixes #3021 
=> feat(charts/osm): add podLabels to osm pods

CONTRIBUTING.md
Clarifies the default merge method and the optional
squash option for maintainers.
`No`
=> contributing: clarify merge method

pkg/envoy/ads/health_test.go
Add unit test to Liveness() and Readiness() and resolves #2700
No
=> test(pkg/envoy/ads): add test to Liveness() and Readiness()

docs/content/docs/tasks_usage/tracing.md
**Description**: Fixes yaml indentation to use whitespaces instead of tabs in tracing doc
no
=> fix(docs/content): fix yaml indentation in tracing.md

charts/osm/templates/osm-deployment.yaml, charts/osm/templates/osm-injector-deployment.yaml
=> feat(charts/osm): add os and arch node selectors

pkg/envoy/route/route_config_test.go
Improves the `buildRoute()` test by making
the expectations more comprehensive while
simplifying the assertions. Also adds a
test for inbound routes. …
=> envoy/route: improve test for buildRoute()

pkg/envoy/xdsutil_test.go
Adds test for GetAccessLog() and resolves #2711
No
=> test(pkg/envoy): Add test to GetAccessLog()

pkg/catalog/ingress.go, pkg/catalog/ingress_test.go
Removes unnecessary escape char in raw string literal. 
`No`
=> catalog/ingress: remove unnecessary escaping in raw string

docs/content/docs/troubleshooting/traffic/ingress.md, docs/content/docs/wip/ingress.md
**Description**: This PR creates a new ingress doc, which consolidates the existing ingress documentation with additional information as well as a sample demo.  …
=> docs/wip: add work-in-progress doc for ingress

pkg/configurator/validating_webhook.go, pkg/configurator/validating_webhook_test.go
Resolves #3078
- Other                  [ X]
No
=> fix(pkg/configurator): fix VWH validateFields() test

pkg/trafficpolicy/trafficpolicy_test.go
**Description**: Convert from set to mapset in trafficpolicy_test.go
=> style(pkg/trafficpolicy/trafficpolicy_test): Alias deckarep/golang-set with mapset

pkg/trafficpolicy/trafficpolicy.go, pkg/trafficpolicy/types.go
**Description**: Alias deckarep/golang-set with mapset in trafficpolicy.go and types.go
=> style(pkg/trafficpolicy): Convert to mapset

pkg/envoy/ads/stream.go
Signed-off-by: storyicon <storyicon@foxmail.com>
I think there may be some clerical errors here, we should make the context meaningful.
- Control Plane          [ X ]
=> fix(control-plane):  fix the context in the StreamAggregatedResources

pkg/configurator/client_test.go
A misshandled initial config event was shifting the results of the tests,
making a test pass that shouldn't.
Fixed both the race (now should be properly synchronized) and the test that
should have failed to begin with.
No
=> configurator: fix race and wrong input

pkg/envoy/route/route_config_test.go
**Description**: Convert from set to mapset in route_config_test.go
=> style(pkg/envoy/route/route_config_test): Alias deckarep/golang-set with mapset

pkg/kubernetes/util.go, pkg/kubernetes/util_test.go
Adds a helper to retrieve k8s server version. This will be
used for the following:
1. To add checks at controller startup to prevent the controller
from starting in unsupported cluster versions. Currently there
is no such check, which results in failures later on such
as when k8s objects are initialized and there is a version
mismatch. Adding this check will simplify root causing
such an issue.
2. To correctly initialize version-specific resources, such as
ingress v1 which is only available in k8s >= 1.19.
Required for #2798 …
=> kubernetes/util: add helper to retrieve k8s server version

pkg/envoy/xdsutil_test.go
Add unit test for getFileAccessLog() and resolves #2710
No
=> test(pkg/envoy): add test for getFileAccessLog()

pkg/envoy/route/rbac_test.go
**Description**: Convert from set to mapset in rbac_test.go
=> style(pkg/envoy/route/rbac_test): Alias deckarep/golang-set with mapset

pkg/envoy/route/route_config.go
**Description**: Convert from set to mapset in route_config.go
=> style(pkg/envoy/route/route_config): Alias deckarep/golang-set with mapset

Makefile, codegen/boilerplate.go.txt, codegen/gen-crd-client.sh, go.mod, go.sum, tools.go
Add script to generate client-go style types and other code from CRD.
Yes
=> Add script to generate types etc, for CRD

docs/content/docs/tasks_usage/traffic_management/ingress.md
Documents the ingress api version compatibility.
Also clarifies a statement regarding ingress support.
Part of #2798 and #2871 …
=> docs/ingress: document api version compatibility

tests/framework/common.go
Getting logs for all envoys can be costly (in terms of time) if
there's a large number of proxies.
`controlPlaneOnly` allows forcing collect logs but for control plane
processes only.
Additionally adds collection of all-namespace events.
No
=> e2e/common: add controlPlaneOnly option for log collection

docs/content/docs/application_health_probes.md, docs/content/docs/control_plane_health_probes.md
This changes moves the health probe docs so they appear on
docs.openservicemesh.io
No
=> chore(docs): promote health probe docs

charts/osm/README.md, charts/osm/templates/osm-configmap.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, docs/content/docs/osm_config_map.md, pkg/catalog/mock_catalog_generated.go, pkg/catalog/proxy.go, pkg/catalog/types.go, pkg/configurator/client.go, pkg/configurator/client_test.go, pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/configurator/mock_client_generated.go, pkg/configurator/types.go, pkg/configurator/validating_webhook.go, pkg/configurator/validating_webhook_test.go, pkg/envoy/ads/errors.go, pkg/envoy/ads/stream.go
Adds and checks configurable limit to envoy connections and resolves #2332
- New Functionality      [ X]
No
=> feat(*): add configurable upper bound to envoy connections

docs/content/docs/tasks_usage/traffic_management/ingress.md
Documents the usage of the v1 ingress API with the
sample demo.
Part of #2798 and #2871
`No`
=> docs/ingress: add v1 ingress resource to the demo

README.md
There is now a playlist for the CNCF OSM meetings. I added the link and clarified the other community meeting details.
=> Updating README's meeting details

docs/content/docs/tasks_usage/traffic_management/demos/gloo_edge_ingress_demo.md, docs/content/docs/tasks_usage/traffic_management/ingress.md
Create demo for using the Gloo Edge Ingress Controller with OSM
=> docs(ingress): Gloo Edge Ingress Demo

tests/scale/osm_common_profile_resources.go
Was missing last map value.
No
=> scale: fix missing values.yaml path override

pkg/catalog/ingress.go
=> catalog/ingress: Fix a tiny typo in a comment

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go, docs/content/docs/application_health_probes.md, docs/content/docs/control_plane_health_probes.md, docs/content/docs/install/manual_demo/_index.md, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml
This PR updates the main branch with the latest release version (v0.8.3)
- Demo …
=> chore(release): updating charts and tags to version v0.8.3

pkg/envoy/ads/stream.go
Move xDS logic into a separate function.
New function `respondToRequest` gets as input Proxy and discoveryRequest,
and its output is a decision boolean indicating if request needs to be
responded or not.
Unit tests for this function will come in future commits.
- No functional changes.
- Consolidated log lines to start with `"Proxy SerialNumber=%s PodUID=%s:..."`
Istio's code has been referred and discussed.
https://github.com/istio/istio/blob/da6178604559bdf2c707a57f452d16bee0de90c8/pilot/pkg/xds/ads.go#L347
=> stream: move the xDS decision making/proto to a separate function

docs/content/docs/design_concepts/osm_components_interactions/_index.md
Signed-off-by: Tim Bertenshaw <tbertenshaw@hotmail.com>
Correct incorrect spelling.
No
=>  correct spelling of interaction

tests/e2e/README.md, tests/e2e/e2e_smi_traffic_target_test.go, tests/framework/common.go, tests/framework/common_apps.go
Modifies only tests/e2e/e2e_smi_traffic_target_test.go to run on OpenShift. All other tests are WIP.
Partially addresses #3097 
- Does this change contain code from or inspired by another project? If so, did you notify …
=> test(openshift): Tests traffic target on OpenShift

pkg/envoy/ads/response.go
Introduced by https://github.com/openservicemesh/osm/pull/3192
Thinning down while addressing CR last commit removed the code that
records the resources sent part on `ads.Response()`.
Things work because requests are replied but stream does not end in
current condition due to never settling resources.
No
=> response: missing record of sent resources

pkg/envoy/ads/stream.go
Both CDS and LDS use at all times wildacard mode (not just at init time).
https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#client-behavior
This makes envoy always ACK whatever it is sent at face-value for LDS and CDS, and the ACK
itself is also wildcarded (it doesn't specify ACKd resources for LDS and CDS).
Current logic for us still works, as the `len` for resource difference for an empty request resources
is 0, hence is treated rightfully as an ACK.
No
=> ads: Fix/address wildacard comments and documentation in ADS code

pkg/envoy/ads/stream.go
Our ADS implementation had some hardcoded push update code upon
`stream.go` start that was meant to handle reconnections and ensure
a new version was always pushed for an envoy upon reconnecting.
This code suffered from several problems, among them was causing unnecessary
versioning to happen before envoy went through init stage, which caused delays
and mishandling of versions as the initial version pushed by control plane
would be ignored in all cases for new envoys.
Code now handles reconnection gracefully following protocol. A connecting envoy
that comes from some other control plane will have a version and nonce applied to it.
We can detect that situation on the control plane by checking if we ever issued
a nonce for that proxy and TypeURL. When we have no `lastNonceSent` registered …
=> ads: fix reconnection of envoy

pkg/envoy/cds/cluster.go, pkg/envoy/cds/cluster_test.go
Signed-off-by: Adithya Krishna <aadithya794@gmail.com>
This PR Fixes #3240
No
=> Bug: Remove References to Synthetic Cluster Code

ci/cmd/maestro/kubernetes_tools.go
Currently, the maestro used to verify the automated demo in CI only
checks if the timeout for a pod to log a success message has been
reached after a log message has been read. If no logs are written (like
if the bookwarehouse is not responding to requests), then the maestro
will hang forever. This change modifies the maestro to check the timeout
independently of when pod logs are read.
- Demo …
=> fix(maestro): timeout when no logs are written

docs/content/docs/install/_index.md, docs/content/docs/install/uninstallation_guide.md, docs/content/docs/osm_config_map.md, docs/content/docs/upgrade_guide.md
Documents how to install and uninstall osm with helm cli
No
=> docs(install): Document how to install and uninstall with Helm

pkg/envoy/rds/response.go, pkg/envoy/rds/response_test.go
Changes in LDS could leave listeners draining, which would apparently
still require the related RDS configuration that was referenced and in use
by the draining state listener to be presented, or otherwise envoy
will keep trying to resolve its RDS dependencies.
This commit ensures that for a given RDS request, we always give back the
referenced RDS resources, filled with empty/stub-like RouteConfigs when
actual logic did not compute them (as they should no longer be necessary
in the new version of LDS).
Fixes #3258
No
=> rds: ensure fulfillment of requested rds resources

cmd/init-osm-controller/init-osm-controller.go, pkg/configurator/validating_webhook.go
Removes a typo from a comment and adds a default value for the
envoy image in the default mesh config.
- Install                [ X ]
no
=> fix: cleanup bugs from PR to move envoy proxy image

pkg/catalog/egress.go, pkg/constants/constants.go, pkg/envoy/lds/ingress.go, pkg/envoy/lds/inmesh.go, pkg/kubernetes/util.go, tests/e2e/e2e_tcp_client_server_test.go, tests/e2e/e2e_tcp_egress_test.go, tests/e2e/e2e_trafficsplit_recursive_split.go, tests/e2e/e2e_trafficsplit_test.go, tests/framework/common_apps.go
Consolidates the constants used for traffic protocols.
`No`
=> pkg/*|tests: consolidate constants for protocols

pkg/catalog/ingress.go, pkg/catalog/ingress_test.go
This change addresses 2 issues when the pathType=Prefix
for an ingress rule based on k8s ingress requirements.
1. It fixes the scenario where path=/ and pathType=Prefix
by programming a string based prefix match to allow the
prefix `/` to match all paths. The previously resulting
regex match `/(/.*)?$` for the path `/` does not work
with Envoy' C++ regex lib. Note that the same regex
pattern works with Golang's `regexp` lib. For wildcard
`/` prefix, a string based prefix match is configured
in Envoy.
2. If fixes the scenario where a request with path=/foo
must match a Prefix path /foo/ in an ingress rule. It
does so by trimming the trailing slash in an ingress rule
for prefix path types.
Resolves #3292
- Documentation …
=> catalog/ingress: conform to k8s prefix path type

charts/osm/crds/meshconfig.yaml, cmd/cli/mesh_upgrade.go, cmd/cli/mesh_upgrade_test.go, docs/content/docs/osm_config_map.md, pkg/apis/config/v1alpha1/mesh_config.go, pkg/apis/config/v1alpha1/zz_generated.deepcopy.go, pkg/configurator/client.go, pkg/configurator/client_test.go, pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/configurator/mock_client_generated.go, pkg/configurator/types.go, pkg/injector/init_container.go, pkg/injector/init_container_test.go, pkg/injector/iptables.go, pkg/injector/patch.go, pkg/injector/patch_test.go, pkg/injector/webhook.go, pkg/injector/webhook_test.go, tests/e2e/e2e_port_exclusion_test.go
This commit updates the type of portExclusion from []string to []int
Fixes #3308
=> fix(portExclusion) : Fix port exclusion to array of int

CONTRIBUTING.md, README.md
Updating readme and contributing guide to fix broken links and clarify explanation of where and how to update docs.
No
=> Fix links and docs guide details

charts/osm/crds/policy.yaml, pkg/apis/policy/v1alpha1/egress.go
Updates the comments for the API types and adds validation
for the IPAddresses and Port fields.
Part of #3045
`No`
=> egress: update comments for types and add field validation

charts/osm/crds/meshconfig.yaml
Makes the port and IP range validations stricter.
`No`
=> charts/meshconfig: make port and IP range validations stricter

.github/pull_request_template.md
Updates the PR template to align the areas to mark
against, and breaks the question regarding attribution
to avoid ambiguity.
| Upgrade                    | …
=> github: update PR template and clarify questions

pkg/apis/config/v1alpha1/mesh_config.go
Updates the comments for the API types of MeshConfig
Part of #3040
=> MeshConfig : update comments for types

charts/osm/templates/osm-rbac.yaml
Restricts capabilities for OSM controller
| CI System                  | [ ] …
=> fix(psp): Update osm-psp capabilities

tests/e2e/e2e_egress_policy_test.go, tests/framework/common.go, tests/framework/common_apps.go
Adds e2e tests for the different supported scenarios
with egress policies.
Part of #3045
| Egress                     | [X] |
=> tests/e2e: add egress policy tests

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.schema.json, charts/osm/values.yaml, cmd/cli/install.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml
=> chore(release): create release v0.8.4

cmd/osm-controller/osm-controller.go
Correctly prints byte array as a string.
Resolves #3355
Signed-off-by: Atharva321 <atharvapatil19202@gmail.com>
=> osm-controller: correctly print byte array

CONTRIBUTING.md, docs/apidocs/README.md, docs/apidocs/apidoc.json
Documents process to generate custom API doc.
=> docs/apidocs: document process to generate custom API docs

README.md
Signed-off-by: Karen Chu <karen.chu@microsoft.com>
| …
=> Add OSM Twitter account to community section

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/crds/meshconfig.yaml, charts/osm/values.yaml, cmd/cli/mesh_upgrade.go, cmd/init-osm-controller/init-osm-controller_test.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml, docs/example/manifests/meshconfig/mesh-config.yaml, docs/release_guide.md, pkg/configurator/methods_test.go, pkg/constants/constants.go
This PR updates the main branch with the latest release version (v0.8.4)
| Egress …
=> chore(release): update charts and tags to v0.8.4

cmd/cli/mesh_list.go, cmd/cli/namespace_list.go, cmd/cli/namespace_test.go, cmd/cli/uninstall_test.go, cmd/cli/util.go, cmd/cli/util_test.go
=> feat(cli): add namespace info to mesh list cmd

docs/release_guide.md
During the release process, there are items that need to be edited on the docs site. This PR adds a section to the release guide for updates to the docs website.
no
no
=> Update the docs site for a release.

tests/e2e/e2e_upgrade_test.go
The upgrade test is broken because of using invalid
chart parameters. This change fixes it.
| Upgrade                    | [X] |
=> tests/e2e: fix install properties in upgrade test

pkg/httpserver/httpserver_test.go
Covered case:
* Calling Stop() when server is not started
Issue #3426 
| Tests                      | ✅ |
| CI System …
=> test: add test case for pkg/httpserver

pkg/catalog/catalog.go, pkg/catalog/mock_catalog_generated.go, pkg/catalog/types.go
This reverts commit c0605a7242aea081ba89ccb9b469eb4145f51d64.
No 
No
=> Revert "catalog: add GetKubecontroller interface"

pkg/ticker/ticker_test.go
Add tests to cover pkg/ticker
Related issue: #3436 
| Tests                      | ✅  |
| CI System                  | [ ] …
=> test: unit test for pkg/ticker

pkg/envoy/cds/response_test.go
This change adds new test cases to increase coverage of the CDS
`NewResponse()` function. The only remaining uncovered lines in
pkg/envoy/cds are handling errors returned by `ptypes.MarshalAny()`.
Fixes #3409 …
=> tests(cds): increase NewResponse coverage

go.mod, pkg/utils/proto.go, pkg/utils/proto_test.go
Adds a unit test for ProtoToYAML and directly leverages
the yaml pkg to perform JSON -> YAML conversions.
=> utils/proto: add unit test and remove duplicated code

pkg/configurator/client_test.go
Add test case to pkg/configurator.
Resolves issue #3407 .
| Tests                      | ✅ |
| CI System                  | …
=> test: add test to pkg/configurator

.mergify.yml
For automerge to work properly, adds checks for the e2e buckets and removes the netlify check as it is no longer required for OSM.
| Upgrade …
=> fix(.mergify.yml): fix checks for automerge feature

cmd/init-osm-controller/init-osm-controller_test.go
Add test for init-osm-controller internal methods
Resolve #3404 
| Tests                      | ✅ |
| CI System …
=> test: add test for init-osm-controller methods

pkg/injector/patch_test.go
Relates to https://github.com/openservicemesh/osm/issues/3432
I've added missing unit tests for pkg/injector/patch. Thank you for your review!
| Tests …
=> tests: add unit tests for pkg/injector/patch

charts/osm/crds/multiclusterservice.yaml
Signed-off-by: timmyreilly <tireilly@microsoft.com>
Adding crd for MulticlusterService
Part of : https://github.com/openservicemesh/osm/issues/3403
| …
=> feat(multicluster): crd only

CONTRIBUTING_LADDER.md
Signed-off-by: Karen Chu <karen.chu@microsoft.com>
| …
=> Creat Contributing Ladder file

pkg/smi/health.go, pkg/smi/health_test.go
Adds unit test for smi.HealthChecker
and resolves #3243
| Tests                      | [x ] |
| CI System …
=> test(pkg/smi): adds test for smi health checker

docs/dev_guide/README.md
Updates the guide to reflect the current usage of
different testing frameworks.
=> docs/dev_guide: update test framework usage

pkg/envoy/ads/jobs.go, pkg/envoy/ads/profile.go, pkg/envoy/ads/response.go, pkg/envoy/ads/secrets.go, pkg/envoy/ads/stream.go, pkg/envoy/cds/response.go, pkg/envoy/eds/response.go, pkg/envoy/lds/response.go, pkg/envoy/proxy.go, pkg/envoy/proxy_test.go, pkg/envoy/registry/registry.go, pkg/envoy/sds/response.go
This change logs the proxy consistently across the code
and also improves the verbosity when the log levels
are either debug or trace.
The previous logging of proxy UID/Serial were not intuitive
as noted in #2924.
| Other                      | [ X] |
=> envoy: make logging consistent and verbose for debug levels

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/crds/meshconfig.yaml, charts/osm/values.yaml, cmd/cli/mesh_upgrade.go, cmd/init-osm-controller/init-osm-controller_test.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml, docs/example/manifests/meshconfig/mesh-config.yaml, pkg/configurator/methods_test.go, pkg/constants/constants.go
=> release: Update versions to 0.9.0

.github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md, docs/release_guide.md
Update release guide to reflect which updates need to be made
| CI System …
=> docs(release): Update chart update requirements

cmd/cli/trafficpolicy_check_test.go
Adds a unit test for the run method on trafficPolicyCheckCmd.
Increases code coverage for the method by testing each error
condition.
| Tests                      | [ X ] …
=> test(cmd/cli): add test for trafficPolicyCheckCmd

docs/release_guide.md
Add details for joining CNCF Slack to announce releases.
no
no
=> Add details for CNCF Slack

pkg/envoy/lds/inmesh.go
=> refactor(pkg/lds) Cleanup a redundant call to ListAllowedServices

docs/envoy/traffic_flow.md
This PR is a crossport of https://github.com/openservicemesh/osm-docs/pull/132.
Documents traffic flow through envoy for a
request from client to server.
=> docs/envoy: document traffic flow

pkg/injector/webhook.go, pkg/injector/webhook_test.go
Addresses an issue where a log message indicates an
annotation being present when it isn't, only
because accessing an invalid key on the map adds
a nil value for the missing key.
Previously:
`"message":" server has sidecar injection annotation: 'openservicemesh.io/sidecar-injection:enabled'"`
Now:
`"message":"Namespace 'server' has sidecar injection annotation: 'openservicemesh.io/sidecar-injection:enabled'"`
Also explicitly sets the object Kind since client-go
does not set the Kind for objects on the cache (see
https://github.com/kubernetes/client-go/issues/308).
1. Does this change contain …
=> injector: fix correctness while checking for annotations

cmd/osm-controller/validate.go, cmd/osm-controller/validate_test.go
**Description**: Adds test case for empty caBundleSecretName. Resolves #3405  …
=> tests: validate osm-controller CLI params

pkg/envoy/sds/response.go, pkg/envoy/secrets/secrets.go, pkg/envoy/secrets/secrets_test.go, pkg/envoy/xdsutil.go, pkg/identity/types.go, pkg/identity/types_test.go
Removes SDS implementation leakage in the identity
pkg.
Resolves #3182
=> envoy/identity: cleanup SDS refs in identity pkg

tests/framework/common_metrics.go, tests/framework/common_profile.go
- Improved readability of few strings that caused confusion.
- Rounded iteration times to seconds
- Number of pods in mesh has been fixed, as it was using an unscrapped
metric.
| Security …
=> scale: fix output and improvements

tests/framework/common.go
This PR removes a few variables, which are never changed, and effectively are bool constants.
=> e2e: Remove unused variables

demo/cmd/bookstore/bookstore.go, demo/cmd/common/const.go
Distributed tracing on the existing demo does not work across services. E.g. requests of bookbuyer->bookstore and bookstore->bookwarehouse are in separate spans. 
This PR adds essential changes to enable it in the demo app.
| Sidecar …
=> chore(demo): cross service distributed tracing in demo

pkg/catalog/endpoint.go, pkg/catalog/endpoint_test.go, pkg/catalog/mock_catalog_generated.go, pkg/catalog/types.go, pkg/envoy/eds/response.go
Resolves issue #3190 
* Use map to iterate over endpoint list, in order to improve performace
* Rename `ListAllowedEndpointsForService()` to `ListEndpointsForServiceIdentity()`
* Rename `destSvcAccount` variable to `destinationServiceIdentity`
| Control Plane              | ✅ |
| SMI Policy …
=> ref(catalog): improve performance of ListAllowedEndpointsForService()

pkg/certificate/providers/vault/certificate_manager_test.go
Adds a test for ListCertificates to increase code coverage for
methods on vault certificate manager.
| Tests                      | [ X ] |
| CI System                  | …
=> test(pkg/certificate): add test for ListCertificates

pkg/config/client.go, pkg/config/mock_client_generated.go, pkg/config/types.go
-->
| New Functionality          | [x ] |
| Demo …
=> feat(pkg/config): simplify the config client to the fields it needs

cmd/osm-controller/log_handler.go, cmd/osm-controller/osm-controller.go, cmd/osm-injector/osm-injector.go, cmd/osm-injector/reconcile.go, pkg/errcode/errcode.go
Logs error codes for errors encountered during app
startup. Additionally moves error logging to the
caller/handler of the error to avoid duplicate
logging.
Part of #2866
=> cmd/osm-*: log error codes for errors during startup

pkg/catalog/egress.go, pkg/errcode/errcode.go
Defines error codes for egress policy related
errors.
| Egress                     | [X] |
=> catalog/egress: define error codes for error logs

pkg/envoy/lds/gateway.go, pkg/envoy/lds/gateway_test.go, pkg/envoy/lds/inmesh.go, pkg/envoy/lds/inmesh_test.go, pkg/envoy/lds/response_test.go, pkg/service/service.go, pkg/service/service_test.go
Proxy mode should allow the gateway to pick up the original
connection string
| New Functionality          | [ x] | …
=> feat(pkg/envoy/lds): Switch the gateway listener to proxy mode

DESIGN.md, cmd/osm-controller/osm-controller.go, pkg/catalog/catalog.go, pkg/catalog/endpoint_test.go, pkg/catalog/errors.go, pkg/catalog/fake.go, pkg/catalog/helpers_test.go, pkg/catalog/inbound_traffic_policies_test.go, pkg/catalog/outbound_traffic_policies.go, pkg/catalog/outbound_traffic_policies_test.go, pkg/catalog/service.go, pkg/catalog/service_test.go, pkg/catalog/traffictarget.go, pkg/endpoint/mock_endpoint_provider_generated.go, pkg/endpoint/types.go, pkg/providers/kube/client.go, pkg/providers/kube/client_test.go, pkg/providers/kube/fake.go, pkg/service/mock_service_provider_generated.go, pkg/service/types.go, pkg/tests/fixtures.go, tests/scenarios/traffic_split_with_apex_service_test.go
**Description**:  Kube Provider is aware of both Service and Endpoint Provider Interfaces and relevant functions have been updated
Related PRs: #3609 and #3614 
Associated Issues: #3456 
| New Functionality          | [ X] | …
=> feat(provider): catalog uses service and endpoint providers methods

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/README.md.gotmpl, charts/osm/crds/meshconfig.yaml, charts/osm/values.yaml, cmd/cli/mesh_upgrade.go, cmd/init-osm-controller/init-osm-controller_test.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml, docs/example/manifests/meshconfig/mesh-config.yaml, pkg/configurator/methods_test.go, pkg/constants/constants.go
Updates the code/docs to default to v0.9.1.
=> release/v0.9.1: update default release refs

pkg/validator/validators.go, pkg/validator/validators_test.go
Signed-off-by: Whitney Griffith <whitney.griffith16@gmail.com>
**Description**: This is the initial validator function to check the MultiClusterService CRD is as expected 
| New Functionality          | [x ] |
| Tests …
=> MultiClusterService validator checks that cluster name is not global

pkg/certificate/providers/certmanager/certificate_manager.go, pkg/certificate/providers/config.go, pkg/certificate/providers/tresor/ca.go, pkg/certificate/providers/tresor/certificate_manager.go, pkg/certificate/providers/vault/certificate_manager.go, pkg/certificate/rotor/rotor.go, pkg/errcode/errcode.go
Adds error codes for errors related to certificate providers.
Part of #2866
| Demo …
=> pkg/certificate: add error codes

pkg/configurator/client.go, pkg/configurator/methods.go, pkg/errcode/errcode.go
Add logging error codes for MeshConfig configurator
| …
=> Meshconfig err codes

pkg/envoy/ads/cache_stream.go, pkg/envoy/ads/grpc.go, pkg/envoy/ads/response.go, pkg/envoy/ads/secrets.go, pkg/envoy/ads/server.go, pkg/envoy/ads/stream.go, pkg/envoy/xdsutil.go, pkg/errcode/errcode.go
Adds error codes for errors related to Envoy ADS.
Part of #2866
| Demo                       | [ …
=> pkg/envoy/ads: add error codes

.github/workflows/nightly-noinstall.yml
**Description**: Address noInstall nightly job build errors. 
| …
=> test(pipelines): fix noinstall nightly

pkg/envoy/bootstrap/config.go, pkg/envoy/cds/cluster.go, pkg/envoy/cds/response.go, pkg/errcode/errcode.go
Adds error codes for errors related to Envoy CDS.
Part of #2866.
| Demo                       | [ …
=> pkg/envoy/cds: add error codes

pkg/envoy/lds/auth.go, pkg/envoy/lds/connection_manager.go, pkg/envoy/lds/egress.go, pkg/envoy/lds/gateway.go, pkg/envoy/lds/ingress.go, pkg/envoy/lds/inmesh.go, pkg/envoy/lds/listener.go, pkg/envoy/lds/rbac.go, pkg/envoy/lds/response.go, pkg/envoy/lds/tracing.go, pkg/errcode/errcode.go
Adds error codes for errors related to Envoy LDS.
Part of #2866
| Demo                       | [ …
=> pkg/envoy/lds: add error codes

cmd/cli/util.go, pkg/apis/config/v1alpha1/multi_cluster_service_test.go, pkg/envoy/lds/listener.go, pkg/providers/kube/client.go
Merely cosmetic changes to replace an empty slice declaration using a literal with a nil slice declaration (although it does change semantics).
=> Replacing empty slice declaration using a literal with nil slice declaration

tests/framework/common.go
There was a set of conditions a bit convoluted. It has been separated
into a function and a check with additional isolated comments to
hopefully better explain the conditions.
Fixes #3754
Tests                      [x] 
No
No
=> test/common: simplify and further explain cleanup conditions

cmd/osm-controller/osm-controller.go, pkg/k8s/metrics.go, pkg/metricsstore/metricsstore.go
**Description**: Add metric for number of services in the mesh …
=> feat(metrics): add service count

charts/osm/templates/osm-rbac.yaml, pkg/announcements/types.go, pkg/catalog/dispatcher.go, pkg/policy/client.go, pkg/policy/client_test.go, pkg/policy/mock_client_generated.go, pkg/policy/types.go
Adds the informer client and events required to process
the IngressBackend resources.
=> policy/ingress-backend: add informer client and events

pkg/gen/client/config/listers/config/v1alpha1/multiclusterservice.go
The Go client code does not seem to be regenerated after recent
changes. This change updates the client.
=> multicluster: regenerate API client

.github/workflows/openshift-nightly.yml
**Description**: Add nightly job for e2es on OpenShift.
| Demo …
=> test(pipelines): Add openshift nightly job

pkg/catalog/ingress.go, pkg/catalog/ingress_test.go
Builds the ingress traffic policies from the IngressBackend
API.
Part of #3779
=> catalog/ingress: build policy from IngressBackend API

charts/osm/README.md, charts/osm/values.yaml, tests/framework/common.go, tests/framework/common_apps.go
Enable CRD converter by default as a part of OSM control plane
Part of #3396
| …
=> feat(crdUpgrades): enable CRD converter in OSM

pkg/envoy/sds/response.go, pkg/envoy/sds/response_test.go
This change tweaks the SAN validation as follows:
1. Drops inbound SAN validation on the root certificate because
this is already done in 2 places: 1. network RBAC filter on
the inbound listener's filter chain, 2. HTTP RBAC on a route
in the inbound RDS route configuration. Since the same root
certificate will be used to validate both in-mesh and ingress
clients for mTLS, the inbound SAN validation via the root
certificate is dropped in favor of using RBAC to validate
the certificate SAN presented by downstream clients.
2. Configures SAN on the outbound root certificate in permissive
mode to be consistent with SMI mode. This simplifies the code
and makes it consistent, so mTLS verification is consistent
regardless of the traffic policy mode.
Part of #3779
**Affected …
=> envoy/sds: skip inbound SAN validation and verify in permissive mode

tests/e2e/e2e_upgrade_test.go
These changes fix current issues with the upgrade e2e test:
- Remove a check that the `kubectl` executable is present before running
the upgrade e2e test. Because CRDs are now upgraded with hooks in the
Helm chart instead of invoking `kubectl` in the test, this is no
longer necessary.
- Remove the step to reinstall the SMI policy resources, since that is
no longer necessary with the new CRD management.
- Restart the injected Pods to handle incompatible certificate common
name formats between the old and new OSM installations.
| …
=> fix(e2e): upgrade test fixes

tests/e2e/e2e_upgrade_test.go
Updated the upgrade e2e to validate that all the CRD's required by OSM are present on the cluster post and upgrade.
Fixes #3396 
| Upgrade …
=> feat(crdUpgrades): Update upgrade e2e to verify all CRD's are present on the cluster

.env.example
**Description**: Add publish_images var for demo as env variable. 
| CI System                  | [ …
=> demo(env): add publish_images var

.github/workflows/openshift-nightly.yml
**Description**: Add cleanup step for openshift nightly job
| …
=> test(openshift/nightly): Add cleanup step

pkg/errcode/errcode.go, pkg/ingress/client.go, pkg/injector/envoy_config.go, pkg/injector/envoy_config_health_probes.go, pkg/injector/patch.go, pkg/injector/webhook.go, pkg/reconciler/reconciler.go, pkg/validator/patch.go, pkg/validator/server.go, pkg/webhook/webhook.go
Adds error codes related to Ingress, OSM Injector, reconciler, and validator.
Part of #2866
| …
=> pkg/*: add error codes for ingress, injector, reconciler, and validator

.env.example, .github/workflows/openshift-nightly.yml, demo/deploy-bookbuyer.sh, demo/deploy-bookstore.sh, demo/deploy-bookthief.sh, demo/deploy-bookwarehouse.sh, demo/run-osm-demo.sh
**Description**: Edit demo for openshift nightly job and add cleanup step. 
| CI System …
=> tests(openshift/nightly): Change secret creation step in demo

.github/workflows/openshift-nightly.yml
| Demo                       | [] |
| …
=> fix(openshift/nightly): Fix always condition

pkg/config/multicluster.go, pkg/constants/constants.go, pkg/crdconversion/config_multiclusterservice_conversion.go, pkg/envoy/ads/stream.go, pkg/envoy/lds/gateway.go, pkg/providers/kube/multicluster.go
Associate context field with multicluster related log lines.
Issue #3820 
| CI System …
=> chore(multicluster): add field for related log lines

pkg/cli/proxy_get.go, pkg/mesh/mesh.go, pkg/mesh/mesh_test.go
chore(cli): Implement check for pod envoy proxy label.
Addresses comments raised in #3881.
| CI …
=> chore(cli): Implement check for pod envoy proxy label

pkg/k8s/event_handlers.go, pkg/k8s/event_handlers_test.go
Fixes a bug where the new and old objects were
being incorrectly set.
The test added in this change fails without the fix.
=> k8s/event_handler: fix bug in update handler

.github/pull_request_template.md
Add testing summary section to PR template.
This helps PR authors to inform reviewers how the changes are tested.
| Tests …
=> chore: add testing summary to PR template

tests/e2e/e2e_http_ingress_test.go, tests/framework/common_apps.go
Moves the code to install nginx ingress to a helper
function so it can be reused by other tests. Moreover,
testing nginx install steps should not be a part of
the test body.
=> tests/e2e: move nginx ingress install to a helper

tests/e2e/e2e_ingressbackend.go, tests/e2e/e2e_k8s_ingress_http_test.go, tests/framework/common_apps.go, tests/framework/namespace.go
Adds an e2e test that validates ingress using the
IngressBackend API.
Also updated the k8s ingress test name.
Part of #3779
| Ingress                     | [X] |
=> tests/e2e: add ingress test using the IngressBackend API

.gitignore
Ignore lock file that gets generated during
`helm dependency update`.
=> gitignore: ignore Helm dependency lock file

charts/osm/README.md, charts/osm/values.yaml, tests/e2e/e2e_ingressbackend.go, tests/e2e/e2e_k8s_ingress_http_test.go
Enables the IngressBackend policy by default for ingress.
Part of #3779 
=> ingress: enable IngressBackend policy by default

tests/framework/common_apps.go
Small fixes on e2e infra waiter.
no
no
=> e2e: fix variable and missing recovers

tests/framework/common.go
**Description**: Set expected pod count to # of replicas for osm controller restart test. The controller restart e2e explicitly hardcodes the expected osm-controller count to 1, which will thus fail if the number of replicas is increased upon deployment.
| SMI Policy                 | …
=> test(e2e/restart): Set podcount to replica num

.github/ISSUE_TEMPLATE/bug_report.md
Updates the template to include the bug report
generated via osm cli.
=> github: update bug report template

cmd/osm-controller/osm-controller.go, cmd/osm-injector/osm-injector.go, pkg/certificate/providers/certmanager/certificate_manager.go, pkg/certificate/providers/config.go, pkg/certificate/providers/tresor/ca.go, pkg/certificate/providers/tresor/certificate_manager.go, pkg/certificate/providers/vault/certificate_manager.go, pkg/certificate/rotor/rotor.go, pkg/configurator/client.go, pkg/ingress/client.go, pkg/injector/webhook.go, pkg/reconciler/reconciler.go, pkg/validator/patch.go, pkg/validator/server.go
Adds the github issue number to each TODO comment and clarifies
the reason follow-up work might be necessary.
| CI System …
=> chore(metrics): update todos for error code metrics

charts/osm/Chart.yaml
Fixes Helm chart to get it working on EKS Kubernetes clusters. Previously, the install was failing due to kubeVersion being checked too stringently. osm install was returning 
> Error: chart requires kubeVersion: >= 1.18.0 which is incompatible with Kubernetes v1.21.2-eks-0389ca3
as per [Helm's internal issue tracker](https://github.com/helm/helm/issues/3810) >= 1.18.0 would not match 1.18.0-anything, and EKS uses a naming convention that uses dashes after the version, resulting in the above error. This PR resolves the issue, allowing the installation to proceed on EKS clusters
| Install …
=> fix(helm-chart-kubeversion-eks): Fixes Helm chart to install on EKS

charts/osm/README.md, charts/osm/crds/config_meshconfig.yaml, charts/osm/values.yaml
Remove default value settings from MeshConfig CRD. Default values should be defined in `values.yaml`
Addressed issue #3908  …
=> chore: remove default value from meshconfig CRD

docs/dev_guide/openshift/openshift_nightly.md
Document the OpenShift nightly job with troubleshooting tips.
| CI System …
=> docs(openshift): Create OpenShift pipeline TSG

cmd/cli/osm.go, cmd/cli/support.go, cmd/cli/support_bugreport.go, go.mod, go.sum, pkg/bugreport/archive.go, pkg/bugreport/namespace.go, pkg/bugreport/pod.go, pkg/bugreport/run.go, pkg/bugreport/run_test.go, pkg/bugreport/types.go, pkg/kubernetes/util.go, pkg/kubernetes/util_test.go
Backports ea27b738 for release v0.9.2 to be able to generate bug reports.
```
$ osm support bug-report --app-namespaces bookbuyer,bookstore --app-deployments bookbuyer/bookbuyer,bookstore/bookstore
[+] Created staging dir /tmp/osm_bug_report_390083083 to generate bug report
[+] Collecting information about meshed namespaces
✓ Finished generating report for meshed namespaces
[+] Collecting information from individual app namespaces
✓ Collected report from Namespace "bookbuyer"
✓ Collected report from Namespace "bookstore"
✓ Finished generating report for individual app namespaces
[+] Collecting information from individual app …
```
=> [backport] bug-report tool in osm cli

wasm/stats.cc
This change moves the metric definitions for the stats WASM module from
the per-stream `Context` to the persistent `RootContext` to prevent
requests from failing after 1-2 hours in the demo with
`response_code_details` of `wasm_fail_stream`.
I'm not 100% certain this is **the** solution, but I've been running a
cluster with this change and requests have been succeeding for 16+
hours.
Fixes #3958
| Egress                     | …
=> fix(wasm): move metrics handles to RootContext

.gitignore, charts/osm/Chart.lock
Instead of re-negotiating the dependencies every time
during a build, used a fixed dependency corresponding
to the latest released version.
=> charts/osm: used fixed dependency for Contour

.github/pull_request_template.md
Updates the PR template as follows:
- moves `Testing done` section right below the description
- sorts the well-known areas for quicker lookup
- removes unnecessary empty lines
=> github: update PR template

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/mesh_upgrade.go, cmd/osm-bootstrap/osm-bootstrap_test.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml, docs/example/manifests/meshconfig/mesh-config.yaml, pkg/configurator/methods_test.go, pkg/constants/constants.go
Update osm default version to v 0.9.2
| Tests …
=> chore(release): update osm version to v0.9.2

docs/release_guide.md
- Adds section for updating API reference documentation
- Adds section for updating error code documentation
| Documentation              | [ x ] |
| …
=> docs(release-guide): update release guide to include OSM doc updates

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/mesh_upgrade.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml, docs/example/manifests/meshconfig/mesh-config.yaml, pkg/configurator/methods_test.go, pkg/constants/constants.go
Is this a release candidate? Yes
| Install                    | [ ] …
=> chore(release): update version to v0.10.0-rc.1

charts/osm/grafana/dashboards/osm-mesh-envoy-details.json
Adds OSM error graphs to the Grafana dashboard.
Graphs added:
- Average rate of increase of osm errors
- OSM controller errors
- OSM injecter errors
The average rate of increase query could be used to configure alerting. The OSM controller errors and OSM injector errors graphs depict the average increase of errors per minute which more accurately shows the number of errors that have occurred.
An OSM Error Code variable was added to more easily filter the OSM Error graphs by error code.
Known issue:
The OSM error code metric is a vector counter and will expose no data until the counter has been increased for a specified label value. The increase() query used for the OSM controller errors and OSM injector errors graphs will return no data until the counter …
=> grafana: add osm error graphs

pkg/injector/envoy_config_health_probes_test.go, pkg/injector/envoy_config_test.go, pkg/injector/health_probes_test.go, pkg/injector/metrics_test.go, pkg/injector/patch_test.go, pkg/injector/webhook.go, pkg/injector/webhook_test.go
This change adds additional tests to increase unit test coverage in
pkg/injector. No functional changes.
Fixes #3432
**Testing done**: Ran unit tests locally.
| Security …
=> tests(injector): increase coverage

demo/cmd/bookwarehouse/bookwarehouse.go, demo/cmd/database/mysql.go, demo/deploy-apps.sh, demo/deploy-mysql.sh, demo/run-osm-demo.sh, docs/example/manifests/apps/mysql.yaml, go.mod, go.sum
Store total books data in a persisted data store. We choose MySQL in this demo.
The data is saved from bookwarehouse service to MySQL service.
In the books demo, there is actually no relational data model. We used a table to simulate key-value data storage model.
Issue: #3328 
| Observability              | …
=> feat(demo): demo app store data to mysql db

tests/e2e/e2e_deployment_client_server_test.go
Count unique servers which replied in e2e test.
Resolves #1827 .
| Tests …
=> Count unique servers which replied in e2e test.

Makefile
Fix CI break due to merge of stale branch
| Sidecar …
=> Fix CI break due to stale merge

pkg/reconciler/mutating_webhook.go
Update filename of mutating webhook reconciler
=> feat(reconciler): Rename mutating webhook file name

scripts/kind-with-registry.sh, tests/e2e/e2e_http_ingress_test.go, tests/framework/common.go
Backporting change to increase node count for kind cluster to avoid insufficient cpu errors. …
=> backport: Update node count for kind cluster on CI #3813

tests/e2e/e2e_upgrade_test.go
Installs the latest 0.9 patch release for the initial OSM install for the upgrade e2e. The test will then upgrade to the latest commit.
| Performance                | [ ] …
=> test(upgrade): Install latest patch release for upgrade e2e

pkg/envoy/proxy.go
This change changes logs from only including pod metadata like namespace
and name at debug and higher verbosity to being included at every log
level.
Part of #2924
Manual testing and inspecting logs.
| Performance …
=> chore(pkg/envoy): log pod metadata always

docs/automerge.md
Adds documentation for autosquash in the automerge doc
| Documentation              | [x ] |
=> docs(docs): Adds autosquash to automerge doc

pkg/validator/server_test.go
This change adds new tests to pkg/validator to increase its unit test
coverage. No functional changes.
Ran unit tests locally
| Security …
=> tests(validator): increate unit test coverage

.github/workflows/main.yml, .golangci.yml
This change addresses the periodic lint failures due to timeout.
CI on main is currently failing because `golangci-lint` is timing out.
| CI System                  | [ x ] |
| Security …
=> fix(lint): increase golangci-lint timeout

charts/osm/templates/preset-mesh-config.yaml
Adds small fix to tracingAddress for preset-mesh-config.yaml
| Other                      | [ x] |
=> fix(charts/osm/templates): fixes syntax for tracingAddress

Makefile
Adds a common `make` target to build the control
plane that is used by both the linux and windows
build targets.
Also fixes an issue with the VERIFY_TAGS value being
overriden and adds an additional target to publish
the control plane image digests to a file. The image
digests will be made available as a part of a pre-release
workflow to publish the control plane images, and the
digests will be used to encode the default images in
the Helm chart and CLI.
Local build and push.
-   Did you notify the …
=> Makefile: add common target for control plane

tests/e2e/e2e_fluentbit_output_test.go
**Description**: Resolves #3138 by disabling the test
| …
=> fix(e2e): disable flakey fluent bit output e2e

pkg/k8s/event_handlers.go
Updates the k8s api event metric before publishing
an event via the pub-sub framework so API events
can be correlated to changes in the cluster
regardless of pub-sub channels being at capacity or
when blocked. The k8s API event counter is useful
to debug issues related to controller and API server
connectivity.
CI suite
=> event_handlers: update event metric before pub-sub

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/mesh_upgrade.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml, docs/example/manifests/meshconfig/mesh-config.yaml, pkg/configurator/methods_test.go, pkg/constants/constants.go
**Description**: Update version to v0.10.0
| …
=> chore(release): update to v0.10.0

pkg/envoy/ads/cache_stream.go, pkg/envoy/ads/grpc.go, pkg/envoy/ads/jobs.go, pkg/envoy/ads/profile.go, pkg/envoy/ads/response.go, pkg/envoy/ads/secrets.go, pkg/envoy/ads/stream.go, pkg/envoy/cds/response.go, pkg/envoy/eds/response.go, pkg/envoy/lds/response.go, pkg/envoy/proxy.go, pkg/envoy/proxy_test.go, pkg/envoy/registry/registry.go, pkg/envoy/sds/response.go
Streamlines the logging of the proxy object
so that logs are consistent in syntax which
makes it easier to correlate log messages.
Required to simplify debugging for #4167
Verified running the demo locally
=> envoy: streamline logging of proxy object

pkg/k8s/announcement_handlers.go
Check for conflicts before logging an error for failed updates of owner
reference to the k8s secrets. This is necessary when multiple instances
of osm-controller are deployed, as they will all try to update the same
resource and only one of them will update it, which is sufficient.
Fixes #3776
**Testing done**: Manually verified that this error no longer occurs with multiple osm-controllers 
| Documentation …
=> fix(OwnerReferenceUpdates): Handle error logging for owner reference updates

cmd/osm-bootstrap/osm-bootstrap.go, cmd/osm-bootstrap/osm-bootstrap_test.go
=> ref(cmd/osm-bootstrap): add test for getBootstrapPod

charts/osm/templates/cleanup-hook.yaml, cmd/cli/uninstall.go, cmd/cli/uninstall_cluster_wide_resources.go, cmd/cli/uninstall_cluster_wide_resources_test.go, cmd/cli/uninstall_mesh.go, pkg/constants/constants.go
This adds a command `osm uninstall cluster-wide-resources`,
which uninstalls cluster-wide resources that may have been
left over after osm was previously uninstalled
(through `osm uninstall mesh`, through helm, or through
uninstallation in a managed environment).
When `osm uninstall mesh` is run, the helm post-delete hook
is invoked as part of the uninstall process. This deletes:
(1) osm control plane pods (in the osm namespace)
(2) osm control plane secrets (in the osm namespace)
(3) mutating webhook configurations
(4) validating webhook configurations
(5) osm control plane mesh config
OSM CRDs and SMI CRDs are not deleted by the helm
post-delete hook.
Additionally, all of the above are not deleted when osm
is uninstalled from a cluster in a managed environment,
as the helm post-delete …
=> feat(cli): add uninstall cluster-wide-resources cmd

docs/release_notes.md
Adds a release notes doc to track breaking
changes and deprecated functionality. Going
forward, this doc must be updated in the same
PR that introduces such changes.
This is required to correctly track such changes
and document an upgrade path to users based on
the changes that are not backward compatible.
=> docs: add release notes doc

charts/osm/grafana/dashboards/osm-control-plane.json, charts/osm/grafana/dashboards/osm-data-plane-container.json, charts/osm/grafana/dashboards/osm-mesh-envoy-details.json, charts/osm/grafana/dashboards/osm-pod.json, charts/osm/grafana/dashboards/osm-service-to-service.json, charts/osm/grafana/dashboards/osm-workload-to-workload.json, charts/osm/grafana/dashboards/osm-workload.json
Updates remaining Grafana version references from 7.0.1 to 8.2.2.
Verified dashboards functioned as expected while running automated demo,
| Observability              | [ x ] |
| Security …
=> fix(grafana): update grafana version in dashboards

docs/release_guide.md
Updates the osm release guide to reference the instructions for
updating the release version references in the osm docs.
Also fixes broken links in the release guide.
Verified the links were functional and accurate.
| Documentation              | [ x ] |
| …
=> docs(release): instructions for updating release version references

charts/osm/grafana/dashboards/osm-control-plane.json, charts/osm/grafana/dashboards/osm-data-plane-container.json, charts/osm/grafana/dashboards/osm-mesh-envoy-details.json, charts/osm/grafana/dashboards/osm-pod.json, charts/osm/grafana/dashboards/osm-service-to-service.json, charts/osm/grafana/dashboards/osm-workload-to-workload.json, charts/osm/grafana/dashboards/osm-workload.json
Updates the Grafana dashboard descriptions to include the OSM
release version. The version will help distinguish the dashboards
for customers and the uploaded revisions on Grafana labs. 
This PR also includes changes to upgrade the mesh details
dashboard to a version supported by Grafana Labs.
When a release branch is created, the dashboard descriptions will be
updated to the release branch version. For example,
`OSM Control Plane Metrics latest` to `OSM Control Plane Metrics v1.0.0-rc.2.`
Part of #4282 
Verified the dashboards still function as expected when running the
automated demo.
| …
=> fix(grafana): add version to dashboard descriptions

pkg/messaging/broker.go, pkg/messaging/broker_test.go
Triggers a proxy update event when feature flags are modified.
The event is scoped to any feature flag because all the feature
flags are associated with proxy config updates.
- Unit test
=> messaging: trigger proxy update when feature flag is toggled

DESIGN.md
Updated OSM Components & Interactions figure link address
| Documentation              | [ X] |
| …
=> Updated figure link

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml, docs/example/manifests/meshconfig/mesh-config.yaml, tests/e2e/e2e_upgrade_test.go
Is this a release candidate? Yes
=> chore(release): cut v1.0.0-rc.2

cmd/cli/namespace_add.go, cmd/cli/namespace_test.go
Modifies the patch command on `osm namespace add --disable-sidecar-injection`
to set the sidecar injection annotation to "disabled"
instead of null. Patching the annotation key with a null value
should have removed the annotation if it existed or had no effect
if the annotation key did not exist. Currently, when the
sidecar injection annotation does not exist on the namespace, the
patch mentioned above adds the annotation with a value of an empty
string. This results in errors in the osm-injector when pods are
added to the namespace.
Resolves #4385 
This PR also includes a change to notify the user if the namespace
being added is already monitored by the mesh.
```shell
$ osm namespace add test --disable-sidecar-injection
Namespace [test] successfully added to mesh [osm]
$ …
```
=> fix(cli): set sidecar injection annotation to disabled

CONTRIBUTOR_LADDER.md
=> Corrected spelling mistake

CODEOWNERS
It has been a privilege working on this project and with
this group of people. Due to time constraints with my current
job and responsibilities, I'll be unable to continue my role
as a core maintainer on this project. Thank you for the
opportunity.
Best,
Michelle Noorali
Signed-off-by: Michelle Noorali <michelle.noorali@fermyon.com>
| …
=> ref(*): stepping down as maintainer

pkg/apis/policy/v1alpha1/ingress_backend.go, pkg/validator/validators.go, pkg/validator/validators_test.go
Validates `source.kind` of the `IngressBackend` object.
Also updates an error message to be consistent.
Part of #4391
Unit tests
=> validator: validate ingress backend source kind

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml, docs/example/manifests/meshconfig/mesh-config.yaml
Is this a release candidate? Yes
=> chore(release): cut v1.0.0-rc.3

CODEOWNERS, CONTRIBUTOR_LADDER.md
I am nominating @jaellio to be an approver
for the osm repo as they have demonstrated
a good understanding of various areas of the
project while having contributed to core areas
such as observability, logging, tests, docs,
and releases.
**Maintainers**, if you agree with this nomination,
leave a "+1" comment and approve the PR.
=> codeowners: add @jaellio as an approver

charts/osm/templates/osm-controller-hpa.yaml, charts/osm/templates/osm-injector-hpa.yaml
Update HPA yamls from averageValue to averageUtilization
and resolves #4451
| Security …
=> [backport] bug(*): Fix memory targetAverageUtilization

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml, docs/example/manifests/meshconfig/mesh-config.yaml
Is this a release candidate? Yes
=> chore(release): cut v1.0.0-rc.4

demo/cmd/bookstore/bookstore.go, demo/cmd/bookwarehouse/bookwarehouse.go, demo/cmd/common/books.go, demo/cmd/common/const.go
There are some distributed tracing issues with the current demo application.
1. We want to see the tracing graph that connects bookbuyer -> bookstore -> bookwarehouse all together, while currently the chain is broken down into spans.
2. Some users mentioned that the trace ID should be 16 bytes, according to the OpenTracing specification [here](https://www.w3.org/TR/trace-context/#trace-id), while in OSM, the trace ID is 8 bytes, and the first span has the same span ID and trace ID. This can be a potential issue for some customers.
This PR adds extra Zipkin tracing headers to the request in the demo application, so that Envoy can correctly generate tracing information for Jaeger to collect.
Deployed the demo application with `demo/run-demo-osm.sh`, and …
=> Improve distributed tracing

.github/pull_request_template.md
**Description**: Adds a question to the PR template as a gentle reminder that code changes should be accompanied by docs changes. Intended to help keep our docs up to date
| SMI Policy                 | [ ] …
=> chore(github): add docs updation to checklist in pr template

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml, docs/example/manifests/meshconfig/mesh-config.yaml
Is this a release candidate? No
=> chore(release): cut v1.0.0

cmd/cli/metrics_test.go
=> Fixed typo

cmd/cli/uninstall_mesh.go, cmd/cli/uninstall_mesh_test.go
Fixes https://github.com/openservicemesh/osm/issues/4439
**Testing done**: Yes
| CLI Tool                   | [X ] | …
=> Command won`t prompt if mesh is non-existent

pkg/catalog/inbound_traffic_policies.go
Removed unused variable for getRoutingRulesFromTrafficTarget() and buildInboundHTTPPolicyFromTrafficTarget()
Ran package tests
| Other                      | [ x] |
=> chore(pkg/catalog): Remove unused variable

cmd/cli/namespace_add.go, cmd/cli/namespace_test.go, tests/e2e/e2e_ignore_namespace_test.go
PR partially fixes https://github.com/openservicemesh/osm/issues/4445
**Testing done**: Yes
| Security …
=> If ignore label exist don`t add namespace

charts/osm/Chart.yaml, charts/osm/README.md
**Description**: Bump the chart version to 1.0.0 per the release guide.
| …
=> chore(chart): bump chart version to 1.0.0

cmd/cli/install.go, cmd/cli/install_test.go
Warns user that they cannot install a new mesh due to single-mesh-enforcement
and resolves #4438
Install osm with enforce-single-mesh true:
Install osm with enforce-single-mesh false:
| CLI Tool                   | [x ] |
1. Does this change contain code from or inspired by another project?no
2. Is this a breaking change?no …
=> fix(cmd/cli): Show single-mesh-enforced warning

charts/osm/grafana/dashboards/osm-mesh-envoy-details.json
This PR changes Grafana visualization so that
injector timings and cert issuance timings are properly
visualized in the heatmap views.
This PR also adds a distribution histogram view of
the 2 timings as discussed with project maintainers.
This is because the aforementioned heatmap shows
a "histogram time series" view of the timing distributions
per minute, while the 2 new histogram distribution panels
show the "total distribution of all timings over all time".
Resolves https://github.com/openservicemesh/osm/issues/4452.
**Testing done**: Y
Original `idelta()` which does not properly show a "histogram time series":
Fixed - uses `rate()` which now properly shows a "histogram time series" distribution.
Also now shows an absolute …
=> feat(viz): control-plane timings viz improvements

cmd/osm-bootstrap/crds/policy_upstream_traffic_setting.yaml
Adds the CRD for UpstreamTrafficSetting API.
Part of #4500
=> crds: add UpstreamTrafficSetting CRD

docs/development_guide/README.md
Updated software design link
| Sidecar Injection          | [ …
=> doc: Updated broken link

charts/osm/templates/osm-rbac.yaml, pkg/announcements/types.go, pkg/apis/policy/v1alpha1/register.go, pkg/messaging/broker.go, pkg/policy/client.go, pkg/policy/types.go
- Adds the informer client
- Adds plumbing for related events
- Adds the API to the group scheme
- Fixes missing cache sync for Retry client
Part of #4500
=> api/UpstreamTrafficSetting: add informer client

docs/release_guide.md, docs/release_process.md
It is important that as an open source software project we have clarity
and transparency on how releases are handled. This includes the
frequency as well as how the community can request for changes. This
also goes into depth about the lifecycle of a request for change and how
it makes it into a release.
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo …
=> Create release process documentation

go.mod, go.sum
Resolves [CWE-843](https://cwe.mitre.org/data/definitions/843.html).
| Security                   | [X] |
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? N/A.
=> Upgrade docker distribution to v2.8.0

README.md
https://github.com/openservicemesh/osm/issues/379 is closed hence removing the "In Progress" comment from https://github.com/openservicemesh/osm#smi-specification-support
| Documentation              | [x ] | …
=> doc: Removing comment for a closed issue

CONTRIBUTOR_LADDER.md, OWNERS
Adds non-codeowner project maintainer and
clarifies OWNERS vs CODEOWNERS requirement.
=> owners: clarify non-codeowner maintainer

environments.md
**Description**: Added environments.md file to be inline with other open source repositories.
**Testing done**: Markdown file renders correctly and links work
| Documentation              | [ x] |
| Security …
=> doc: add environments.md

cmd/cli/osm.go, cmd/cli/verify.go, cmd/cli/verify_connectivity.go, cmd/osm-controller/osm-controller.go, pkg/cli/verifier/connectivity_pod_to_pod.go, pkg/cli/verifier/connectivity_pod_to_pod_test.go, pkg/cli/verifier/envoy_config_parser.go, pkg/cli/verifier/envoy_config_parser_test.go, pkg/cli/verifier/namespace.go, pkg/cli/verifier/testdata/sample-envoy-config-dump-bookbuyer.json, pkg/cli/verifier/testdata/sample-envoy-config-dump-bookstore.json, pkg/cli/verifier/verifier.go, pkg/smi/client.go, pkg/smi/client_test.go
**Description**: Add unbackported changes from main to release-v1.1 for the v1.1.0 release.
- No merge conflicts, so this exact same code has been tested on main (aside from the version changes for v1.1.0-rc.1)
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? N/A
=> Backport remaining changes for v1.1.0

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml
- [x ] I have cherry-picked any changes [labelled](https://github.com/openservicemesh/osm/labels) `needs-cherry-pick-vX.Y.Z`
- [ x] I have made all of the following version and patch updates:
- [x ] I have checked that the base branch for this PR is correct as defined by the release guide
Is this a release candidate? no
=> chore(release): cut v1.1.0 

README.md
The current state of OSM is that it is currently production-ready. This
PR changes the README to reflect this updated status.
N/A. Documentation only.
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? Yes.
=> Reword the README note about OSM's production readiness

charts/osm/README.md, charts/osm/values.yaml
**Description**: Update default prometheus version to v2.34.0 …
=> update prometheus v2.34.0

pkg/cli/verifier/connectivity_pod_to_pod_test.go, pkg/cli/verifier/envoy_config.go, pkg/cli/verifier/testdata/httpbin1_permissive.json, pkg/cli/verifier/testdata/httpbin2_permissive.json
Adds the destination verifier for connectivity checks.
Also updates the test configs to reflect the name change
made to inbound filter chains in 82492c0b.
Part of #4634
```
$ osm verify connectivity --from-pod curl/curl-7bb5845476-8hggq --to-pod httpbin/httpbin-69dc7d545c-z5l6r --service httpbin --app-protocol http
[+] Context: Verify if pod "curl/curl-7bb5845476-8hggq" can access pod "httpbin/httpbin-69dc7d545c-z5l6r" for app protocol "http"
```
```
$ osm verify connectivity --from-pod bookbuyer/bookbuyer-5c6bc7b74d-r7x5g --to-pod bookstore/bookstore-v1-6bc7859dbf-9c7s8 --service bookstore-v1
[+] …
```
=> cli/verifier: verify destination for connectivity config

docs/release_guide.md
- Backported changes should be included before images are published
- Clarification on version updates
| Sidecar …
=> fix(doc): update release guide

pkg/bugreport/controlplane.go, pkg/bugreport/ingress.go, pkg/bugreport/run.go
Collects more information pertaining to ingress by
avoiding early termination, and fetches control
plane namespace scoped resources.
```
$ osm support bug-report --app-namespaces httpingress --app-deployments httpingress/httpbin --ingress  --osm-namespace kube-system
[+] Created staging dir /tmp/osm_bug_report_1586314353 to generate bug report
[+] Collecting information about meshed namespaces
✓ Finished generating report for meshed namespaces
[+] Collecting information from individual app namespaces
✓ Collected report from Namespace "httpingress"
✓ Finished generating report for individual app namespaces
[+] Collecting information from individual app pods
✓ Collected report for Pod "httpingress/httpbin-69dc7d545c-brbcf"
✓ Finished generating report for …
```
=> bugreport: collect more ingress & control plane info

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml
Is this a release candidate? yes
=> Release v1.1.1-rc.1

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml
Is this a release candidate? No
=> chore(release): cut v1.1.1

cmd/cli/verify.go, cmd/cli/verify_ingress_connectivity.go, pkg/catalog/ingress.go, pkg/cli/verifier/connectivity_ingress_to_pod.go, pkg/cli/verifier/connectivity_pod_to_pod.go, pkg/cli/verifier/envoy_config.go, pkg/cli/verifier/ingressbackend.go, pkg/cli/verifier/sidecar.go, pkg/service/types.go, pkg/trafficpolicy/ingress_types.go, pkg/validator/validators.go
Verifies common configuration settings for ingress traffic
within OSM.
Part of https://github.com/openservicemesh/osm/issues/4634
Failure:
```shell
osm verify ingress --from-service ingress-nginx/ingress-nginx-controller --to-pod httpbin/httpbin-7c6464475-456pn --to-service httpbin/httpbin --ingress-backend httpbin --to-port 14001
[+] Context: Verify if service "ingress-nginx/ingress-nginx-controller" can access pod "httpbin/httpbin-7c6464475-456pn" for app protocol "http" via ingress
Status: Failure
Reason: A verification step failed
Suggestion: Please follow the suggestions listed in the failed steps below to resolve the issue
[++] Context: Verify if namespace "ingress-nginx" is monitored …
```
=> cli/verifier: add ingress verification

tests/framework/common.go
**Description**: Openshift nightly job was failing the e2e_certmanager test. After testing this locally, it seems to be an intermittent issue due to https://cert-manager.io/docs/concepts/webhook/#webhook-connection-problems-shortly-after-cert-manager-installation (as detailed in the InstallCertManager method in common.go). I increased the retry timeout to 20s and ran this locally several times on OpenShift and the issue seems to be mitigated. 
Resolves: https://github.com/openservicemesh/osm/issues/4784
**Testing done**: Ran 10+ times locally on OpenShift and the e2e_certmanager test passed every time. 
| CI …
=> Increase retry timeout cert-manager

cmd/cli/install.go
Uppercase error message edited, part of fixing https://github.com/openservicemesh/osm/issues/4524
**Testing done**: NA
| CLI Tool                   | [x ] |
| SMI Policy                 | [ …
=> cli: Improved error handling

docs/release_notes.md
Adds rate limiting to the v1.2 release notes.
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? `n/a`
=> release-notes: add rate limiting to v1.2 notes

pkg/injector/bootstrap_test.go, pkg/injector/envoy_container.go, pkg/injector/envoy_container_test.go
Fixes #4850
Added unit test for envoy sidecar OS specific components
| Security                   | [X] |
-   Did you notify the maintainers and provide attribution? N/A
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? no
=> Don't allow envoy sidecar privilege escalation

docs/release_notes.md
Add/adjust release notes for completeness
N/A
=> Modify release notes

cmd/osm-healthcheck/osm-healthcheck.go, go.mod, go.sum, pkg/health/health_test.go, pkg/httpserver/httpserver.go, pkg/smi/client_test.go, pkg/webhook/server.go
1. Bump prom client
2. Add ReadHeaderTimeout of 10s
=> fix golints and security scan issues

charts/osm/Chart.yaml, charts/osm/README.md
**Description**: Bumping the Chart.yaml version to match the latest release, per the release guide.
| Sidecar Injection          | [ …
=> chore(release) bump Chart.yaml version to 1.2.0

Makefile
**Description**: Build demo images for linux/amd64 arch
**Testing done**: Pushed to my local dockerhub registry using the docker-build-cross-demo step, and ensured that linux/amd64, windows/amd64, and arm64 were all available for that image. 
| Demo                       | [X] |
| …
=> Build demo images ARM64

Makefile, docs/development_guide/README.md
This adds some instructions on how to build, deploy and update the OSM components
| Security …
=> Give explicit instruction for getting started with Development

cmd/osm-bootstrap/osm-bootstrap.go, cmd/osm-controller/osm-controller.go, cmd/osm-injector/osm-injector.go, pkg/certificate/providers/tresor/fake/fake.go, pkg/crdconversion/crdconversion.go, pkg/crdconversion/crdconversion_test.go, pkg/injector/webhook.go, pkg/injector/webhook_test.go, pkg/k8s/events/types.go, pkg/validator/server.go, pkg/webhook/server.go, pkg/webhook/server_test.go
Fixes: https://github.com/openservicemesh/osm/issues/4817
This PR subscripts to updates to certificate changes for the webhooks and uses existing code that will update the Webhook CRD configuration.
Builds on functionality added in: https://github.com/openservicemesh/osm/pull/4833 which added ability to patch the configurations but wasn't listing to the cert changes produced.
-
| …
=> feat(certs): update webhooks to handle root certificate rotations

DESIGN.md, docs/identity.md
After doing research for #4750, I've written up what I've learned about Idenity in OSM and how it is used.  This describes how an Identity for a Pod is created and used with Envoy. …
=> Detailed documentation on Identity in OSM

pkg/envoy/sds/builder.go, pkg/envoy/sds/response.go, pkg/envoy/sds/response_test.go, pkg/envoy/sds/types.go, pkg/errcode/errcode.go
Description: 
Leverage builder pattern in SDS resources generation. 
Resolves issue #4922 
Signed-off-by: Whitney Griffith <whitney.griffith16@gmail.com> …
=> ref: leverage builder pattern for sds

docs/release_notes.md
Adds global rate limiting to the list of notable
changes for v1.3.0.
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? `n/a`
=> docs: add global rate limit to v1.3.0 release notes

docs/development_guide/openshift/openshift_nightly.md
**Description**: Add documentation for updating the OpenShift cluster used in the nightly job. 
Part of: https://github.com/openservicemesh/osm/issues/5003
**Testing done**: Local testing on OpenShift nightly job cluster to perform upgrades. Also results of nightly job, which is now unblocked: https://github.com/openservicemesh/osm/runs/7889995412?check_suite_focus=true
| Egress …
=> Document openshift update process

pkg/certificate/providers/tresor/fake/fake.go
#5116 had tests passing but https://github.com/openservicemesh/osm/pull/5115 merged inbetween tests running and github doesn't rebase before merging (?!)
| Performance …
=> Use new issue cert api introduced in #5116

docs/development_guide/README.md
Addresses feedback after having a few folks set up tilt.
| Tests …
=> Update Tilt instructions

pkg/envoy/bootstrap/config_test.go
Fix flakiness in health probe tests due to using a map data structure
Fixes #5162 
`go test ./pkg/envoy/bootstrap --run TestBuild -count 10`
| Performance                | …
=> Fix health probe test flakiness

pkg/envoy/bootstrap/config_test.go
**Description**: Adds values to bootstrap test for keepalive changes made in #5189 
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? n/a
=> test(envoy/bootstrap): add keepalive values to bootstrap test

pkg/injector/webhook.go, pkg/injector/webhook_test.go, pkg/validator/patch.go, pkg/validator/patch_test.go, tests/e2e/e2e_spiffe_test.go
The name space selectors must be in a specific format https://github.com/kubernetes/kubernetes/issues/92157#issuecomment-825160958. This was causing the webhook to not run validation.
Once those are turned on there is a bug in the upgrade e2e test that leave a webhook around becuase the version of the webhook label is not upgraded and there for not removed by our tooling.
This was found during #5182
| CI System                  | [x] |
| Demo …
=> Fix Namespace selector & ensure correct webhook version

pkg/catalog/mock_catalog_generated.go, pkg/certificate/manager.go, pkg/certificate/mrc_reconciler.go, pkg/certificate/providers/mrc.go, pkg/compute/mock_compute_client_generated.go, pkg/k8s/client.go, pkg/k8s/informers.go, pkg/k8s/mock_controller_generated.go, pkg/k8s/types.go
Adds MRCResyncInterval which is half the MrcDurationPerStage and resolves #5176
| Certificate Management     | [x ] |
=> feat(cerst): Adds MRCResyncInterval

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, docs/release_notes.md
Bumping the Chart.yaml version per the release guide
| Other                      | [ x] |
=> chore(release) bump Chart.yaml version to 1.1.3

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, docs/release_notes.md
Bumping Chart.yaml to 1.2.2 per the release guide
| Other                      | [ x] |
=> chore(release): Bump Chart.yaml to 1.2.2

docs/release_guide.md
Adds command examples on how to backport changes in addition to example pull requests and resolves #5217
=> doc(release): Update release guide

pkg/bugreport/run_test.go, tools.go
**Description**: Formatted according to gofmt -s for clear gofmt score https://goreportcard.com/report/github.com/openservicemesh/osm
**Testing done**: yes
| SMI Policy …
=> Gofmt error removed

cmd/osm-bootstrap/osm-bootstrap_test.go, pkg/certificate/fake_manager.go
Addresses PR feedback for #5201 
Related to issue: #5198 
Re-ran certificate package unit tests
| Certificate Management     | [X] | …
=> nit(certificates): Address PR 5201 feedback

charts/osm/templates/preset-mesh-root-certificate.yaml, cmd/cli/certificate_rotate.go, cmd/cli/certificate_rotate_test.go, cmd/osm-bootstrap/crds/config_mesh_root_certificate.yaml, cmd/osm-bootstrap/osm-bootstrap.go, cmd/osm-bootstrap/osm-bootstrap_test.go, pkg/apis/config/v1alpha2/meshrootcertificate.go, pkg/catalog/inbound_traffic_policies_test.go, pkg/certificate/errors.go, pkg/certificate/mrc_reconciler.go, pkg/certificate/mrc_reconciler_test.go, pkg/certificate/providers/config.go, pkg/certificate/providers/config_test.go, pkg/certificate/providers/tresor/fake/fake.go, pkg/errcode/errcode.go, pkg/k8s/client_test.go, pkg/validator/validators.go, pkg/validator/validators_test.go, pkg/webhook/server_test.go, tests/e2e/e2e_meshrootcertificate_test.go
Updates the MRC intent field to role.
Resolves #5222 
- CI
=> ref(certs): update MRC intent field to role

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, docs/release_notes.md
Is this a release candidate? no
Image digests: https://github.com/openservicemesh/osm/actions/runs/3690857830/jobs/6248301694
=> Release v1.2.3

CODEOWNERS, OWNERS
I no longer have the time to dedicate to this project, so I
am transitioning myself to emeritus status.
Good luck to everyone.
=> maintainers: transition myself to emeritus status

CODEOWNERS, OWNERS
Since I'm no longer active in the project, I'm moving myself to emeritus status. Thanks everyone!
You all know where to find me!
=> Stepping down as maintainer

README.md
The demonstration`s description states how to step by step deploy apps, the earlier link doesn't point to the same in docs hence updating.
| Documentation              | [x ] |
| Performance                | [ …
=> Updated demonstration description

cmd/osm-bootstrap/osm-bootstrap.go, dockerfiles/Dockerfile.init, pkg/reconciler/client.go, tests/e2e/e2e_reconciler_test.go
=> [backport] cherry-pick b3b0f9a1 to release-v1.1

go.mod, go.sum
=> [backport] build(deps): bump github.com/docker/docker (#5315)

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, docs/release_notes.md
=> chore(release): bump version to v1.1.4 and update release notes

README.md
Updating project status to inform community that the project is proposed for archive status with the CNCF. 
Testing not applicable.
| Security …
=> project status update
