docs/patterns/ingress.md
Previously, OSM only supported HTTPS ingress. Since both HTTP and HTTPS
backends are supported with ingress, updates the document to reflect
the current behavior.
Resolves #1251
=> docs/ingress: update ingress doc in lieu of HTTP being the default

CONTRIBUTING.md
Updates the project's contributing guide to reflect existing
guideline being followed, and the workflow to create PRs
not ready for review or merge.
=> chore(contributing): update contributing guide with PR workflow

docs/patterns/observability.md
without the root slash it's relative to current filepath - which is wrong.
=> Fix Obersvability gif absolute path

demo/run-osm-demo.sh
Rerunning the demo in specific environments results in an error because the existing
namespace is not deleted prior to recreation:
Error from server (AlreadyExists): namespaces "osm-system" already exists
=> demo: cleanup stale namespace before recreating

pkg/envoy/cds/cluster.go, pkg/envoy/cds/cluster_test.go, pkg/envoy/cds/response.go, pkg/envoy/cds/response_test.go, pkg/envoy/lds/listener.go, pkg/envoy/lds/listener_test.go
When operating in permissive traffic policy mode, OSM relies on native
kubernetes networking to route traffic to services. Since Kubernetes
is already aware of how to discover and route traffic to services,
rely on this instead of the control plane to explicitly program and
discover endpoints. This change makes the controller logic simpler for
permissive mode and is an optimization over the current implementation.
The change also moves the ListenerFilters in the outbound listener to the
mesh filter chain since the mesh traffic requires them as well, and removes
the unused TlsInspector filter.
Resolves #1403
- Does this change contain code from or inspired by another project? `no` (If so, did you notify the maintainers and provide …
=> envoy/permissive-mode: use cluster service discovery and routing

docs/development_guide.md
Continuous was misspelled. 
- [X ] Documentation
=> Fix typo in dev guide

charts/osm/templates/osm-deployment.yaml, cmd/cli/install.go, cmd/cli/install_test.go, cmd/osm-controller/osm-controller.go, demo/run-osm-demo.sh, docs/patterns/certificates.md
Cert-manager as a CLI argument is misleading, wherein it confuses the
user with the open source project by Jetstack called cert-manager.
Switching to a more descriptive argument name to capture the meaning and
not cause in confusion.
Signed-off-by: Nitish Malhotra <nitish.malhotra@gmail.com>
Resolves #1440
- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? no
=> Switch from cert-manager to certificate-manager

docs/development_guide.md
Fixes the development_guide.md to have the proper makefile command displayed for make go-test
No
=> docs(development/guide): fixes docs for makefile go-test rule

docs/example/manifests/bookstore-v2/bookstore-v2.yaml
The automated demo and helper scripts use port 80 for the bookstore-v2
service. Use the same port so that the scripts can be reused with
the manual demo workflow.
- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? `No`
=> example/manifests: update bookstore-v2 port to 80

pkg/envoy/rds/response.go, pkg/envoy/route/config.go, pkg/envoy/route/config_test.go
The current code relies on passing bools around for source/destination
route configs and if the route corresponds to a local cluster. This can
be confusing and hard to understand if one does not know how these
booleans are interpreted in the code.
This change simplies the logic by introducing the concept of a direction
for a route. Routes can be outbound (to reach a remote service), or
inbound (to accept traffic on the local cluster host). Since the route
configurations are already using Inbound/Outbound terminology, updates
the variable names to reflect this.
There is no functional change introduced in the code, and the routing
logic remains as before.
- CLI Tool …
=> envoy/rds: use route direction while creating routes

docs/patterns/egress.md, docs/patterns/ingress.md
Inspired by Christian Posta's demo https://www.youtube.com/watch?v=eFawBTtoJmE,
to use a one liner to update the ConfigMap. This makes it easier to
run and automate as opposed to the `kubectl edit` command.
Also removes `$` from command blocks and uses the `bash` markdown
syntax for consistency, which is an alias for `shell, sh, zsh`. …
=> docs: use patch command to edit ConfigMap

pkg/envoy/eds/response.go, pkg/envoy/eds/response_test.go
This change adds adds tests for EDS. It improves the
test coverage from 0% to 80%. A subsequent change
will refactor the code further to make the existing
code more unit testable.
Part of #1489 
`No`
=> envoy/eds: add test for EDS response

pkg/endpoint/providers/kube/client.go, pkg/endpoint/providers/kube/client_test.go
Part of a recent effort to strengthen the test coverage accros the repo.
`pkg/endpoint/providers/kube	0.135s	coverage: 79.6% of statements`
No
=> tests: adding coverage for kube endpoint provider

.github/workflows/main.yml
This change will push Docker images tagged with the git sha of the commit on each push to the main branch. Since this is added to the main CI workflow, new images will not be pushed when only docs change.
Fixes #1492 
- Does this change contain code from …
=> feat(ci): push images on each push to main

pkg/catalog/routes.go
Instead of using `namespace/svc`, the policy was incorrectly
stringifying the k8s service object.
Resolves #1503
`No`
=> catalog/routes: fix naming for TrafficTarget policy

pkg/certificate/providers/vault/certificate_manager_test.go
Adding unit tests to `pkg/certificate/providers/vault`
```
$ go test -cover ./pkg/certificate/providers/vault/...
ok      github.com/openservicemesh/osm/pkg/certificate/providers/vault  0.005s  coverage: 13.6% of statements
```
```
$ go test -cover ./pkg/certificate/providers/vault/...
ok      github.com/openservicemesh/osm/pkg/certificate/providers/vault  3.051s  coverage: 51.9% of statements
```
This PR partially addresses https://github.com/openservicemesh/osm/issues/1489
---
- Security …
=> certificates: Unit tests for Hashicorp Vault integration

DESIGN.md, pkg/catalog/debugger.go, pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/endpoint/providers/azure/kubernetes/client.go, pkg/endpoint/providers/azure/kubernetes/errors.go, pkg/endpoint/providers/azure/provider.go, pkg/endpoint/providers/kube/client.go, pkg/endpoint/providers/kube/errors.go, pkg/smi/client.go, pkg/smi/errors.go, pkg/smi/fake.go, pkg/smi/types.go
Previously we added type assertions for kubernetes resources in their
caches. These type assertions can only result from bugs in the code
if there is a mismatch between the resource type in the informer
and the code that asserts for the resource type in the informer cache.
Such a scenario is not possible to test if the code is correct (as is
the case now), and the code must be buggy for a potential unit test
to even be able to test such mismatches. Its also not possible for
such a bug to creep in because the tests would panic and fail.
This change removes such checks in the informer caches since its not
possible to even unit test the need for such code. It also simplifies
the return values of some functions that were only returning an error
for these scenarios.
- New Functionality      [ …
=> pkg/*: remove type assertions that can be safely asserted (dead code)

charts/osm/templates/osm-configmap.yaml
This PR adds updates the configmap to show zipkin related values only when zipkin tracking is enabled in OSM
=> zipkin : Updating configmap for zipkin

DESIGN.md, go.sum, pkg/smi/client.go, pkg/smi/client_test.go, pkg/smi/fake.go, pkg/smi/types.go
The SMI client has a lot of code but no tests.
`github.com/openservicemesh/osm/pkg/smi  coverage: 0.0% of statements`
This change uses fake kubernetes clients to test all the functions that
implement the MeshSpec interface. It also removes dead code.
It helps improve the code coverage from 0.0% to 74.6%.
`github.com/openservicemesh/osm/pkg/smi coverage: 74.6% of statements`.
Due to some limitations of fake kubernetes clients such as not being
able to enforce label selector semantics with client informers and
caches, a few code paths repeated in each function are not testable.
Part of #1489
- …
=> smi/test: add test coverage for pkg/smi

.github/workflows/release-chart.yml, .github/workflows/release.yml, docs/release_guide.md
Publish './charts' to gh-pages branch on git tags with 'chart' prefix.
Signed-off-by: stefanprodan <stefan.prodan@gmail.com>
Ref: #1424 
* create OSM release
* wait for the container image to be pushed to Docker Hub
* set the container image tag in `charts/osm/values.yaml` and `charts/osm/Chart.yaml`
* bump the chart version in `charts/osm/Chart.yaml`
* create a PR with the above changes and merge it to main
* create a git tag from main in the format `chart/vx.x.x` where `vx.x.x` is the chart version
* push the git tag to origin
* GH Actions runs [helm-gh-pages](https://github.com/stefanprodan/helm-gh-pages) that packages the charts, updates `index.yaml` and pushes the changes to `gh-pages` branch
* GH Pages publishes the new version, making the chart available at …
=> Add Helm chart release workflow

docs/example/README.md
This PR just adds the `--all-namespaces` flag to the `kubectl get svc` command. All of the demo app services are namespaced, so without the flag, it doesn't return any services.
- Does this change contain code from or inspired by another project? No.
=> Minor doc update: services are namespaced

charts/osm/values.yaml, cmd/cli/install.go, demo/run-osm-demo.sh
Both Zipkin deployment and tracing config
are being marked as disabled by default.
Both of the options are still configurable
at config/install time.
---
No
=> Disable zipkin by default

docs/example/README.md
I believe it's just a minor writing mistake, but I have to submit a PR ( avoiding to mislead people ) cuz up to this point ( before deploying traffic split policy for bookstore v2 ), using kubectl describe trafficsplit bookstore-split -n bookstore command will see bookstore v1 still have 100% weight of the traffic sending through. And after that point, it works pretty well to lift 100% traffic to bookstore v2 and it can be adjusted using traffic split policy.  Like this demo ! Simple and well-explained ! …
=> Update guidance traffic split bookstore v2

pkg/smi/client_test.go
This comment was added during debugging an issue while developing
the test with fake caches. It no longer holds true.
`No`
=> smi/test: remove comment left behind during development

.github/workflows/main.yml
A few CI runs are failing due to the CI timing out just
before the test passes. This change makes the CI timeout
consistent for tests and increasing the timeout by a bit
to give slower CI runs a chance to pass.
`No`
=> ci: use consistent wait times across test scenarios

.github/workflows/main.yml
Only the nosplit integration test is meant to run without traffic
split. This change makes the cert-manager scenario testable with
SMI policies similar to the `tresor` scenario.
`No`
=> ci: run cert-manager scenario with SMI policies enabled

.github/workflows/main.yml
This reverts commit 5e711564bc7a9b0ff011ec034ede06c22e13dbc3.
Commit 5e711564bc7a9b0ff011ec034ede06c22e13dbc3 accidentally changed
the wrong test.
`No`
=> Revert "ci: run cert-manager scenario with SMI policies enabled (#1549)"

pkg/configurator/client.go
This PR updates the way the optional values in the osm-config configmap are assigned. It fixes #1543 
- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? `No`
=> Updating assignment of optional values in osm-config ConfigMap

DESIGN.md, pkg/catalog/routes.go, pkg/catalog/service.go, pkg/catalog/types.go
Returns a list of services instead of a single service for a given service account 
No
=> feat(mesh catalog): Return list of services for a given service account

pkg/endpoint/providers/kube/client_test.go
Using channel instead of expect/time based wait.
No
=> Address proper handling of assync behavior on test

docs/example/README.md, scripts/port-forward-all.sh, scripts/port-forward-bookbuyer-ui.sh, scripts/port-forward-bookstore-ui-v1.sh, scripts/port-forward-bookstore-ui-v2.sh, scripts/port-forward-bookthief-ui.sh
fixes #1483
This allows users to specify port numbers for the Bookstore Demo Applications.  It will prompt with the default port numbers but these can be changed.  The port-forward-ui scripts can be run individually or from port-forward-all.sh
- Does this …
=> Updated Bookstore Demo Apps requesting custom port number

pkg/debugger/fake.go, pkg/health/fake.go, pkg/httpserver/httpserver.go, pkg/httpserver/httpserver_test.go, pkg/httpserver/types.go
Adds HTTPServer test coverage.
Adds fakes for Probes and DebugServer, which are needed
for HTTPServer class.
`0.0%` -> `89.5%`
No
=> tests: HTTPServer test coverage

pkg/envoy/ads/response_test.go, pkg/envoy/ads/server.go, pkg/envoy/ads/stream.go
I find going through the `getHandlers()` to take more cycles while reading or reasoning about this code than if the list of XDS handlers was directly in the struct.
To make this slightly more readable - removing `getHandlers()` 
---
- Control Plane          [ x ] …
=> ads: Simplify and delete getHandlers()

pkg/httpserver/httpserver.go, pkg/httpserver/httpserver_test.go
Check for ErrServerClosed before calling Fatal() since ListenAndServe
will return this error when the server is shutdown.
Also fixes linting issues.
Resolves #1562
`No`
=> httpserver: fix test which fails when the server is stopped

Makefile, cmd/cli/version.go, cmd/osm-controller/osm-controller.go, pkg/health/health.go, pkg/version/version.go
This PR adds version info to the liveness and readiness probes, also prints version info as the very first line of the OSM Controller stdout.
In this PR:
- OSM CLI and Controller will reuse the same `pkg/version` for storing these values
- added `VersionInfo` struct to help create a JSON string for liveness/readiness probes
- removed unused `PrintVersionAndExit()`
Result:
```
$ ./demo/tail-osm-controller-logs.sh | head
{"level":"info","component":"osm-controller/main","time":"2020-08-17T20:28:20Z","file":"osm-controller.go:110","message":"Starting osm-controller v0.1.0-rc.1; 247062da; 2020-08-17-13:27"}
```
```
$ ./bin/osm version
Version: dev; Commit: 247062da; Date: 2020-08-17-13:27
```
---
- Documentation          [ …
=> version: Set Version variables; Show in liveness/readiness probes

cmd/osm-controller/osm-controller.go, pkg/envoy/ads/response.go, pkg/envoy/ads/response_test.go, pkg/envoy/ads/server.go, pkg/envoy/ads/types.go, pkg/envoy/cds/response.go, pkg/envoy/cds/response_test.go, pkg/envoy/eds/response.go, pkg/envoy/eds/response_test.go, pkg/envoy/lds/response.go, pkg/envoy/rds/response.go, pkg/envoy/sds/response.go
This PR removes unused parameters passed to the XDS handlers, as well as fields in of the ADS struct.
---
- Control Plane          [ x ]
=> ads: Simplify XDS Handlers

docs/design/uninstall_osm.md
This PR adds documentation for the design of `osm mesh delete`. While this command is already implemented, the document gives context on the feature, motivation, and future direction.
- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? No. I took a look at how Kubernetes …
=> docs(*): add design doc for uninstalling osm

DESIGN.md, pkg/catalog/types.go, pkg/catalog/xds_certificates.go, pkg/catalog/xds_certificates_test.go, pkg/envoy/ads/response.go, pkg/envoy/ads/stream.go, pkg/envoy/cds/response.go, pkg/envoy/eds/response.go, pkg/envoy/lds/response.go, pkg/envoy/rds/response.go, pkg/envoy/sds/response.go
Return a list of services for an envoy certificate instead of just the first one
No
=> feat(envoy): Return list of services in GetServiceFromEnvoyCertificate

.github/workflows/main.yml, .golangci.yml, Makefile, docs/development_guide.md, go.mod, go.sum, scripts/pre-push-hook, tools.go
This PR standardizes on `golangci-lint` as the primary static analysis tool for source code across the Makefile, other scripts, and CI. The initial settings only point out new issues (based on git history) and enable all linters (per @draychev). I expect we'll tweak settings as we go, but if we find it's too restrictive we can override the return code to 0 to prevent CI from failing while still showing issues it found.
Some standalone `go vet`, `go lint`, and `go fmt` checks have been removed since `golangci-lint` uses them under the hood.
One notable difference is that by default, `golangci-lint` ignores the ever-popular `exported method should have a comment or be unexported` and …
=> ref(*): Integrate golangci-lint

cmd/cli/install.go, cmd/cli/install_test.go, cmd/cli/namespace_add.go, cmd/cli/namespace_test.go
fixes: https://github.com/openservicemesh/osm/issues/1196
This has changes to return an error when a user tries to add a namespace which has osm control plane running in it.
todo:
=> fix(cli): osm namespace add should fail when adding osm-system NS

pkg/envoy/route/config.go
The field max_program_size in v3.RegexMatcher.GoogleRE2 is
deprecated, so this change removes it.
`No`
=> envoy: remove deprecated field in RegexMatcher proto

.golangci.yml
+ we had go-vet, gofmt and go-lint enabled before
using golangci-lint, so I've re-enabled that setting
using golangci-lint. Let's iteratively add linters. …
=> chore(*): specify linters to run

pkg/configurator/client.go, pkg/configurator/errors.go
Debug logs shouldn't log errors, remove error tag to prevent the
logger from logging unnecessary error fields in the logs. This
log statement is intended to be Debug level, as changed by PR #1547.
`No`
=> configurator: remove error field from debug log

pkg/catalog/service.go, pkg/endpoint/providers/azure/provider.go, pkg/endpoint/providers/kube/client.go, pkg/endpoint/providers/kube/client_test.go, pkg/endpoint/providers/kube/errors.go, pkg/endpoint/providers/kube/fake.go, pkg/endpoint/types.go
Providers should return all associated services for a service account, not just 1.
No
=> feat(providers): Update providers to return list of services for a service account

ci/cmd/maestro.go, pkg/constants/constants.go, pkg/injector/init-container.go, pkg/injector/patch.go, pkg/injector/sidecar.go
This commit adds the output for both Envoy containers
and Init containers in-mesh directly on stdout,
for CI maestro logging.
To follow up with folks to see if this is something
we want through this output form.
No
=> Retrive logs for all containers in CI

pkg/envoy/cds/cluster.go, pkg/envoy/cds/cluster_test.go, pkg/envoy/cds/response_test.go
Currently OSM does not honor the protocol version of downstream
connections. As a result, HTTP2 clients are unable to route traffic
to HTTP2 servers. By default, Envoy uses HTTP 1.1 if
http2_protocol_options is not configured, as is the case now.
This change configures Envoy to use a HTTP protocol version
based on the downstream connection, allowing both HTTP1.1 and
HTTP2 clients to be able to route traffic. Default values
are used for the http2_protocol_options, but option must be
explicitly set as a part of the cluster config.
This change is primarily useful for HTTP2 connections over
plaintext, ex. with `grpc.WithInsecure()`.
Testing done:
```
curl -v --http2 -H "client-app: bookbuyer" \
-H "user-agent: Go-http-client/1.1" \
http://bookstore.bookstore/books-bought
< HTTP/1.1 200 OK
< …
```
=> envoy/cds: use downstream connection for HTTP protocol selection

pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/catalog/xds_certificates.go, pkg/endpoint/providers/kube/client_test.go, pkg/utils/service.go, pkg/utils/service_test.go
Use K8sSvcToMeshSvc helper function to convert between corev1.Service and service.MeshService
No
=> ref: Use K8sSvcToMeshSvc util

pkg/endpoint/providers/kube/client_test.go
This changes modifies a flaky test not to rely on the order of services
returned from `GetServicesForServiceAccount()`.
No
=> test(kube endpoints): fix flaky test

pkg/smi/client.go, pkg/smi/types.go
Renames the import aliases and types to reflect the core
package. Also renames the informer for the HTTPRouteGroup
resource since the informer is specific to that kind.
`No`
=> smi/client: rename import and objects to reflect pkg group

pkg/envoy/ads/response_test.go
=> ads, test: use 'new' instead of manual object creation

.env.example, cmd/cli/install.go, cmd/cli/install_test.go, demo/run-osm-demo.sh
Commit a42c772 changed the default pull policy for
OSM images to `IfNotPresent`, which breaks local
testing where the same CTR_TAG is used across
reruns of the demo. As a result, when a new change
is made locally and the demo is rerun, they don't
get picked by the demo. Even using the git SHA as the
default tag will not solve this problem because an
amended commit will have the same image tag.
This change makes the image pull policy configurable
in the install cli, with the default being set
to `IfNotPresent` as before. The demo is updated
to set the pull policy to `Always` so that rerunning
the demo always picks up the latest built image,
irrespective of the tag.
Resolves #1605
- …
=> install: make OSM ImagePullPolicy configurable

pkg/catalog/routes_test.go, pkg/endpoint/providers/kube/client_test.go, pkg/smi/client_test.go
This test previously flaked if the elements were returned in a different order. Using `BeElementOf` to avoid dependency on ordering …
=> test: Fix ListAllowedOutboundServices test flake

DESIGN.md, pkg/catalog/ingress.go, pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/catalog/types.go, pkg/envoy/rds/response.go, pkg/envoy/rds/response_test.go, pkg/envoy/route/config.go, pkg/envoy/route/config_test.go, pkg/tests/fixtures.go, pkg/trafficpolicy/types.go
Currently the code refers to an HTTPRoute as a Route in a traffic target
policy. Rename this to HTTPRoute to be explicit. In the future, a route
for different traffic types will be supported, ex. TCPRoute.
This also helps disambiguate the HTTP route type in the traffic target from
the XDS Route type in Envoy. …
=> Rename Route type to HTTPRoute where applicable

docs/issue_triage_guide.md
Adds a guide with steps for triaging OSM's GitHub issues
- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? no
=> docs(issue triage): add issue triage guide for github issue queue

cmd/cli/install.go
I was reviewing this code with the new folks on the team and realized it could use a little re-organization to make it easier to understand what is happening.
* No functional code changes
* Adds comments in line
=> ref(cmd/cli): isolate install validation logic

scripts/test-w-coverage.sh
The test output will be shown because of the `tee` command, so printing it again if the tests fail is redundant.
No
=> ref(tests): remove duplicate test output when tests fail

pkg/catalog/routes_test.go
Don't enforce the order of traffic policies returned by `getTrafficPoliciesForService()`.
No
=> tests(catalog): fix flaky test

cmd/osm-controller/osm-controller.go
+ clean up azure references
+ remove TODO line around cobra - don't think we need to
switch to using cobra as this isn't a user facing cli
tool that needs all the functionality cobra provides
=> ref(cmd/osm-controller): rm unused Azure vars

cmd/cli/namespace_add.go, cmd/cli/namespace_remove.go, cmd/cli/namespace_test.go, demo/join-namespaces.sh, demo/run-osm-demo.sh, docs/example/README.md, docs/onboard_services.md, docs/patterns/sidecar_injection.md, pkg/constants/constants.go, pkg/injector/types.go, pkg/injector/webhook.go, pkg/injector/webhook_test.go
Currently it is not possible to enroll specific pods within
the mesh for sidecar injection without enrolling the entire
namespace. This behavior is not desirable when several
application pods run in the same namespace and only certain
pods need to be enrolled in the mesh with a sidecar.
This change decouples the sidecar injection for pods from
the namespace monitoring workflow.
A pod will be injected with the sidecar if its namespace
is monitored, and either of the following are true:
1. The pod is explicitly enabled for injection
2. The namespace is enabled for injection and the pod
is not explicitly disabled for injection
This change also extends the `osm namespace add` command
with an `--enable-sidecar-injection` flag which automatically
adds the sidecar injection annotation on the …
=> sidecar-injection: provide granular control for injection

cmd/osm-controller/osm-controller_test.go
The test hardcodes the expected length for a certificate, compare
the certificate content instead. An issue was seen when the Go
version was updated, possibly resulting from a change in a lib
used for generating the certs. This change removes the length
check and directly compares the certificate.
Resolves #1635
- Does this change contain code …
=> osm-controller/test: compare cert for equality instead of its length

cmd/osm-controller/certificates.go, cmd/osm-controller/osm-controller.go, cmd/osm-controller/validate.go, cmd/osm-controller/validate_test.go
This PR restructures how we do CLI parameter validation and adds tests for validation. It also re-organizes how we set up the certificate manager and debugger (certificate.Manager, debugger.CertificateManagerDebugger). With this PR, code coverage for `cmd/osm-controller/` goes from 27.20% to 38.1%. These changes are part of a larger re-factor and effort to make the `cmd/osm-controller/` more readable and testable and more changes are to come after this.
- Tests / …
=> ref(cmd/osm-controller): simplify validation, certificate manager setup

.github/workflows/main.yml, .github/workflows/release.yml, Dockerfile, Makefile, demo/README.md, dockerfiles/Dockerfile.bookbuyer, dockerfiles/Dockerfile.bookstore, dockerfiles/Dockerfile.bookthief, dockerfiles/Dockerfile.bookwarehouse, dockerfiles/Dockerfile.init, dockerfiles/Dockerfile.osm-controller, docs/development_guide.md, go.mod
This PR updates go to 1.15 and alpine to 3.12.
It also removes the patch version from these dependencies to allow for implicit patch upgrades which are considered non-breaking but often include important security fixes.
In addition I added `-s -w` to the ldflags for `osm` and `osm-controller` to remove debug symbols.
Size Before:
`55M	bin/osm-controller/osm-controller`
After:
`39M	bin/osm-controller/osm-controller`
- Other …
=> Rev go to 1.15 & alpine to 3.12

.env.example, .github/workflows/main.yml, demo/deploy-apps.sh, demo/deploy-bookstore-with-same-sa.sh, demo/deploy-traffic-target-with-same-sa.sh, demo/run-osm-demo.sh
This PR has changes in the scripts for the automated demo to depicting the support of multiple services with one service, which can be enabled/disabled anytime with the use of a environment variable `DEPLOY_WITH_SAME_SA` 
The CI has also been updated to test this scenario …
=> (automated demo) : Update  automated demo to support multiple services per service account

pkg/endpoint/types.go
Rewords a few comments in the endpoint.Provider interface for clarity.
`No`
=> endpoint/provider: reword comments for types

cmd/osm-controller/certificates.go, cmd/osm-controller/osm-controller.go, cmd/osm-controller/validate_test.go
+ cleans up azure related and azure key vault related code
since we do not support azure VMs or AKV at this time
=> ref(cmd/osm-controller): rm unused keyvault refs

charts/osm/templates/osm-rbac.yaml, pkg/smi/client.go, pkg/smi/client_test.go, pkg/smi/fake.go, pkg/smi/types.go, pkg/tests/fixtures.go
Adds the informer, cache, and an API to retrieve the
TCP routes.
Part of #1521
`No`
=> smi/client: add API to fetch TCP routes

.env.example, .github/workflows/main.yml, ci/cmd/maestro/kubernetes_tools.go, ci/cmd/maestro/types.go, demo/README.md, demo/cmd/common/const.go
The clientcmd package in k8s.io/client-go provides helpers for getting a
kube config that automatically check in-cluster first and fallback to
out-of-cluster and handle parsing and merging files listed in the
`$KUBECONFIG` variable to match the behavior of `kubectl`. This change
eliminates the need to explicitly define `$KUBECONFIG` for the maestro
when the file is in the default location. …
=> ref(ci): Use default KUBECONFIG handling

pkg/catalog/endpoint.go, pkg/catalog/endpoint_test.go, pkg/catalog/errors.go, pkg/catalog/types.go
One of our ongoing proposals in order to implement per-service filtering
at listener level will require being able to identify the traffic destination
of an ongoing request.
For that to be able to happen, we need to be able to do L3/L4 mapping to
a service.
In cases where the service is behind a cluster IP (in K8s), the FQDN resolvable IP is that
of the Cluster IP, henceforth we will require to get the Cluster IP from a specific
service when programming the outbound listener.
This commit introduces a new API called GetResolvableServiceEndpoints,
which post-conditions to return the expected resolvable endpoint where a service
is made available from a client application perspective.
To properly test, needs some larger changes that I will follow up
with on a commit on top.
Please describe …
=> catalog: add an API to retrieve endpoints for service FQDN

pkg/envoy/eds/response.go
Leverages an existing API to filter traffic policies on
outbound services instead of implementing the filtering.
`No`
=> eds: use existing API to filter on outbound services

charts/osm/templates/grafana-configmap.yaml, charts/osm/templates/grafana-deployment.yaml, charts/osm/templates/grafana-rbac.yaml, charts/osm/templates/grafana-svc.yaml, charts/osm/templates/prometheus-configmap.yaml, charts/osm/templates/prometheus-deployment.yaml, charts/osm/templates/prometheus-rbac.yaml, charts/osm/templates/prometheus-svc.yaml, charts/osm/values.yaml, cmd/cli/install.go, cmd/cli/install_test.go
Remove the "enableMetricStack" flag for the OSM install command. Replace with two separate flags, enable-grafana and enable-prometheus to decouple installation of Grafana and Prometheus
=> feat(metrics): Decouple Grafana and Prometheus installation for OSM install command

docs/development_guide.md
=> Add profiling info to development_guide

charts/osm/templates/osm-deployment.yaml, ci/cmd/maestro.go, ci/cmd/maestro/kubernetes_tools.go, cmd/osm-controller/osm-controller.go, cmd/osm-controller/validate.go, cmd/osm-controller/validate_test.go, pkg/injector/webhook.go
Currently the code uses the term 'webhook name' or the variable
'webhookName' when in fact it is referring to the
mutatingwebhookconfiguration name. This is confusing because
the mutatingwebhookconfiguration has a webhook with a name, and
it would be easy to confuse the two.
This change resolves this ambiguity. Commit 03e00587 removed
part of this ambiguity by renaming the the variable used
to represent the name of the webhook.
- Tests / CI System      [ …
=> Resolve ambiguity between webhook config and webhook name

.env.example, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go, cmd/cli/install_test.go, demo/run-osm-demo.sh, pkg/configurator/methods_test.go, pkg/constants/constants.go
This PR : 
- sets the default value of the log level for the envoy to `error` when OSM is installed
- exposes `envoy-log-level` as an install feature flag so that the demo and cli can run in the debug mode for envoy
- updates the demo and .env file to have the log level as debug 
Please answer the following questions with yes/no.  …
=> Set envoy log level as error to default in OSM

docs/development_guide.md, pkg/debugger/server.go, pkg/httpserver/httpserver.go
The http server was not a proper place.
- Debugging          [X]
No
=> Move pprof endpoints in debugger pkg

cmd/osm-controller/certificates.go, cmd/osm-controller/certificates_test.go, cmd/osm-controller/errors.go
This change refactors the `getCertFromKubernetes` function to
handle error scenarios. The function is only expected to error
if it finds a secret with an invalid root certificate. It also
helps remove the call to `log.Fatal` while parsing the root
certificate.
Also updates the existing test context (Ginkgo based) to test error scenarios.
- Does …
=> cmd/certificate: handle error scenarios when fetching secret

pkg/certificate/providers/tresor/ca.go, pkg/certificate/providers/tresor/certificate.go, pkg/certificate/providers/tresor/certificate_manager.go, pkg/certificate/providers/tresor/debugger_test.go, pkg/certificate/providers/tresor/types.go
Updates the issuing CA attribute for tresor.Certificate to
make it consistent with the other certificate providers (Vault
and CertManager).
`No`
=> certificate/tresor: use consistent api to retrieve CA

cmd/osm-controller/osm-controller.go, pkg/kubernetes/client.go, pkg/kubernetes/client_test.go, pkg/smi/client_test.go
Fixes the return value and signature when a new Kubernetes
Controller is being initialized by returning the interface
and an error.
`No`
=> kubernetes/Controller: Fix return type during initialization

cmd/osm-controller/osm-controller.go, pkg/envoy/ads/server.go, pkg/httpserver/httpserver.go, pkg/kubernetes/events/types.go, pkg/utils/grpc.go
Updates the code to record fatal events in the httpserver
goroutine and when the ADS server initialization fails.
`No`
=> Record fatal events and return error where possible

cmd/osm-controller/osm-controller.go, pkg/kubernetes/client.go, pkg/kubernetes/client_test.go, pkg/smi/client_test.go
Renames `NewKubernetesClient` to `NewKubernetesController`
based on the suggestion https://github.com/openservicemesh/osm/pull/1705#discussion_r489566700.
Also renames the kubernetes endpoints provider variable.
`No`
=> Rename function that creates kubernetes controller

pkg/envoy/ads/response.go
Info logging for the overall time spent updating one proxy,
Debug logging for individual xDS protos.
(Note: can't use fancy defer functions as they do not run out-of-scope
with golang loops)
- Debugging                  [X]
No
=> Track time for xDS verticals

ci/cmd/maestro.go, demo/cmd/bookwarehouse/bookwarehouse.go
This change makes the bookwarehouse emit the same success token as the bookbuyer and bookthief whenever it receives a request past its second and changes the maestro to look for that success token vs. a string that is only logged once. Currently, the maestro only succeeds if it is run immediately after the apps have been deployed. This change allows users to run the maestro at any point after the apps have been deployed.
I described more details here: https://github.com/openservicemesh/osm/issues/1710#issuecomment-693632564
- Metrics …
=> fix(maestro): Make bookwarehouse emit success token

cmd/cli/namespace_list.go, cmd/cli/namespace_test.go
Please describe the motivation for this PR and provide enough information so that others can review it.
You can clearly let users know which namespace enabled Sidecar is automatically injected.
NO
```
osm namespace list …
```
=> feat(cli) : Show whether the namespace is enabled with Sidecar Injection

cmd/cli/metrics.go, cmd/cli/metrics_disable.go, cmd/cli/metrics_enable.go, cmd/cli/metrics_test.go, cmd/cli/osm.go, demo/configure-app-namespaces.sh, demo/run-osm-demo.sh, go.sum, pkg/constants/constants.go, pkg/injector/metrics.go, pkg/injector/metrics_test.go, pkg/injector/patch.go
Adds support to configure namespaces for metrics
collection.
- osm cli command to enable/disable metrics on
select namespaces. Existing mesh participating
pods will be enabled for metrics.
- injector changes to auto enable metrics on
pods belonging to namespaces for which metrics
are enabled.
`osm metrics` command is limited to namespace scope
configurations at this time. It should be possible
in the future to enable metrics for select pods.
Part of #1016
- Security               [ …
=> metrics: support configuring select namespaces

docs/patterns/observability.md
Adds doumentation for metrics scraping configuration.
Part of #1016
`No`
=> docs/observability: document how to configure metrics scraping

cmd/cli/mesh_list.go, cmd/cli/mesh_list_test.go, cmd/cli/metrics.go, cmd/cli/metrics_disable.go, cmd/cli/metrics_enable.go, cmd/cli/metrics_test.go
Ensures that metrics can only be enabled or disabled on
namespaces that are monitored.
Updates existing code in mesh_list* to reuse code to
list all the mesh names so that a namespace can be
validated for monitoring.
Part of #1016
`No`
=> cli: restrict metrics command to monitored namespaces

docs/patterns/observability.md
Metrics is only scraped for namespaces that are part of the mesh,
update the doc to reflect this.
Part of #1016
`No`
=> docs/observability: update preprequisite for metrics scraping

cmd/cli/install.go
Adds a silent import for the client-go auth plugins,
which allows for Kube configurations that use auth plugins
for client credentials to work correctly.
Personally, not a fan of the import side effects,
but this is the current way to do it, see kubernetes/client-go#242
Fixes #1415.
Signed-off-by: Nick Young <ynick@vmware.com>
- …
=> fix(cmd/cli): Add client-go auth plugin import

pkg/endpoint/providers/kube/client.go, pkg/endpoint/providers/kube/client_test.go, pkg/endpoint/providers/kube/types.go
This change modifies the kube endpoints provider to watch Pods instead
of Deployments to map ServiceAccounts to Services. This will allow OSM
to work with workloads deployed as bare Pods or as other workload kinds
that control Pods besides only Deployments.
Fixes #1744 …
=> fix(endpoints): watch Pods instead of Deployments

charts/osm/Chart.yaml, charts/osm/values.yaml, cmd/cli/install.go
Updates the chart and container image versions used as a
part of v0.4.0 release.
`No`
=> charts: update chart and image version for v0.4.0 release

pkg/injector/errors.go, pkg/injector/metrics.go, pkg/injector/metrics_test.go, pkg/injector/webhook.go, pkg/injector/webhook_test.go, pkg/kubernetes/client.go, pkg/kubernetes/client_test.go, pkg/kubernetes/mock_controller.go, pkg/kubernetes/types.go
Identified a problem/bottleneck with webhook, where with enough pods/calls,
the webhook takes too much time to reply and times out, rendering any further
mesh deployments undone.
This fixes going through local caches instead of API calls to get
namespaces. This improves but doesn't totally solve the problem.
- Added tests, fixed existing tests
No
=> kubecontroller: add GetNamespace interface and impl

charts/osm/README.md, charts/osm/templates/osm-configmap.yaml, charts/osm/values.yaml, cmd/cli/install.go, cmd/cli/install_test.go, demo/run-osm-demo.sh, docs/patterns/egress.md, go.sum, pkg/configurator/client.go, pkg/configurator/client_test.go, pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/configurator/mock_client.go, pkg/configurator/types.go
After the introduction of per service outbound filter chains
in dac3552f72ea38f0d283af842d80e4ce0400ec81, there is no
longer a need for the mesh cidr ranges to be explicitly
configured for egress to work.
This change removes code related to mesh cidr ranges in
osm-controller and osm cli that are no longer used.
Resolves #1340 …
=> egress: remove mesh cidr dependency

cmd/osm-controller/osm-controller.go, pkg/catalog/fake.go, pkg/catalog/xds_certificates.go, pkg/catalog/xds_certificates_test.go, pkg/debugger/proxy.go, pkg/debugger/server.go, pkg/debugger/server_test.go, pkg/debugger/types.go, pkg/kubernetes/client.go, pkg/kubernetes/mock_controller.go, pkg/kubernetes/types.go
GetPodFromCertificate and ListPods were two remaining APIs used by
pretty much all verticals which were still going through kubeclient API
REST calls.
In E2E tests, with a higher count of pods we've seen slowness issues,
which ranged k8s API throttling, go-routine contention (as envoy updates pile up)
and webhooks timeout.
These additions remove any network/API dependency from the XDS paths, making
verticals' execution range between 50-100ms in demo conditions and debug logging.
(Down from 7-10seconds per vertical) …
=> Move remaining XDS vertical API calls to use kubecontroller caches

Makefile, demo/deploy-apps.sh, demo/deploy-smi-policies.sh, demo/reset.sh, demo/run-osm-demo.sh
While running the demo scenario via `demo/run-osm-demo.sh` I ran into a few tiny issues.
This PR:
- correct the names of the shell scripts invoked
- add an error message to `demo/run-osm-demo.sh` to exit early if/when Docker daemon is not found
- augment the docker push error with some context …
=> demo: Small fixes to the demo scripts and Makefile

scripts/go-test.sh, scripts/test-w-coverage.sh
Adding `-failfast` to the 2 scripts that run unit tests (both locally and in the CI system). Per [documentation](https://golang.org/pkg/cmd/go/internal/test/) this option will: `not start new tests after the first test failure`
This should lead to quicker discovery of broken tests.
---
- Does this change contain code from or inspired by another project? If …
=> tests: Adding -failfast to go test

pkg/injector/init-container.go, pkg/injector/init-container_test.go, pkg/injector/patch.go, pkg/injector/types.go
This PR adds unit tests for the functions creating the init container.
Also in this PR:
- Rename `InitContainerData` to `InitContainer`
- Change the signature of `getInitContainerSpec(...)` - removed unused `pod *corev1.Pod` param
This PR is a piece of https://github.com/openservicemesh/osm/pull/1772
--- …
=> injector: Init container test

pkg/certificate/providers/tresor/debugger_test.go, pkg/certificate/providers/tresor/fake.go
This PR adds `NewFakeCertificate()` funcion to `pkg/certificate/providers/tresor`, which is a helper function to create certificates for testing.
Other use cases for this are in the PR, which this was carved out from: https://github.com/openservicemesh/osm/pull/1772
--- …
=> certificate: Adding NewFakeCertificate() - creates certs for testing

pkg/certificate/providers/tresor/fake.go, pkg/injector/config_test.go
This PR is a step in preparation towards https://github.com/openservicemesh/osm/pull/1772, which adds new unit tests for the injector package.  These are small tweaks in string literals, no functional code changes.
This PR is stacked on top of https://github.com/openservicemesh/osm/pull/1773
This PR is a small piece of https://github.com/openservicemesh/osm/pull/1772
--- …
=> injector: Simplify tests and use YAML values closer to reality

charts/osm/templates/mutatingwebhook.yaml, cmd/cli/namespace.go, cmd/cli/namespace_ignore.go, cmd/cli/namespace_test.go, demo/run-osm-demo.sh, docs/patterns/sidecar_injection.md
This change provides a mechanism to explicitly ignore
namespaces to prevent sidecar injection from happening.
A new cli command `osm namespace ignore` is added for this
purpose.
Additionally, the mutatingwebhookconfiguration is updated
to only accept admission requests belonging to namespaces
that are not explicitly ignored and not osm control plane
namespace.
Enhancements such as checking if a namespace is ignored before 
enabling monitoring will be considered in a subsequent change.
Part of #1759
- SMI Policy …
=> Allow explicitly ignoring a namespace for injection

demo/run-osm-demo.sh
Commit 5fc44c5df90dc8078023e553feefda493f1d6c99 added this
check but it breaks the demo for users running the Docker
daemon on Windows and exposing the daemon over localhost.
`No`
=> demo: remove check for docker daemon

demo/run-osm-demo.sh
Commit 81648aa removed the docker daemon check because
it does not work in certain environments where the docker
daemon is exposed over a localhost.
This change adds the check back although by relying on the
`docker info` command instead, which returns an exit code
if the daemon is not running.
Co-authored-by: Edu Serra <eduser25@gmail.com> …
=> demo: check if docker daemon is up in a generic way

pkg/catalog/routes_test.go, pkg/tests/fixtures.go
This change ensures we test that all traffic target permutations are returned by ListTrafficPolicies
No
=> test(routes): ListTrafficPolicies should include all services for a service account

pkg/catalog/routes_test.go
The order of traffic policy objects cannot be assumed, compare
presence of element in list instead along with checking the
length of the list.
Resolves #1791
`No`
=> tests/catalog: remove assumption regarding ordering in list

README.md
We're establishing community meetings and need to publish the links for the zoom call, the meeting doc, and the calendar.
Not applicable
=> Adding links for community meetings

pkg/envoy/lds/listener.go, pkg/envoy/lds/listener_test.go, pkg/envoy/lds/response.go
In conditions where the the outbound listener filter logic cannot find any endpoints,
or there are no destination services (nor egress) programmed via SMI for a local
service, we should not attempt to program the listener altogether.
fixes #1793
No
=> Fixing empty filterchain/endpoint conditions on Outbound listener

pkg/configurator/client.go, pkg/configurator/client_test.go, pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/configurator/mock_client.go, pkg/configurator/types.go
Adds a new config option to retrieve the service certificate validity
duration. This is a prerequisite to make the service cert validity
duration dynamically configurable via the osm-config ConfigMap.
Part of #1757 …
=> configurator: add config option for service cert validity duration

scripts/test-w-coverage.sh
This PR increases the timeout on testing with coverage to 120s.  This is needed for https://github.com/openservicemesh/osm/pull/1772, which adds many more tests and needs more time.
- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? no
=> ci: Increase timeout when testing with coverage

.github/workflows/release-chart.yml
**Description**: We've seen the GH action we use to publish the OSM chart to gh-pages is not triggered on releases. The `*` character in the tag match does not match the `/` character that we've documented to use for chart release tags, so `chart*` does not match a tag like `chart/0.4.1`. This change updates the filter to match those tags.
ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
- Tests …
=> fix(release): update chart release tag match

go.sum, pkg/injector/config_test.go, pkg/injector/init-container.go, pkg/injector/patch.go, pkg/injector/patch_test.go, pkg/injector/volumes_test.go, pkg/injector/webhook.go, pkg/injector/webhook_test.go
This PR adds more unit test coverage for the `pkg/injector`
This PR also includes a rewrite of the `updateAnnotation()` function - to simplify and correct.
Previous iteration of this function returned `add` `JSONPatchOperation` with `Value` being sometimes `string` and other times ` map[string]string`. The most recent iteration always creates `add` `JSONPatchOperation` with `Value` of `map[string]string`.
```sh
$ go test -cover ./pkg/injector/...
ok      github.com/openservicemesh/osm/pkg/injector     0.058s  coverage: 27.6% of statements
```
```sh
$ go test -cover ./pkg/injector/...
ok      github.com/openservicemesh/osm/pkg/injector     6.821s  coverage: 75.7% of statements
```
---
- …
=> injector: Adding unit tests for the injector package

pkg/catalog/routes_test.go
**Description**: Change TestListTrafficPolicies to not test order of returned elements.
No
=> tests(catalog): fix flake in TestListTrafficPolicies

pkg/kubernetes/events/events.go
Each of the xxxEvent() apis exposed by the EventRecorder already
log at the corresponding log levels. This change removes the
additional trace logging which results in duplicate log messages
for each event.
The additional logging as a part of the event recorder also
results in data races in unit tests, which is similar to the issue
seen in https://github.com/kubernetes/kubernetes/issues/92500.
Part of #1791
- …
=> kubernetes/events: remove unnecessary logging

charts/osm/values.yaml
Helm Chart ConfigMap is using `OpenServiceMesh.serviceCertValidityDuration`
Current default values are using `OpenServiceMesh.certmanager.serviceCertValidityDuration`
Looking at the other places this is referenced I believe this should be updated to be outside of certmanager. It looks like it doesn't happen in the [osm cli](https://github.com/openservicemesh/osm/blob/11e7e5eae48790bef3c7e3a51f7d1e6206d45a0d/cmd/cli/install.go#L210) because it is passing the value itself.
[Configmap Template](https://github.com/openservicemesh/osm/blob/11e7e5eae48790bef3c7e3a51f7d1e6206d45a0d/charts/osm/templates/osm-configmap.yaml#L21):
```
service_cert_validity_duration: {{ .Values.OpenServiceMesh.serviceCertValidityDuration | quote }}
```
Updating default values file on the helm charts …
=> Fix spacing issues on values.yaml file

cmd/osm-controller/certificates.go, cmd/osm-controller/certificates_test.go, cmd/osm-controller/osm-controller.go
The private key for the CA bundle secret was not being written
to, because of which restarting a pod (not recreating the deployment)
results in the controller not starting up fine when it loads
the root certificate from the CA bundle secret.
Resolves #1742 …
=> cmd/osm-controller: write private key to CA bundle secret

tests/e2e/e2e_trafficsplit_test.go
- Test runs HTTP from multiple source client deployments to one
destination traffic split, backed by multiple server services
- Number of clients and servers backing the traffic split is tunable
By default:
- 2 Clients with 5 replica
- 5 Servers with 2 replica
- Adds traffic targets
- Creates traffic split service and adds all servers as traffic split backends.
It then tests traffic from all clients to the traffic split FQDN.
- Server instances are instrumented to reply with their pod name. The test will
also verify all server backing the traffic split are actually and eventually
reached.
**Affected area:**
- Tests [X]
No
=> tests/e2e: client-server deployment traffic split test

tests/e2e/e2e_deployment_client_server_test.go
- Test runs HTTP from multiple source client deployments to one
destination server deployment.
- Number of clients and replicaset can be tunned in the test (it
is not parametrized through test flags though)
By default:
- 5 clients and 5 replicas
- 1 server, with 5 replicas
- It then adds TrafficTargets from all clients to the server,
- Finally tests HTTP traffic from all client pods to the server (FQDN)
(It currently does not verify that all servers reply, TrafficSplit test
has some logic to do that that could be reused here if needed)
No
=> tests/e2e: client-server deployment test

tests/e2e/common.go, tests/e2e/e2e_hashivault_test.go
**Description**: This PR adds a new e2e test that uses HashiCorp Vault to issue certificates. It otherwise runs the same test as the original simple client/server test.
No
=> tests(e2e): add vault test

pkg/catalog/debugger_test.go, pkg/catalog/endpoint_test.go, pkg/catalog/fake.go, pkg/catalog/ingress_test.go, pkg/catalog/routes_test.go, pkg/debugger/namespace_test.go, pkg/debugger/policy_test.go, pkg/endpoint/providers/kube/client_test.go, pkg/endpoint/providers/kube/fake.go, pkg/envoy/ads/response_test.go, pkg/envoy/cds/cluster_test.go, pkg/envoy/cds/response_test.go, pkg/envoy/lds/response_test.go, pkg/envoy/rds/response_test.go, pkg/envoy/sds/response_test.go, pkg/envoy/xdsutil_test.go, pkg/kubernetes/client_test.go, pkg/smi/client_test.go, pkg/smi/fake.go, pkg/tests/fixtures.go, pkg/utils/service_test.go
This PR refactors existing tests to use two traffic split backends to more closely model real world scenarios.
No
=> test(split): Refactor tests to use two traffic split backends

demo/clean-kubernetes.sh, demo/run-osm-demo.sh
It is useful to run the cleanup script by itself. The mesh
delete command must also be run to cleanup mesh resources
created by install. This change moves the mesh delete command
into the cleanup script so that this single cleanup script
can be used to clean up all resources deployed by the demo.
- Does …
=> demo: move mesh delete command into the cleanup script

.github/workflows/main.yml, tests/e2e/common.go, tests/e2e/e2e_deployment_client_server_test.go, tests/e2e/e2e_pod_client_server_test.go, tests/e2e/e2e_trafficsplit_test.go
Will run all tests under e2e folder. Failfast is enabled as these can potentially be slow.
Also added proper CTR_TAG reading on test framework.
patchset[]:
- Increased all static timeouts for most pod bringup and some test conditions (as seen pod bringup could sometimes take a lot of time).
Future efforts will include parametrization (#1825)
- CI System          [X]
No
=> CI: Add e2e to CI pipeline

tests/e2e/common_traffic.go, tests/e2e/e2e_deployment_client_server_test.go, tests/e2e/e2e_hashivault_test.go, tests/e2e/e2e_pod_client_server_test.go, tests/e2e/e2e_trafficsplit_test.go
**Description**: Currently all test HTTP requests in the e2e framework are hardcoded to use `http://` and expect a port defined. This change consolidates all those fields into one so they're easier to customize for each test. …
=> ref(e2e): consolidate HTTP request host, port, and path into one field

.golangci.yml, demo/cmd/bookstore/bookstore.go, demo/cmd/common/books.go, go.sum, pkg/catalog/xds_certificates.go, pkg/certificate/file.go, pkg/certificate/rotor/rotor.go, pkg/cli/chart_source.go, pkg/debugger/envoy.go, pkg/health/health.go, pkg/injector/webhook.go, pkg/utils/mtls.go, tests/e2e/common.go
Enables security code checking using gosec linter. 
Some of the existing false positives have been annotated
so that gosec does not flag these when run locally.
Individual commits in the PR have more details 
regarding changes in that commit.
Part of #1845  …
=> Add security code checker using gosec linter

tests/e2e/common.go
Seen a condition where OSM is not necessarily always pulled if present in
container cache in nodes (even with `latest` tag) and registry is enabled.
Verified this was the case comparing SHAs. ~Not sure the reason though.~
Reason is install cli sets`imagePullPolicy` to `IfNotPresent` by default (and never omitted)
https://kubernetes.io/docs/concepts/containers/images/#updating-images
No
=> tests/e2e: force always pull in non kind-based deployment

Makefile
This PR makes go-lint use the same configuration as the CI for the OSM repo
No
=> tools: Use golangci-lint config in make go-lint

ci/cmd/maestro.go, demo/cmd/bookbuyer/bookbuyer.go, demo/cmd/bookthief/bookthief.go, demo/cmd/common/books.go, pkg/utils/env.go, pkg/utils/env_test.go, tests/e2e/common.go
Addressing comment from previous PR https://github.com/openservicemesh/osm/pull/1828#discussion_r505042224
No
=> tests/e2e: Generalize GetEnv

Makefile
This change adds two new variables to the Makefile to handle e2e test
flags: `E2E_FLAGS` and `E2E_FLAGS_DEFAULT`. These flags can optionally
be defined on the command line while invoking `make test-e2e` so flags
can be modified while also automatically building the required images.
Two separate flags were created so a sensible set of
defaults can be kept in `E2E_FLAGS_DEFAULT` and flags more likely to be
changed like cleanup or focus can be overridden without redefining all
the default flags. The default flags include verbose output and image
parameters, so the `test-e2e` target will always test with locally built
images from the current source. To use pre-built images, `go test`
should be invoked directly.
The default behavior for `make test-e2e` is unchanged.
**Affected …
=> ref(make): add variables for e2e test flags

pkg/injector/webhook.go, pkg/injector/webhook_test.go
Adds an extra safety check to ignore osm-controller namespace
from injection. This will only come into use if the controller
namespace does not have a label used to prevent the webhook
from being invoked (namespaceSelector in the
mutatingwebhookconfiguration).
Resolves #1859 …
=> injector: ignore osm-controller namespace

tests/e2e/common.go
With enough test applications/namespaces in combination with a slow
instance of gh actions, we've seen some delays to clean up all test
namespaces, and consequently test failures.
Relaxing further the wait-for-namespaces cleanup time, as re-running
the test suite for a non-osm-related/infra timeout can be a lot more expensive
than grating additional infra cleanup time.
No
=> CI cleanup timeout increase

charts/osm/README.md, charts/osm/templates/osm-deployment.yaml, charts/osm/values.yaml, cmd/cli/install.go, cmd/cli/install_test.go
--enable-single-mesh enforces that only one mesh is installed in the cluster
Fixes #1754
No
=> cli: Add enforce single mesh functionality to osm install

tests/e2e/e2e_trafficsplit_same_sa_test.go
**Description**: This test is based off the existing TrafficSplit test. The only difference is the server backends all use the same ServiceAccount for this test vs. each having their own ServiceAccount as in the existing test. This change adds a new test instead of modifying the existing test to preserve readability of each scenario. …
=> tests(e2e): add traffic split test using shared service account

tests/e2e/common.go, tests/e2e/e2e_certmanager_test.go
This change adds a simple e2e test with one pod trying to reach one
server using cert-manager to issue certificates.
Fixes #1734
No
=> tests(e2e): add cert-manager test

cmd/cli/dashboard.go, cmd/cli/portforward.go
This change exposes port forwarding capability generically
(previously implemented in the dashboard cmd) 
so that other commands that require to port forward to a pod
can leverage this. It updates the dashboard cmd to leverage
the generic port forwarder.
A subsequent change that requires port forwarding from the cli
will also leverage the newly added port forwarding APIs.
There also doesn't seem to be a trivial way to mock
port forwarding to a pod, so this will likely have to be
tested using e2e for automated tests.
- SMI …
=> cli: expose portforwarding capability and refactor dashboard cmd

tests/e2e/common.go, tests/e2e/e2e_deployment_client_server_test.go, tests/e2e/e2e_trafficsplit_same_sa_test.go, tests/e2e/e2e_trafficsplit_test.go
Removed some of the cumbersomeness from the namespace cleaning
code.
All created testing NS, for a given test, will now be tagged with `osmTest`
as label, and the random seed used by Ginkgo as value.
On test cleanup, only tests matching that specific label (and label value)
will be cleaned up.
When a test error occurs and cleanup can't be done (because of some major
error condition that prevents cleanup from executing altogether),
stale test applications and config can be left behind.
From now on, this can be easily addressed and cleanup using something like:
`kubectl delete namespaces -l osmTest`
Additionally, with Kind, will avoid K8s test cleanup if the kind setup
is about to be trashed anyway (saving some precious time on big tests).
- …
=> tests/e2e: rework NS cleanup

tests/e2e/common.go, tests/e2e/e2e_permissive_test.go
**Description**: This change adds an e2e test for the permissive traffic policy mode. It tests that two services can communicate without any SMI policies when permissive mode is enabled, disables permissive mode, then tests that the services cannot communicate.
Fixes #1815 …
=> tests(e2e): add permissive traffic policy mode test

cmd/cli/dashboard.go, cmd/cli/portforward.go
Removes deprecated code in dashboard.go and fixes the portforwarding
code to use the correct namespace.
`No`
=> cli: remove deprecated code and fix namespace usage with portforwarding

cmd/cli/osm.go, cmd/cli/proxy.go, cmd/cli/proxy_configdump.go, cmd/cli/proxy_configdump_test.go
Adds a cli command to dump proxy configuration
for a given pod. This is useful for debugging 
purpose.
Resolves #1762
`No`
=> cli: add proxy command to dump config

charts/osm/values.schema.json
This PR adds a values.schema.json file to indicate which values are required, type, description, examples, defaults. The schema file will help prevent us from accidentally changing the values file and breaking things as well as ensuring we are specifying the required values any time this chart is installed.
From the docs (https://helm.sh/docs/topics/charts/#schema-files): 
> This schema will be applied to the values to validate it. Validation occurs when any of the following commands are invoked:
> - helm install
> - helm upgrade
> - helm lint
> - helm template
- Install                [X ]
- Networking …
=> feat(charts): validate chart values w/ json schema

cmd/cli/install.go, demo/clean-kubernetes.sh, demo/run-osm-demo.sh, pkg/cli/environment.go, pkg/cli/environment_test.go, tests/e2e/common.go
This change is an RFC to discuss the proposal
to rename the global namespace flag exposed in
osm cli, which reflects the control plane namespace.
The reason to do so is because local command flags
could also expose a namespace flag, which don't
show up in the help text for the command. Moreover,
the global namespace flag isn't used by several
commands (ex. osm metrics, osm proxy etc.).
The proposal is to rename the global flag to represent
OSM's namespace to `osm-namespace` so that local
commands wanting to expose `namespace` as a flag can
do so with command specific description.
Part of #1884
- Certificate …
=> cli: rename global namespace flag

cmd/cli/namespace_add.go, cmd/cli/namespace_test.go, demo/configure-app-namespaces.sh, demo/join-namespaces.sh, docs/example/README.md, docs/onboard_services.md, docs/patterns/sidecar_injection.md, tests/e2e/common.go
Based on usability feedback, we want sidecar injection to be enabled
by default with the `osm namespace add` command. This change flips
the flag to `--disable-sidecar-injection` to explicitly disable
sidecar injection only if the flag is specified.
Refer to #1896 for more details. …
=> cli: enable sidecar injection by default with namespace add command

.github/workflows/main.yml, tests/e2e/README.md, tests/e2e/common.go, tests/e2e/e2e_certmanager_test.go, tests/e2e/e2e_deployment_client_server_test.go, tests/e2e/e2e_egress_test.go, tests/e2e/e2e_fluentbit_test.go, tests/e2e/e2e_hashivault_test.go, tests/e2e/e2e_permissive_test.go, tests/e2e/e2e_pod_client_server_test.go, tests/e2e/e2e_trafficsplit_same_sa_test.go, tests/e2e/e2e_trafficsplit_test.go
This change organizes tests into tiers based on priority to keep CI
running reasonably quickly against PRs while still regularly running all
tests. Currently 2 tiers are defined. Tier 1 tests have the highest
priority and run against PRs. Tier 2 tests are run on each merge into
the main branch. More tiers will likely be defined and tests may move
between tiers as the test suite grows.
This change also updates the e2e developer docs with the latest info and
guidance for these changes.
- Security …
=> ref(e2e): organize e2e tests into tiers

tests/e2e/common.go, tests/e2e/e2e_certmanager_test.go
This change will uninstall all Helm releases in the namespaces being
cleaned up before deleting the namespaces to avoid the namespaces
getting stuck in a Terminating state.
Fixes #1880 …
=> fix(e2e): cleanup helm releases in e2e

pkg/catalog/types.go, pkg/catalog/xds_certificates.go, pkg/catalog/xds_certificates_test.go, pkg/constants/constants.go, pkg/envoy/ads/response_test.go, pkg/envoy/cds/response_test.go, pkg/envoy/eds/response_test.go, pkg/injector/patch.go, pkg/injector/patch_test.go, pkg/injector/webhook.go, pkg/tests/fixtures.go
This PR changes the type of the `proxyUUID` variable from `string` to `uuid.UUID`.
Also renames ProxyID, EnvoyUID etc. to `ProxyUUID` for consistency.
---
=> injector/catalog: Use UUID type for proxyUUID variable; consistent naming

cmd/cli/install.go, cmd/cli/mesh_list.go, cmd/cli/metrics_disable.go, cmd/cli/metrics_enable.go, cmd/cli/namespace_add.go, cmd/cli/namespace_ignore.go, cmd/cli/namespace_list.go, cmd/cli/namespace_remove.go, cmd/cli/proxy_configdump.go
Encodes the actual error when a command fails due to kubeconfig
issues or the cluster not being accessible. Without this, it is
difficult to understand the actual cause of the error. …
=> cli: encode error along with message for additional context

pkg/injector/errors.go, pkg/injector/profiling.go, pkg/injector/profiling_test.go, pkg/injector/webhook.go, pkg/injector/webhook_test.go
Adding a small piece to help track time spent by individual routines
handling webhooks.
It parses the timeout value from the webhook call, and based on some
static thresholds will log differently depending on how much time is
taking vs. the timeout value given by the url.
No
=> pkg/injector: Add webhook time tracking facility

.github/workflows/main.yml, tests/e2e/common.go, tests/e2e/e2e_deployment_client_server_test.go, tests/e2e/e2e_egress_test.go, tests/e2e/e2e_fluentbit_test.go, tests/e2e/e2e_hashivault_test.go, tests/e2e/e2e_helm_install_test.go, tests/e2e/e2e_permissive_test.go, tests/e2e/e2e_pod_client_server_test.go, tests/e2e/e2e_trafficsplit_same_sa_test.go, tests/e2e/e2e_trafficsplit_test.go
Adds new e2e install option `NoInstall`.
NoInstall means to run the tests assuming there is already
a running, permanent instance of OSM in namespace `osmNamespace`, part
of the test suite flags.
OSM will therefore not be installed/cleaned up between tests,
all other resources used by the tests (clients, other namespaces,
SMI defs, etc) will get cleaned though.
Since a single install is assumed, it assumes inmutability of the
install, so tests that _require_ or test specific parts of the
installation will be skipped.
Dynamic configuration (configmap) is however supported, and tests
that would usually call Install will instead set/reset the dynamic
config map values that the install command would originally set.
- …
=> tests/e2e: add NoInstall option

ci/cmd/maestro/types.go
This PR permanently switches the logs coming out of the maestro CI module into human-readable logs.
---
=> maestro: Always print human readable logs in lieu of JSON

cmd/osm-controller/osm-controller.go
This PR augments the OSM Controller so that on startup it emits all feature flags in use in logs in JSON format.
This is very helpful in debugging the OSM Controller.
---
=> main: Print feature flags in use on OSM Controller start-up

pkg/catalog/routes.go
I noticed that `ListTrafficPolicies` was emiting a bit too many log lines.  To lower the noise, I propose we emit `Listing traffic policies for service...` at `Trace` level.
This PR also adds more detail to the `getHTTPPathsPerRoute()` error message.
---
`no`
=> catalog/routes: Change log level for ListTrafficPolicies from Info to Trace

pkg/debugger/feature_flags.go, pkg/debugger/server.go
This PR adds the `/debug/feature-flags` endpoint to the debug server, which shows current enabled feature flags.
---
`no`
=> debugger: Expose all feature flags via /debug/feature-flags endpoint

Makefile
Currently, we make tags of the form `v.X.Y.Z` for binary releases and
`chart/X.Y.Z` for the Helm chart. The version is passed to the
osm-controller binary via a linker flag. If both a chart and regular
semver tag exist on the same commit, the chart tag may be passed instead
of the regular version tag. This change ensures only our regular semver
tags are used for the versions embedded in the binaries.
- …
=> fix(build): ensure controller version is not a chart version

charts/osm/templates/mutatingwebhook.yaml, cmd/cli/install_test.go, pkg/injector/config_test.go, pkg/injector/errors.go, pkg/injector/metrics_test.go, pkg/injector/patch_test.go, pkg/injector/profiling_test.go, pkg/injector/types.go, pkg/injector/webhook.go, pkg/injector/webhook_test.go
While running OSM I noticed an `Info` level message in the OSM Controller pod:
```json
{
"level": "info",
"component": "sidecar-injector",
"time": "2020-10-19T23:46:59Z",
"file": "webhook.go:208",
"message": "Skipping sidecar injection"
}
```
The message stated what was already obvious to me:  a newly created pod was not injected with an Envoy sidecar. 
This PR adds a bit more context to the error messages in the Injector package.  Where possible we should show the namespace and pod. A log message that contains the exact object that was skipped for annotation would make it a bit easier to then search logs for that pod name to understand why.
Examples of new augmented log messages:
```json
{
"level": "trace",
"component": "sidecar-injector",
"time": "2020-10-22T01:51:07Z",
"file": …
```
=> injector: Augment log messages with admission request details

DESIGN.md, pkg/catalog/mock_catalog.go, pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/catalog/types.go, pkg/envoy/rds/response.go, pkg/envoy/rds/response_test.go, pkg/kubernetes/util.go, pkg/kubernetes/util_test.go
Currently, while programming the service FQDNs for an
upstream service in the downstream envoy's virtual_host config
the shorthand service FQDN using the service name without the namespace
is always programmed. This is incorrect because the same service (name)
could exist in multiple namespaces. The service FQDN without the
namespace should only be programmed on downstream clients that are
in the same namespace. If the downstream client is in a different namespace,
then shorthand FQDNs without the namespace for the upstream service 
should not be programmed.
Consider the following example:
Imagine the following 3 services of the form `namespace/service`:
`foo/bookbuyer, foo/bookstore, bar/bookstore`
bookbuyer is allowed to reach the bookstore service in both namespaces …
=> catalog: correctly program shorthand service FQDN

cmd/osm-controller/osm-controller_test.go, pkg/certificate/providers/tresor/types.go
Trading off bits on RSA key size for performance.
Shows a 12x to 15x less time spent generating certificates, which right
now is synchronous inside webhook handling.
see #1931 for additional context
fixes #1931
No
=> Reduce default number of bits used per RSA certificate key to 2048

charts/osm/templates/osm-deployment.yaml
Recent findings show OSM to hit early max limits (128MB)
with as much as 100~120 pods.
It's hard to estimate the memory used per envoy as it
will also very much depend on the traffic structrues used
by the deployment (service and trafficspec caches, etc).
On the specific tests, it showed a 0.5~0.6 MB/envoy.
No
=> charts/osm: Increase max memory limit

DESIGN.md, pkg/catalog/mock_catalog.go, pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/catalog/types.go, pkg/envoy/rds/response.go, pkg/envoy/rds/response_test.go, pkg/envoy/route/config.go, pkg/envoy/route/config_test.go, pkg/kubernetes/util.go, pkg/kubernetes/util_test.go, pkg/trafficpolicy/types.go
Fixes : #1798  and #1316 
- SMI Policy             [X]
=> bug(pkg/*) : Fixing access to backend services

.github/workflows/release.yml, Makefile
This change combines the `CLI_VERSION` and `CONTROLLER_VERSION` Makefile variables into a single `VERSION` variable since they were being used for the same purpose.
No
=> ref(build): consolidate version Makefile variables

.github/workflows/release.yml, DESIGN.md, Makefile, charts/osm/templates/mutatingwebhook.yaml, charts/osm/templates/osm-deployment.yaml, cmd/cli/install_test.go, cmd/osm-controller/osm-controller_test.go, pkg/catalog/mock_catalog.go, pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/catalog/types.go, pkg/certificate/providers/tresor/types.go, pkg/envoy/rds/response.go, pkg/envoy/rds/response_test.go, pkg/envoy/route/config.go, pkg/envoy/route/config_test.go, pkg/injector/config_test.go, pkg/injector/errors.go, pkg/injector/metrics_test.go, pkg/injector/patch_test.go, pkg/injector/profiling_test.go, pkg/injector/types.go, pkg/injector/webhook.go, pkg/injector/webhook_test.go, pkg/kubernetes/util.go, pkg/kubernetes/util_test.go, pkg/trafficpolicy/types.go
**Description**: Update release-v0.5 branch with the latest changes on `main`.
No
=> Merge main into release-v0.5

pkg/injector/patch.go, pkg/injector/patch_test.go
This PR generalizes the `updateLabels()` function so that it could be given any pod and key/value for a label and it will patch it.
Function signature changed (from/to):
- `updateLabels(pod *corev1.Pod, proxyUUID uuid.UUID) *JSONPatchOperation`
- `updateLabels(pod *corev1.Pod, label, value string) *JSONPatchOperation`
--- …
=> injector: Generalize updateLabels() function

pkg/announcements/types.go, pkg/catalog/repeater.go
This PR adds the skeleton of a new package `pkg/announcements`.  This package is intended to contain the types for the messages that will be passed around via the announcement system OSM employs.
In this PR we also include an example of how this may be used: every announcement `interface{}` is examined / type asserted to see if it is `Announcement{}`.  When it is - it is passed to a handler, which could further examine the properties of the message and do something specific.
The first use case for this more specific messaging system would be https://github.com/openservicemesh/osm/issues/1719, where we need to react to Pod Deletion events and clean-up relevant certificates.
For more context on how this could be used - see draft PR here: https://github.com/openservicemesh/osm/pull/1956
--- …
=> RFC: Add announcements package & mesage handler

pkg/catalog/catalog.go, pkg/catalog/repeater.go, pkg/catalog/types.go
This PR simplifies `catalog.MeshCatalog` by removing the `announcementChannels mapset.Set` field.
Instead we will be using the `mc.getAnnouncementChannels()` function.
---
=> catalog: Remove the announcementChannels set field from the MeshCatalog struct

tests/e2e/common_traffic.go, tests/e2e/e2e_trafficsplit_test.go
To verify new RDS changes:
https://github.com/openservicemesh/osm/pull/1929
- CI System              [x]
No
=> tests/e2e: adding test to individual backend services on trafficsplit

pkg/catalog/errors.go, pkg/catalog/xds_certificates.go, pkg/catalog/xds_certificates_test.go, pkg/endpoint/providers/kube/client.go, pkg/endpoint/providers/kube/client_test.go, pkg/service/types.go, pkg/service/types_test.go, tests/e2e/e2e_pod_client_server_test.go
With https://github.com/openservicemesh/osm/issues/1180 we documented the fact that there are use cases where one would want to install a Pod without a backing Kubernetes Service (perhaps some tool / jump pod etc.) and that Pod would then be used to troubleshoot to the various services in the cluster. For instance - you want to install a pod w/ `curl` in it and then `curl http://bookstore.bookstore/` in our current demo. This will not work until a kubernetes service is created for this new pod.
Current version of OSM (v0.4.2 as of this writing) requires each inbound or outbourd pod to be part of a Kubernetes service.
This PR provides a simple solution to this limitation. With this change a Kubernetes Service is no longer required for the client / outbound service Envoy to be configured. …
=> endpoint: Create synthetic service when a pod is in the mesh without a service

ci/cmd/maestro.go, ci/cmd/maestro/kubernetes_tools.go, ci/cmd/maestro/types.go, pkg/strings/all.go, pkg/strings/all_test.go, pkg/strings/which.go, pkg/strings/which_test.go
The goal of this PR is to simplify `maestro` so that it is really easy at a first glance to understand what this is doing.
Changes in this PR that (I believe) achieve that goal:
- created a new package `strings` in OSM to help with iterating over list of strings and finding certain thruths about these - inspired by fn langs
- removed the `type TestResult int` and using `string` instead -- `passed`, `failed`, `timedout` -- love type aliases, but I believe this actually makes things much simpler
- carved out a few large and repetetive blocks of code into helper functions; Naming the functions helps eliminate comments and gives us a high-level overview of what is happening:
- `getPodNames()`
- `printLogsForInitContainers()`
- `printLogsForContainers()`
- `cleanUp()`
Overall no functional …
=> ci: Refactor to simplify maestro

pkg/envoy/lds/ingress.go, pkg/envoy/lds/inmesh.go
Names the inbound filter chains used for in-mesh and ingress
traffic. Naming it makes it easier to examine the envoy config
dump and logs.
`No`
=> envoy/lds: name the inbound filter chains

pkg/identity/kubernetes.go, pkg/identity/kubernetes_test.go, pkg/identity/types.go
Adds a new `ServiceIdentity` type that is to be used to provide
identity to services managed by OSM. Provides an API to use
Kubernetes ServiceAccount as service identities.
The kubernetes based service identity makes use of a trust domain
that determines the domain within which an identity can be trusted.
Within the same cluster, a Kubernetes service identity would be
"service-account.namespace.cluster.local". The trust domain provides
the ability to extend a `ServiceIdentity` beyond kubernetes domains.
Part of #1965
- SMI …
=> identity: add abstraction for service identity

cmd/cli/trafficpolicy_check.go, cmd/cli/trafficpolicy_check_test.go, pkg/configurator/client.go, pkg/configurator/client_test.go, pkg/configurator/methods_test.go
Reuses the configurator package to parse the permissive mode
config key in the ConfigMap as a part of osm cli.
Functionally, this change does not change the existing behavior
of the configurator client in osm-controller, which ignores errors
while initializing parsing the keys in the osm-config ConfigMap to
use default values where applicable.
Resolves #1962
- Other …
=> cli,configurator: reuse api to parse osm-config ConfigMap

pkg/endpoint/providers/kube/client.go
This is a noop change, which renames a variable from `service` to `kubeService` to avoid collision w/ an imported package.
=> endpoint: Rename variable to remove collision w/ imported package

pkg/injector/webhook.go, pkg/injector/webhook_test.go
While working on an unrelated area, I noticed that one of the `pkg/injector` log messages provided insufficient context to understand exactly what is happening. The message is not useful without the context of the kind and name of object for which we are observing an annotation.
Example:
```
{"level":"trace","component":"sidecar-injector","time":"2020-11-03T00:21:56Z","file":"webhook.go:330","message":"Sidecar injection annotation: 'openservicemesh.io/sidecar-injection:'"}
```
This PR augments this message to add the kind and name of the object.
With this PR the message would look like this: `pod a/b has sidecar injection annotation: 'openservicemesh.io/sidecar-injection:"true"'`
- …
=> injector: Augment log message with object kind and name

.github/workflows/main.yml, tests/e2e/README.md, tests/e2e/common.go, tests/e2e/e2e_certmanager_test.go, tests/e2e/e2e_deployment_client_server_test.go, tests/e2e/e2e_egress_test.go, tests/e2e/e2e_fluentbit_test.go, tests/e2e/e2e_hashivault_test.go, tests/e2e/e2e_helm_install_test.go, tests/e2e/e2e_permissive_test.go, tests/e2e/e2e_pod_client_server_test.go, tests/e2e/e2e_trafficsplit_same_sa_test.go, tests/e2e/e2e_trafficsplit_test.go
This change adds the capability to run e2e tests in parallel in CI.
Tests are now organized into buckets, where each bucket runs in parallel
and tests within each bucket run sequentially. How e2e tests are defined
at the top-level has been refactored to include a new parameter
identifying in which bucket a test should run.
Tests were not organized into buckets initially based on any heuristic,
so rebalancing may be necessary. Adding more buckets is also simple.
All of the changes to the tests themselves aside from adding the bucket ID are whitespace as they're indented by one extra level.
Fixes #1877
- …
=> ref(e2e): divide tests into buckets

README.md, docs/onboard_services.md
Fixed the typo errors in the links to Observability section which was throwing 404 Page Not Found error
No this doesn't contain any code changes
=> docs: fix typos in observability document links

DESIGN.md, pkg/certificate/providers/certmanager/certificate_manager.go, pkg/certificate/providers/tresor/certificate_manager.go, pkg/certificate/providers/vault/certificate_manager.go, pkg/certificate/types.go
This PR introduces `ReleaseCertificate()` into the `certificate.Manager{}` interface.
This new method will inform the underlying certificate issuer that the given cert will no longer be needed. This method could be called when a Kubernetes Pod is terminated for instance. Calling this should remove certs from cache and free memory if possible -- dependent on the certificate manager implementation.
This a step forward towards addressing https://github.com/openservicemesh/osm/issues/1719
---
- Security …
=> certificate: Adding ReleaseCertificate() to the Manager interface

.github/workflows/release.yml, scripts/release-notes.sh
This change adds a script that will generate the release notes for a
given git tag. It will calculate the previous tag and perform a
formatted `git log $prev..$next` to generate a changelog added to the
GitHub release. More details can be found in the script.
Something with how we've been updating release branches with changes
from main is causing some commits to show in the changelog we don't
want, like changes from v0.4.1 are showing in its changelog and the one
for v0.5.0-rc.1 since the commits have the same changes but different
SHAs. This can be addressed the next time we update the release-v0.5
branch with changes from main.
Currently, the release notes only contain this changelog, but it should
be simple to add anything else that can be generated. The release notes …
=> feat(ci): generate release notes

pkg/catalog/traffictarget_test.go
Updates the test to not rely on ordering of elements
in the expected list of elements.
=> catalog/test: ignore ordering of elements in test

docs/installation_guide.md
This change updates the control plane installation section of the install guide to clarify that when using a CLI built from source, the control plane images should also be built from source and that those images should be passed to `osm install`, overriding the default image location.
Fixes #1527
- Does …
=> docs(install): clarify CLI/image version compatibility

pkg/endpoint/providers/kube/client.go, pkg/endpoint/providers/kube/client_test.go
Because these log messages may be emitted by a number of instances of the kubernetes endpoints provider, prepending the name of the particular provider would be helpful.
For some messages changing log level to `Trace()`.
For the log statements that are emitted only on launch of the OSM Controller pod - changing from `Debug` to `Info` …
=> endponit/providers/kube: Adding the name of the endpoint provider to the log messages

pkg/catalog/repeater.go
This PR changes a log statement from `Info()` to `Trace()` to lower the noise in logs.  Also removing `[repeater]`, which is already included in the `file` field of the JSON log message:
```json
{
"level": "info",
"component": "mesh-catalog",
"time": "2020-11-04T23:10:04Z",
"file": "repeater.go:20",
"message": "[repeater] Received announcement from Namespace"
}
```
Please …
=> catalog/repeater: Change noisy log statement from Info to Trace

tests/scenarios/helpers.go, tests/scenarios/traffic_split_with_apex_service_test.go
This PR adds a test, which confirms the bug discovered with Issue https://github.com/openservicemesh/osm/issues/1979.
A secondary goal for this PR is to start a new set of tests and tooling so that we can test what Envoy configuration would be generated based on a set of SMI policies (plus Services, Pods etc).
Here is the Envoy config for the bookstore proxy, which I believe points to the root cause for this:
```json
{
"version_info": "23",
"route_config": {
"@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration",
"name": "RDS_Outbound",
"virtual_hosts": [
{
"name": "outbound_virtualHost|bookstore",
"domains": [
"bookstore.bookstore.svc",
"bookstore.bookstore.svc.cluster",
"bookstore.bookstore.svc.cluster.local",
"bookstore.bookstore:80",
"bookstore.bookstore.svc:80", …
```
=> rds: Create a new high-level test for a particular scenario

ci/cmd/suite_test.go, cmd/cli/suite_test.go, cmd/osm-controller/suite_test.go, pkg/apis/suite_test.go, pkg/certificate/providers/vault/suite_test.go, pkg/certificate/suite_test.go, pkg/cli/suite_test.go, pkg/configurator/suite_test.go, pkg/constants/suite_test.go, pkg/endpoint/providers/azure/suite_test.go, pkg/endpoint/providers/kube/suite_test.go, pkg/endpoint/providers/suite_test.go, pkg/endpoint/suite_test.go, pkg/envoy/ads/suite_test.go, pkg/envoy/cds/suite_test.go, pkg/envoy/eds/suite_test.go, pkg/envoy/lds/suite_test.go, pkg/envoy/rds/suite_test.go, pkg/envoy/sds/suite_test.go, pkg/envoy/suite_test.go, pkg/featureflags/suite_test.go, pkg/health/suite_test.go, pkg/httpserver/suite_test.go, pkg/injector/suite_test.go, pkg/metricsstore/suite_test.go, pkg/smi/suite_test.go, pkg/version/suite_test.go
Most of the tests in `suite_test.go`  were named as `TestEndpoints`, this PR cleans up and fixes the naming of the tests in the various packages appropriately. No functional changes, only renaming …
=> clean-up : fixing test naming

pkg/envoy/sds/response.go
Changes the log level to warn for the message logged when SDS
receives a certificate request for a service not associated with
the given proxy. This does not result in a control plane error,
so a warn log seems appropriate. …
=> sds/response: change log level to warn

pkg/constants/constants.go, pkg/envoy/ads/grpc.go, pkg/envoy/proxy.go, pkg/envoy/xdsutil.go, pkg/envoy/xdsutil_test.go, pkg/injector/envoy_config_test.go, pkg/injector/envoy_container.go
The metadata of the Pod on which a given Envoy is installed would be of immense value to OSM.  There are a few ways to link an Envoy to the Pod metadata - this PR prososes one.
Using the Envoy `--service-node` bootstrap param, we pass some of the metadata of the Pod to the OSM control plane.
Here is a log line as an example of the data that we get from Envoy:
```json
{
"level": "trace",
"component": "envoy",
"time": "2020-11-05T02:59:07Z",
"file": "proxy.go:34",
"message": "Recorded metadata for Envoy 785c9a2e-63d1-4306-bbf5-9fc886232513.bookthief.bookthief: podUID=d2384c3e-0b25-44b1-af62-218e34286f7f, podNamespace=bookthief, podIP=10.244.2.181, podServiceAccountName=bookthief, envoyNodeID=bookthief"
}
```
So we now know that Pod with CN …
=> envoy: Augment Envoy's Node ID with Pod metadata

pkg/envoy/cds/cluster.go, pkg/envoy/cds/cluster_test.go, pkg/envoy/cds/response.go, pkg/envoy/cds/response_test.go, pkg/envoy/lds/listener.go
As per #1860, uses consistent terminilogy to refer to the source/client
as downstream, and the destination/remote/server as upstream.
`No`
=> envoy: use consistent terminology for downstream and upstream service

pkg/configurator/client.go
This change makes use of the filtering capability in informers
to filter API responses on the server side, by using a FieldSelector
to filter on the name of the ConfigMap as opposed to filtering all
objects on the client (osm-controller) side. The informer is already
namespaced, so the namespace and name should be enough to accurately
only have OSM's ConfigMap in the informer cache and events.
This change will also reduce the number of ConfigMap related events
the controller will receive when there are additional ConfigMaps in
the controller's namespace (ex. Grafana's ConfigMap when Grafana is
deployed as a part of control plane), and thus improving performance
in such scenarios. The informer resyncs are on a per resource basis,
so unnecessary events can take up …
=> configurator: optimize ConfigMap informer filtering

pkg/catalog/catalog.go, pkg/catalog/catalog_test.go, pkg/catalog/fake.go, pkg/catalog/ingress_test.go, pkg/envoy/rds/response_test.go, pkg/kubernetes/client.go, pkg/kubernetes/client_test.go, pkg/smi/client_test.go
The namespace informer is only necessary to check if namespaces are
monitored (via the monitoring label), which is done via the cache
store provided by client-go.
We do not need to trigger events to catalog when a namespace is
is added/updated/deleted for a few reasons:
1. Envoy configuration updates are not concerned with individual
namespace resources events. Adding a new namespace or updating
the namespace (ex with a label/annotation) does not concern
proxy configurations. Deleting a namespace however does affect
proxy configurations, but since the catalog subscribes to pod
and service specific events, a namespace deletion event would
also result in pod/service deletion events in such a namespace
which will suffice to recompute proxy configs for proxies
fronting …
=> kubernetes/client: remove announcement channel for namespace informer

docs/README.md
Changes a couple of legacy `master` refs to `main`.
=> [docs] edit readme for correct branch name

DESIGN.md, pkg/catalog/mock_catalog.go, pkg/catalog/service.go, pkg/catalog/service_test.go, pkg/catalog/types.go
Adds an api to MeshCataloger interface to retrieve a list of service
accounts associated with the given service.
This api will be used by clients to correctly validate the identity
of upstream services they are connecting to via the validation
context specified in the SDS secrets. …
=> catalog: add an api to retrieve service accounts for a service

pkg/kubernetes/client.go, pkg/kubernetes/client_test.go
Pod announcements were incorrectly being announced on the channel
meant for the Service resource. This change fixes it and also
adds additional safety checks in a test that caught the failure. …
=> kubernetes/client: use correct channel for pod announcements

cmd/cli/install_test.go
This PR uses the default install command and the default values map for all tests. This cuts down on the number of lines of code considerably, making this file easier to read and edit.
Additionally, new tests were being added by copying old tests. This resulted in each test configuring certain settings in different ways across the tests even though no meaningful difference was made by these changed settings. For example, a test for checking the namespace could include settings that were used in a test for cert-manager. 
This made the tests more difficult to interpret as it was not possible to tell exactly which fields were necessary for the testing scenario. However this new format makes it easy to see which settings differ from the default.
- New …
=> test(cli/install): Refactor tests to use default install commands

cmd/osm-controller/osm-controller.go, cmd/osm-controller/osm-controller_test.go
Currently, the tests that dynamically start/stop the debug HTTP server
rely on a `sync.WaitGroup` that signals when a mocked debug server has
been started or stopped. `TestConfigureDebugServerErr` was failing
occasionally because `configureDebugServer` wasn't guaranteed to finish
stopping the server before the test's `sync.WaitGroup` signalled it was
done.
This change removes the `sync.WaitGroup` from the tests and instead adds
a new channel parameter to `configureDebugServer` that will emit errors
(or nil if successful) whenever the server is started or stopped. Then,
the tests can be sure that `configureDebugServer` has finished before
checking any values.
- Control …
=> tests(debug server): fix race condition

pkg/kubernetes/client_test.go
The tests had synchronization issues resulting from missing and blocking
event notifications.
The missing events were a result of the tests
not waiting till the namespace used in the test is monitored, which
in turn causes the caches for the other Kubernetes resources to
be filtered out as unmonitored. The result is that the resource is
only marked as monitored upon the next resync from k8s informers
(currently every 30s). This is fixed by ensuring an async wait
on the namespace to be monitored before waiting on k8s events for
resources belonging to the namespace.
Since unbuffered channels are used for announcements, it is better
to read as soon as data is available rather than to batch reads,
which results in writes being blocked. This is also addressed in
the tests. …
=> kubernetes/test: fix slow tests

pkg/catalog/catalog.go
This PR fixes the re-configuration ticker, which makes sure that every X seconds we update proxies w/ the latest config, regardless of other events that may have triggered that.
=> catalog: Make the re-configuration ticker actually tick

tests/e2e/common.go
Defaulted to debug for e2e.
- Debugging          [X]
No
=> tests/e2e: envoy log level for testing

pkg/kubernetes/event_handlers.go, pkg/kubernetes/types.go
This PR is a small refactor of the Kubernetes eventing system;  Goal is to remove unused code and specialize a type. This PR:
- removes the unused `EventType int` type and creates a new `EventType string`
- changes the type of the ADD/DELETE/UPDATE constants to `EventType`
- changes the signatures of the functions using these (from `string`, to `EventType`)
This PR is in preparation for https://github.com/openservicemesh/osm/pull/2028 and https://github.com/openservicemesh/osm/pull/1956 and is a small step forward towards solving GitHub issue https://github.com/openservicemesh/osm/issues/1719
---
- …
=> kube: Refactor Event Types

pkg/catalog/repeater.go
This PR renames the `broadcast()` function to `broadcastToAllProxies()` to add context and clarity -- upon reading one would know **to what** this is sending messages.
---
=> catalog: Rename broadcast to broadcastToAllProxies for context and clarity

pkg/catalog/repeater.go
This PR is an overall noop:
- removes an indentation level by using `continue`
- adds a log message for when (if ever) a message does not assert to `Announcement`
- augments the log message, which reports the type of announcement and the system it came from
--- …
=> catalog: Refactor repeater() for clarity and to remove indentation level

pkg/catalog/routes.go, pkg/catalog/routes_test.go
This func allows one to get a list of trafficpolicy.HTTPRoute objects from a set of rules from an SMI Traffic Target resource. The larger change can be seen in #2035 where routesFromRules is named HTTPRoutesFromRules (renamed to allow for the function to later also return TCPRoutes from rules in the future).
There are no functional changes to the system in this PR. It is part of #2034 and a chunk of #2035.
=> feat(pkg/catalog): Add routesFromRules func

go.sum, pkg/catalog/fake.go, pkg/envoy/ads/response.go, pkg/envoy/ads/response_test.go, pkg/envoy/cds/cluster.go, pkg/envoy/cds/response_test.go, pkg/envoy/lds/response_test.go, pkg/envoy/sds/response.go, pkg/envoy/sds/response_test.go, pkg/envoy/xdsutil.go, pkg/envoy/xdsutil_test.go
This change fixes how a client validates the service certificate presented
up an upstream server. Previously, the identity of the upstream
server was being validated against a list of upstream service
identities that the client is allowed to communicate to. This is
vulnerable to security issues where a server not authorized
to run the given upstream service the client is attempting to reach
can successfully trick the client as long as the client is allowed
to reach the unauthorized service identity for a different service.
This change prevents this by ensuring the service identities presented
by the upstream server are indeed authorized to run the service the
client is attempting to communicate to.
This change also decouples the context of validation context for an
SDS …
=> envoy: correctly validate SANs in certificate

pkg/announcements/types.go, pkg/catalog/repeater.go, pkg/configurator/client.go, pkg/endpoint/providers/kube/announcements.go, pkg/endpoint/providers/kube/announcements_test.go, pkg/endpoint/providers/kube/client.go, pkg/ingress/client.go, pkg/kubernetes/client.go, pkg/kubernetes/event_handlers.go, pkg/kubernetes/event_handlers_test.go, pkg/smi/client.go
This PR continues the work started in https://github.com/openservicemesh/osm/pull/2010 and contributes towards resolving issue https://github.com/openservicemesh/osm/issues/1719
This PR adds announcement types (add, delete, update) for Pods and Kubernetes Endpoints.
This also changes `GetKubernetesEventHandlers()` so it emits the appropriate `AnnouncementType` based on which Kubernetes object is observed.
With this change the following block of code, which handles these announcement messages will have access to a) the type and b) the UID of the relevant object:
https://github.com/openservicemesh/osm/blob/e50d75b636b29c2f052dd92e61fe0f1e6e5c21e8/pkg/catalog/repeater.go#L21-L37
This is currently only implemented for Pods and Endpoints.  The work to populate the other kind of events we …
=> announcements: Increase specificity of events coming from Kubernetes

go.mod, go.sum
When building on Mac, the following errors are shown:
../../go/pkg/mod/github.com/docker/docker@v1.4.2-0.20200203170920-46ec8731fbce/pkg/term/tc.go:13:28: undefined: unix.SYS_IOCTL
../../go/pkg/mod/github.com/docker/docker@v1.4.2-0.20200203170920-46ec8731fbce/pkg/term/tc.go:18:28: undefined: unix.SYS_IOCTL
../../go/pkg/mod/github.com/docker/docker@v1.4.2-0.20200203170920-46ec8731fbce/pkg/term/termios_bsd.go:24:31: undefined: unix.SYS_IOCTL
../../go/pkg/mod/github.com/docker/docker@v1.4.2-0.20200203170920-46ec8731fbce/pkg/term/termios_bsd.go:37:31: undefined: unix.SYS_IOCTL
This change is the result of running `go get -u github.com/onsi/gomega@v1.14.1`. It looks like both the Docker and Ginkgo modules share a dependency on `golang.org/x/sys`.
- New …
=> fix(*): fix Mac build error

pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/endpoint/providers/kube/fake.go
- This PR contains a function called GetServicesForServiceAccounts that returns a list of services corresponding
to a list service accounts. Part of #2034. See this change as part of the bigger change in #2035. There
are no functional changes to the system in this PR.
- This PR also updates and existing test to use an existing var
=> feat(pkg/catalog): Add GetServicesForServiceAccounts func 

pkg/catalog/helpers_test.go, pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/tests/fixtures.go, pkg/trafficpolicy/trafficpolicy.go, pkg/trafficpolicy/trafficpolicy_test.go, pkg/trafficpolicy/types.go
- adds TrafficPolicy object to represent route configuration
between a source and a destination
- adds a buildTrafficPolicies function that takes a list of source services,
destination services, and routes and returns a list of traffic policies for each
source + destination combination
- adds a GetHostnamesForUpstreamService func to get a list of resolvable hostnames
for traffic policy
This PR includes no functional changes to the system. It is part of #2034. See #2035 for how it will integrate into the overall routes refactor work. As a follow up, `GetHostnamesForUpstreamService` should replace `GetResolvableHostnamesForUpstreamService` but the latter is left in the codebase for now to ensure nothing breaks during non functional changes and a clean transition to the new route programming …
=> feat(*): add TrafficPolicy struct and helpers

charts/osm/templates/osm-deployment.yaml, charts/osm/values.yaml
Currently it's hardcoded in deployment.
This gives at least some short term flexibility till we add
configMap update, which has some ongoing discussion as
how to tackle.
No
=> osm-deployment: parametrize osm log level in values.yaml

.github/workflows/main.yml, go.mod, go.sum
CI was only checking the exit code of `go mod tidy`, but that is still 0 if it makes changes to the files. This change instead invokes the makefile target which will explicitly check if the files were modified by `go mod tidy` and fail if they were. …
=> fix(ci): fix go mod tidy check

pkg/envoy/lds/rbac.go, pkg/envoy/lds/rbac_test.go, pkg/envoy/lds/response.go, pkg/envoy/lds/types.go
This change introduces an RBAC filter in the inbound mesh filter
chain. Currently, the RBAC filter grants full access to client identities 
(ServiceAccounts) that are permitted by an SMI traffic target policy.
HTTP filtering based on HTTP routes still happens within RDS.
The RBAC filter is omitted in permissive mode.
This change is a part of #1964 and is required by #1521.
- Other …
=> envoy/rbac: add support for server side RBAC fitler

cmd/osm-controller/osm-controller.go
The `mgr.Start()` below blocks forever on line 255: https://github.com/openservicemesh/osm/compare/main...draychev:fix-controller-manager?expand=1#diff-fc4c2be496da13e6544e74c71a0fb5cc15b1f998fb1fbd471562411622ea4f8dR255
This prevents the DebugServer from ever starting.
--- …
=> Fix debug server and OSM Controller Manager

pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/catalog/traffictarget.go, pkg/catalog/traffictarget_test.go
This PR adds some convenience functions and is part of #2034. More specifically it:
* add `trafficTargetIdentitiesToSvcAccounts` func
* add `isValidTrafficTarget` func
Validation of SMI resources has come up in the past and is being tracked in #172 so in the future isValidTrafficTarget should be replaced with the overall community solution for validating SMI resources (#2052)
There are no functional changes to the system in this PR. See #2035 for how these functions play into the overall refactor.
=> ref(pkg/catalog): add convenience functions

scripts/test-w-coverage.sh
The `./tests/scenarios` directory appears as one with no test coverage. It should be excluded from our tool.
=> Exclude tests/scenarios from test coverage tool

pkg/catalog/catalog.go, pkg/catalog/debugger.go, pkg/catalog/proxy.go, pkg/catalog/repeater.go, pkg/catalog/types.go
To simplify things, this PR changes the 
```go
connectedProxies     map[certificate.CommonName]connectedProxy		
connectedProxiesLock sync.Mutex
```
with 
```
connectedProxies sync.Map
```
There are 2 other similar fields that will be changed with another PR to keep things simple and clean.
---
Ran a quick test to verify the debug server works as expected;
---
Please …
=> catalog: Convert connectedProxies to sync.Map

pkg/catalog/catalog.go, pkg/catalog/debugger.go, pkg/catalog/proxy.go, pkg/catalog/repeater.go, pkg/catalog/types.go
This PR changes the 
```go
disconnectedProxies     map[certificate.CommonName]connectedProxy		
disconnectedProxiesLock sync.Mutex
```
with 
```
disconnectedProxies sync.Map
```
This PR is stacked on https://github.com/openservicemesh/osm/pull/2061
---
- Does this change contain code from or inspired by another project? If …
=> catalog: Convert disconnectedProxies to sync.Map

cmd/osm-controller/osm-controller.go, cmd/osm-controller/osm-controller_test.go, go.mod, go.sum, pkg/configurator/client.go, pkg/configurator/client_test.go, pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/configurator/mock_client.go, pkg/configurator/types.go, pkg/httpserver/debugger.go
This commit introduces a configuration interface to subscribe to
announcement types for configurator.
This interfaces provides a simple way for multiple remote
packages/modules/goroutines to subscribe to events of their interest.
The reasoning is to prioritize decoupling between modules so much
they can handle their own logic, as opposed to having a single
thread/goroutine handle all configuration updates, thus triggering
remote functions on the appropriate modules upon config changes.
The `GetAnnouncementChannel()` interface has been removed, and instead a
middleman routine in configurator has been spawned, which will be the one
to multiplex announcement channel updates through the publish interface.
Some cleanup has happened for DebugServer, which was consuming the cfg channel
interface …
=> pkg/configurator: introducing pubsub for config updates

pkg/catalog/catalog.go, pkg/catalog/debugger.go, pkg/catalog/proxy.go, pkg/catalog/repeater.go, pkg/catalog/types.go
This PR changes the 
```go
expectedProxies     map[certificate.CommonName]expectedProxy		
expectedProxiesLock sync.Mutex
```
with 
```
expectedProxies sync.Map
```
This PR is stacked on https://github.com/openservicemesh/osm/pull/2061 and https://github.com/openservicemesh/osm/pull/2062
---
- Does this change contain code …
=> catalog: Convert expectedProxies to sync.Map

LICENSE
We needed to relicense when we transferred the OSM project to the CNCF. 
Reference: https://github.com/openservicemesh/osm/issues/2065
=> Correct license

dockerfiles/Dockerfile.bookbuyer, dockerfiles/Dockerfile.bookstore, dockerfiles/Dockerfile.bookthief, dockerfiles/Dockerfile.bookwarehouse, dockerfiles/Dockerfile.osm-controller
Use distroless base & static images (depending on openssl requirements)
Replace ADD with COPY instructions & remove unnecessary layers
Remove chmod since built binaries are executable
Fix #1538 …
=> Use distroless images for osm & demo

pkg/constants/constants.go
This PR removes the `AzureProviderName` constant, which is no longer in use after https://github.com/openservicemesh/osm/pull/2039
=> Remove unused constant AzureProviderName

cmd/osm-controller/osm-controller.go, pkg/kubernetes/event_handlers.go, pkg/kubernetes/events/event_pubsub.go, pkg/kubernetes/events/event_pubsub_test.go, pkg/kubernetes/events/types.go
This commit introduces a global interface to pass messages and events,
from multiple writers to multiple readers, based on topic.
Single channel mechanisms suffer from some coupling, where
the object holding the channel or channel itself has to be passed around.
Additionally, we are seeing situations where individual modules could be
interested in being notified for certain events so they could run
their own isolated logic (mind the isolation), current single channel model
poses several issues on that front (need a middleman multiplexer, etc.)
This commit doesn't yet introduce a consumer of this API, though in subsequent
we will introduce/rework some channel uses that will immediately greatly benefit
from this feature (proxy's global boadcasting, configurator, etc.)
Addresses #1914 …
=> events: Add pubsub global interface for OSM events

pkg/certificate/providers/vault/certificate_manager.go, pkg/certificate/providers/vault/tools.go, pkg/certificate/providers/vault/tools_test.go, pkg/certificate/providers/vault/types.go
This PR adds specialized types `vaultPath` and `vaultRole` (in lieu of strings)
This is a small chunk from the larger Draft PR https://github.com/openservicemesh/osm/pull/2070
ref  https://github.com/openservicemesh/osm/issues/507
--- …
=> certificates/vault: Use new types vaultRole and vaultPath

.env.example, charts/osm/README.md, charts/osm/templates/grafana-configmap.yaml, charts/osm/templates/grafana-deployment.yaml, charts/osm/templates/grafana-rbac.yaml, charts/osm/templates/grafana-svc.yaml, charts/osm/templates/osm-configmap.yaml, charts/osm/templates/prometheus-configmap.yaml, charts/osm/templates/prometheus-deployment.yaml, charts/osm/templates/prometheus-rbac.yaml, charts/osm/templates/prometheus-svc.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, cmd/cli/install.go, cmd/cli/install_test.go, demo/README.md, demo/run-osm-demo.sh, docs/example/README.md, docs/osm_config_map.md, docs/patterns/observability/README.md, docs/patterns/observability/metrics.md, pkg/constants/constants.go, tests/e2e/common.go
This PR disables Prometheus by default in `osm install` but deploys prometheus by default for the demo only.
Fixes #1753 #1893 #1897 
No
=> feat(metrics): Disable Prometheus by default

OWNERS
I am told (as of today) that the CNCF uses this file to determine who can open service desk tickets for a given project. Phillip is definitely someone who should be able to do such, as the PM on the project.
=> Adding Phillip Gibson as OWNER for public record

DESIGN.md, pkg/certificate/mock_certificate.go, pkg/certificate/providers/certmanager/certificate.go, pkg/certificate/providers/tresor/certificate.go, pkg/certificate/providers/vault/certificate_manager.go, pkg/certificate/providers/vault/certificate_manager_test.go, pkg/certificate/types.go, pkg/injector/webhook_test.go
For some cert issuers, like Hashicorp Vault, the `serial_number` of the certificate is important and we need to keep track of that.
The `serial_number` is used, for instance, to revoke a given cert.
This PR adds `GetSerialNumber()` to the `Certificater` interface.  Other PRs will implement `serial_number` where necessary.
In this PR we also add `serialNumber string` for the Hashicorp Vault `Certificate{}` and implement `GetSerialNumber()` based on that field.
ref https://github.com/openservicemesh/osm/pull/2070 https://github.com/openservicemesh/osm/issues/507
--- 
- …
=> certificate: Adding GetSerialNumber() to Certificater interface

pkg/certificate/providers/vault/certificate_manager.go, pkg/certificate/providers/vault/certificate_manager_test.go, pkg/certificate/providers/vault/debugger.go, pkg/certificate/providers/vault/debugger_test.go, pkg/certificate/providers/vault/types.go
This PR removes the `cacheLock` mutex from `Certificate{}` and uses a `sync.Map` instead of `*map[certificate.CommonName]certificate.Certificater`
ref https://github.com/openservicemesh/osm/issues/507
--- …
=> certificate/vault: Change cache from a map to sync.Map

cmd/osm-controller/osm-controller_test.go, pkg/catalog/fake.go, pkg/catalog/helpers_test.go, pkg/catalog/ingress_test.go, pkg/certificate/providers/tresor/certificate.go, pkg/certificate/providers/tresor/certificate_manager.go, pkg/certificate/providers/tresor/debugger.go, pkg/certificate/providers/tresor/debugger_test.go, pkg/certificate/providers/tresor/fake.go, pkg/certificate/providers/tresor/types.go, pkg/certificate/rotor/rotor_test.go, pkg/envoy/ads/response_test.go, pkg/envoy/rds/response_test.go, pkg/injector/patch_test.go, pkg/injector/webhook_test.go, pkg/utils/grpc_test.go, pkg/utils/mtls_test.go, tests/e2e/scenario_mutatingwebhook_reconcile_test.go
Use a `sync.Map` for Tresor's cache instead of `*map[certificate.CommonName]certificate.Certificater`
ref https://github.com/openservicemesh/osm/issues/507
---
=> certificate/tresor: Change cache from a map to sync.Map

pkg/envoy/rbac/policy.go, pkg/envoy/rbac/policy_test.go, pkg/envoy/rbac/types.go
This change adds a new rbac pkg to build RBAC policies.
Currently this change doesn't affect existing functionality
and the goal is to have a generic rbac policy builder
that can be used when an RBAC policy needs to be built.
LDS builds RBAC policies to enforce RBAC on inbound
connections from downstreams. RDS will require to enable
RBAC on a per route basis in the future. This pkg will
serve as a modeler for RBAC policies.
Part of #2088
- …
=> envoy/rbac: add generic RBAC policy builder

pkg/envoy/lds/inmesh.go, pkg/envoy/lds/listener.go
Moves code related to building outbound mesh filter chain
to the `inmesh.go` file which deals with in-mesh listener components. …
=> envoy/lds: move mesh related filter chain code to its file

tests/e2e/README.md, tests/e2e/e2e_certmanager_test.go, tests/e2e/e2e_debug_server_test.go, tests/e2e/e2e_deployment_client_server_test.go, tests/e2e/e2e_egress_test.go, tests/e2e/e2e_fluentbit_test.go, tests/e2e/e2e_hashivault_test.go, tests/e2e/e2e_helm_install_test.go, tests/e2e/e2e_permissive_test.go, tests/e2e/e2e_pod_client_server_test.go, tests/e2e/e2e_trafficsplit_same_sa_test.go, tests/e2e/e2e_trafficsplit_test.go, tests/framework/common.go, tests/framework/common_apps.go, tests/framework/common_smi.go, tests/framework/common_traffic.go, tests/scenarios/scenario_mutatingwebhook_reconcile_test.go, tests/scenarios/suite_test.go
New file structure:
- tests/
- framework/
-  Contains framework files. Importing these will automatically
set up init, BeaforeEach, AfterEach... hooks we usually run
between tests.
- e2e/
- contains end-to-end tests.
- scenarios/
- Contains larger, use-case driven tests that might benefit from
using framework itself.
Changes:
- Updated some README.md references
- Moved framework specific files to "framework" folder.
- Made most of the usable framework structures and attributess
public for importing modules/tests to use.
- Moved mutating_webhook scenario under scenarios. …
=> tests/e2e: isolate framework from tests, restructure files

pkg/certificate/providers/vault/certificate_manager.go, pkg/certificate/providers/vault/certificate_manager_test.go
The goal of this PR is to carve out the function figuring out the Issuing CA for the connected Hashicorp Vault in a separate function.
This obviously adds more code and still does the same thing.  The idea is to eventually implement `pki/revoke` in the Hashi Vault API via the `ReleaseCertificate` function, so that the temp certificate does not linger around Vault and is never renewed etc.
The `pki/revoke` API call to Hashicorp Vault will happen as part of this GitHub Issue: https://github.com/openservicemesh/osm/issues/2068
ref https://github.com/openservicemesh/osm/pull/2070 https://github.com/openservicemesh/osm/issues/507
---
- CLI Tool               [ …
=> vault: Carve out fetching of Issuing CA into a function

pkg/certificate/providers/vault/certificate_manager_test.go
Two recent PRs introduced a compilation error, which is failing on main.  This was caused by a semantic merge conflict, which did not break on the individual PRs.
1) Introduced a change to a type:  https://github.com/openservicemesh/osm/pull/2074/files#diff-e7b3046705df4aa3c3cf672ccbb4860037655b8bb52d87adbdd53383d9ac0a64R23
2) Introduced a new test using the old type:  https://github.com/openservicemesh/osm/pull/2069/files#diff-a262c8109d371baa7fc9661024a7d4b8099a24d4954efccc8862dd4d3501c515R112
The PR here fixes the test (2), which must use the new type (1).
---
- …
=> Fixing Hashi Vault integration test

pkg/envoy/lds/inmesh.go, pkg/envoy/lds/listener.go, pkg/envoy/lds/listener_test.go
Currently, OSM only supports HTTP protocol, and as such the outbound
filter chain is specific to HTTP (via the HTTP filter). This change
renames the function and adds an additional filter chain match criteria
to the HTTP filter chain to be specific to HTTP protocols that the
downstream client is allowed to use for HTTP requests. Since OSM
only supports non TLS based HTTP request origination for in-mesh
traffic, the supported protocols are http/1.0, http/1.1,
h2c (HTTP2 without TLS, ex. grpc.Insecure()). HTTP2 over TLS (h2)
is not supported since OSM requires clients create HTTP requests
over plaintext, with OSM providing mTLS capability via proxy-proxy
communication.
The additional filter chain matching based on application protocols
should not affect the egress filter, …
=> envoy/lds: Make outbound HTTP filter chain specific to HTTP traffic

pkg/envoy/cds/cluster.go, pkg/envoy/cds/response_test.go, pkg/envoy/lds/ingress.go, pkg/envoy/lds/inmesh.go, pkg/envoy/lds/listener.go, pkg/envoy/lds/rbac.go, pkg/envoy/xdsutil.go
Uses `ptypes.MarshalAny` directly instead of wrapper api that doesn't
add value.
`No`
=> envoy: use ptypes.MarshalAny directly instead of unnecessary wrapper

pkg/envoy/lds/inmesh.go, pkg/envoy/lds/listener.go, pkg/envoy/lds/listener_test.go
Renames the function and changes its signature to remove
unused argument.
`No`
=> envoy/lds: change HTTP filter's function signature

pkg/catalog/catalog.go, pkg/kubernetes/client_test.go, pkg/kubernetes/types.go
- OSM does not hard-require periodic re-configs to guarantee state
correctness in its current form. In order to help maintain this statu quo,
we will disable ticker and increase the k8s resync period, which will
help catch issues that break on-event updates at testing/CI time.
- Since we still believe periodic arbitrary resyncs could be something
that we still might want to have at later time/different circumstances, to
ensure config correctness, we will add configurability into ticker and
resync intervals in a later patch (#2103).
No
=> osm: disable ticker, space k8s resyncs to 5m

pkg/envoy/lds/inmesh.go, pkg/envoy/lds/listener.go, pkg/envoy/lds/listener_test.go, pkg/envoy/lds/response.go, pkg/envoy/lds/types.go
This change consolidates functions used to build the listener
component as method receivers for the `listenerBuilder` type.
This results in better organization of related code and avoids
passing MeshCataloger and Configurator objects repeatedly
between different functions.
This is in preparation for #2056 and #1521.
- Other …
=> envoy/lds: use listenerBuilder type to build listener and filters

pkg/envoy/lds/inmesh.go, pkg/envoy/lds/listener.go, pkg/envoy/lds/listener_test.go
To be able to construct the outbound filter chain for an upstream
service, the upstream service needs to have endpoints. If endpoints
are missing, then the filter chain cannot be constructed.
This change logs an error in the case when the filter chain for
an upstream cannot be constructed. It also continues building
the filter chains for other services so that connectivity to
other upstream services are not impacted when a particular
upstream filter chain cannot be constructed.
- Metrics                [ …
=> envoy/lds: update error handling while building HTTP filter chain

pkg/kubernetes/client_test.go, pkg/kubernetes/events/event_pubsub.go, pkg/kubernetes/events/event_pubsub_test.go, pkg/kubernetes/events/types.go, pkg/smi/client_test.go
- Introduces Unsub() to pubsub
- adds a Unsub() test
- moves few tests to use pubsub and not read from individual channels
fixes #2108
----
No
=> pubsub: introduce pubsub chan Unsub(), fix few sync tests

pkg/envoy/lds/inmesh.go, pkg/envoy/lds/inmesh_test.go, pkg/envoy/lds/listener.go
Consolidates logic to build the outbound HTTP filter chain.
This is in preparation to build the outbound TCP filter chain.
No functional change being introduced.
`No`
=> envoy/lds: consolidate HTTP filter chain building

charts/osm/values.schema.json
This change updates values.schema.json to allow defining an empty
OpenServiceMesh.image.pullPolicy, which behaves as described here:
https://kubernetes.io/docs/concepts/containers/images/#updating-images …
=> fix(chart): allow empty OpenServiceMesh.image.pullPolicy

charts/osm/templates/prometheus-configmap.yaml, charts/osm/templates/prometheus-deployment.yaml
(tentative)
We are using large amounts of labels to tag our metrics with addtional
dimensions of interest. This is good for visibility, however this explodes
in RAM consumption on Prometheus once scraped.
Most of the heavily unscaling metrics are the time-bucket series, which
already have large number of dimensions due to the buckets themselves.
- By filtering out time-bucket series (which might contain latency and
request total time buckets), we can cut the memory consumption around
66~70%, allowing larger scales to work under 2Gb, compared with same
scale crashing at 4Gb).
- Additionally, rose the RAM limit for prometheus to 2Gb.
Purely tentative, proper discussion on relabeling has to happen, this
is however required to even support slightly larger number of pods for
the time being. …
=> prometheus: drop time-bucket series, increase ram limit to 2G

pkg/kubernetes/event_handlers.go
As an increasing number of packages' channels are becoming unused
in favor of pubsub channels, these logs are quickly becoming a hog as warn.
We will however keep them as trace if we ever need them.
```
kubectl logs osm-controller-7545bfb54c-8x7vl | grep "Channel for provider Kubernetes is full" | wc -l
5069
```
No
=> pkg/kubernetes: reduce warn log to trace

pkg/envoy/rds/response.go, pkg/envoy/rds/response_test.go
Signed-off-by: addozhang <duwasai@gmail.com>
PR for #2092 
Sorry, the forked repo deleted by mistake. 
=> #2091 filter out split service from weighted cluster in route config

tests/framework/common.go
A new option to configure tagging the Namespaces with OSM annotations
to expose prometheus endpoints have been added, and are enabled by default.
Minor also: enable Debug server by default for all testing, when
not overriden by the test.
No
=> tests/e2e: EnableNsMetrics and EnableDebugServer enabled by default

docs/design/service_app_protocol.md
This change adds a proposal doc to address the need to be able
to determine the application protocol served by a service's port.
Part of #1521 …
=> [RFC] docs/design: proposal to determine application protocol

cmd/cli/dashboard.go, cmd/cli/proxy_configdump.go, pkg/kubernetes/portforward.go, pkg/utils/portforward.go
This commit just moves PortForwarder to a more generic/utils
location in the repo.
Testing will require immediate use of port-forwarding; moving
it to a less bloated/more generic package hopes to reduced number
of imports and coupling between users of this feature.
No
=> cli: move portForwarder to a more generic location

charts/osm/README.md, charts/osm/templates/osm-deployment.yaml, charts/osm/templates/proxy-config.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, docs/patterns/observability/logs.md
**Description**: Adds support for outbound proxy with Fluent Bit. Updates Fluent Bit to v1.6.4.
- New Functionality      [x]
no, no
=> fluent bit: Add support for outbound http proxy

pkg/envoy/cds/response.go, pkg/envoy/cds/response_test.go, pkg/envoy/route/config.go, pkg/envoy/route/config_test.go, pkg/envoy/types.go, pkg/envoy/xdsutil.go, pkg/service/types.go
Instead of leaking local cluster syntax across pkgs, using
an api makes the code cleaner. This api will be used to
retrieve the local cluster name for a given service cluster. …
=> envoy: use an api to retrieve the local cluster name

pkg/endpoint/providers/kube/client_test.go
Since addition of PubSub, class announcement channels are not
reliable to get k8s update notifications; pubsub has to be used instead
for accuracy.
No
=> endpoint/k8s: Fix unit test sync

ci/cmd/maestro.go, ci/cmd/maestro/kubernetes_tools.go
This change adds Helm release deletion to the `DeleteNamespaces` function called
by the maestro to cleanup resources to prevent any cluster-wide
resources from lingering after the rest of the installation is gone.
- Does this change contain code from or inspired by another project? If so, did you notify …
=> fix(maestro): cleanup helm releases in deleted namespaces

pkg/envoy/rbac/policy.go, pkg/envoy/rbac/policy_test.go, pkg/envoy/rbac/types.go
Currently, the rbac policy generator only support programming
principal rules, with the permission set to ANY, if not specified
in the rule spec. This change allows programming destination ports
as permissions in RBAC rules.
This is required to enable TCP port based filtering.
Part of #1521
- Does this …
=> envoy/rbac: support destination port permission in rules

pkg/envoy/lds/inmesh.go, pkg/envoy/lds/inmesh_test.go
This change adds the plumbing necessary to be able to
proxy indbound TCP traffic for a service. Similar to
the inbound HTTP filter chain, a TCP filter chain
is adder per TCP port exposed on the service. This
is the first change in the series to support TCP traffic.
Subsequent changes will enable enforcing TCP port based
rules as a part of the RBAC policies.
Note that this change will not allow TCP clients to access
TCP based services yet because outbound TCP proxying with
TLS still needs to be implemented. This change does not
affect HTTP traffic.
Part of #1521
- Networking …
=> envoy/lds: add support for inbound TCP proxying

charts/osm/templates/fluentbit-configmap.yaml
**Description**: This change updates the Fluent Bit input plugin to make it read from the head of the log file rather than the tail. Reading from the tail was causing the first few logs to be missed. …
=> fix(fluent bit): make input plugin read from head of file

pkg/trafficpolicy/trafficpolicy.go, pkg/trafficpolicy/trafficpolicy_test.go
feat(pkg/trafficpolicy): add routes to outbound traffic policy
* adds AddRoute method + test to outbound traffic policy
* part of #2034
--> …
=> feat(pkg/trafficpolicy): add routes to outbound traffic policy

Makefile, demo/cmd/tcp-client/tcp-client.go, demo/cmd/tcp-echo-server/tcp-echo-server.go, demo/deploy-tcp-client.sh, demo/deploy-tcp-echo-service.sh, dockerfiles/Dockerfile.tcp-client, dockerfiles/Dockerfile.tcp-echo-server
This change adds simple tcp client and server apps to
demo tcp support in OSM. The client opens a connection,
sends a number of messages, and prints the server response.
The server simply echoes back the client's message.
Part of #1521, to be used as a simple demo to showcase TCP
traffic when OSM supports TCP. TCP support is still in progress
but the apps don't depend on it.
- Other …
=> demo/tcp: adds simple tcp client server demo

pkg/catalog/mock_catalog.go, pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/catalog/types.go
This PR adds a method to pkg/catalog which assess traffic targets and queries related Kubernetes services to determine which services a workload with the given service account can access. This will be used in determining outbound routes for both TCPRoute and as part of the route refactor described n #2034 to program remote clusters via CDS.
- Control Plane          [ X]
Please answer …
=> feat(pkg/catalog): list allowed outbound services for identity

docs/release_guide.md
This change makes clear that `git push` commands in the release process
should go to the remote representing the main repo, not forks. It
changes the example origin name from `origin` to `upstream` to reduce
accidental pushes to forks and better stand out in command snippets. …
=> docs(release): clarify remotes in release guide

pkg/catalog/helpers_test.go, pkg/catalog/routes.go, pkg/catalog/routes_test.go
This PR updates `ListAllowedOutboundServicesForIdentity` to handle permissive mode. When allowed outbound services are requested for a workload, all services running in the mesh will be returned. …
=> ref(pkg/catalog): update ListAllowedOutboundServicesForIdentity

charts/osm/grafana/dashboards/osm-mesh-envoy-details.json
For display purposes, and for quickly changing values, `rate` properly
gives an average but this gets diluted if multiple values with
high variance appear in the same bucket.
For measures which have high variance and might be of interest
to understand the deltas with as much precision possible,
irate will always compute the delta between previous and current point,
regardless of bucket size, which makes sense to understand sudden
changes of trend which could get diluted/avgd otherwise.
No
=> Grafana/dashboards: change rate to irate

tests/framework/common.go
Two small improvements:
- Allows specifying a deterministic name to the test folder by test parameter
- Allows setting osm install cli overrides
No
=> tests/frmwrk: Add testFolder and setOverrides

DESIGN.md, pkg/catalog/mock_catalog.go, pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/catalog/types.go, pkg/envoy/ads/response.go, pkg/envoy/eds/response.go, pkg/envoy/lds/listener.go, pkg/envoy/lds/response.go
This change deprecates the `ListAllowedOutboundServices` api
in favor of the newer `ListAllowedOutboundServicesForIdentity` api.
The newer api fetches the outbound services purely based on
TrafficTargets -> service mapping, while the older one constructed
all possible combinations of traffic policies for the service,
going through all SMI policies, and using the internally built
`trafficpolicy.TrafficTarget` to figure out the outbound services,
which affects performances (repeated cache access for different
k8s resources).
This also updates the moves the code related to building
outbound filter chains per service to its own function.
- CLI …
=> pkg/*: use newer api to list outbound services and update outbound listener building

charts/osm/templates/mutatingwebhook.yaml
failurePolicy in the MutatingWebhookConfiguration should
always be set to Fail so that no new resources get created
and thus bypass SMI Traffic Target policies if the for some
reason the webhook server is down. This is intentional and
guarentees that new pods in the monitored namespaces and those
intended to be injected with the sidecar are indeed injected.
Setting this value to Ignore may expose Pods to traffic
they should not be exposed to.
- Tests                  [ …
=> doc(charts): doc why failurePolicy must be Fail

tests/framework/common_apps.go, tests/scale/README.md
**Description**: `s/GetOSMPrometheusaHandle/GetOSMPrometheusHandle/`
No
=> fix(e2e): fix typo in method name

tests/framework/common_apps.go, tests/framework/common_metrics.go
This change adds the ability to stop the port-forward that happens when
getting a handle to Prometheus or Grafana to support detaching and
reattaching in the middle of a test. …
=> fix(e2e): gracefully stop port forwarding to Prometheus/Grafana

demo/cmd/tcp-client/tcp-client.go, demo/deploy-tcp-client.sh, demo/deploy-tcp-echo-service.sh, pkg/envoy/lds/inmesh.go, pkg/envoy/lds/inmesh_test.go, pkg/envoy/lds/listener.go, pkg/envoy/lds/listener_test.go, pkg/envoy/lds/response.go
This change adds support proxying outbound TCP traffic.
Similar to the HTTP filter chain per upstream, a TCP proxy
filter chain is creater per upstream on the client.
Also updates the TCP app specs and client's connection and
messages per connection paramters to see more new connections
periodically.
Part of #1521 …
=> tcp: add outbound proxying support and update tcp demo

pkg/envoy/sds/response.go, pkg/envoy/sds/response_test.go, tests/framework/common.go
Use of fallthrough statement is unnecessary in these cases because
we don't have multiple different statements for these cases. Cases
with the same underlying statements should simply be grouped under
the same case clause. …
=> pkg/*: use mutliple value case statement instead of fallthrough

pkg/kubernetes/util.go, pkg/kubernetes/util_test.go
* These functions return hostnames based on whether you
want hostnames local to the namespace for the service or
namespace scoped hostnames. It breaks up the function
below it (GetHostnamesForService).
* These functions will make it easier to build policies
for clients running in the same namespace as service vs.
outside
* part of #2034
* see #2187 for how these will be used
Signed-off-by: Michelle Noorali <michellemolu@gmail.com>
- CI …
=> feat(util): add convenience funcs to get hostnames

.github/workflows/main.yml, Makefile, tests/e2e/README.md, tests/e2e/e2e_pod_client_server_test.go, tests/framework/common.go, tests/framework/common_apps.go, tests/framework/common_smi.go, tests/framework/common_traffic.go
This change adds an e2e test for TCP traffic. The test verifies
that the inbound and outbound TCP filtering and proxying works
as expected. It uses `netcat` to initiate TCP connections
to the `tcp-echo-server` that echoes back the response.
Due to the absence of TCPRoute spec support at this moment, the
test uses a TrafficTarget without specific TCP rules to verify
inbound and outbound proxying of TCP traffic. The test will need
to be updated to be able to perform RBAC on TCP routes when the
TCPRoute spec is available to use.
It also updates the client container image for the test to rely
on an image with additional tools (ex. netcat in this case).
Part of #1521
- …
=> tests/e2e: add e2e test for TCP traffic

charts/osm/templates/fluentbit-configmap.yaml, charts/osm/templates/osm-deployment.yaml, docs/patterns/observability/logs.md
* Adds the osm controller name as a key/value pair in the logs to help users query/refine log output
* Makes environment variables explicitly defined
no, no
=> fluent bit: add identifier to help query logs in output 

demo/join-namespaces.sh, demo/unjoin-namespaces.sh
This PR changes:
- how we change the `osm-config` ConfigMap - tweak only the `permissive_traffic_policy_mode` instead of the entire Configmap
- applies a different `bookstore` service depending on whether we are in the mesh or not - this Service reflects the current state of the mesh in order to make the demo work - it should ideally be the exact same YAML
Please answer …
=> demo: Tweaking join/unjoin demo scripts

.github/workflows/release-chart.yml
This change adds a step to the chart release CI workflow to force git to
signoff commits to pass the DCO check.
No
=> fix(ci): workaround DCO requirement for gh-pages branch

tests/framework/common_apps.go
On setups ~<1.18 setting AppProtocol can throw issues if the AppProtocol
is present but it has not been enabled on the setup as a gate flag (for the
ones that support it) :
```
99 Unexpected error:
100 <*errors.errorString | 0xc0004192b0>: {​​​​​​​​
101 s: "Could not create Service: Service \"traffic-split\" is invalid: spec.ports[0].appProtocol: Forbidden: This field can be enabled with the ServiceAppProtocol feature gate",
```
No
=> tests/e2e: set AppProto only if definition has it set

scripts/test-w-coverage.sh, tests/scale/osm_common_profile_resources.go, tests/scale/scale_trafficSplit_test.go
Body and operation of the test is close to identical to existing
`e2e_trafficsplit_test.go`, with few differences to be able to 
iterate repetitively over the body of the test itself.
Test will repeat the test operation till a failure is observed.
At each iteration, the timestamps are recorded, and later statistics
for relevant pods are gathered and output as part of the results,
for every iteration and its duration.
Test results are stored in a test folder generated by the test itself,
if not given by parametre. 
- `tests/scale/`
- `osm_common_profile_resources.go`: contains a set of convenience
functions that define usual resources and outputs we are interested
in keeping/having for OSM specific tests.
- `scale_trafficSplit_test.go`: test implementation
Please mark with X for applicable …
=> tests/scale: pod/traffic split scaling test

pkg/envoy/ads/stream.go
This commit adds back the `sendAllResponse` that was removed [here](https://github.com/openservicemesh/osm/pull/213/files#diff-a85c2c3be39b51ce94870509935533e4eb8de6dec7111bf672c5bfdcdd238353L38)
On a controller re/start, the controller synchronizes all kubernetes
objects and only after starts the ADS server.
When an envoy reconnects to the new ctrl plane, there might be no event
or trigger that pushes a new configuration to the envoy, which in the case
of a restart, new service certificates need to be issued and pushed.
For the time being, we will mandatorily push a full config on a
connecting envoy, which will guarantee it gets the new certs in case
of a restart, and in case no new events are generated by config.
Fixes: #2131
- Does this change contain code …
=> envoy/ads/stream.go: Force full config of an envoy when it connects

tests/e2e/e2e_controller_restart_test.go, tests/framework/common.go
This change adds an e2e test to test the connectivity between
client and server before/during/after osm-controller restarts.
Previously this was resulting in 503s due to issue #2131 which
has been fixed.
Resolves #2146 and tests #2145.
- Does this change contain code from or inspired by another project? …
=> tests/e2e: add connectivity test with osm-controller restart

pkg/catalog/mock_catalog.go, pkg/catalog/traffictarget.go, pkg/catalog/traffictarget_test.go, pkg/catalog/types.go, pkg/smi/client.go, pkg/smi/fake.go, pkg/smi/mock_meshspec.go, pkg/smi/types.go, pkg/trafficpolicy/types.go
Adds an API to retrieve a list of traffic target objects along
with their associated routes (limited to TCP). The traffic target
objects will be used to directly map to RBAC policies configured
on the upstream proxy.
This API will be leveraged to implement RBAC policies for TCP traffic.
For ex., the following TrafficTarget policy and TCPRoute will generate
an RBAC policy as seen below.
```
kind: TCPRoute
metadata:
name: tcp-route
namespace: default
spec:
matches:
ports:
- 8080
---
kind: TrafficTarget
metadata:
name: test
namespace: default
spec:
destination:
kind: ServiceAccount
name: sa-1
namespace: default
rules:
- kind: TCPRoute
name: tcp-route
sources:
- kind: ServiceAccount
name: sa-2
namespace: default
---
```
rbac_policy on proxy with identity `default/sa-1`
```
{ …
```
=> pkg/*: add api to list traffic targets composed of associated routes

pkg/catalog/dispatcher.go, pkg/configurator/client.go
Currently, dispatcher listens to ConfigMap changes and triggers
global envoy update based on any changes on OSM's config map.
A more specific handler for ConfigMap could identify specific changes
that require a global config update and notify dispatcher instead,
avoiding full configs for things that are not needed.
No
=> configurator: add specific ConfigMap handler

pkg/catalog/mock_catalog.go, pkg/catalog/traffictarget.go, pkg/catalog/traffictarget_test.go, pkg/catalog/types.go
Updates the api added in 85f8810a to encode the fully qualified
service identities instead of the identities being encoded
only as the service account information. This avoids leaking
service account primitives to XDS components that will leverage
this API. This API will be used to build the RBAC policies and
will not have to deal with service accounts after this change
due to the ServiceIdentity abstraction.
This change additionally adds a workaround to implement TCP route
matching by relying on a `ports` label on the v1alpha3 TCPRoute
resource which does not have a spec yet. Upon migration to v1alpha4
of TCPRoute, the logic to rely on labels will be removed.
Part of #1521
- Install …
=> catalog: update api to retrieve traffic targets

demo/cmd/bookstore/bookstore.go
This PR adds 3 new paths to the bookstore web server
- `/liveness`
- `/readiness`
- `/startup`
These are going to be part of the test for the solution (n/a) for https://github.com/openservicemesh/osm/issues/2207
---
--> …
=> demo: Adding /liveness, /readiness, /startup paths to the bookstore web server

pkg/injector/envoy_config.go, pkg/injector/envoy_config_test.go
This PR creates a 2 helper functions to create the Envoy bootstrap config.
**No Functional Code Or Struct Changes**  (this is proven by the fact that existing tests for the entire Envoy bootstrap config did not change)
- `getXdsCluster()` creates the static XDS cluster struct
- `getStaticResources()` creates the `static_resources` struct, which contains the XDS cluster
This is merely moving struct creation into a new function and adding a test (albeit duplicating an existing overall test)
---
- Security …
=> injector: Split Envoy bootstrap config generation into smaller functions

pkg/envoy/lds/inmesh_test.go, pkg/envoy/lds/rbac.go, pkg/envoy/lds/rbac_test.go, pkg/envoy/rbac/policy.go, pkg/envoy/rbac/policy_test.go, tests/e2e/e2e_pod_client_server_test.go, tests/framework/common_smi.go
This change integrates the RBAC policies applied
via the RBAC network filter with the ports specified
via TCPRoutes. Only ports specified via the TCPRoute
resource will be allowed at the upstream if a TCPRoute
resource is associated as a rule in a TrafficTarget
resource.
This change also updates the TCP e2e tests to create
a TCPRoute resource with ports for the test to function
with RBAC policies.
Part of #1521 …
=> rbac/tcp: support port based RBAC for tcp traffic

pkg/envoy/lds/rbac_test.go, pkg/envoy/rbac/policy.go, pkg/envoy/rbac/policy_test.go
Renames the helper functions used for RBAC principals
and permissions to make them sound better.
Based on suggestion in https://github.com/openservicemesh/osm/pull/2224#discussion_r546144684. …
=> envoy/rbac: rename rbac policy helper functions

pkg/kubernetes/event_handlers_test.go
Race checking the size of a channel, in which the event might
or might have not arrived.
No
=> kubernetes/events: Fix race on event handler test

charts/osm/templates/proxy-config.yaml
* Updates fluent bit proxy secret to allow http or https proxy value to be empty when the other is in use
* Resolves #2229  …
=> fix(fluent bit): allow httpProxy or httpsProxy value to be empty

DESIGN.md
Signed-off-by: aisuko <urakiny@gmail.com>
Hi guys, I'm working on https://github.com/layer5io/meshery-osm, the adapter for deploying `OSM`, and I'd like to find some more native way to deploy OSM to the Kubernetes cluster(We are deploying OSM by executing the bash script, which may not a good way for me). So, I came here and find a more native way and hit little issues of the `Design.md`.
- Performance …
=> fix(docs/Design.md): Fix the wrong title links of document contents

pkg/envoy/lds/inmesh.go, pkg/envoy/lds/inmesh_test.go
Remove duplicated IP ranges for a single filter chain which
occurs from multiple ports per service.
Part of #2237 
No
=> envoy/lds: remove duplicated address_prefix

demo/README.md, docs/example/README.md
Signed-off-by: aisuko <urakiny@gmail.com>
The `./scripts/port-forward-osm-debug.sh` `port-forward` the container port to localhost `9092`, so changed the port from `http://localhost:9091/debug` to `http://localhost:9092/debug` in the `demo/README.md` …
=> fix(demo/README.md): Fixing the OSM controller debug port in README

pkg/configurator/validating_webhook.go
The port 9090 which was previously being used is already
used by the sidecar injector webhook. This change updates
the server's listen port to 9093 instead.
Fixes:
```
{"level":"error","component":"configurator","error":"listen tcp :9090: bind: address already in use","time":"2021-01-04T21:50:49Z","file":"validating_webhook.go:139","message":"Validating webhook HTTP server failed to start: listen tcp :9090: bind: address already in use"}
```
- Tests                  [ …
=> configurator: update validating webhook's port

charts/osm/templates/validatingwebhook.yaml
With the deletion being monitored, uninstall fails
because the webhook gets deleted only after the
controller serving the webhook gets deleted.
Since delete is not tested yet with uninstall workflows,
remove this, otherwise mesh deletion and install
gets impacted.
Resolves #2244 …
=> charts/validatingwebhook: allow webhook deletion

demo/cmd/bookbuyer/bookbuyer.go, demo/cmd/bookstore/bookstore.go, demo/cmd/bookthief/bookthief.go, pkg/logger/logger.go, pkg/smi/fake.go, pkg/tests/stream.go, pkg/webhook/webhook_test.go
Use `_` for unused fn params.
---
=> Use _ for unused function params

cmd/cli/metrics_disable.go, cmd/cli/metrics_enable.go
This PR fixes a typo in 2 separate comments.
---
=> Fix typo s/namepace/namespace/g

pkg/catalog/announcement_handlers_test.go, pkg/catalog/debugger.go, pkg/certificate/providers/tresor/certificate_manager.go, pkg/certificate/providers/tresor/debugger.go, pkg/certificate/providers/vault/certificate_manager.go, pkg/certificate/providers/vault/certificate_manager_test.go, pkg/certificate/providers/vault/debugger.go
This PR explains what the `return true` does.
I find myself spending a mental cycle to recollect what this `return true` does. I believe that adding this comment would make it easy for the next person who looks at this `return true` to understand that this is what makes `mapset`'s `Range()` continue the iteration until the end of the set.
--- …
=> catalog: Add comment to explain what a bool return does

pkg/catalog/routes.go, pkg/catalog/routes_test.go
This PR simplifies `isValidTrafficTarget()`
Added a test to cover non-nil but empty Rules.
---
=> catalog: simplify function isValidTrafficTarget()

pkg/kubernetes/event_handlers.go
I noticed the `informerName` and `providerName` function params were unused and was going to remove them. But they are important context - should be preserved. Decided to add them to the debug log message. I suspect we'll use them in other debugging tools we build around this
--- …
=> kubernetes: Log the informer and provider names w/ debug log messages

charts/osm/templates/validatingwebhook.yaml
Since the validating webhook has been disabled by c48acb9c due to
issue #2264, the validating webhook config needs to be disabled as
well. Otherwise config-map update will be broken. …
=> charts: disable validating webhook configuration

pkg/envoy/ads/stream.go, pkg/metricsstore/metricsstore.go, pkg/metricsstore/metricsstore_test.go
Adds a metric for the number of connected proxies.
Part of #902
`No`
=> metrics: expose metrics for number of connected proxies

pkg/injector/profiling.go, pkg/injector/profiling_test.go, pkg/injector/webhook.go, pkg/metricsstore/metricsstore.go
Adds two new metrics:
- InjectorSidecarCount: keeps track of number of sidecar injector webhooks
dealt over time.
- InjectorRqTime: time taken to process injector webhooks
No
=> metrics: add injector webhook metrics

charts/osm/templates/prometheus-configmap.yaml
Prometheus is still (by default) scrapping a large number of metrics we
are currently not using on our deployments.
This does not mean to say they are usless (which they are not), but by
default adding all metrics is causing serious memory bottlnecks when
increasing scale even at lower numbers.
A previous commit hacked the bucket timeseries out of the equation, as they
amounted for roughly 75% of memory usage on prometheus (from 20Mb per pod to 6Mb)
https://github.com/openservicemesh/osm/pull/2117
This patch pinpoints the exact metrics we use on our deployments, and limits
ingestion to only metrics we we are currently using.
This brings down 6Mb to 2Mb per pod (additional 66%), further allowing operation
of prometheus under larger setups.
Fixes: #2122
- Performance …
=> prometheus: limit scrapping to currently used metrics only

pkg/kubernetes/event_handlers.go, pkg/metricsstore/metricsstore.go, pkg/metricsstore/metricsstore_test.go
This change changes the osm_k8s_api_event_count metric to be
a counter vector so that the counters can be grouped as a counter
collection sharing the same description with variable labels.
Part of #902 …
=> metrics: add type and namespace label to k8s event metric

charts/osm/README.md, charts/osm/values.schema.json, charts/osm/values.yaml, go.mod, go.sum, pkg/envoy/lds/listener.go, pkg/envoy/lds/response.go
Currently the egress filter chain is a part of `listener.filter_chains`
config. While this works for now, there is the risk of egress traffic
matching in-mesh filter chains due to the way envoy performs
filter chain matching as we augment the service filter chains
with additional match criteria such as ports. The `listener.default_filter_chain` 
was specifically introduced to avoid such unintentional matching.
This is also required to be able to do port:protocol matching
on the oundbound filter chains with the introduction of TCP
support to distinguish between protocol specific traffic by
its port.
Resolves #2096
- …
=> envoy: update to v1.17 to leverage default_filter_chain matching

charts/osm/grafana/dashboards/osm-mesh-envoy-details.json, charts/osm/templates/osm-deployment.yaml, charts/osm/templates/prometheus-configmap.yaml
OSM has since recently started exporting prometheus format metrics.
This commit adds scrapping annotation on the OSM deployment, which will
be automatically picked up by Prometheus's Pod-based scrapping.
Also added Injector histogram and Connected proxies on the Mesh details
dashboard.
No
=> Adding scraping to OSM pod

pkg/kubernetes/event_handlers.go
Instead of add/update/delete values for the `type`
label for the metric, use the event type that is
a part of the announcement.
Part of #902 …
=> metrics: use event type value as the metric label

pkg/envoy/ads/profile.go, pkg/envoy/ads/response.go, pkg/envoy/ads/stream.go, pkg/envoy/types.go, pkg/metricsstore/metricsstore.go
- Added proxy config_update_time, histogram which keeps track of
how much time does individual XDS paths take to compute.
- The use of `newAggregatedDiscoveryResponse` + `s.send` has been abstracted
into a single function, to allow collection of metrics in both `stream.go` (request triggered)
and `response.go` (full config triggered). This is in order to account for being able to confirm
receipt of the configuration on envoy's side.
Some examples:
```
// Full update that no errors were seen
ProxyConfigUpdateTime["CDS", "svc_8491...", "true"] = 0.2792
ProxyConfigUpdateTime["EDS", "svc_8491...", "true"] = 0.122 
ProxyConfigUpdateTime["LDS", "svc_8491...", "true"] = 0.5445
ProxyConfigUpdateTime["RDS", "svc_8491...", "true"] = 0.921
ProxyConfigUpdateTime["SDS", "svc_8491...", "true"] = 1.2565 …
```
=> ads/metrics: implement xds path time metrics

pkg/catalog/errors.go, pkg/catalog/mock_catalog.go, pkg/catalog/service.go, pkg/catalog/service_test.go, pkg/catalog/types.go
This change adds an api to retrieve a service's port
to application protocol mapping, where the port is
the one used by clients to send requests to. This
port can be different than the actual ports exposed
by the service's application binary, ie. the api
returns the a service's `port` as opposed to its
`targetPort`.
This api will be used to program outbound filter chains
for upstream services which need to match on the ports
the clients send traffic to, and the protocol mapping
to be used for determining the type of traffic being
sent on that port.
For backwards compatibility, the default appProtocol
for a port is assumed to be `http` if not specified,
similar to other usages of the `appProtocol` field. …
=> catalog: add api to retrieve port:protocol mapping

pkg/envoy/lds/response.go, pkg/envoy/sds/response.go
This PR fixes a typo in 2 log messages (`s/SerivceAccount/ServiceAccount/g`).
---
=> xds: Fixing a typo in log message w/ ServiceAccount

pkg/envoy/lds/inmesh.go, pkg/envoy/lds/inmesh_test.go, pkg/envoy/lds/listener.go
This change updates how the outbound filter chains are built
per upstream service on the downstream proxy. Instead of
relying on the http_inspector listner_filter to inspect
the application protocol, filter chains use the destination
port of the service as a match, and the type of filter (http,
tcp etc.) is determined by the application protocol for that
port. The port-protocol mapping is already leveraged for
protocol specific filtering and proxying on the inbound
listener, this is now being leveraged for outbound filtering
as well.
This is also beneficial for the following reasons:
1. Application protocols such as mySQL where the server
initiates the application protocol handshake will result
in listener filters such as tls_inspector and
http_inspector to time out since …
=> envoy/lds: build outound service filter chains per service port

charts/osm/grafana/dashboards/osm-mesh-envoy-details.json, pkg/envoy/ads/response.go
- Fixed using the right shortname for labeling XDS types
- Added Grafana heatmaps for both Webhook and XDS (ADS only for now)
opeartions. See example below.
No
=> metrics: fix use of short XDS name, heatmaps for recent histograms

pkg/envoy/ads/stream.go, pkg/injector/patch.go, pkg/metricsstore/metricsstore.go
Description:
Adds a metric for the number of connected proxies.
Part of #902
Sample output for demo : 
- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? `No`
=> metrics : exposing metric for number for xds certificates issued

charts/osm/README.md, charts/osm/templates/osm-deployment.yaml, charts/osm/values.schema.json, charts/osm/values.yaml
=> changed from connectvault to certmanager in osm_deployment

pkg/injector/patch.go, pkg/injector/profiling.go, pkg/metricsstore/metricsstore.go
Description:
Adds a metric for the time take to issue of xds certificates.
`No`
=> metrics : exposing metric for time take to issue xds certificates 

docs/patterns/certificates.md, pkg/certificate/README.md, pkg/injector/webhook.go
This PR augments the `docs/patterns/certificates.md` document with the types of certificates used in OSM, where these are issued, the validity duration, and sample CN.
Also added a comment and renamed a few variables to increase verbosity and add clarity.
--- …
=> certificate: Document kinds of certificates in OSM

cmd/osm-controller/certificates_test.go, pkg/certificate/mock_certificate.go, pkg/certificate/providers/certmanager/certificate.go, pkg/certificate/providers/certmanager/certificate_manager.go, pkg/certificate/providers/certmanager/debugger_test.go, pkg/certificate/providers/certmanager/helpers.go, pkg/certificate/providers/certmanager/types.go, pkg/certificate/providers/tresor/ca.go, pkg/certificate/providers/tresor/certificate.go, pkg/certificate/providers/tresor/certificate_manager.go, pkg/certificate/providers/tresor/fake.go, pkg/certificate/providers/tresor/types.go, pkg/certificate/providers/vault/certificate_manager.go, pkg/certificate/providers/vault/certificate_manager_test.go, pkg/certificate/providers/vault/debugger_test.go, pkg/certificate/types.go, pkg/configurator/validating_webhook_test.go, pkg/injector/webhook_test.go
This PR implements `GetSerialNumber()` which is a member of the `Certificater` interface.
This function was stubbed and panicked.  Also returned string.
This PR:
- introduces `certificate.SerialNumber` type, which is an alias to string.
- changes `GetSerialNumber()` to return `SerialNumber` type instead of `string`
- adds `serialNumber` to Certificate structs and initializes it
This will fix https://github.com/openservicemesh/osm/issues/2312
---
- CI System …
=> certificate: Implement GetSerialNumber() for all certificate issuers/providers

pkg/envoy/ads/response_test.go, pkg/envoy/sds/response.go, pkg/envoy/xdsutil.go, pkg/envoy/xdsutil_test.go
This PR removes mentions of a `requestedCertType` variable and `getRequestedCertType()` function, which no longer exist.
This PR also removes `Outbound` and `Inbound` constants, which are not used. …
=> sds: Correct comments and tests - remove mentions of non-existent requestedCertType function

pkg/envoy/ads/response.go
**Description**: Closes #2309 
no, no
=> logging: remove response from log

pkg/certificate/providers/tresor/ca.go, pkg/certificate/providers/tresor/certificate_manager.go, pkg/certificate/providers/vault/certificate_manager.go, pkg/certificate/rotor/rotor.go, pkg/debugger/certificate.go, pkg/debugger/envoy.go, pkg/debugger/proxy.go
This PR replaces logging of certificate's CN with certificate's SerialNumber.
This PR partially addresses the concerns outlined in https://github.com/openservicemesh/osm/issues/2311
This PR does not address all issues - this is first of a few.
--- …
=> log: Replace CN with SerialNumber in log messages (where possible)

pkg/envoy/ads/stream.go, pkg/utils/mtls.go, pkg/utils/mtls_test.go
This PR changes the `ValidateClient()` function so that it returns not only the Envoy xDS certificate's CommonName, but also the certificate's SerialNumber, which will be used in log statements.
Also in this PR: removed logging of Pod IP and xDS certificate Subject CommonName
=> Change ValidateClient to return certificate SerialNumber for newly connected Envoy proxies

pkg/catalog/announcement_handlers_test.go, pkg/catalog/debugger_test.go, pkg/catalog/proxy.go, pkg/envoy/ads/grpc.go, pkg/envoy/ads/response_test.go, pkg/envoy/ads/stream.go, pkg/envoy/cds/response.go, pkg/envoy/cds/response_test.go, pkg/envoy/eds/response_test.go, pkg/envoy/proxy.go, pkg/envoy/proxy_test.go, pkg/envoy/sds/response_test.go, pkg/utils/mtls.go, tests/scenarios/helpers.go
This PR adds `SerialNumber` to the `NewProxy()` function in the `pkg/envoy` package.
With this change the `Proxy{}` struct is going to record not only the xDS certificate CommonName, but also the SerialNumber, and also the UID of the Pod the Envoy is fronting.
In a follow-up PR (https://github.com/openservicemesh/osm/pull/2333), the xDS certificate's `SerialNumber` is going to be used for all (most) log lines instead of the `CommonName`
=> proxy: Add certificate SerialNumber as a parameter to the NewProxy() function and as a field to the Proxy{} struct

pkg/catalog/routes.go, pkg/injector/profiling.go, pkg/injector/webhook.go
This PR rewrites log statements that attempt to log an `err` message using `log.Error().Msgf(err)` to using `log.Error().Err(err).Msgf()`
---
=> injector: Idiomatic logging of error messages with log.Error().Err(err)

pkg/catalog/announcement_handlers_test.go, pkg/catalog/proxy.go, pkg/catalog/types.go, pkg/certificate/providers/certmanager/certificate_manager.go, pkg/debugger/envoy.go, pkg/envoy/ads/grpc.go, pkg/envoy/ads/response.go, pkg/envoy/ads/stream.go, pkg/envoy/cds/response.go, pkg/envoy/eds/response.go, pkg/envoy/lds/response.go, pkg/envoy/proxy.go, pkg/envoy/proxy_test.go, pkg/envoy/rds/response.go, pkg/envoy/sds/response.go
This PR removes XDS Certificate CommonName from log messages and uses XDS Certificate's SerialNumber.
---
=> ads: Do not log Envoy's XDS Certificate CN; log cert's SerialNumber instead

pkg/envoy/ads/stream.go, pkg/envoy/proxy.go
This PR ensures that log messages emitted by `ads/stream.go` abide by the heuristic we established - we will log the Envoy xDS Certificate SerialNumber and not the Subject CommonName.
---
=> ads: Curate log messages when Envoys connect to xDS control plane

pkg/envoy/ads/grpc.go, pkg/envoy/ads/response.go, pkg/envoy/ads/stream.go, pkg/envoy/cds/response.go, pkg/envoy/sds/response.go
This PR replaces Envoy's XDS Certificate CommonName in logs with SerialNumber.
---
=> logs: Use Certificate SerialNumber instead of Subject CN

pkg/envoy/lds/inmesh.go, tests/e2e/e2e_grpc_client_server_test.go, tests/framework/common_traffic.go
OSM supports gRPC traffic since gRPC uses HTTP2 as the transport.
gRPC traffic is supported as long as a gRPC client uses plaintext
request origination and lets OSM upgrade it to TLS.
This change allows specifying `grpc` as an application protocol
so that it can leverage HTTP based routing. 
An e2e test has been added where a gRPC client 
[grpcurl](https://github.com/fullstorydev/grpcurl) makes gRPC requests to the [grpcbin](https://github.com/moul/grpcbin) service.
Part of #2353
Sample output from test:
```
STEP: Creating SMI policies
...
> (client/client -> server.server:9000) gRPC req succeeded, response: {
"reply": "hello client"
}
> (client/client -> server.server:9000) gRPC req succeeded, response: {
"reply": "hello client"
}
... …
```
=> gRPC: allow specifying gRPC as appProtocol for service ports

pkg/reconciler/mutatingwebhook/reconcile.go
Tweak the verbiage and capitalization of an error message.  Remove `.String()` as `NamespacedName` already implements `Stringer` interface:  https://github.com/kubernetes/kubernetes/blob/e79a873b4c0d6ae4d2cd49462e034999f80147d2/staging/src/k8s.io/apimachinery/pkg/types/namespacedname.go#L19-L39
--- …
=> reconciler: Tiny adjustment to a log message

pkg/injector/webhook.go
This PR fixes a bug in the positioning of the string template and corrects the Pod UID; also simplifies the message.
---
=> injector: Small correction to a log message

docs/patterns/observability/README.md
**Description**: Just fixes up a typo in one of the docs pages.
- Does this change contain code from or inspired by another project? **No.** If so, did you notify the maintainers and provide attribution? **N/A**
=> Fix typo on Prometheus enablement flag

pkg/catalog/xds_certificates.go, pkg/injector/patch.go
This PR adds context to some of the log messages in mesh catalog.
=> catalog: Augment log messages with Pod UID

pkg/envoy/route/config.go
I found this line to provide little to no value - decided to remove it.
Should we ever need to log the activity of this function we may consider augmenting the log line with additional context to know a bit more about what is being updated.
---
- Does this change contain code from …
=> envoy/route: Delete log line providing little info

pkg/envoy/ads/response.go
Adding a comment to a log line to remind us of the importance of logging ADS request/responses carefully
---
=> ads: Adding a comment to a log line to remind us of the importance of logging ADS request/responses carefully

pkg/envoy/ads/stream.go
Adding Envoy's Pod UID to some log messages for more context.
=> ads: Add more context with Envoy Pod UID to some log messages

pkg/injector/webhook.go
Fixing a log line - adding missing variable.
---
=> injector: Augmenting log line with missing variable

pkg/envoy/rds/response.go
This PR augment an error log message with the relevant Pod UID
=> rds: Augment error log message with Pod UID

pkg/envoy/ads/grpc.go, pkg/envoy/ads/stream.go
This PR tweaks a few ADS messages to add more context.
Changing log.Error to log.Debug for when a gRPC is cancelled.
=> envoy/ads: Augment log messages with context

pkg/configurator/client.go
Changing log.Info to log.Debug; adding context to log messages.
=> configurator: Convert Info log messages to Debug

pkg/certificate/providers/tresor/certificate_manager.go
Convert log.Info to log.Debug.
=> tresor: Change log level for a statement from Info to Debug

Makefile
This flag changed from `-kindCluster` to `-installType=KindCluster` but
the Makefile wasn't updated. This change adds the fix so `make test-e2e`
doesn't throw an error for the unknown flag. …
=> fix(make): update e2e kind cluster flag

.github/workflows/release.yml, Makefile, scripts/publish-image.sh
Makes image tags immutable for releases, github actions will not override image tags if it exists, and resolves #1797
- Other                  [x ]
no
=> feat(.github/workflows): add immutable image tag for releases

pkg/catalog/helpers_test.go, pkg/catalog/ingress_test.go, pkg/catalog/xds_certificates_test.go, pkg/envoy/ads/response_test.go, pkg/envoy/cds/response_test.go, pkg/envoy/eds/response_test.go, pkg/envoy/lds/response_test.go, pkg/injector/patch_test.go, pkg/kubernetes/event_handlers_test.go, pkg/tests/fixtures.go, pkg/tests/helpers.go, tests/scenarios/traffic_split_with_apex_service_test.go
This PR unifies the label/selector creation across all tests. 
For tests that involve getting the services from the proxy/cn it is necessary that the labels on the pods match the selectors on the services. This was being done incorrectly for a few tests, this PR mainly focuses on fixing that. In addition it also unifies the fixture creation by creating a single method  `NewPodFixture()`, that takes all the parameters required to create a pod ( namespace, pod name, service account and labels).  With this new method all previous methods have been deleted.
- …
=> (tests): Fix labels and selectors while creating pods and services for various test scenarios

pkg/configurator/validating_webhook_test.go
A variable that should be scoped to the given
test case in the table of tests was scoped
to the function, causing new tests being added
to the table to fail. Currently this test only
passes because of the way existing tests in the
table are ordered.
- …
=> configurator/test: fix bug due to test pollution

docs/content/_index.md
Follow-up to #2328. This moves the `_index.htm` file to ensure the docs landing page exists at the site root.
Signed-off-by: flynnduism <dev@ronan.design>
=> docs: landing page

pkg/configurator/client.go, pkg/configurator/client_test.go, pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/configurator/mock_client.go, pkg/configurator/types.go, pkg/injector/init_container.go, pkg/injector/init_container_test.go, pkg/injector/iptables.go, pkg/injector/patch.go, pkg/injector/patch_test.go
Adds capability in `injector` to configure global outbound
IP range exclusion list via the osm-config ConfigMap. This
is required in managed environments where certain outbound
traffic (ex. access to node's metadata service, retrieve
AAD access tokens for pods in AKS etc.) needs to bypass the
proxy.
It also updates iptables rules generation for better readability.
A subsequent change will expose configuring this option via
osm cli, document this option, and add validation webhook checks
when ready to use.
Part of #2344
- Networking …
=> injector: allow outbound IP range exclusions

docs/content/docs/design/service_app_protocol.md, go.mod, pkg/catalog/service.go, pkg/endpoint/providers/kube/client.go, pkg/endpoint/providers/kube/client_test.go, pkg/endpoint/providers/kube/fake.go, pkg/kubernetes/util.go, tests/framework/common_apps.go
Currently the application protocol for a port (http, tcp etc.)
is determined by specifying the `appProtocol` field on the service's
port spec. The app protocol is required to correctly configure protocol
specific filtering and routing. Since the appProtocol field is only
enabled by default in kubernetes version >= 1.19, clusters using an
older version cannot leverage features such as TCP, gRPC etc.
This change provides a workaround by allowing to specify the app
protocol for a service port by prefixing the protocol name in the
port. The e2e test suite has been updated to be backward compatible
with older k8s API versions by leveraging named service ports in
k8s < 1.19.
- …
=> Allow named service ports to specify application protocol

docs/content/docs/design/service_app_protocol.md, pkg/catalog/service_test.go, pkg/endpoint/providers/kube/client_test.go
Adds tests to verify that the port's `appProtocol` field takes
precedence over the `name` field if both are specified.
`No`
=> test: verify service port's appProtocol precedence over name

charts/osm/README.md, charts/osm/values.yaml
Updates to using the autogenerated README from `make chart-readme`
and removes trailing whitespace in `values.yaml`.
`No`
=> charts/osm: update README and remove trailing whitespace

charts/osm/README.md, charts/osm/templates/osm-configmap.yaml, charts/osm/values.yaml, docs/content/docs/osm_config_map.md
osm-config configMap allows specifying the outbound IP
ranges to exclude from sidecar interception. Allow
users to set this at install time.
This can be set via the Helm chart directly or by
using the `--set` option with the osm install command.
```
osm install \
--set="OpenServiceMesh.outboundIPRangeExclusionList={1.1.1.1/32,2.2.2.2/24}"
```
Part of #2344
- …
=> charts/osm: make IP range exclusion configurable

pkg/envoy/ads/profile.go, pkg/injector/patch.go, pkg/metricsstore/metricsstore.go
They are causing serious memory outages on Prometheus at a larger number
of pods. Storing is linear (0.5Mb/pod), but once the metrics are queried,
Prometheus spikes in memory footprint really hard on these.
Disabling for the time being, we will reintroduce them with config switches
for 0.8, for setups that either can or want to handle the extra resource consumption: 
https://github.com/openservicemesh/osm/issues/2408
No
=> metricstore: remove high cardinality labels from metrics osm metrics

.github/workflows/main.yml
This change only updates codecov on GitHub "push" events (to the main
branch) so transient PR branch coverage stats aren't stored in codecov.
Resolves #2413 
No
=> fix(ci): skip codecov update on PRs

.github/workflows/main.yml, scripts/test-w-coverage.sh
Enables codecov on pull actions till we have a way to generate
more meaningful coverage reports on a per PR basis. Currently
the diff does not show up correctly on the codecov dashboard.
Also ignores demo/test related files from coverage reporting.
Additionally, experimental autogenerated Go code is ignored.
- Other …
=> codecov: enable on pull action and ignore demo/test code

charts/osm/grafana/dashboards/osm-mesh-envoy-details.json
- Updates namespace, service and pod counts on mesh to rely on
new osm-controller metrics (alleviates pressure on computing other
more complex queries on prometheus)
- Adds Certificate issue timings
- Adds success/failed injector webhook counts
- Adds success/failed ADS update counts
- Latest prometheus has fixed idelta behavior, which better represents
delta between points now.
Example below.
No
=> Update mesh-details dashboard

charts/osm/README.md, charts/osm/values.yaml
Jaeger was turned off by default but tracing was left on, which
causes envoys to report connection errors to the Jaeger cluster.
Turning it as off, to follow Jaeger's current defaults.
No
=> Turn off tracing by default

charts/osm/templates/osm-configmap.yaml, docs/content/docs/osm_config_map.md, pkg/configurator/validating_webhook.go
The ConfigMap keys related to tracing are optional and not
required. Update the validating webhook to not expect them
by default.
This fixes the CI breakage introduced from ea1d39ad.
- Does this change contain code from or inspired by another project? If …
=> configurator: remove optional tracing config keys from required list

tests/e2e/e2e_helm_install_test.go
After ea1d39ad and dcfe26eb, tracing defaults to false and
the tracing config is only set when tracing is enabled.
This change updates the Helm install test to reflect this. …
=> tests/e2e: fix default expectations in Helm install test

tests/e2e/e2e_ip_exclusion_test.go
Adds an e2e test to verify the IP range exclusion
feature. Iptable exclusion rules are programmed
so that a client can reach a server without
sidecar proxy redirection.
Part of #2344
- Does this change contain code from or inspired by another project? If …
=> tests/e2e: Add a test to verify IP range exclusion

.github/workflows/release.yml
This change modifies the release CI workflow to automatically tag alpha,
beta, and RC GitHub releases as pre-releases.
No
=> feat(ci): mark alpha, beta, and rc releases as pre-releases

scripts/release-notes.sh
Now that we're adding merge commits, the generated changelog includes lots of "Merged pull request..." messages which are just noise. This change adds `--no-merges` to the `git log` command used in the release notes script to automatically filter those messages out.
I already edited v0.7.0-rc.1 to remove the merge commit messages from the changelog. …
=> fix(release): remove merge commit lines from generated changelog

.github/workflows/release-chart.yml, docs/content/docs/release_guide.md
This change adds details about how to cut a patch release to the release
guide. It also consolidates the instructions for cutting CLI/image
releases and chart releases, since those will be done in sync and it
simplifies the steps.
Fixes #2058 …
=> docs(release): add patch release instructions

pkg/catalog/routes.go, pkg/catalog/routes_test.go
This PR removes references to GetServicesForServiceAccounts as it no longer used
Fixes #2038 
=> ref(pkg/catalog/*): Remove reference to GetServicesForServiceAccounts

DESIGN.md, pkg/catalog/ingress.go, pkg/catalog/ingress_test.go, pkg/catalog/mock_catalog.go, pkg/catalog/routes.go, pkg/catalog/types.go, pkg/envoy/lds/response.go, pkg/envoy/rds/ingress.go, pkg/envoy/rds/new_response.go, pkg/envoy/rds/new_response_test.go, pkg/trafficpolicy/trafficpolicy.go, pkg/trafficpolicy/trafficpolicy_test.go
This change enables use of ingress resources in osm for the routes v2 and fixes #2367 
Unit tests have also been added as a part of this PR to test that the ingress resources and inbound routes are being built correctly for different scenarios. 
This change has been tested with an Nginx Ingress Controller based on the documentation provided here : https://github.com/openservicemesh/osm/blob/main/docs/content/docs/patterns/ingress.md#using-nginx-ingress-controller
When an ingress resource with the host specified the envoy config is as follows : 
Ingress resource :  (https://github.com/openservicemesh/osm/blob/main/demo/ingress/deploy-ingress-nginx-with-host.sh) 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: bookstore-v1
namespace: bookstore
annotations: …
```
=> feat(ingress): Add support for ingress resources in routes v2

DESIGN.md, pkg/catalog/mock_catalog.go, pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/catalog/types.go
Removing references to methods `GetHostnamesForUpstreamService` which is not being used. Also added TODO's to remove `GetResolvableHostnamesForUpstreamService` once we cut over to routes v2.
Fixes  #2048 
- Other                  [X} …
=> ref(pkg/catalog/*) : Remove references to GetHostnamesForUpstreamService

tests/e2e/README.md
Provided additional information in the e2e readme as to how users can use the ginkgo.focus and test.timeout flags. 
No
=> Update e2e readme

cmd/cli/trafficpolicy_check.go
Previously the user would not know why the permissive mode setting could not be checked since the Kubernetes error was not returned. …
=> fix(cli): Return config map errors to user when using osm policy command

docs/example/manifests/apps/bookstore.yaml
This PR removes the label version: v1 from the bookstore deployment. It is not necessary at the moment and may cause confusion.
=> ref(docs): rm unnecessary label from bookstore manifest

cmd/osm-controller/osm-controller.go, pkg/constants/constants.go
`OSMServicePort` is ambiguous because osm-controller exposes
multiple ports for the `osm-controller` service: ADS server,
webhook, debug server etc. …
=> constants: rename HTTP server port constant for clarity

charts/osm/values.yaml
(Tentative)
256 falls a bit short in memory to support up to 200 pods.
Updating max limits 512, to at least be able to support acknowledge
current limits with current defaults, without having K8s prune it due
to OOM.
No
=> Update memory limits for OSM

pkg/envoy/ads/debugger.go, pkg/envoy/ads/profile.go, pkg/envoy/ads/response.go, pkg/envoy/ads/response_test.go, pkg/envoy/ads/server.go, pkg/envoy/ads/types.go
There is a race when multiple envoys are connecting at the same time, where
multiple writes can happen on the xdslog map.
Although rare, it's easy to hit with a beefier setup with more pods, or specially
when OSM restarts (since all pods will attempt to connect mostly at the same time).
- For now this is gated with a simple mutex. If this introduces unwanted penalties
we could discuss dropping all this in-memory logging and have regular logging do
the job instead.
- Also limited the number of logs we can store at a time per proxy (before
had no upper limit)
- A copy of the map is now handed to debugger, to avoid read/write concurrent
accesses on the map.
Fixes #2441 …
=> xdslogs, fix race when multiple verticals write in xdslog map

cmd/osm-controller/certificates_test.go, cmd/osm-controller/osm-controller.go, cmd/osm-controller/validate.go, cmd/osm-controller/validate_test.go
The value for a flag can only be used after `flags.Parse()`
is invoked. Since the cert provider kind is an enum and
can't be set directly via the call to `flags.Parse()`, parse
the provider kind as a string and set it to `providers.Kind`
only when necessary. …
=> cmd/osm-controller: fix bug in flag parsing

tests/e2e/e2e_certmanager_test.go
There is an ongoing issue with cert-manager.io e2e possibly
timing related, that causes the cert-manager install to fail.
More details can be found in issue #2475.
This change disables the test from running in the CI till
the issue has been addressed. Local runs of the automated
demo work `CERT_MANAGER=cert-manager ./demo/run-osm-demo.sh`,
although there is a potential timing issue in the existing
demo script as well. …
=> tests/e2e: disable cert-manager.io e2e test

pkg/debugger/proxy.go
This change is a temporary workaround till issue #2481 is
addressed. As a part of #1939, `injector` will be taken
out of `osm-controller`, after which we will no longer
get the list of expected proxies. …
=> debugger: disable printing expected proxy list

pkg/injector/envoy_config_test.go, pkg/injector/envoy_container.go, pkg/injector/patch.go
This change refactors `getEnvoySidecarContainerSpec` to accept the pod
object as an argument so its other fields do not have to be passed as
additional arguments explicitly. In particular, the pod's owner
references will be read to keep track of which workload it is a part of,
which is needed to implement SMI metrics.
---
* (YOU ARE HERE) **ref(injector): pass pod object to getEnvoySidecarContainerSpec**
* feat(metrics): add WASM metrics source
* docs(metrics): Add docs for WASM stats
* feat(metrics): Add WASM feature flag
* feat(metrics): Add stats.wasm to workload pods
* feat(injector): …
=> ref(injector): pass pod object to getEnvoySidecarContainerSpec

DESIGN.md, charts/osm/templates/osm-rbac.yaml, pkg/announcements/types.go, pkg/catalog/dispatcher.go, pkg/catalog/fake.go, pkg/catalog/mock_catalog.go, pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/catalog/types.go, pkg/envoy/rds/new_response.go, pkg/envoy/rds/new_response_test.go, pkg/envoy/rds/response.go, pkg/kubernetes/client.go, pkg/kubernetes/client_test.go, pkg/kubernetes/mock_controller.go, pkg/kubernetes/types.go, pkg/tests/fixtures.go, pkg/utils/serviceaccount.go, pkg/utils/serviceaccount_test.go
This change supports permissive mode in routes v2. 
For allow all/permissive mode inbound and outbound policies for a given proxy  are built based on service discovery. Unit tests have been added to validate various scenarios. 
For a demo setup with bookbuyer, bookstore-v1, bookstore-v2 and bookthief in permissive mode the route configurations are as follows : 
1. Route configuration for bookbuyer : 
```
"dynamic_route_configs": [
{
"version_info": "7",
"route_config": {
"@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration",
"name": "RDS_Outbound",
"virtual_hosts": [
{
"name": "outbound_virtualHost|bookstore-v1-bookstore",
"domains": [
"bookstore-v1.bookstore",
"bookstore-v1.bookstore.svc",
"bookstore-v1.bookstore.svc.cluster", …
```
=> feat(permissive-mode): Add support for permissive mode in routes v2

pkg/catalog/ingress.go, pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/envoy/rds/new_response_test.go, pkg/envoy/route/config.go, pkg/envoy/route/route_config_test.go, tests/scenarios/traffic_split_with_apex_service_test.go
The virtual_host naming is changed to the following syntax: `inbound-virtual-host|<svc-name>.<namespace>`
=> chore(pkg/*): Improve virtual host naming syntax

charts/osm/templates/osm-rbac.yaml
Although we do not explicitly use `Watch()` on `serviceaccount`,
the client-go informers use this internally for event
notifications.
Resolves the following error:
```
E0209 20:12:36.556469       1 reflector.go:383] pkg/mod/k8s.io/client-go@v0.18.8/tools/cache/reflector.go:125: Failed to watch *v1.ServiceAccount: unknown (get serviceaccounts)
```
- Performance …
=> charts/osm-rbac: add watch verb for serviceaccounts

pkg/catalog/ingress.go, pkg/catalog/ingress_test.go
Creating a function to build the ingress policy name rather than building it in-line
=> chore(pkg/catalog/*) : Add a function to create ingress policy name

.github/workflows/main.yml, Makefile
Adds a make target to check if the chart readme is up to date, 
and a github action to ensure the readme for the chart is updated 
together with the chart. …
=> Makefile: add target to check chart readme

tests/e2e/e2e_routesv2_permissive_test.go, tests/e2e/e2e_routesv2_pod_client_server_test.go, tests/framework/common.go
This PR adds two e2e tests. The first test is to validate that permissive mode works with routesv2 and the second is to validate traffic target scenario with routes v2. These are temporary tests and will be deprecated once we cut over and make routesv2 the default in osm
Part of #2391  …
=> test(routesv2): add e2e tests for routes v2

pkg/envoy/cds/cluster.go, pkg/envoy/cds/cluster_test.go, pkg/envoy/cds/response.go, pkg/service/types.go
The `getLocalServiceCluster` function was returning an xds cluster with endpoints based on Kubernetes service endpoints when it should have been building local cluster endpoints based on the port specified in the service spec. i.e. 0.0.0.0:<port>
As a result, there were 18 extra, duplicate  entries in the envoy local clusters that were being programmed per Kubernetes service endpoints (or Pod replicas)
This PR fixes the getLocalServiceCluster to return a local cluster with endpoints based on the Kubernetes ports rather than the Kubernetes Service endpoints. The tests in the clusters_test.go have been converted from gingko to use the go testing framework and tests for getLocalServiceCluster has been added.
To see the issue exposed in a test, please pull down this branch …
=> fix(cds): return local cluster endpoints per  port

charts/osm/README.md, charts/osm/values.yaml
Changes the default controller log level from trace
to info. It was set to trace for local development
purpose.
It can be changed as follows:
```
osm install --set="OpenServiceMesh.controllerLogLevel=trace"
```
```
./demo/run-osm-demo.sh --set="OpenServiceMesh.controllerLogLevel=trace"
```
Please answer …
=> charts/osm: change default controller log level to info

tests/framework/common.go
This change adds additional log statements to the
`WaitForPodsRunningReady()` helper when the check times out that print
the pod names and statuses.
No
=> feat(e2e): print pod statuses when ready/running check times out

docs/content/docs/development_guide.md, docs/content/docs/patterns/observability/metrics.md, docs/developer/wasm.md
This change adds documentation regarding the WASM-based Envoy extension
used to implement SMI metrics. User-facing docs have been added with
what metrics are generated and known gaps. Developer documentation
includes how to build the extension and a high-level description of how
it works.
---
3. (YOU ARE HERE) **docs(metrics): Add docs for WASM stats**
4. feat(metrics): Add WASM feature flag
5. feat(metrics): Add stats.wasm to workload pods
6. feat(injector): …
=> docs(metrics): Add docs for WASM stats

docs/README.md
This PR adds notes to the `docs/Readme.md` regarding:
* best practices for creating links, in both Github and the Hugo website (as per #2453)  
* includes the v0.7 [release docs](https://release-v0-7--osm-docs.netlify.app/) as an example in the versioning section
* includes the installation of npm packages in steps to run site locally
--- …
=> docs: update website readme

pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/tests/fixtures.go
* Adds function for building outbound traffic split policies
* Part of #2400 
-->
=> feat(pkg/catalog): build outbound traffic split policies

pkg/envoy/eds/response.go, pkg/envoy/eds/response_test.go
This PR removes the dependency on services from EDS and updates the tests. Further it converts the test from ginkgo to use go testing framework
Part of #1658  …
=> ref(pkg/envoy/eds/*): Remove redundant code from EDS and update test

README.md
When looking at https://github.com/openservicemesh/osm/pull/2492 I realized we have had a number of subtle errors and broken links creep into the README. I've corrected them in this PR. (Note: the license changed months ago, but we just didn't say so in the README, just in the license file.)
=> Correcting typos and errors

pkg/catalog/helpers_test.go, pkg/catalog/routes_test.go, pkg/endpoint/providers/kube/fake.go, pkg/envoy/eds/response_test.go, pkg/smi/fake.go, pkg/tests/fixtures.go
This PR updates the the test fixtures so that bookstore-v1 and bookstor-v2 belong to different service accounts. Corresponding tests have also been updated
Signed-off-by: Sneha Chhabria <snchh@microsoft.com> 
Part of #1658  …
=> test(*): Update test fixtures to have multiple traffic targets

pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/catalog/traffictarget.go, pkg/catalog/traffictarget_test.go
While building traffic policies for HTTP routes, if
the code encounters TCP route policies it logs an
error that the Kind for the rule is invalid. This
is misleading because the Kind is valid but just
simply be ignored while building HTTP traffic policies.
This change removes this misleading log and adds
extra validations for the TrafficTarget object before
it is consumed for policy building.
Also extends the helper to check for a valid
traffic target to examine the rules kind.
- Metrics                [ …
=> catalog: fix misleading error log

experimental/routes_refactor/demo/scripts/port-forward-bookbuyer-envoy.sh, experimental/routes_refactor/demo/scripts/port-forward-bookbuyer-ui.sh, experimental/routes_refactor/demo/scripts/port-forward-bookstore-ui-v1.sh, experimental/routes_refactor/demo/scripts/port-forward-bookstore-ui-v2.sh, experimental/routes_refactor/demo/scripts/port-forward-bookstore-v1-envoy.sh, experimental/routes_refactor/demo/scripts/port-forward-bookstore-v2-envoy.sh, experimental/routes_refactor/demo/scripts/port-forward-bookthief-envoy.sh, experimental/routes_refactor/demo/scripts/port-forward-bookthief-ui.sh, scripts/port-forward-bookbuyer-ui.sh, scripts/port-forward-bookbuyer.sh, scripts/port-forward-bookstore-ui-v1.sh, scripts/port-forward-bookstore-ui-v2.sh, scripts/port-forward-bookstore-ui.sh, scripts/port-forward-bookstore.sh, scripts/port-forward-bookthief-ui.sh, scripts/port-forward-bookthief.sh, scripts/port-forward-grafana.sh, scripts/port-forward-jaeger.sh, scripts/port-forward-osm-debug.sh, scripts/port-forward-osm-metrics.sh, scripts/port-forward-prometheus.sh
This PR updates the kubectl get pod lines in our port forward scripts to handle scenarios where there are multiple replicas of the application pods running. It specifically adds `NR==1` which is an awk command that stands for number of lines returned. The lines in the scripts now return the first pod matching the conditions specified. …
=> ref(*): update scripts to handle multiple replicas

pkg/envoy/cds/cluster.go, pkg/envoy/cds/cluster_test.go
`connect_timeout` is mandatory for a cluster. Resolves
the error reported by Envoy when a synthetic cluster
is programmed.
```
{"level":"error","component":"envoy/ads","time":"2021-02-16T19:54:57Z","file":"stream.go:82","message":"[NACK] DiscoveryRequest error from Envoy with xDS Certificate SerialNumber=79974573966902936937525501793231715299 on Pod with UID=5871a4f2-69e2-4b52-9480-43e098480a98: code:13 message:\"Error adding/updating cluster(s) client-two/client-two.client-two.osm.synthetic-084dcde9-9d6a-4511-8a77-cd7bb5b8c3ae-local: Field 'connect_timeout' is missing in: name: \\\"client-two/client-two.client-two.osm.synthetic-084dcde9-9d6a-4511-8a77-cd7bb5b8c3ae-local\\\"\\ntype: STATIC\\n\" "}
```
- …
=> envoy/cds: set mandatory connect_timeout on synthetic cluster

tests/e2e/e2e_http_ingress_test.go, tests/framework/common.go
This change adds a new e2e test that verifies services outside the
cluster where OSM is running can make requests to services in a mesh in
the cluster. It performs the following steps:
1. Install OSM with the default settings
2. Create a simple HTTP service (with proxy sidecar)
3. Install the nginx ingress controller
4. Checks that an external service receives HTTP 404 when trying to
connect to the service in the mesh
5. Creates an Ingress resource mapping to the service in the mesh
6. Checks that an external service successfully reaches the service in
the mesh
Resolves #2327
- …
=> tests(e2e): Add HTTP ingress test

.gitignore, Makefile, pkg/envoy/lds/connection_manager.go, pkg/envoy/lds/listener_test.go, pkg/envoy/lds/wasm.go
This change propagates the stats.wasm module to each sidecar proxy's
config. stats.wasm is built and embedded in the osm-controller binary
and configured inline via LDS.
Follow-up from #2531
---
5. (YOU ARE HERE) **feat(metrics): Add stats.wasm to proxy config**
6. feat(injector): Add name, workload name, workload kind to PodMetadata
7. feat(metrics): Add …
=> feat(metrics): Add stats.wasm to proxy config

cmd/osm-injector/osm-injector.go, pkg/kubernetes/client.go
osm-injector only requires the namespace informer
provided by `kubernetes.Controller`. This change
adds support to do so. …
=> osm-injector: only initialize namespace informer

pkg/injector/envoy_config_health_probes_test.go, pkg/injector/test/test_helpers.go, tests/envoy_xds_expectations/actual_output_getProbeCluster.yaml, tests/envoy_xds_expectations/expected_output_getAccessLog.yaml, tests/envoy_xds_expectations/expected_output_getLivenessCluster.yaml, tests/envoy_xds_expectations/expected_output_getLivenessListener.yaml, tests/envoy_xds_expectations/expected_output_getProbeCluster.yaml, tests/envoy_xds_expectations/expected_output_getProbeListener.yaml, tests/envoy_xds_expectations/expected_output_getReadinessCluster.yaml, tests/envoy_xds_expectations/expected_output_getReadinessListener.yaml, tests/envoy_xds_expectations/expected_output_getStartupCluster.yaml, tests/envoy_xds_expectations/expected_output_getStartupListener.yaml, tests/envoy_xds_expectations/expected_output_getVirtualHosts.yaml
This PR is a subset of https://github.com/openservicemesh/osm/pull/2269.
---
This PR adds unit tests for the Pod payload rewrite functions added with https://github.com/openservicemesh/osm/pull/2233
The functions tested here mostly generate Envoy YAML config.  For that reason - I added a helper function to marshal the structs and compare them with expectations saved in YAML files in this repo.
I believe having the expected YAML in a file makes it 
a) easy to load and compare the output of the functions (vs in code) and 
b) documents the Envoy config we'd ship to enable health probes through Envoy
This PR is stacked on https://github.com/openservicemesh/osm/pull/2233 (it contains the changes from https://github.com/openservicemesh/osm/pull/2233)
=> injector: Test payload health probes

pkg/envoy/proxy.go, pkg/envoy/xdsutil.go, pkg/envoy/xdsutil_test.go, pkg/injector/envoy_config_test.go, pkg/injector/envoy_container.go
This change adds the pod name and controlling workload name and kind to
the `PodMetadata` tracked with each proxy. These fields are needed to
implement SMI metrics.
---
5. (#2546) ~~feat(metrics): Add stats.wasm to proxy config~~
6. (YOU ARE HERE) **feat(injector): Add name, workload name, workload kind to PodMetadata**
7. feat(metrics): Add source labels …
=> feat(injector): Add name, workload name, workload kind to PodMetadata

pkg/injector/health_probes_test.go
This PR adds unit tests for the functions in `pkg/injector/health_probes.go`
- `rewriteHealthProbes`
- `rewriteLiveness`
- `rewriteReadiness`
- `rewriteStartup`
- `rewriteProbe`
- `getPort`
=> injector: Test health probe functions

pkg/injector/envoy_config_test.go, pkg/injector/test_fixtures/.gitignore, pkg/injector/test_fixtures/README.md, pkg/injector/test_fixtures/expected_envoy_bootstrap_config.yaml, pkg/injector/test_fixtures/expected_xds_cluster_with_probes.yaml, pkg/injector/test_fixtures/expected_xds_cluster_without_probes.yaml, pkg/injector/test_fixtures/expected_xds_static_resources_with_probes.yaml
This PR adds unit tests for the Pod payload rewrite functions added with https://github.com/openservicemesh/osm/pull/2233
The functions tested here mostly generate Envoy YAML config.  For that reason - I added a helper function to marshal the structs and compare them with expectations saved in YAML files in this repo.
I believe having the expected YAML in a file makes it 
a) easy to load and compare the output of the functions (vs in code) and 
b) documents the Envoy config we'd ship to enable health probes through Envoy
This PR is stacked on https://github.com/openservicemesh/osm/pull/2233 (it contains the changes from https://github.com/openservicemesh/osm/pull/2233)
---
- Control …
=> injector: Test all Envoy config functions

pkg/kubernetes/client.go, pkg/kubernetes/types.go, pkg/smi/client.go, pkg/smi/types.go
Makes a few exported types and variables that are
package scoped to be scoped within the package.
`No`
=> pkg/smi,kubernetes: unexport package scoped types

pkg/envoy/lds/connection_manager.go, pkg/envoy/lds/ingress.go, pkg/envoy/lds/inmesh.go, pkg/envoy/lds/inmesh_test.go, pkg/envoy/lds/listener_test.go, pkg/envoy/lds/response.go, pkg/envoy/lds/types.go, pkg/envoy/lds/wasm.go, pkg/envoy/proxy.go, pkg/envoy/proxy_test.go
This change adds a simple Lua HTTP filter to add the necessary source metadata
for SMI metrics to each request's headers which are read in the WASM
extension and used to tag the generated metrics.
---
5. (#2546) ~~feat(metrics): Add stats.wasm to proxy config~~
6. (#2554) ~~feat(injector): Add name, workload name, workload kind to PodMetadata~~
7. (YOU …
=> feat(metrics): Add source labels to WASM metrics

.github/workflows/automerge.yml
Github actions is not able to read private key secret, so then automerge workflow is not able to generate token.
Error:
`parse error: Expected value before ',' at line 1, column 9
unable to load key file
140318512952448:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: ANY PRIVATE KEY`
- Other                  [ X] …
=> fix(.github/workflows): specify shell and pem extension for automerge bug

.github/workflows/automerge.yml
Two access token URLs are available, but need just one for the automerge feature
- Other                  [ X]
=> fix(.github/workflows) Grab the first access token URL

.github/workflows/automerge.yml
Added double quotes because not interpolating ID because ENV variable is not wrapped in double quotes.
=> fix(.github/workflows): Wrap env variables in double quotes when using in JSON

pkg/catalog/xds_certificates.go, pkg/endpoint/providers/kube/client.go, pkg/endpoint/providers/kube/client_test.go, pkg/kubernetes/client.go, pkg/kubernetes/client_test.go
This PR fixes a bug in how service selectors are matched against pod
labels. If there were no selectors for a service it was considered as a
match. With the changes in this PR services without selectors are not
considered for a match.
*Note*: This will break the current implementation of routes v2 (a feature under test), but I will tackle this  with issue #2545 
Fixes #2578
- CI System …
=> fix(pkg/*): Fix service selector match logic

pkg/envoy/rds/new_response.go, pkg/envoy/rds/response.go, pkg/envoy/route/config.go, pkg/envoy/route/config_test.go, pkg/envoy/route/route_config.go, pkg/envoy/route/route_config_test.go
This change configures RDS to add the destination metadata necessary for
SMI metrics to each response's headers. The headers are then read by the
WASM extension and used to tag the generated statistics. This change has
been integrated with both routes v2 and the existing routes
implementation.
---
5. (#2546) ~~feat(metrics): Add stats.wasm to proxy …
=> feat(metrics): Add dest labels to WASM metrics

pkg/identity/kubernetes_test.go
Increasing test coverage of `./pkg/identity`
```
$ go test -cover ./pkg/identity/...
ok      github.com/openservicemesh/osm/pkg/identity     (cached)        coverage: 100.0% of statements
```
=> pkg/identity: Increase test coverage

charts/osm/templates/osm-rbac.yaml, demo/ingress/deploy-ingress-agic.sh, demo/ingress/deploy-ingress-nginx-with-host.sh, demo/ingress/deploy-ingress-nginx.sh, docs/content/docs/patterns/ingress.md, pkg/catalog/fake.go, pkg/catalog/helpers_test.go, pkg/catalog/ingress_test.go, pkg/envoy/rds/response_test.go, pkg/ingress/client.go, pkg/ingress/mock_client_generated.go, pkg/ingress/types.go, tests/e2e/e2e_http_ingress_test.go
Updates the API group for the ingress resource to
`networking.k8s.io`, which has been available since
k8s 1.14. The `extensions` API group will be
deprecated in k8s v1.22. Newer versions of some
ingress controllers also warn about using a much
older api version, which makes issues harder to
debug.
Also updates the docs, and tests that were incorrectly
using older mock versions.
- CI System …
=> ingress: update api group to networking.k8s.io

docs/config.toml
Show correct release version no on docs site. Closes #2549.
---
> Documentation          [x]
> No
=> docs: update version menu to show the correct release number

cmd/cli/mesh_list.go, cmd/cli/mesh_list_test.go
Updates the mesh list command to display
the controller pods and joined namespaces.
`No`
=> cmd/cli: update mesh list command

pkg/catalog/mock_catalog_generated.go, pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/catalog/types.go, pkg/envoy/rds/new_response.go, pkg/envoy/rds/new_response_test.go
This PR refactors routes v2 to build inbound routes based on the proxy's
services rather than its service account. This is necessary so that only
routes and clusters for the proxy's service are only programmed.
To make this change the routes v2 api that build both inbound and
outbound routes together is split into two separate api's.
Fixes #2591
- Performance …
=> ref(routesv2): Build inbound routes in routes v2 using proxy service

tests/e2e/e2e_pod_client_server_test.go
Adding a comment and a variable to provide clarity for the casual code reader who may be interested in this test.
ref https://github.com/openservicemesh/osm/pull/1570
=> e2e: Add comments to no-service pod test

pkg/envoy/lds/connection_manager.go, pkg/envoy/lds/listener_test.go
Because `destination_*` tags are generated at the request's destination,
requests that invoke a local response from Envoy have no `destination_*`
values. This change modifies Envoy to add the expected header keys with
the value "unknown" to stay consistent with the behavior for requests
that don't invoke a local reply.
---
5. (#2546) ~~feat(metrics): Add …
=> feat(metrics): Add "unknown" for dest labels on local replies

cmd/osm-controller/osm-controller.go, cmd/osm-injector/osm-injector.go, pkg/injector/patch.go, pkg/metricsstore/metricsstore.go, pkg/metricsstore/metricsstore_test.go
Initialization still happens for unrelated metrics to the componenets,
but this will at least prevent exposing unrelated metrics when scraping.
Additionally:
- `XdsCertCount/Times` have have had the `Xds` prefix stripped to be more generic for both Injector and OSM.
No
=> metrics: set dynamic metric registration

DESIGN.md, pkg/catalog/ingress.go, pkg/catalog/ingress_test.go, pkg/catalog/mock_catalog_generated.go, pkg/catalog/types.go, pkg/envoy/rds/new_response.go, pkg/envoy/rds/new_response_test.go, pkg/envoy/route/rbac.go, pkg/envoy/route/rbac_test.go, pkg/service/types.go
Since ingress policies are not based on service accounts, traffic
policy routes derived from ingress rules should not enforce RBAC
policies based on the downstream's service account.
This change adds support to wildcard the allowed service accounts
for an ingress route so that the corresponding RBAC policy
can create a rule that allows any downstream principal.
This is required for ingress to work with routesV2 and RBAC
per route policies.
- …
=> ingress/rbac: allow any downstream principal to access the service

README.md, docs/content/docs/design_concepts/osm_components_interactions.md
After the site navigation updates in https://github.com/openservicemesh/osm/pull/2597 we will need to fix some links from the README and one image on the docs site.
=> Adjusting links for new site structure

charts/osm/templates/prometheus-configmap.yaml
The proxy-wasm SDK doesn't directly tag the metrics it generates.
Instead, it encodes the tags in the metric name. This change modifies
the Prometheus config to modify the metrics and move the encoded tags to
actual Prometheus tags.
One limitation to note is that because Prometheus doesn't allow '-' or
'.' in metric names, proxy-wasm converts all instances of either to '_'.
This means a metric on a pod named 'abc-123' will have a pod name tag of
'abc_123' and will collide with the metrics on a pod named 'abc.123'.
This limitation has been documented in docs/content/docs/patterns/wasm.md.
For example,
envoy_response_code_200_source_namespace_bookbuyer_source_kind_Deployment_source_name_bookbuyer_source_pod_bookbuyer_74ff55c5b_kcb8q_destination_namespace_bookstore_destinatio …
=> feat(metrics): clean up WASM metrics in Prometheus config

Makefile, cmd/osm-controller/osm-controller.go, demo/README.md
This PR adds the `check-go-version` Makefile target, which ensures that the version of Go used to build OSM meets some minimal requirement. The requirement is hard-coded in the Makefile as well.
Fixes https://github.com/openservicemesh/osm/issues/2363
Example:
```bash
$ make build
You are building OSM with Go version 1.15.2. OSM requires Go version 1.15.7 or higher!
Makefile:40: recipe for target 'check-go-version' failed
make: *** [check-go-version] Error 1
```
=> Require Go version 1.15.7

pkg/catalog/mock_catalog_generated.go, pkg/catalog/routes.go, pkg/catalog/routes_test.go, pkg/catalog/types.go, pkg/envoy/rds/response.go, pkg/envoy/rds/response_test.go
The PR gets rid of the `ListPoliciesForPermissiveMode` API and includes
the permissive mode logic within the `ListInboundTrafficPolicies` and `ListOutboundTrafficPolicies`
API's respectively.
Unit tests have also been updated as a part of this PR.
Fixes #2598 …
=> ref(pkg/catalog) : Use the same catalog APIs to build inbound and outbound traffic policies for SMI and permissive mode

Makefile
Fixes the check for the minor version to take into
account minor versions greater than the minimum
required minor version, and to set a value of
0 for versions that are not patches. The previous
checks were failing to detect version 1.16 correctly.
Also simplifies the command used to retrieve the version
info.
- Other …
=> Makefile: fix go version check

charts/osm/grafana/dashboards/osm-mesh-envoy-details.json
- support for multi osm-controller instances with global variable
- support for multi osm-injector instances with global variable
- support individual setting of xDS path information with global variable
- fixed some recently renamed certificate metrics
- parametrized all mesh-details dashboard to use vars
- some shortened names have been expanded to full pod names for better
visibility now that we can have multiple ones.
No
=> grafana-dashboard update

pkg/catalog/routes_test.go, pkg/tests/fixtures.go, tests/scenarios/traffic_split_with_zero_weight_test.go
A unit test has been added in tests/scenarios to validate a service
having zero weight in traffic split
Fixes #2424 
=> test(trafficSplit): Add a test for service with zero weight in traffic split

tests/e2e/e2e_metrics_test.go
This change adds an e2e test for the WASM metrics Envoy extension. It
creates a client and server, waits for the client to make 5 successful
requests to the server, then queries Prometheus to ensure those 5
successful requests were recorded correctly.
---
5. (#2546) ~~feat(metrics): Add stats.wasm to proxy config~~
6. (#2554) ~~feat(injector): Add name, …
=> tests(e2e): add WASM metrics test

pkg/configurator/client.go
This Error should be a Warning. It is acceptable for the OSM ConfigMap to not exist - we have default values.
Message: 
```
6:04PM ERR ConfigMap osm-system/osm-config does not exist in cache component=configurator file=client.go:257
```
=> pkg/configurator: Demote Error to a Warning; Clarification

pkg/envoy/rds/response_test.go
This PR updated the TestNewResponse test to now test for the outbound
policies as well.
This test previously validated only inbound and ingress policies. …
=> test(pkg/envoy/rds/response_test.go): Update RDS response test to validate inbound and outbound policies

pkg/envoy/sds/response_test.go
Moving anonymous structs out into their own type - `testCase`.
=> sds: Carve out new testCase struct type

tests/e2e/e2e_multiple_services_per_pod_test.go
Adds a test for the scenario where multiple services have
the same label selector that matches the same pod.
This is possible with routesV2 after commit ff5f421b
added support to program multiple services per proxy.
Part of #2610 and #2134.
- Does this …
=> tests/e2e: add test for multiple services matching same pod

pkg/envoy/sds/response.go, pkg/envoy/sds/response_test.go, pkg/envoy/sds/types.go
This PR cleans up SDS:
- removes  `proxyServices` from the `sdsImpl` struct
- removes the use of `GetServicesFromEnvoyCertificate()`, which is no longer needed.
=> sds: Remove unused services list from SDS struct

pkg/envoy/sds/response.go, pkg/envoy/sds/response_test.go, pkg/envoy/sds/types.go
Increasing unit test coverage for `sds.NewResponse()`
Also in this PR:
- merged `newSDSImpl()` back into `NewResponse()` -- makes the code a bit simpler
- Removed `proxy` and `proxySvc` from the `sdsImpl ` struct (we don't need `proxySvc` at all any more)
- Exported all `pkg/catalog` errors (this PR only needs `ErrInvalidCertificateCN` to be accessible outside the `catalog` package)
=> sds: Adding more unit tests

docs/README.md, docs/content/docs/patterns/observability/_index.md, docs/content/docs/patterns/observability/tracing.md, docs/content/docs/tasks_usage/logs.md, docs/content/docs/tasks_usage/metrics.md
It seems that aliases are the correct way to achieve links that work on both github and the website. This PR will serve as a test for the website build (to see if this is correct).
=> fix links to work on both github and the website

pkg/envoy/ads/stream.go, pkg/envoy/proxy.go
This PR removes the unused `announcements` channel from the `Proxy{}` struct
=> pkg/envoy: Remove announcement channel from Proxy{}

pkg/service/types.go, pkg/service/types_test.go
This PR is a tiny simplification to the `String()` method of the `service.K8sServiceAccount` struct & adds a test for it.
=> service: Simplify stringer method for K8sServiceAccount

pkg/envoy/proxy.go, pkg/envoy/proxy_test.go
This PR adds test for the methods of `Proxy{}` struct in `pkg/envoy`.
=> envoy: Test Proxy{} methods

pkg/envoy/route/route_config.go, pkg/tests/fixtures.go, pkg/trafficpolicy/types.go
Removal of unused structs from the `trafficpolicy` package post migration
to routesv2. No functional changes
Fixes #2397 …
=> chore(routesv2): Remove unused struct from `trafficpolicy` package

cmd/osm-injector/osm-injector.go, cmd/osm-injector/reconcile.go, pkg/constants/constants.go, pkg/injector/webhook.go, pkg/reconciler/reconciler.go, tests/scenarios/scenario_mutatingwebhook_reconcile_test.go
There was a race when creating webhook certificate, would prevent
multiple injectors to receive webhook calls.
This PR synchronizes the certificate creation for multiple instances
through secrets API.
No
=> Fix race on webhook certificate creation

DESIGN.md, docs/content/docs/design_concepts/design_appendix.md, docs/content/docs/design_concepts/interfaces.md, pkg/catalog/debugger.go, pkg/catalog/debugger_test.go, pkg/catalog/mock_catalog_generated.go, pkg/catalog/types.go, pkg/debugger/mock_debugger_generated.go, pkg/debugger/policy.go, pkg/debugger/policy_test.go, pkg/debugger/types.go, pkg/envoy/lds/inmesh.go, pkg/service/types.go, pkg/smi/client.go, pkg/smi/client_test.go, pkg/smi/fake.go, pkg/smi/mock_meshspec_generated.go, pkg/smi/types.go, pkg/tests/fixtures.go
The `ListTrafficSplitServices` api does not provide any additional
information compared to the `ListTrafficSplits` api. Use a single
api for consistency.
Since `ListTrafficSplits` lists the entire SMI traffic split resource,
this is sufficient enough in the debugger. The traffic split dump
in the debugger was previously duplicating traffic split resources
from two different apis.
- CI …
=> pkg/*: deprecate older API to list traffic splits

tests/e2e/e2e_fluentbit_out_test.go
**Description**: Tests that log output from Fluent Bit is filtered correctly:
* Modify filter for adding osm controller pod name
* Grep filter for log level
Resolves #2159 
no
=> tests(fluent bit): add e2e to test fluent bit for correct output

tests/e2e/e2e_hashivault_test.go, tests/framework/common.go
The HashiCorp Vault e2e test fails occasionally because of the new pod
restart check because the osm-controller sometimes comes up before the
Vault pod is ready, so it fails and restarts and the rest of the test
succeeds. This change waits for the Vault pod to become ready before
installing OSM.
Fixes #2670 …
=> fix(e2e): wait for automatic vault installation

.github/workflows/main.yml, tests/e2e/README.md, tests/e2e/e2e_debug_server_test.go, tests/e2e/e2e_deployment_client_server_test.go, tests/e2e/e2e_egress_test.go, tests/e2e/e2e_fluentbit_test.go, tests/e2e/e2e_hashivault_test.go, tests/e2e/e2e_http_ingress_test.go, tests/e2e/e2e_ip_exclusion_test.go, tests/e2e/e2e_metrics_test.go, tests/e2e/e2e_multiple_services_per_pod_test.go, tests/e2e/e2e_permissive_test.go, tests/e2e/e2e_pod_client_server_test.go, tests/e2e/e2e_smi_traffic_target_test.go, tests/e2e/e2e_tcp_client_server_test.go, tests/e2e/e2e_tcp_egress_test.go, tests/e2e/e2e_trafficsplit_same_sa_test.go, tests/e2e/e2e_trafficsplit_test.go, tests/e2e/e2e_upgrade_test.go
Adds 2 more buckets to parallelize e2e tests and reorganizes
them roughly based on their areas.
`No`
=> tests/e2e: add more buckets and reorganize test bucketing

scripts/get-osm-namespace-logs.sh
Adds a simple script to store at `dirName` all logs for current
and previous instance runs logs found for all pods and all containers
in `$K8S_NAMESPACE`
- Logging              [X]
No
=> Scripts: get-osm-namespace-logs script

tests/e2e/e2e_upgrade_test.go
The upgrade e2e test is currently failing consistently in CI but not
locally for me. I suspect the kind cluster spun up for CI doesn't have
sufficient CPU to handle spinning up the new control plane before
tearing down the old one. This is causing CI to run longer than
necessary while we don't have a fix. Issue #2675 is tracking this. …
=> tests(e2e): disable upgrade test

tests/e2e/e2e_upgrade_test.go
This change reduces the CPU requests for the osm-controller and
osm-injector pods so that the kind cluster in CI can handle standing up
the new control plane before tearing the old one down.
Fixes #2675 …
=> fix(e2e): reduce CPU needed for upgrade test

pkg/envoy/lds/connection_manager.go, pkg/envoy/lds/listener_test.go, pkg/envoy/lds/wasm.go
This change adds a couple of unit tests to improve coverage in functions
related to WASM configuration via LDS. A couple of other small changes
were made to prevent extra configuration from being added when the WASM
extension is not configured.
Fixes #2698 …
=> tests(pkg/envoy/lds): improve unit test coverage

charts/osm/crds/access.yaml, charts/osm/crds/specs.yaml, charts/osm/crds/split.yaml
The SMI CRDs are borrowed from the smi-sdk-go repo
https://github.com/servicemeshinterface/smi-sdk-go
only because those CRDs are not published as charts
which we can mark as a dependency in our project.
The CRDs copied over aren't modified.
- Does this …
=> charts/crds: attribute orginal authors for SMI CRDs

cmd/cli/mesh_upgrade.go, cmd/cli/mesh_upgrade_test.go
This change updates the `osm mesh upgrade` command with two additional
flags mapping to fields recently added to the osm-config ConfigMap:
`--outbound-ip-range-exclusion-list`
`--enable-privileged-init-container`
Fixes #2651 …
=> fix(cli): Add missing flags for upgrade

scripts/get-osm-namespace-logs.sh
This change adds the OSM namespace to each necessary `kubectl` command
in `scripts/get-osm-namespace-logs.sh`. Running the script previously
resulted in empty log files being created because the pods could not be
found without specifying the namespace. …
=> fix(scripts): add namespace to osm logs script

README.md, docs/content/docs/getting_started/_index.md
As OSM became a CNCF project and now is not a Microsoft-owned project, this support language is outdated; in this PR I update it.
=> Clarify support

pkg/metricsstore/metricsstore_test.go
This change restructures the tests in pkg/metricsstore so that the call
to `(*MetricsStore).Stop()` is moved from `TestMain` to an individual
test function to be counted for coverage. No functional changes.
Fixes #2689 …
=> tests(metricsstore): Refactor to improve coverage

tests/e2e/README.md, tests/e2e/e2e_grpc_insecure_origination_test.go, tests/e2e/e2e_grpc_secure_origination_test.go, tests/framework/common_traffic.go
Adds an e2e test for secure (over TLS) gRPC origination
that is routable using TCP routes. Unlike the insecure
gRPC origination test, this test needs to use TCP routes
vs HTTP routes because the requests are encrypted within
the client app, thereby making HTTP based routing void
due to the TCP payload being encrypted.
- Other …
=> tests/e2e: add test for secure gRPC origination

tests/e2e/e2e_controller_restart_test.go, tests/e2e/e2e_grpc_insecure_origination_test.go, tests/e2e/e2e_grpc_secure_origination_test.go, tests/e2e/e2e_ip_exclusion_test.go, tests/e2e/e2e_multiple_services_per_pod_test.go, tests/e2e/e2e_permissive_test.go, tests/e2e/e2e_pod_client_server_test.go, tests/e2e/e2e_tcp_client_server_test.go, tests/e2e/e2e_tcp_egress_test.go
This change removes the extra scoping of the whole
function in tests, which is redundant and doesn't
serve any purpose. 
No functional changes have been made to the tests.
It changes:
```
func() {
{
...
}
}
```
to
```
func() {
...
}
``` …
=> tests/e2e: remove redundant scoping within function

tests/e2e/README.md, tests/e2e/e2e_upgrade_test.go
Moves the upgrade test to bucket 4 from bucket 1, so the
tests times per bucket are more equalized pre-checkin.
Currently bucket 1 takes the longest and bucket 4 the
shortest in the pre-checkin CI. …
=> tests/e2e: move upgrade test to bucket 4 to balance time

tests/framework/common.go
Rule out if debug log level is actually affecting
the already slow gh kind CI environment.
If we observe same failures, this will be instantly rolled back.
No
=> Change e2e log level to info

.env.example, DESIGN.md, demo/README.md, demo/cmd/bookbuyer/bookbuyer.go, demo/cmd/bookstore/bookstore.go, demo/cmd/bookthief/bookthief.go, demo/cmd/bookwarehouse/bookwarehouse.go, demo/cmd/common/books.go, demo/deploy-bookbuyer.sh, demo/deploy-bookstore-with-same-sa.sh, demo/deploy-bookstore.sh, demo/deploy-bookthief.sh, demo/deploy-bookwarehouse.sh, demo/ingress/deploy-ingress-agic.sh, demo/ingress/deploy-ingress-nginx-with-host.sh, demo/ingress/deploy-ingress-nginx.sh, demo/join-namespaces.sh, demo/unjoin-namespaces.sh, docs/content/docs/design_concepts/components_desc.md, docs/content/docs/tasks_usage/ingress.md, docs/example/manifests/apps/bookstore-v1.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookwarehouse.yaml, scripts/port-forward-bookbuyer-ui.sh, scripts/port-forward-bookstore-ui-v1.sh, scripts/port-forward-bookstore-ui-v2.sh, scripts/port-forward-bookstore-ui.sh, scripts/port-forward-bookthief-ui.sh
This PR updates the ports in the automatic and manual demos to use a "random" port that will not be reserved by OpenShift.
In the future, we can make the port configurable.
Fixes #2744 …
=> feat(demo): Update demo to work on OpenShift

cmd/cli/dashboard.go, cmd/cli/proxy_configdump.go, pkg/kubernetes/portforward.go, pkg/kubernetes/portforward_test.go, tests/e2e/e2e_metrics_test.go, tests/framework/common_apps.go
This change primarily adds tests for the `PortForwarder` wrapper in
pkg/kubernetes/portforward.go, enabled by some light refactoring. The
only changes outside the `PortForwarder` implementation and tests are
for compatibility, no functional changes.
Fixes #2691 …
=> tests(pkg/kube): Add portforward tests

pkg/service/types_test.go
Fixes: #2687 
**Description:**
this change adds a test for the `ClusterName.String()` method in
pkg/service/types.go
Signed-off-by: DelusionalOptimist <rudrakshpareek3601@gmail.com>
no
=> test: pkg/service ClusterName.String() method

pkg/injector/envoy_config.go, pkg/injector/test_fixtures/expected_envoy_bootstrap_config.yaml
The Envoy admin interface allows to perform destructive
operations as well as exposes sensitive information.
Access to the portal should be restricted to within
the localhost.
More info can be found at
https://www.envoyproxy.io/docs/envoy/latest/operations/admin
Port forwarding to the proxy pod to access the admin portal
over localhost will work as expected.
- …
=> injector: restrict envoy admin access to localhost

pkg/envoy/sds/response.go
Bumps the log level to info for SDS entrypoint.
Without this, its hard to catalog SDS requests
for a proxy leading to no visibility into SDS
issues. …
=> envoy/sds: bump log level to info

charts/osm/README.md, charts/osm/values.schema.json, charts/osm/values.yaml
A zero day vulnerability was found in v1.17.0
related to JWT filters. Although OSM does not
use JWT filters, updating the default image
is beneficial from a security compliance
perspective and allows downstream projects
that have forked the repo to use upstream
charts as is.
Refer to the following announcement for more info:
https://groups.google.com/g/envoy-security-announce/c/Hp16L27L00Q
- Performance …
=> charts/osm: update envoy to 1.17.1

pkg/catalog/dispatcher.go, pkg/envoy/ads/profile.go, pkg/envoy/ads/response.go, pkg/envoy/ads/stream.go
Enables info logging for high level events, that should give sufficient
insight to understand what was the control plane up to at a specific point
in time while not drowning the logging facility.
- Dispatcher top level events
- Scheduling proxy broadcast, firing proxy broadcast
- ADS
- End of ADS update (includes time full config took, ONLY full ADS, not per xds path)
- Stream.go
- Discovery request wake (important, as individual paths will not log)
- Broadcast update wake
- Logging                   [x]
No
=> pkg/envoy: Enable some logs at info

pkg/envoy/xdsutil.go, pkg/envoy/xdsutil_test.go
When configuring transport sockets for clusters and
listeners, it is possible for the SDS secret fetch
to timeout (defaults to 15s). This timeout poses problems
because after timeout, the secret is never fetched,
leaving the proxy with broken TLS connections. This breaks
the eventual consistency model. The side effect of using
a timeout is that clusters and listeners that are warming
become active after the timeout, leading to connection
resets and rejections.
This change makes the proxy indefinitely wait till
it can retrieve the SDS secrets referenced in the
transport socket configurations of clusters and
listeners.
Potentially addresses #2749
- …
=> envoy: wait indefinitely on TLS secrets

scripts/test-w-coverage.sh
Ignore fakes when measuring unit test coverage.
---
This moves us (as of this commit) from `66.33%` to `66.75%` - so not much at all.
=> tests: Ignore fakes when measuring unit test coverage

pkg/configurator/methods_test.go
This change adds tests for the tracing host, port, and endpoint fields
for the OSM ConfigMap client.
Fixes #2717, fixes #2718, fixes #2719
No
=> tests(pkg/configurator): add tracing tests

pkg/kubernetes/util_test.go
Add test for GetAppProtocolFromPortName()
Fixes: #2694 
=> test(pkg/kubernetes): Add test for GetAppProtocolFromPortName()

pkg/announcements/types.go, pkg/certificate/mock_certificate_generated.go, pkg/certificate/providers/certmanager/certificate_manager.go, pkg/certificate/providers/certmanager/types.go, pkg/certificate/providers/tresor/certificate.go, pkg/certificate/providers/tresor/certificate_manager.go, pkg/certificate/providers/tresor/fake.go, pkg/certificate/providers/tresor/types.go, pkg/certificate/providers/vault/certificate_manager.go, pkg/certificate/providers/vault/types.go, pkg/certificate/rotor/rotor_test.go, pkg/certificate/types.go, pkg/envoy/ads/response.go, pkg/envoy/ads/response_test.go, pkg/envoy/ads/stream.go
Certificates are not being rotated as expected
because the channel on which they are making
announcements is no longer used and had been
dropped in favor of the pub-sub messaging infra.
This change fixes cert rotation as follows:
1. Uses the pub-sub model to publish cert rotation
events when a cert corresponding to a given CN
is rotated.
2. Updates the certificates stored in Envoy for those
proxies whose identity matches the CN being rotated.
Verified that updated certs are correctly pushed to
proxies with this change.
Resolves #2786
- Certificate Management …
=> certificate/rotation: correctly rotate certs

pkg/catalog/routes.go, pkg/catalog/service.go
fix(pkg/catalog): resolve root service hostnames
the routes v2 logic was assuming that the root service was
a kubernetes service with no namespace suffix. So specifying
"bookstore.bookstore" as the root service didn't work.
There is more work to be done here to make sure that we follow
the SMI spec which states that a root service should be an
fqdn but for the time being, this fix allows us to run the manual
demo successfully.
Followup: #2797 
- SMI Policy             [ …
=> fix(pkg/catalog): resolve root service hostnames

pkg/envoy/xdsutil_test.go
Fixes #2713 
adds a test for `ParseEnvoyServiceNodeID` in pkg/envoy/xdsutil_test.go
which checks whether it handles when `serviceNodeID` yields less than
5 chunks on splitting
Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>
- Does this change contain code from or inspired by another project? …
=> test(pkg/envoy): ParseEnvoyServiceNodeID with less than 5 chunks in the NodeID string

pkg/cli/environment_test.go
This change adds a test in pkg/cli for the `(*EnvSettings).EnvVars()`
function. It also adds a change in the tests for `New()` to undo any
environment variable changes so the new test runs the same both in
isolation and in the context of the other tests.
Fixes #2721 …
=> tests(pkg/cli): add test for EnvVars()

pkg/envoy/lds/inmesh.go, pkg/envoy/lds/inmesh_test.go, tests/e2e/e2e_trafficsplit_test.go, tests/framework/common_apps.go
Adds support to split outbound TCP traffic based on SMI
traffic split. Existing e2e test for traffic split has
been extended for TCP.
Also replicates the appProtocol logic in SimplePodApp
to the SimpleDeploymentApp definition and method.
The test is mostly unchanged, except for creating
TCP routes instead of HTTP and fixing indentation.
Resolves #2666
- SMI Policy             [X]
- …
=> envoy/lds: support for outbound TCP traffic splitting

demo/README.md, demo/run-osm-demo.sh, docs/content/docs/install/_index.md, docs/content/docs/install/manual_demo/_index.md
Document how to install OSM on OpenShift
Fixes #2785
No
=> docs(install): Document how to install on OpenShift

pkg/cli/environment_test.go
This change adds a test in pkg/cli for the
`(*EnvSettings).RESTClientGetter()` method.
Fixes #2720
No
=> tests(pkg/cli): add test for RESTClientGetter()

pkg/catalog/fake.go, pkg/catalog/helpers_test.go, pkg/catalog/ingress.go, pkg/catalog/ingress_test.go
Makes the tests comprehensive to exactly match all expected
policies from ingress. The previous version of this test
was not thorough in verifying ingress -> policy translation.
Also voids the need for fake ingresses and fixes a logic
in the code related to path matching. Additionally, the
fake catalog helper is moved to fake.go.
- …
=> catalog/ingress: make tests comprehensive and correct check

pkg/envoy/ads/stream_test.go
Change 9a7904c6 missed committing the unit test
since the new test was an untracked file. Adds
the test that was supposed to be a part of 9a7904c6. …
=> envoy/ads: add unit test for helper

pkg/workerpool/workerpool.go, pkg/workerpool/workerpool_test.go
Workerpool is an implementation of the thread-pool paradigm
in Go. The benefits of it in Go however, can be quite different
from any other language able to schedule themselves on system threads.
By using a workpool model, the main focus and intention is to limit the
number of goroutines that can do busy-work and get scheduled concurrently
at any point in time.
Too many goroutines being scheduled at the same time will cause other
goroutines (maybe more critical ones) to be scheduled less often, thus
incurring in resource starvation on those and potentially triggering other
issues.
By being able to queue up work, we should be able to run a more deterministic
runtime (despite Go's nature, this we will not be able to help), less dependant
on the scheduler and more accurate in terms of time, …
=> workerpool: introduce workerpool concept and unit tests

tests/e2e/e2e_upgrade_test.go
Fixed the "skip" step in e2e_upgrade_test.go, as I noticed this test was not being skipped in the osm-azure CI even when the installType was set to NoInstall.  …
=> Fix skip statement in upgrade e2e test

tests/e2e/e2e_http_ingress_test.go
The nginx ingress controller installation was failing because Helm was
running hooks in the "osm-system" namespace, defaulted from OSM's
`*cli.EnvSettings`, even though the install was intended for a different
namespace. The hooks would fail because the "osm-system" namespace
doesn't exist when OSM is installed in a different namespace. This
change forces Helm's kube client to run in the context of the release's
namespace.
- CI System …
=> fix(e2e): fix HTTP ingress test when OSM is installed outside osm-system

pkg/catalog/xds_certificates.go, pkg/catalog/xds_certificates_test.go, tests/e2e/e2e_trafficsplit_recursive_split.go
Keeping this prevents us from referencing just a service name
without the namespace suffic as the traffic split root service …
=> fix(*): rm filterTrafficSplit logic as it is no longer needed

pkg/envoy/ads/grpc.go
Currently ADS skips requests with an empty TypeUrl.
This has been noticed sometimes and might need to
be handled differently. This change logs the such
a request to get more info, because it is unexpected. …
=> envoy/ads: log the request with an empty TypeUrl

docs/content/docs/install/manual_demo/_index.md
This change makes it clearer in the manual demo that users should
install OSM with the provided Prometheus, Grafana, and Jaeger enabled to
view dashboards as instructed by the demo without having to reinstall
the control plane. …
=> docs(demo): clarify installing optional components

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/improvement---feature-request.md
Add demo checkbox to issue templates. This may be used by customers who find a bug in the demo (such as it doesn't work on OpenShift). These instances are separate from the CI system but are also common enough to warrant a new checkbox.
- Does this …
=> Add demo checkbox to issue templates

docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml
gets rid of kubectl error on commandline.
redundant action since namespace was already created during
previous manual demo steps
resolves #2836 …
=> ref(docs): rm ns yaml from manual demo manifests

charts/osm/templates/validatingwebhook.yaml
There is a race condition between osm-config ConfigMap creation
and osm config validator webhook. It has been observed sometimes
where the validating webhook config is deployed *before*
osm-config-validator service is ready. When this happens,
creation of osm-config ConfigMap fails because the validating
webhook is not ready, and as a result install of osm fails.
Since creation of osm-config ConfigMap is handled by the install
workflow (cli or Helm) internally, it is safe to remove interception
of CREATE osm-config webhook requests and only validate mutations
(UPDATE) to the osm-config ConfigMap.
Error seen:
```
Failed calling webhook, failing closed osm-config-webhook.k8s.io: \
failed calling webhook "osm-config-webhook.k8s.io": \
Post …
```
=> charts/osm: remove osm-config ConfigMap validation for CREATE

docs/content/docs/application_requirements.md, pkg/injector/health_probes.go
Documents ports used by Envoy so that customers know not to use them for their applications.
Closes #2106 
=> docs(envoy): Document ports used by envoy

docs/example/manifests/samples/curl/curl.yaml, docs/example/manifests/samples/httpbin/httpbin.yaml, docs/wip/traffic/_index.md, docs/wip/traffic/permissive_traffic_policy_mode.md
Adds a document for permissive traffic policy mode as
described in #2855. The troubleshooting guide for
permissive mode will be documented separately.
Note that the docs are under a TBD `wip` folder till the
final location for such docs are established, at which time
this will be moved into a different folder.
- Performance …
=> docs/wip/traffic: document permissive traffic policy mode

Makefile
Signed-off-by: Abhilash Gnan <abhilashgnan@gmail.com>
Remove buggy echo errors when go version checks out - `make check-go-version` is used in automated demo script(maybe in more places) to check go version is `>= 1.15.7` before building osm. This command prints error message even when go version check passes.
=> Fix check-go-version error message

pkg/configurator/methods_test.go
This change updates the tests in pkg/configurator/methods_test.go to use
the standard Go testing library and testify.
Part of #1704
No
=> tests(pkg/configurator): refactor to use stdlib + testify

pkg/catalog/ingress.go, pkg/catalog/routes.go, pkg/trafficpolicy/trafficpolicy.go, pkg/trafficpolicy/trafficpolicy_test.go
+ now accepts a slice of service.WeightedCluster
+ easier to create RouteWeightedCluster now where there
is more than one backend/weighted cluster
+ prep for #2368
-->
- Control Plane          [ X] …
=> ref(pkg): update NewRouteWeightedClusters method

docs/content/docs/dev_guide/_index.md
**Description**: Fixes link and statement to clarify that it points to manual demo docs, not install docs.
- Demo                   [x]
=> docs(demo): fix broken link and clarify statement

README.md, docs/content/docs/dev_guide/_index.md
This PR removes the `automated demo`, which provides little value to new comers to this project. The automated demo is mainly needed for CI and development purposes.
The doc in `./demo/README.md` is still useful within the developer's guide, but not as a way to fully experience OSM.
=> docs: Remove automated demo; Make manual demo main and only demo

docs/content/docs/tasks_usage/traffic_management/egress.md, docs/content/docs/tasks_usage/traffic_management/ingress.md
Internal links to docs (links within docs/content/docs) needs
to have an alias so they are navigable directly on the website. …
=> docs/tasks_usage: alias docs to render correctly on website

docs/demos/first_steps.md
This PR adds a new demo, which attempts to be the simplest possible demo, which shows:
1. how to download and install OSM
2. create 2 pods
3. apply an SMI policy to allow traffic between the 2 pods.
The goal is to create a series of demos, which build on each other, are very easy to follow, and walk us through everything the current manual demo does.
ref #2854
=> doc: Adding a new simple demo - first steps

charts/osm/templates/mutatingwebhook.yaml
The injector's mutating webhook is incorretly labeled
to osm-controller. This should be matching on the
osm-injector app label set on osm-injector's
deployment.
Currently the label on the mutating webhook is not
used anywhere else. …
=> charts/osm: fix label on injector's mutating webhook

.github/workflows/release.yml
**Description**: Fixes bug that causes release page preview to render as: 
Tested this change here: https://github.com/SanyaKochhar/osm/releases/tag/v0.8 …
=> fix(release): fix release title bug

.github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md, docs/content/docs/release_guide.md
**Description**: Adds a PR template that can be used via URL or pasted into the PR description box. [GitHub does not currently provide a UI](https://github.community/t/multiple-pull-request-templates/1850) to toggle between PR templates as it does for issue templates, so a little manual toggling will have to do for now.
Resolves #2919 
Please …
=> chore(release): adds a PR template for releases

pkg/envoy/xdsutil.go, pkg/envoy/xdsutil_test.go
This reverts commit 96faee85a81bd766e58243b41e9fb854dcc8ac48.
The original commit causes issues with the existing SDS logic
in a way that degrades performance. We will revisit this when
we introduce XDS snapshot cache.
Related to #2749 …
=> Revert "envoy: wait indefinitely on TLS secrets"

scripts/release-notes.sh
**Description**: This PR fixes a bug with respect to the order of the tags and the $prev tag in the release-notes.script. Note: this original bug was not occurring for everybody so it may not be reproduceable. 
- Does this change contain code …
=> Fixed tag order in release-notes.sh

pkg/announcements/types.go, pkg/catalog/catalog.go, pkg/ticker/ticker.go, pkg/ticker/ticker_test.go
New package contains a ticker implementation that is fully
interacted through pubsub (this will allow us to decouple
from whichever way we want to configure it with, configmap,
pflag, debugServer endpoint, etc.)
It starts turned off by default and is run after dispatcher
starts. Next commit will introduce configurability.
No
=> pkg/ticker: reintroduce ticker concept

pkg/envoy/ads/response.go, pkg/envoy/ads/response_test.go, pkg/envoy/xdsutil.go, pkg/envoy/xdsutil_test.go
Cherry-picks 2 SDS related bug fixes to v0.8:
- 93afc227: reverts SDS config fetch timeout
- 351db1b3: fix missing service cert referenced in LDS inbound filter chain 
---------
Backports SDS related bug fixes to the v0.8 branch. …
=> Cherry-picks 2 SDS related bug fixes to v0.8

docs/content/docs/troubleshooting/traffic/egress.md, docs/content/docs/troubleshooting/traffic/permissive_traffic_policy_mode.md
Internal links (links within `docs/content/docs`) should
use relative paths so there are navigable within the website.
Before this change, browsing the doc on the website would
redirect to the github page. …
=> docs: use relative paths for internal links

.github/workflows/main.yml
cherry-pick of ed870c38, no functional changes to OSM
---
This change configures CI to additionally push images with the git SHA
tag on each push to release branches like for pushes to main. …
=> feat(ci): push images for each push to release branches

pkg/configurator/client.go, pkg/configurator/client_test.go, pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/configurator/mock_client_generated.go, pkg/configurator/types.go
Adds ticker config in config map.
Off by default if either empty or non-duration value passed
as a string.
Imposed minimum configurable limit will be in place in ticker
class in next commit.
No
=> cfgmap: add ticker config

.mergify.yml, CONTRIBUTING.md, docs/content/docs/automerge.md
Add documentation for automerge and removed redundant rebase rule for `automerge` label and resolves #2945 
No
=> docs(docs/content/docs): Add documentation for automerge 

pkg/catalog/catalog.go, pkg/catalog/helpers_test.go, pkg/ticker/ticker.go, pkg/ticker/ticker_test.go
Ticker will run it's own configmap listener and watch for changes
on the `ConfigResyncInterval` value, and configure ticker accordingly.
Added also stop channels to stop routines for testing.
No
=> configResync: Add config hooks to start/stop ticker

pkg/envoy/ads/response_test.go, pkg/envoy/ads/secrets.go, pkg/envoy/ads/secrets_test.go, pkg/envoy/lds/ingress.go, pkg/envoy/lds/inmesh.go, pkg/envoy/sds/errors.go, pkg/envoy/sds/response.go, pkg/envoy/sds/response_test.go, pkg/envoy/xdsutil.go, pkg/envoy/xdsutil_test.go, pkg/service/types.go, pkg/service/types_test.go
Since all proxy certs are based on the proxy identity
(service account), the existing implementation results
in multiple SDS secrets with the exact same certificate.
This happens because even though a given proxy presents
the same certificate during a TLS handshake to its peer
proxy regardless of whether it is an upstream or downstream,
the SDS service-cert secret was being created once per
direction (inbound and outbound connections).
Additionally, the root validation certs on the inbound
listener's DownstreamTlsContext are the same regardless
of the number of services associated with the proxy. So
it makes more sense to associate the inbound root validation
certificates with the proxy's service account instead, since
otherwise there would be duplicate SDS secrets for …
=> envoy: optimize SDS secrets per proxy

docs/wip/osm_controller_health_probes.md
This change adds a new WIP doc that explains OSM's health probes and how
to determine why they may be failing.
Fixes #2877
No
=> docs(health): add health probe doc

pkg/catalog/catalog.go, pkg/catalog/helpers_test.go, pkg/ticker/ticker.go, pkg/ticker/ticker_test.go
Cherry-picks edc0354e from main to release-v0.8 branch.
---------------------
Ticker will run it's own configmap listener and watch for changes
on the ConfigResyncInterval flag, and configure ticker appropriately.
Ticker is off by default.
No
=> ticker: Add config hooks to start/stop ticker

pkg/envoy/lds/connection_manager.go, pkg/envoy/lds/listener_test.go, pkg/envoy/lds/response.go
Instead of passing constants as function arguments, use
them directly. Also updates the stat prefix corresponding
to the prometheus listener's http connection manager and 
the route's virtual host name for clarity.
- Does this …
=> envoy/lds: use constants directly and update stat prefix

pkg/envoy/lds/connection_manager.go, pkg/envoy/lds/listener_test.go
The stat prefixes help debug issues faster by
examining stats corresponding to specific envoy
config. This change updates the stat prefix
for the http connection manager so that http
stats corresponding to inbound and outbound
route configurations are easy to locate
and parse.
Previously:
```
http.http.downstream_rq_timeout: 0
```
With this change:
```
http.mesh-http-conn-manager.RDS_Outbound.downstream_rq_timeout: 0
```
Part of #2156
- Security …
=> envoy/lds: improve http stat prefix

docs/content/docs/tasks_usage/traffic_management/permissive_traffic_policy_mode.md, pkg/envoy/rds/response_test.go, pkg/envoy/route/route_config.go, tests/scenarios/traffic_split_with_apex_service_test.go, tests/scenarios/traffic_split_with_zero_weight_test.go
Use `resource-name` style for naming RDS configs to be
consistent with other config names (listener, filter chains,
virtual host, stats etc.).
No functional change. …
=> rds: use consistent naming style for config name

pkg/envoy/types_test.go
Add test for TypeURI.String() and resolves #2704
- Does this change contain code from or inspired by another project? No
- If so, did you notify the maintainers and provide attribution?
=> test(pkg/envoy): add test for TypeURI.String()

pkg/configurator/validating_webhook_test.go
Adds a test that fails IP ranges of the form
a.b.c.d, because the expected range should be
of the form a.b.c.d/x. …
=> configurator: add test for invalid IP range format

pkg/envoy/lds/inmesh.go, pkg/envoy/lds/inmesh_test.go
Updates the stat prefix for the tcp proxy filters
to:
1. be consistent with other stat prefixes (HTTP conn
manager)
2. Remove ':' from the prefix because it gets converted
to an '_', and is reserved for displaying key:value.
Part of #2156 …
=> envoy/lds: fix stat prefix for tcp-proxy filters

pkg/envoy/ads/response.go
Wrong error line gives wrong insight on error.
=> Fix Log line on handler

pkg/envoy/lds/listener.go
Makes the stat prefix for the egress tcp proxy filter
consistent with other stat prefixes.
Part of #2156 …
=> envoy/lds: make stat prefix for egress consistent

pkg/catalog/inbound_traffic_policies.go, pkg/catalog/inbound_traffic_policies_test.go
This change simplifies the inbound route for permissive
mode by using the concept of a wildcard service account
to allow all downstream service accounts that the
corresponding RBAC policy must allow. This is similar
to what is done for ingress where all service account
are allowed to access a given upstream via RBAC.
This optimization allows building the inbound route
for a service in permissive mode in O(1) time as
opposed to O(n) where n is the number of service
accounts in the mesh.
- Metrics …
=> catalog: simplify inbound route for permissive mode

.github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md
I'd like to copy the file `.github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md` from `main` to `release-v0.8` branch.
This allows us to have version links in documents.  I'm going to use this in the `docs/content/docs/release_guide.md` file, which currently points to `main` branch.
---
This is part of the #2854 effort
=> Adding release_pull_request_template.md to release-v0.8 branch

tests/e2e/e2e_http_ingress_test.go
For NoInstall, nginx could install in `kube-system` if `OsmNamespace` is there.
It's not a major problem, but it makes cleanup better in case something
fails, as later the namespace can be just removed, as opposed to
deleting individual leftovers from `kube-system`.
No
=> e2e: Make a namespace for ingress nginx

docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml
This PR removes the `bookbuyer` and `bookthief` Services, which are no longer needed for OSM v0.8 and above to operate.
Additionally - rewording YAML comments from "Deploy ..." to "Create ..."  (create deployment, create service account etc.)
---
The following PR makes the same change on `main` branch: #3008
---
This is part of the #2854 effort
=> docs/manifests: Cleanup client services - not needed in v0.8.2

docs/content/docs/install/manual_demo/_index.md
This PR updates the **Download and install** section of the "OSM Manual Demo" document.
Goals:
- simplify and clarify the verbiage
- point to v0.8.2 release be explicit about the version of OSM this is relevant for (v0.8.2)
- include instructions on downloading it on GNU/Linux, macOS, and Windows
---
This is one of a few steps to update the entire doc as part of #2845
Related PRs:
- #3010
---
Once the entire doc is rewritten - all changes will be applied to the `release-v0.8` branch.
=> docs: Update the download and install section of the OSM Manual Demo document

pkg/envoy/lds/rbac.go
Unlike other stats, the RBAC stat prefix gets suffixed
with `rbac`. This change updates the stat prefix for the
network RBAC policy type so it renders correctly:
previously:
`RBACrbac.allowed: 0`
now:
`network-rbac.allowed: 0`
Part of #2156 …
=> envoy/lds: update stat prefix for network RBAC

pkg/configurator/validating_webhook.go
Adds duration value validation for `config_resync_interval` in
validating webhook.
No
=> validatingWebhook: Add duration validation for config_resync_interval

tests/e2e/e2e_controller_restart_test.go
Seeing some instances of what seems slow curl turnaround execution,
increasing timing and adding time logs for the test to better
identify the cause.
```
STEP: Restarting OSM controller
STEP: [WaitForRepeatedSuccess] waiting 40s for 20 iterations to succeed
> (client/client -> server.server) HTTP Req succeeded: 200
> (client/client -> server.server) HTTP Req succeeded: 200
> (client/client -> server.server) HTTP Req succeeded: 200
> (client/client -> server.server) HTTP Req succeeded: 200
> (client/client -> server.server) HTTP Req succeeded: 200
> (client/client -> server.server) HTTP Req succeeded: 200
> (client/client -> server.server) HTTP Req succeeded: 200
> (client/client -> server.server) HTTP Req succeeded: 200
> (client/client -> server.server) HTTP Req succeeded: 200
> …
```
=> e2e: Increase verification time for restart test, adds time checks

cmd/cli/namespace_list.go, cmd/cli/namespace_list_test.go
This change fixes a bug in the `osm namespace list` command where after
doing `osm namespace add bookbuyer` and then `osm namespace ignore bookbuyer`,
`osm namespace list` would incorrectly show sidecar injection enabled in
the bookbuyer namespace. This change notates namespaces with both the
sidecar injection annotation "enabled" and the ignore label set as
`disabled (ignored)` in the `SIDECAR-INJECTION column` of the command's
output.
Unit tests have also been added to the `osm namespace list` command.
Fixes #2965
- SMI …
=> fix(cli): note ignored namespaces in "osm namespace list"

charts/osm/templates/mutatingwebhook.yaml, charts/osm/templates/validatingwebhook.yaml, ci/cmd/maestro/kubernetes_tools.go, cmd/osm-controller/osm-controller.go, cmd/osm-injector/osm-injector.go, pkg/configurator/validating_webhook.go, pkg/configurator/validating_webhook_test.go, pkg/injector/patch.go, pkg/injector/patch_test.go, pkg/injector/webhook.go, pkg/injector/webhook_test.go, pkg/webhook/webhook.go, pkg/webhook/webhook_test.go, tests/framework/common_apps.go, tests/scenarios/scenario_mutatingwebhook_reconcile_test.go
OSM has been using admissionregistration.k8s.io/v1beta1
API for the admission webhooks (injector and config
validator webhooks). The v1beta1 API was deprecated
in v1.16 and will not be served in v1.22. Since
OSM only supports versions >= v1.17, this change
upgrades to the v1 API available since v1.16.
v1 API requires additional fields on the webhook
configurations to be set, namely `sideEffects` and
`admissionReviewVersions`. Since the injector
webhook has a sideEffect (creating k8s secret
for the Envoy bootstrap config), the side effect
has been skipped for dry-run requests as indicated
in the [API](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#side-effects)
Also updates the injector's timeout to 20s. Previously
this defaulted …
=> Update to admissionregistration.k8s.io/v1

Makefile, charts/osm/values.schema.json
Adds a schema for injector's properties and fixes the podLabels
schema for osmController, which was incorrectly defined under
`osmController.resource` in 04780f07.
Adds check to ensure chart values are always validated by
its schema. `make chart-checks` is invoked in the CI.
Resolves #3023
- Other …
=> charts/osm: add schema for injector and fix podLabels schema

cmd/osm-injector/reconcile.go
Fixing the name of the mutating webhook that the reconciler will operate on. 
=> bug(reconciler): fix name of mutating webhook in reconciler

pkg/catalog/xds_certificates_test.go
Fixes a flaky test that relies on ordering of
values returned in the slice.
`No`
=> catalog: fix flaky test relying on ordering

docs/content/docs/install/manual_demo/_index.md
**Description**: Noticed some typos as I was testing the manual demo for v0.8.2 of osm-arc, creating this PR to address them. 
The bookstore service on :8084 is available initially with permissive_traffic_policy mode enabled, we should not be saying that it's unavailable initially. Moreover, as there is no separate bookstore v1 service on :8081 anymore, we should remove the ref to :8081. Finally, there was a typo where bookstore was stated to be on port :8083 instead of :8084. 
- Tests …
=> Fix typos in manual demo

go.mod, pkg/catalog/ingress.go, pkg/catalog/ingress_test.go, pkg/envoy/route/route_config.go, pkg/envoy/route/route_config_test.go, tests/e2e/e2e_http_ingress_test.go
Currently, ingress programs all paths as regex path
matches in Envoy. This is incorrect because the
`pathType` specifier for a path in an ingress rule
is not honored. There are other limitations this
change addresses with respect to matching on HTTP
paths.
This change extends the ingress implementation to
adhere to the spec as follows:
1. Implements ingress routes based on the `pathType`
specified for a path in an ingress rule. In addition
to regex based path matching, exact and prefix based
path matching is implemented.
2. `Prefix pathType` in k8s ingress is not a string prefix,
but an element-wise prefix of paths. This is translated
to a regex match in the envoy route. `Prefix pathType`
in k8s ingress requires that request /foo match path
/foo/bar and not match /foobar. …
=> ingress: add support for Exact, Prefix and ImplementationSpecific path matching

charts/osm/templates/_helpers.tpl, charts/osm/templates/fluentbit-configmap.yaml, charts/osm/templates/grafana-configmap.yaml, charts/osm/templates/grafana-deployment.yaml, charts/osm/templates/grafana-rbac.yaml, charts/osm/templates/grafana-svc.yaml, charts/osm/templates/jaeger-deployment.yaml, charts/osm/templates/jaeger-service.yaml, charts/osm/templates/mutatingwebhook.yaml, charts/osm/templates/osm-configmap.yaml, charts/osm/templates/osm-deployment.yaml, charts/osm/templates/osm-injector-deployment.yaml, charts/osm/templates/osm-injector-service.yaml, charts/osm/templates/osm-rbac.yaml, charts/osm/templates/osm-service.yaml, charts/osm/templates/prometheus-configmap.yaml, charts/osm/templates/prometheus-deployment.yaml, charts/osm/templates/prometheus-rbac.yaml, charts/osm/templates/prometheus-svc.yaml, charts/osm/templates/proxy-config.yaml, charts/osm/templates/validatingwebhook.yaml, pkg/certificate/providers/config.go, pkg/constants/constants.go, pkg/injector/envoy_config.go, pkg/injector/envoy_config_test.go, pkg/injector/types.go, pkg/injector/webhook.go
This change modifies all resources created by OSM to contain the
following labels:
app.kubernetes.io/name: openservicemesh
app.kubernetes.io/instance: <mesh name>
app.kubernetes.io/version: <Chart.yaml appVersion>
These labels have been added as a helper template in the Helm chart
named "osm.labels". In addition, Envoy bootstrap secrets created by the
injector will also contain these labels. The osm-ca-bundle created by
osm-controller will contain the above labels besides
`app.kubernetes.io/instance` because the same secret may be used across
different OSM instances. The labels have not been added to SMI CRDs as
they are not directly owned by OSM.
No functional changes as no existing labels have been removed or
modified. Cleanup and consistency of existing labels may be …
=> chore(*): add app labels to all OSM resources

pkg/configurator/client.go
Was not listed to update proxies; new configs have to be pushed to updated lds
when config changes.
No
=> config: add prometheus_scraping flag to trigger envoy reconfig on change

docs/wip/application_health_probes.md
This change adds a new document describing how OSM modifies HTTP health
probes and adds Envoy configuration to meshed Pods so startup, liveness,
and readiness probes can continue to function from inside a mesh.
Fixes #2876 …
=> docs(health): add app health probe doc

pkg/configurator/client_test.go
Adds a test for the event trigger routine in configurator.
No
=> configurator: Add event trigger routine test

docs/content/docs/install/manual_demo/_index.md
This PR updates the **Installing OSM on Kubernetes** section of the "OSM Manual Demo" document.
Goals:
- add clarity and simplify verbiage
- be explicit about the version of OSM (v0.8.2) this document is written for
- include links to other documentation
---
This is one of a few steps to update the entire doc as part of #2845
Related PRs:
- #3010
- #3011 
---
Once the entire doc is rewritten - all changes will be applied to the `release-v0.8` branch.
=> doc: Updating the Installing OSM on Kubernetes section of the Manual Demo document

pkg/envoy/ads/debugger_test.go
Add unit test for Server.GetXDSLog() and resolves #2702
No
=> test(pkg/envoy/ads): Add test for Server.GetXDSLog()

mockspec/rules, pkg/catalog/fake.go, pkg/catalog/ingress.go, pkg/catalog/ingress_test.go, pkg/ingress/client.go, pkg/ingress/errors.go, pkg/ingress/mock_client_generated.go, pkg/ingress/types.go
This change is in preparation to support multiple versions
of the ingress API: networking.k8s.io/v1beta & v1.
The v1beta1 API has been deprecated in k8s 1.19, and will
be unusable in 1.22. However since OSM supports versions
`>= 1.18`, the v1beta1 API must still be supported. Moreover,
existing users could be leveraging the older v1beta1 API.
This change introduces versioning for ingress resources,
with the goal to support ingress v1 and making the
version configurable in subsequent changes.
Also updates the ordering of mock generation to avoid
dependency issues.
Part of #2798
- CLI Tool …
=> ingress: prepare for supporting multiple ingress versions

pkg/catalog/ingress.go, pkg/catalog/ingress_test.go, pkg/ingress/client.go, pkg/ingress/mock_client_generated.go, pkg/ingress/types.go
Adds support to parse and build traffic policies
from the networking.k8s.io/v1 ingress api.
The key differences from v1beta1 -> v1 are:
- spec.backend -> spec.defaultBackend
- backend.serviceName -> backend.service.name
- backend.servicePort -> backend.service.port.number
The core logic to parse and build routes for v1beta1 and
v1 objects are exactly the same, with only the objects
being different as noted above. The logic and test cases
have been duplicated for v1beta1 and v1 api because
abstracting the differences in the object attributes
seemed hacky. This also simplifies the process when
a particular api needs to be deprecated, which would
simply require deleting the code corresponding to the
given version without affecting other versions.
Part of #2798
**Affected …
=> ingress: add support for ingress v1

pkg/envoy/ads/response.go, pkg/envoy/ads/server.go, pkg/envoy/ads/types.go, pkg/envoy/cds/response.go, pkg/envoy/cds/response_test.go, pkg/envoy/eds/response.go, pkg/envoy/eds/response_test.go, pkg/envoy/lds/response.go, pkg/envoy/lds/response_test.go, pkg/envoy/rds/response.go, pkg/envoy/rds/response_test.go, pkg/envoy/sds/response.go, pkg/envoy/sds/response_test.go, tests/scenarios/traffic_split_with_apex_service_test.go, tests/scenarios/traffic_split_with_zero_weight_test.go
Currently, each xDS path will marshal and create each DiscoveryResponses
on the same vertical. This limits the vision that ads/server has over responses,
and and in addition causes the marshalling logic to exist in all paths.
This commit decouples getting the xDS resources from the Marshal/SendToServer
logic.
This removes some common code for all xDS paths, but more
importantly enable us to unlock additional features such as global consistency
checks between Requests/Responses, use of xDS server cache implementations,
etc.
No
=> ads: change xDS path responses to generic interface

pkg/envoy/rds/response_test.go
This PR re-aliases `deckarep/golang-set` to `mapset` for consistency.
=> rds: Alias deckarep/golang-set to mapset

charts/osm/templates/cleanup-hook-rbac.yaml, charts/osm/templates/cleanup-hook.yaml
This change adds a Helm hook to be run after the chart resources have
been uninstalled with `helm uninstall` or `osm mesh uninstall`. The hook
is implemented as a Kubernetes Job that will run `kubectl` commands to
delete resources created outside the chart associated with the control plane.
Currently only the osm-config ConfigMap will be cleaned up by the hook
(in preparation for #2932).
Resources NOT cleaned up by the hook:
- CRDs (as they may still be in use)
- osm-ca-bundle (as it may be used for a future OSM installation)
- Envoy bootstrap secrets (because injected Pods still mount them as volumes)
Fixes #2931
- CLI Tool …
=> feat(chart): add post-delete cleanup hook

cmd/cli/mesh.go, cmd/cli/osm.go, cmd/cli/uninstall.go, cmd/cli/uninstall_test.go, demo/clean-kubernetes.sh, docs/content/docs/install/manual_demo/_index.md, docs/content/docs/install/uninstallation_guide.md, docs/content/docs/todo/uninstall_osm.md, docs/wip/demo_prometheus.md
Change the `osm uninstall` cmd to be a first-level
subcommand. Extracts cmd from `osm mesh uninstall`.
Update relevant docs to reflect this new change.
Resolves #2793.
- Does this change contain code from or inspired by another project? …
=> feat(cli): change uninstall cmd to match install

pkg/catalog/fake.go, pkg/catalog/ingress.go, pkg/catalog/ingress_test.go, pkg/ingress/client.go, pkg/ingress/errors.go, pkg/ingress/mock_client_generated.go, pkg/ingress/types.go
This change implements the capability to serve multiple
versions of the ingress API based on [Proposal 1](https://docs.google.com/document/d/19rqJaJD_kDEfrvk7J0N--x45IYqUSmrJHo2PdYkC3Bg/edit#heading=h.hkcgqkq1jn5t?usp=sharing).
It does the following:
1. Figures out the k8s server version at runtime.
2. Initializes the appropriate versioned ingress
informers/caches depending on if the k8s server
version supports the ingress api version.
3. Updates `mesh-catalog` to build routes based on
all api versions of the ingress resource.
4. Updates tests to handle multiple versions of
ingress.
Part of #2798
- Certificate …
=> ingress: dynamically initialize versioned ingress clients

pkg/ingress/client.go, pkg/ingress/client_test.go
Use client-go's discovery interface to check if
candidate ingress versions are supported by the
k8s API server.
Part of #2798 …
=> ingress: discover supported API versions

charts/osm/Chart.yaml, tests/e2e/e2e_k8s_version_test.go
Description: Add a pre-install check to ensure that the kubernetes cluster is a supported version for the current version of OSM. We were initially considering limiting this to downstream charts, but this change may be relevant upstream as well.  …
=> feat(osm/Chart.yaml): Pre-install check for k8s version

charts/osm/templates/validatingwebhook.yaml
Adds objectSelector for ` app.kubernetes.io/name`, this allows us to narrow down the VWH to only look at OSM's configmaps so that if a user addds their own configmap to the `osm-system` namespace it will be overlooked by the VWH and resolves #2926  …
=> chore(charts/osm/templates): add objectSelector  for VWH

tests/e2e/e2e_deployment_client_server_test.go, tests/e2e/e2e_trafficsplit_recursive_split.go, tests/e2e/e2e_trafficsplit_test.go, tests/framework/common_traffic.go, tests/scale/scale_trafficSplit_test.go, tests/scenarios/scenario_mutatingwebhook_reconcile_test.go
Cleanup will be skipped and test will exit bypassing cleanup
if a different context goroutine panics or asserts without
deferring the ginkgo recover function.
This causes logs to not be collected in some situations (ie,
when a test has some goroutines waiting for NS to come up
but they don't).
No
=> e2e: fix ginkgo panic recoveries

pkg/envoy/ads/jobs.go, pkg/envoy/ads/server.go, pkg/envoy/ads/stream.go, pkg/envoy/ads/types.go, pkg/envoy/proxy.go, pkg/utils/stringhash.go, pkg/utils/stringhash_test.go
This change makes envoy configurations to be serialized in a preset,
constant number of go routines as opposed to having each envoy using
his own ADS worker/goroutine context to compute its configuration.
This change helps in making the runtime more deterministic as the number
of active work/ers to be scheduled by the scheduler will remain mostly
constant regardless of the number of proxies connected. 
- This prevents too many active workers starving other critical routines, which include
liveness probes, dispatcher routine, or other lower level library routines like
Kubernetes informers or other network-related routines (grpc steams).
- This patch allows also to better determine how much time an envoy update
actually takes, as before it depended directly and entirely on how much other …
=> ads: sendResponse to workequeue/jobs

pkg/catalog/mock_catalog_generated.go, pkg/catalog/types.go, pkg/debugger/namespace.go, pkg/debugger/namespace_test.go
This PR removes `ListSMIPolicies()` and `ListMonitoredNamespaces()` from `MeshCataloger` interface.
`MeshCataloger` does not need or required these.
On the other hand these are required by the [MeshCatalogDebugger interface](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/debugger/types.go#L41-L56).
fix #3084
=> Removing ListSMIPolicies() and ListMonitoredNamespaces() from MeshCataloger interface

docs/content/docs/install/manual_demo/_index.md
This PR updates the **Prerequisites** section of the "OSM Manual Demo" document.
Goals:
- simplify and clarify the verbiage
- be explicit about the version of OSM this is relevant for (v0.8.2)
---
This is one of a few steps to update the entire doc as part of #2845
---
Once the entire doc is rewritten - all changes will be applied to the `release-v0.8` branch.
=> docs: Update Prerequisites section of OSM Manual Demo document

tests/scale/scale_trafficSplit_test.go
At +1000 proxies, our prometheus will start taking +4G of mem. If it has not been
bestowed enough memory, it will eventually be OOM killed for this test.
Since this test is mostly qualifying control plane, we will stop scrapping the
proxies for the time being.
Mesh-wise control plane metrics are still being scrapped (which are still
of interest to this test).
- Performance            [x]
=> test/scale: disallow scraping envoy proxies at scale

docs/wip/application_health_probes.md, pkg/injector/health_probes.go, pkg/injector/health_probes_test.go, tests/e2e/e2e_health_probe_test.go
This change rewrites `tcpSocket` health probes for pods entering a mesh
to use an Envoy-configured port instead of the user-defined one so the
probes work as they would outside a mesh. This is the same approach as
used in #3098 to handle HTTPS probes.
Fixes #2543
- Does this …
=> feat(injector): modify tcpSocket health probes

pkg/envoy/lds/ingress.go, pkg/envoy/rds/response.go, pkg/envoy/rds/response_test.go, pkg/envoy/route/route_config.go, pkg/envoy/route/route_config_test.go
There is an existing problem where an ingress route
can open up routes to the service within the mesh
for clients that are part of the mesh even if an
SMI policy does not exist for in-mesh clients to
access the service over the routes specified in
the ingress resource.
This is because both in-mesh routes based on SMI
policies and ingress routes based on k8s ingress
use the same inbound route configuration. This is
problematic and even a security concern because
using ingress also allows in-mesh clients to access
the service over the ingress routes when the client
has access to some but not all routes on the service.
Consider the following example where `client` and
`server` are part of the mesh.
- `server` exposes 2 paths: `/foo` and `/bar`
- `client` should only access …
=> envoy/ingress: use a separate route config for ingress

pkg/configurator/client.go, pkg/configurator/client_test.go, pkg/configurator/methods_test.go
There might be a race on Pubsub library creation and use, where Pubsub
could have potentially not finished subscribing due to the nature
of Go, and we might miss an event as a consequence in some corner cases.
Subscribing uses unbuffered channel message passing to subscribe internally,
inside pubsub lib. A goroutine handles the actual subscription (adding the sub channel to maps, etc).
Depending on scheduling, a quick publish on a channel recently subscribed to
could theoretically loose the event if the scheduler didn't fully finish the subscribe
handler (ie. the routine yielded for whatever reason).
The result is the test is stuck waiting for a notification that might have happened before
subscription was committed.
```
2021-04-12T19:58:14.6347348Z goroutine 222 [chan receive, 1 …
```
=> configurator: fixes for configurator event listener

cmd/cli/mesh_list.go, cmd/cli/mesh_list_test.go, cmd/cli/metrics_test.go, docs/content/docs/control_plane_health_probes.md
Show the OSM control plane version when osm mesh list
is run. This uses the OSM version label that is present
in all OSM resources.
This leverages the work previously done in PR #3068.
This resolves issue #2848.
- Does …
=> feat(cli): show osm version for osm mesh list

pkg/catalog/inbound_traffic_policies.go, pkg/catalog/inbound_traffic_policies_test.go
This change wildcards the path and/or method for a HTTPRouteGroup when
not specified. This is necessary to prevent an envoy configuration error
as described in issue #3128.
The mock blocks for all the unit tests in files related to this change
have been moved inside the loop to prevent the tests from being flaky.
Fixes : #3128 
- SMI Policy             [X]
- …
=> bugfix(pkg/catalog) : wildcard path and/or method in http route when not specified

pkg/catalog/inbound_traffic_policies.go, pkg/catalog/ingress.go, pkg/catalog/outbound_traffic_policies.go, pkg/envoy/rds/response.go, pkg/trafficpolicy/trafficpolicy.go, pkg/trafficpolicy/trafficpolicy_test.go
This commit allows partial hostname matches while merging both inbound
and outbound traffic policies. This change is necessary to support host
headers that users will specify as a part of the TrafficSpec and as this
will be a single host, so can only partially match to an existing
traffic policy and if that is the case the two policies should be
merged.
The commit also improves the logic of the 'subset` function in this
package. It checks is either slice is a subset of the other and returns a union of them
This is part of #2369
- …
=> feat(pkg/trafficpolicy) : updating merge logic for inbound and outbound traffic policies

cmd/osm-controller/osm-controller.go, pkg/catalog/catalog.go, pkg/catalog/debugger.go, pkg/catalog/debugger_test.go, pkg/catalog/mock_catalog_generated.go, pkg/catalog/types.go, pkg/debugger/mock_debugger_generated.go, pkg/debugger/proxy.go, pkg/debugger/server.go, pkg/debugger/server_test.go, pkg/debugger/types.go, pkg/envoy/ads/grpc.go, pkg/envoy/ads/response_test.go, pkg/envoy/ads/server.go, pkg/envoy/ads/stream.go, pkg/envoy/ads/types.go, pkg/envoy/registry/announcement_handlers.go, pkg/envoy/registry/announcement_handlers_test.go, pkg/envoy/registry/debugger.go, pkg/envoy/registry/debugger_test.go, pkg/envoy/registry/registry.go, pkg/envoy/registry/suite_test.go, pkg/envoy/registry/types.go
This change removes methods from the MeshCataloger interface pertaining
to tracking proxies as they connect and disconnect. The following
methods have been removed:
ExpectProxy(certificate.CommonName)
RegisterProxy(*envoy.Proxy)
UnregisterProxy(*envoy.Proxy)
The same functionality is now in a new package pkg/envoy/registry
encapsulated in a new `*ProxyRegistry` struct. No functional changes.
Fixes #3105, fixes #3106
- CI System …
=> ref(catalog): factor out proxy registry functionality

tests/framework/common_profile.go, tests/scale/osm_common_profile_resources.go, tests/scale/scale_trafficSplit_test.go
- Default error log level for scale tests to avoid
log burden on the nodes (specially for envoy)
- Store only logs for control plane on test exit
- Set 1G request/limits for OSM in scale-tests
- Verify restarts of control plane processes after
every test iteration.
X
=> e2e/scale: update test install values

docs/content/docs/tasks_usage/traffic_management/ingress.md
Documents the ingress path matching semantics.
Part of #2798 and #287
`No`
=> docs/ingress: document path matching semantics

pkg/envoy/ads/profile.go, pkg/envoy/ads/response.go, pkg/envoy/types.go
This PR refactors the `sendResponse` function.
Goals:
- make it easier to read and understand
- remove indentation levels
- remove single letter variables
- use concrete types instead of strings
- introduce new variables to capture state and improve readability (`fullUpdateRequested`, `thereWereErrors`)
- remove unnecessary `else` clauses
=> envoy: Refactor sendResponse to increase readability

pkg/catalog/mock_catalog_generated.go, pkg/catalog/outbound_traffic_policies.go, pkg/catalog/service.go, pkg/catalog/types.go
This PR changes [the **MeshCataloger** interface](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/catalog/types.go#L62-L132) by removing [GetServicesForServiceAccount ](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/catalog/types.go#L112) from it.
I see that we are not using `GetServicesForServiceAccount()` anywhere outside of `pkg/catalog`. It seems unnecessary to have this exposed via Interface to the rest of the world.  I propose we privatize [GetServicesForServiceAccount ](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/catalog/types.go#L112) and remove it from `MeshCataloger` interface.
=> catalog: Remove GetServicesForServiceAccount from MeshCataloger interface

pkg/catalog/endpoint.go, pkg/catalog/endpoint_test.go, pkg/catalog/mock_catalog_generated.go, pkg/catalog/types.go, pkg/envoy/eds/response_test.go
This PR changes [the **MeshCataloger** interface](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/catalog/types.go#L62-L132) by removing [ListEndpointsForService](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/catalog/types.go#L88) from the interface.
The [ListEndpointsForService](https://github.com/openservicemesh/osm/pull/3113/files#diff-36dbb2945d53716f02bbfd8723c99ead936d22ceca948cf619a6d5466cf40c98L9) function is not used anywhere outside of `pkg/catalog` and could be privatized.
=> catalog: Remove ListEndpointsForService from MeshCataloger interface

pkg/catalog/dispatcher.go
This PR removes a comment (seems unnecessary).
Also renames `castOk` to `ok` to make this more Go idiomatic. Also to correct `cast`, which is technically `type assertion`.
=> dispatcher: Remove unnecessary comment; rename variable for correctness

pkg/catalog/dispatcher.go
This PR removes an unnecessary `.String()`.
`AnnouncementType` implements Stringer, used by `%s` formatting.
=> dispatcher: Removing unnecessary .String()

docs/content/docs/application_health_probes.md
This change clarifies how OSM handles `exec` probes on Pods in a mesh
and when they are or are not expected to continue working.
No
=> docs(health): clarify exec probe behavior

pkg/identity/types.go, pkg/identity/types_test.go
This PR is the 1st part of:
- **Moving K8sServiceAccount from pkg/service to pkg/identity** #3152
This PR merely creates a copy of `K8sServiceAccount` from `pkg/service` to `pkg/identity`.
The goal is to alleviate the review load from #3152.
Next step: **Change import of K8sServiceAccount from pkg/service to pkg/identity** #3154
=> Copy K8sServiceAccount from pkg/service to pkg/identity

charts/osm/crds/meshconfig.yaml, go.mod, go.sum, pkg/announcements/types.go, pkg/apis/config/v1alpha1/mesh_config.go, pkg/configurator/crd_client.go, pkg/configurator/crd_client_test.go, pkg/configurator/types.go
Add informer for MeshConfig CRD. This is a prerequisite for migrating from configuration using configmap to CRD.
MeshConfig CRD informer is developed but not used in this PR. In consequent PRs, osm controller will start to a meshConfig client, and update service mesh config accordingly. 
Close #3038 
`No`
=> Mesh config informer

pkg/catalog/inbound_traffic_policies.go, pkg/catalog/inbound_traffic_policies_test.go, pkg/catalog/ingress.go, pkg/catalog/outbound_traffic_policies.go, pkg/catalog/outbound_traffic_policies_test.go, pkg/catalog/service.go, pkg/catalog/service_test.go, pkg/catalog/traffictarget.go, pkg/envoy/cds/response_test.go, pkg/envoy/lds/inmesh.go, pkg/envoy/lds/response.go, pkg/envoy/rds/response.go, pkg/envoy/route/route_config.go, pkg/envoy/sds/response.go, pkg/kubernetes/client_test.go, pkg/kubernetes/events/event_pubsub.go, pkg/strings/which.go, pkg/strings/which_test.go, pkg/tests/helpers.go, pkg/trafficpolicy/trafficpolicy.go, pkg/utils/grpc_test.go, pkg/utils/mtls_test.go, tests/e2e/e2e_trafficsplit_recursive_split.go, tests/e2e/e2e_trafficsplit_same_sa_test.go, tests/e2e/e2e_trafficsplit_test.go, tests/framework/common_metrics.go, tests/framework/common_profile.go, tests/framework/common_traffic.go, tests/scale/scale_trafficSplit_test.go
This PR replaces empty slice declaration using a nil slice declaration.
This does functionally change the code. These are not equivalent, however the second one seems to be subtly more efficient.
Found these using:
```bash
grep -Iir ":= \[\]" $(find . -name '*.go') | grep '\{\}'
```
---
Make it a guideline (so where possible) for OSM contributions to use a nil slice declaration.
So prefer `var x []string`, and not `x := []string{}`
=> [RFC] Replacing empty slice literals with nil slice declarations

pkg/catalog/xds_certificates_test.go, pkg/endpoint/providers/kube/client.go, pkg/endpoint/providers/kube/fake.go, pkg/envoy/ads/response.go, pkg/envoy/ads/secrets_test.go, pkg/envoy/eds/cluster_load_assignment.go, pkg/envoy/rds/response.go, pkg/envoy/sds/response_test.go, pkg/kubernetes/util.go, pkg/utils/grpc.go, tests/framework/common_apps.go
This PR removes `.String()` for variables that implement stringer and are used in formatted strings.
I used this to find these:
```bash
grep -Iir ".String()" $(find . -name '*.go') | grep '\%s' | awk -F':' '{print $1}' | sort | uniq
```
=> Removing unnecessary .String()

charts/osm/crds/meshconfig.yaml
The MeshConfig CRD applies to a control plane
instance running in a given namespace. The CRD
needs to be scoped to a namespace so that multiple
meshes (control plane instances) can each have
their own config CRD.
Not scoping the CRD will also result in client-go
returning meshconfig resources with an empty namespace,
which will break checks in the control plane that
check for the object's namespace to match.
- Tests …
=> charts/crd: fix scope of meshconfig CRD

pkg/smi/client.go, pkg/smi/types.go
Un-exports the SMI client type that implements
the MeshCataloger interface.
`No`
=> smi/client: un-export internal pkg type

pkg/smi/client.go, pkg/smi/types.go
The logger logs the component `smi-mesh-spec` in this case
for logs emitted by this package. The prefixing of log
messages removed in this change predates the usage of
the logger currently being used. The additional prefix
is not required and is also inconsistent with existing
log messages.
Also tweaks the log message.
- Performance …
=> smi/client: remove unnecessary prefix in log message

DESIGN.md, docs/content/docs/design_concepts/interfaces.md, pkg/catalog/mock_catalog_generated.go, pkg/catalog/traffictarget.go, pkg/catalog/traffictarget_test.go, pkg/catalog/types.go, pkg/envoy/sds/response.go, pkg/envoy/sds/response_test.go
This PR renames ` ListAllowedInboundServiceAccounts` to `ListAllowedInboundServiceIdentities`
The type changes will arrive with another PR.
---
This is one of the few steps towards addressing: **Use ServiceIdentity type in catalog APIs instead of service.K8sServiceAccount** #2218
---
This is a small chunk from #3170 
---
=> catalog: Rename ListAllowedInboundServiceAccounts to ListAllowedInboundServiceIdentities

pkg/envoy/ads/jobs.go, pkg/envoy/ads/response.go, pkg/envoy/ads/response_test.go, pkg/envoy/ads/stream.go, pkg/workerpool/workerpool.go, pkg/workerpool/workerpool_test.go
This PR tackles converts `sendResponse` to a variadic function.
This removes the need to pass a `mapset` then iterate over a list while checking against the existence of an item in the map to ensure order.
Also in this PR:
- change to `WorkerPool.AddJob()` to return the `done` channel of the job
- for the previous point - added a `GetDoneCh() <-chan struct{}` to the `Job` interface.
- removed unused `ADSUpdateStr`
- renamed a few variables colliding with imported packages
- fixed a few typos
Goal of this PR is to simplify and make the code easier to understand.
This will fix #3127
=> ads: Convert sendResponse to a variadic function; Simplify job dispatch

DESIGN.md, docs/content/docs/design_concepts/interfaces.md, pkg/catalog/fake.go, pkg/catalog/mock_catalog_generated.go, pkg/catalog/service.go, pkg/catalog/service_test.go, pkg/catalog/types.go, pkg/envoy/sds/response.go, pkg/envoy/sds/response_test.go, pkg/kubernetes/client.go, pkg/kubernetes/client_test.go, pkg/kubernetes/mock_controller_generated.go, pkg/kubernetes/types.go
This PR renames `ListServiceAccountsForService` to `ListServiceIdentitiesForService`
The type changes will arrive with another PR.
---
This is one of the few steps towards addressing: **Use ServiceIdentity type in catalog APIs instead of service.K8sServiceAccount** #2218
---
This is a small chunk from #3170 
---
=> catalog: Rename ListServiceAccountsForService to ListServiceIdentitiesForService

pkg/identity/errors.go, pkg/identity/suite_test.go, pkg/identity/types.go, pkg/identity/types_test.go
This PR introduces a few (not yet used) functions to help with the transition from `K8sServiceAccount` to `ServiceIdentity` (#2218)
- `ServiceIdentity{}.ToK8sServiceAccount()` converts a `ServiceIdentity` to a `K8sServiceAccount` - examples of how this will be used are here #3170
- `K8sServiceAccount{}.ToServiceIdentity()` converts a `K8sServiceAccount` to a `ServiceIdentity` - examples are also in #3170
- `ServiceIdentity{}.GetSDSCSecretName()` needed to create the string keys used as names for SDS Certs / Secrets - this is going to be used instead of `K8sServiceAccount{}.String()`
---
The type changes will arrive with another PR.
---
This is one of the few steps towards addressing: **Use ServiceIdentity type in catalog APIs instead of …
=> identity: Adding K8sServiceAccount.ToServiceIdentity() and ServiceIdentity.ToK8sServiceAccount()

DESIGN.md, docs/content/docs/design_concepts/interfaces.md, pkg/catalog/endpoint.go, pkg/catalog/mock_catalog_generated.go, pkg/catalog/traffictarget.go, pkg/catalog/traffictarget_test.go, pkg/catalog/types.go, pkg/envoy/eds/response_test.go
This PR renames `ListAllowedOutboundServiceAccounts ` to `ListAllowedOutboundServiceIdentities`
The type changes will arrive with another PR.
---
This is one of the few steps towards addressing: **Use ServiceIdentity type in catalog APIs instead of service.K8sServiceAccount** #2218
---
This is a small chunk from #3170 
---
=> catalog: Rename ListAllowedOutboundServiceAccounts to ListAllowedOutboundServiceIdentities

charts/osm/README.md, charts/osm/templates/prometheus-deployment.yaml, charts/osm/values.yaml
This commit adds prometheus resource configurability through
`values.yaml`.
Based on https://github.com/eduser25/osm/actions/runs/720587234:
- Bumped requested Mem to 512M, which is the highest of the lowest we can go with
(should support up to 100pods consistently without having prom get killed if the node under
memory pressure form other pods).
- Also adjusted CPU requested. 100m is too low for even 100 pods.
Half vcpu should be a more solid value to consistently support the values we advertise.
- Metrics                [x]
No
=> prometheus: add deployment resource values to values.yaml
