pkg/envoy/proxy.go
Since a `NewProxy` returns a pointed struct, and in all our
codebase the proxy is used through pointer, consolidate
the API/functions provided by by the proxy package to use
pointer to `self`.
This avoids object copy in functions that were using
passed by value `self`. This seems more appropriate
given the way we use the class.
No
=> proxy: consolidate proxy functions to use `self` pointer

cmd/cli/dashboard.go, cmd/cli/install.go, cmd/cli/mesh_upgrade.go, cmd/cli/proxy_get.go, cmd/cli/proxy_get_test.go, cmd/cli/trafficpolicy_check.go, cmd/cli/uninstall.go, cmd/cli/uninstall_test.go, cmd/cli/util.go, cmd/cli/util_test.go
Adds annotated diagnostic and error messages for various
commands. These annotations print the OSM namespace
and mesh name, which improves the CLI UX. Fixes #2455.
Adds annotated diagnostic and error messages for various
commands. These annotations print the OSM namespace
and mesh name, which improves the CLI UX. Fixes #2455.
- …
=> fix(cli): print namespace and mesh for commands

pkg/service/service.go, pkg/service/types.go, pkg/service/types_test.go
This PR:
- moves the location of `MeshService` `String()` from `pkg/service/service.go` to `pkg/service/types.go` -- to be close to the `MeshService{}` definition
- also changes the implementation of the `MeshService` stringer interface -- preserves the output
=> Moving the location of MeshService.String()

tests/e2e/e2e_metrics_test.go
Commit 491e6e77 updated the CPU request for the prometheus
deployment which results in insufficient CPU issues in the CI,
causing this test to consistently fail.
This change temporarily disables this test till issue #3199
is correctly resolved - either with increased CPU availability
or some other mechanism to ensure this test passes in the CI.
Temporarily unblocks CI failures due to #3199 …
=> tests/e2e: disable test to unblock CI

tests/e2e/e2e_metrics_test.go, tests/e2e/e2e_upgrade_test.go
CI is failing due to low resorce provision on CI.
Making sure limits are set to allow Prometheus to run
in restricted resource environments.
- CI System              [x]
No
=> e2e: Fix resource consumption of Prometheus

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go, docs/content/docs/install/manual_demo/_index.md, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml
This PR cuts release v0.8.3 
[X] I have cherry-picked any changes
=> chore(release) : cutting release v0.8.3

pkg/apis/policy/v1alpha1/egress.go, pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
Adds an optional `ipAddresses` field to the egress API to specify
a list of IP ranges the egress policy applies to. This is specifically
required when more than 1 external TCP endpoints use the same port
because just port alone will not be sufficient to route traffic
differently for the different endpoints.
Part of #3045  …
=> egress/api: add ipAddresses field to match TCP based traffic

demo/README.md
Clarifies the need to update `CTR_REGISTRY` in the `.env` environment
variable file when using a remote Kubernetes cluster for the OSM
automated demo. …
=> docs(demo): add line to OSM automated demo docs

pkg/envoy/ads/stream.go, pkg/envoy/proxy.go, pkg/envoy/types.go
Commit addresses nonce handling mostly. It adds resource subscription/checking on OSM's side, and improves handling of some other nonce situations.
- Adds resource comparison and checks, when a request is seen and nonce ACKs last version, a comparison to make sure resources ACKd by envoy are the same as the ones we sent is put in place.
Now will do resource comparison when no-error and nonce is matched.
- Force update when no nonce is seen on message such as uninitialized nonce (first message on stream guaranteed). This is mostly wildcard situation, as LDS/CDS will wildcard the request on the first one. These first requests come with no acknowledged nonce.
- Also moves some code in `ads/response.go` to avoid storing new nonce/version/resources until
send has succeeded; a failed `Send` …
=> xDS: address some xDS issues

charts/osm/crds/policy.yaml
Adds the CRD for egresses.policy.openservicemesh.io
API.
Part of #3045
`No`
=> charts/crds: add CRD for egress policy API

charts/osm/crds/meshconfig.yaml, pkg/apis/config/v1alpha1/mesh_config.go, pkg/configurator/crd_client.go, pkg/configurator/crd_client_test.go
change MeshConfig CRD fields to camelCase naming convention
Change MeshConfig CRD fields to camelCase naming convention.
In Kubernetes the CRD fields uses camelCase for naming. …
=> style(crd): change MeshConfig fields to camelCase

pkg/envoy/sds/errors.go, pkg/envoy/sds/response.go, pkg/envoy/sds/response_test.go
This PR factors out a new function called `getServiceIdentitiesFromCert()`.
This, I believe shows clearly the purpose of it - to compute the Subject Alt Names for the `MatchSubjectAltNames` Envoy config.
I think the purpose of this block of code, prior to this PR, is lost in the sheer volume of code.
---
In this PR:
- carved out a block of code into `getServiceIdentitiesFromCert()`
- no functional code changes
- removed `switch / case` -- using `if / return` instead - for simplicity (fewer indentations)
- renamed `errGotUnexpectedCertRequest` to `errCertMismatch` for clarity
- renamed `getSubjectAltNamesFromSvcAccount` to `getSubjectAltNamesFromSvcIdentities` for correctness
=> sds: Factor out new function getServiceIdentitiesFromCert()

pkg/envoy/route/route_config.go, pkg/envoy/route/route_config_test.go, tests/scenarios/traffic_split_with_apex_service_test.go
LDS refers to `rds-inbound` whenever a pod is backed by a service,
however RDS does not necessarily send `rds-inbound` unless there is
inbound routes for the proxy.
The net result is things work, but envoy will still perpetually try to request
`rds-inbound` as it will be kept referenced on LDS (now that we handle proto
resource diffs, this is a problem).
This change makes `rds-inbound` and `rds-outbound` to always be sent, even
when there are no routes in them. If envoy does not request for one or either of them,
they will just be ignored, but otherwise this is a guarantee to be consistent with a potential
LDS reference, when present. …
=> ads/rds: send always inbound/outbound resources

DESIGN.md, docs/content/docs/design_concepts/interfaces.md, pkg/catalog/mock_catalog_generated.go, pkg/catalog/types.go, pkg/catalog/xds_certificates.go, pkg/catalog/xds_certificates_test.go, pkg/envoy/ads/secrets_test.go, pkg/envoy/cds/response.go, pkg/envoy/cds/response_test.go, pkg/envoy/lds/response.go, pkg/envoy/rds/response.go, pkg/envoy/rds/response_test.go, tests/scenarios/traffic_split_with_zero_weight_test.go
Renames GetServicesFromEnvoyCertificate to GetServicesForProxy to
increase readability and updates the parameter type from
certificate.CommmonName to *envoy.Proxy. Resolves #3117. …
=> ref(pkg/*): rename GetServicesFromEnvoyCertificate

pkg/smi/client.go
Logs a warning if a requested resource via a `Get` API
call is found but does not belong to a monitored namespace.
- SMI Policy             [X] …
=> smi/client: warn if requested resource is not monitored

demo/cmd/common/books.go, demo/deploy-bookwarehouse.sh, pkg/catalog/inbound_traffic_policies.go, pkg/catalog/inbound_traffic_policies_test.go, pkg/catalog/outbound_traffic_policies.go, pkg/catalog/outbound_traffic_policies_test.go, pkg/catalog/service.go, pkg/envoy/route/route_config.go, pkg/envoy/route/route_config_test.go, pkg/tests/fixtures.go, pkg/trafficpolicy/trafficpolicy.go, pkg/trafficpolicy/trafficpolicy_test.go
This commit adds new inbound and outbound traffic policies if host
header is provided in the route.
Sample configuration on envoy where the host header is re-written for bookwarehouse based on traffic spec : https://github.com/openservicemesh/osm/blob/77826735a5c6b125f7942092d96c96e6e60b26c1/demo/deploy-traffic-specs.sh#L48
Note: This feature is currently only supported for host headers with host names belonging to k8s services due to #3150 
Part of  #2369
- SMI Policy …
=> feat(routes) : configure inbound and outbound routes with host headers

cmd/cli/mesh_list.go, cmd/osm-controller/osm-controller.go, docs/content/docs/control_plane_health_probes.md, pkg/constants/constants.go, pkg/smi/client.go, pkg/smi/client_test.go
Adds supported smi version info in the output
of `osm mesh list`. Also adds a supported http
endpoint in the osm controller (/smi/version)
that returns a JSON reponse containing supported
smi versions.
Resolves #2849. …
=> feat(cli): show supported smi for osm mesh list

charts/osm/templates/osm-rbac.yaml
Fixes #3230
Adds hostaccess SCC when fluentbit is deployed on OpenShift so that osm-controller can be scheduled without manually adding the scc. …
=> fix(install): Adds hostaccess SCC when fluentbit is enabled on OpenShift

docs/content/docs/install/manual_demo/_index.md
This PR inlines the deployment YAMLs in lieu of using kubectl to a URL.
This PR is a chunk from #2845
This is similar to:  **docs: Inline TrafficSplit in Manual Demo** #3224
=> docs: Inline Deployments for Manual Demo

charts/osm/crds/meshconfig.yaml, charts/osm/templates/osm-configmap.yaml, charts/osm/templates/osm-injector-deployment.yaml, cmd/cli/mesh_upgrade.go, cmd/cli/mesh_upgrade_test.go, cmd/osm-injector/osm-injector.go, docs/content/docs/osm_config_map.md, pkg/apis/config/v1alpha1/mesh_config.go, pkg/configurator/client.go, pkg/configurator/client_test.go, pkg/configurator/crd_client.go, pkg/configurator/crd_client_test.go, pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/configurator/mock_client_generated.go, pkg/configurator/types.go, pkg/configurator/validating_webhook.go, pkg/configurator/validating_webhook_test.go, pkg/constants/constants.go, pkg/injector/envoy_config_test.go, pkg/injector/envoy_container.go, pkg/injector/patch.go, pkg/injector/patch_test.go, pkg/injector/types.go, pkg/injector/webhook_test.go
Moves the envoy proxy image information from the osm-injector
deployment to OSM's ConfigMap. This change allows the image to be
patched without having to patch the osm-injector deployment. 
Resolves #3135.
- Install                [ X ]
- Does this change contain code from or inspired by another project? …
=> ref(pkg/*): move envoy proxy image to OSM's ConfigMap

charts/osm/templates/osm-rbac.yaml, cmd/osm-controller/osm-controller.go, mockspec/rules, pkg/catalog/catalog.go, pkg/catalog/dispatcher.go, pkg/catalog/egress.go, pkg/catalog/fake.go, pkg/catalog/helpers_test.go, pkg/catalog/mock_catalog_generated.go, pkg/catalog/types.go, pkg/trafficpolicy/egress_types.go
This change does the following:
- Starts the k8s controller for the policy API
- Initializes catalog with the policy controller
- Adds the egress trafficpolicy types
- Adds an API in catalog to retrieve egress policy
for the given source identity (implementation
is stubbed out to be added in a subsequent PR).
Next steps:
- Implement the API in catalog (replace stub)
- Envoy XDS changes (LDS, RDS, CDS etc.)
Part of #3045
- Security               [ …
=> egress/v1alpha1: add types and API stub in catalog

README.md, docs/content/_index.md, docs/content/docs/install/_index.md, docs/demos/first_steps.md
OSM support k8s versions >= 1.18.0, as specified
by `kubeVersion` in `charts/osm/Chart.yaml`.
`No`
=> docs: correct minimum supported k8s version

docs/content/docs/install/manual_demo/_index.md
This PR changes the Manual Demo doc and expands a few `kubectl` commands to fetch more resources (Deployments, Pods, Endpoints etc.) and focuses on specific namespaces instead of `--all-namespaces`
---
This PR is a chunk from #2845
=> docs: Verbose kubectl commands to get k8s deployments etc for Manual Demo

docs/content/docs/install/manual_demo/_index.md
This PR is a chunk of #2845.
This inlines the TrafficTarget YAML needed to be applied for the Manual Bookbuyer/Bookstore demo in lieu of kubectl applying URLs.
This, I believe, shows immediately what the YAML is going to be, without the need to click and navigate to other pages.
Also - this guarantees that the YAML is relevant to that particular version of the doc (release-v0.8 as of this PR).
=> docs: Inline TrafficSplit in Manual Demo

charts/osm/README.md, charts/osm/crds/meshconfig.yaml, charts/osm/templates/osm-configmap.yaml, charts/osm/values.yaml, cmd/cli/mesh_upgrade.go, cmd/cli/mesh_upgrade_test.go, docs/content/docs/osm_config_map.md, docs/content/docs/tasks_usage/traffic_management/iptables_redirection.md, docs/content/docs/troubleshooting/traffic/iptables_redirection.md, pkg/apis/config/v1alpha1/mesh_config.go, pkg/apis/config/v1alpha1/zz_generated.deepcopy.go, pkg/configurator/client.go, pkg/configurator/client_test.go, pkg/configurator/crd_client.go, pkg/configurator/crd_client_test.go, pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/configurator/mock_client_generated.go, pkg/configurator/types.go, pkg/configurator/validating_webhook.go, pkg/configurator/validating_webhook_test.go, pkg/injector/init_container.go, pkg/injector/init_container_test.go, pkg/injector/iptables.go, pkg/injector/patch.go, pkg/injector/patch_test.go
This PR adds support for global outbound port exclusion via the
configmap and meshconfig in osm.
Fixes #3249 …
=> feat(portExclusion): adding outbound port exclusion list to osm

pkg/catalog/egress.go, pkg/catalog/egress_test.go, pkg/trafficpolicy/egress_types.go
Implements the API in MeshCataloger to retrieve
the egress traffic policy for the given source
identity.
Updates the `AllowedDestinationIPRanges` type to
a slice for convenience. The catalog API guarantees
there will be no duplicates.
Next steps:
- Integrate API with XDS verticals
Part of #3045 …
=> egress/catalog: implement egress traffic policy

pkg/envoy/ads/response.go, pkg/envoy/ads/stream.go, pkg/envoy/types.go
- Renames `Wildcard` to `EmptyURI` to avoid naming overlap with xDS
"wildcard" mode for a given URI.
- Avoid handling Empty URI as some of the logic needs some work for
it to be properly handled.
We will revisit this after further exploration.
Fixes #3258
No
=> ads: do not handle empty URI

pkg/envoy/cds/cluster.go, pkg/envoy/cds/cluster_test.go, pkg/envoy/cds/response.go, pkg/envoy/cds/response_test.go
Builds egress clusters based on the given cluster configs.
HTTP based external clusters are resolved using DNS to
prevent malicious clients from pretending to access
the allowed host by setting the :host header in the
HTTP request while connecting to a different IP address
not associated with the actual host.
Part of #3045 …
=> envoy/cds: build clusters based on egress cluster configs

pkg/envoy/route/route_config.go, pkg/envoy/route/route_config_test.go
Un-exports variables used within the package scope.
`No`
=> envoy/route: un-export package local variables

demo/cmd/common/books.go, pkg/envoy/route/route_config.go, pkg/envoy/route/route_config_test.go
This commit removed host rewite and adds a header match when host header
is provided via SMI
Fixes #3283 …
=> fix(hostHeaders) : updating host headers configuration on envoy

cmd/cli/install.go, cmd/cli/install_test.go, cmd/cli/mesh_upgrade.go, cmd/cli/mesh_upgrade_test.go, demo/run-osm-demo.sh, docs/content/docs/install/manual_demo/_index.md, docs/content/docs/tasks_usage/certificates.md, docs/content/docs/tasks_usage/logs.md, docs/content/docs/tasks_usage/metrics.md, docs/content/docs/tasks_usage/onboard_services.md, docs/content/docs/tasks_usage/tracing.md, docs/content/docs/tasks_usage/traffic_management/egress.md, docs/content/docs/tasks_usage/traffic_management/iptables_redirection.md, docs/content/docs/tasks_usage/traffic_management/permissive_traffic_policy_mode.md, docs/content/docs/troubleshooting/observability/grafana.md, docs/content/docs/troubleshooting/observability/prometheus.md, docs/wip/demo_prometheus.md, tests/framework/common.go
Remove install command CLI flags in favor of using --set flag for overriding helm chart values and update docs referring to osm install cmd.
Reference: #3124
Signed-off-by: Cizer Pereira <mail@cizer.dev>
As mentioned in #3124, if this PR merges - it will remove install cmd flags used specifically to override the default chart values defined in `charts/osm/values.yaml`, in favor of using the `--set` flag.
Removes few flag validation from `install.go` for instance validation of envoy and controller log level type.( which is already implemented using JSON schema(`values.schema.json`) validation)
- Certificate …
=> feat(cli/install): remove install cmd cli flags

tests/framework/common.go
Commit bff18e72 introduced a regression in the test
by using an incorrect name for the chart param.
`No`
=> tests: fix fluent bit deployment flag

pkg/envoy/rds/response.go, pkg/envoy/rds/response_test.go, pkg/envoy/route/route_config.go, pkg/envoy/route/route_config_test.go, tests/scenarios/traffic_split_with_zero_weight_test.go
This change builds the RDS route configs for HTTP egress
routing rules.
Part of #3045
`No`
=> envoy/rds|route: build egress route config based on policies

docs/content/docs/tasks_usage/traffic_management/iptables_redirection.md, docs/content/docs/troubleshooting/traffic/iptables_redirection.md, pkg/injector/patch.go, pkg/injector/patch_test.go, pkg/injector/webhook.go, pkg/injector/webhook_test.go, tests/e2e/README.md, tests/e2e/e2e_port_exclusion_test.go
This commit adds support for a pod level annotation, that allows ports
mentioned as a part of this annotation to be excluded from proxy
redirection.
Fixes #3251
Signed-off-by: Sneha Chhabria snchh@microsoft.com …
=> feat(podLevelPortExclusion): Add outbound port exclusion list at pod level

Makefile
Currently, if building a docker image through the Makefile fails but
pushing succeeds, then the Makefile will still exit with a success error
code. In the demo script, this leads to silent failures. This change
makes the Makefile fail the `docker-push*` targets when its
corresponding `docker-build*` fails. …
=> fix(build): fail Makefile docker-push targets when build fails

charts/osm/crds/policy.yaml, go.mod, go.sum, pkg/catalog/egress.go, pkg/catalog/egress_test.go, pkg/constants/constants.go, pkg/trafficpolicy/egress_types.go, pkg/trafficpolicy/trafficpolicy.go, pkg/trafficpolicy/trafficpolicy_test.go
The current implementation of the egress policy API
only supports building HTTP based configs. This change
extends the API and code to build configs for TCP
and HTTPS egress destinations.
Notable changes:
- hosts is optional for TCP
- ipAddresses is optional for HTTP
- MeshCataloger builds configs for TCP, HTTPS ports
- Deduplication helpers for TrafficMatch and
EgressClusterConfig types
Part of #3045
- Demo …
=> egress: extend API for TCP and HTTPS traffic

charts/osm/crds/meshconfig.yaml
Fix type definition of outboundPortExclusionList field in MeshConfig.
It should be an array of strings.
This PR fixes the test below:
```
Unexpected error: 
827 <*errors.errorString | 0xc0015ccaa0>: { 
828 s: "UpdateOSMConfig(): MeshConfig.config.openservicemesh.io \"osm-mesh-config\" is invalid: spec.traffic.outboundPortExclusionList: Invalid value: \"string\": spec.traffic.outboundPortExclusionList in body must be of type integer: \"string\"", 
829 } 
830 UpdateOSMConfig(): MeshConfig.config.openservicemesh.io "osm-mesh-config" is invalid: spec.traffic.outboundPortExclusionList: Invalid value: "string": spec.traffic.outboundPortExclusionList in body must be of type integer: "string" 
831 occurred 
832 
833 /home/runner/work/osm/osm/tests/e2e/e2e_port_exclusion_test.go:70 …
```
=> fix(test): fix type definition of outboundPortExclusionList

pkg/envoy/cds/cluster.go, pkg/envoy/cds/cluster_test.go, pkg/envoy/cds/response.go
- Adds capability for TCP based egress cluster configs,
ie. configs without the HTTP Host set.
- Consolidates duplicate code for the original destination
cluster type.
- Un-exports pkg scoped function
Part of #3045 …
=> envoy/cds: support TCP based egress clusters

cmd/cli/mesh_list_test.go, cmd/cli/namespace_add.go, cmd/cli/namespace_test.go, cmd/cli/util_test.go
The command osm namespace add should check if
the mesh exists before adding the namespace.
Otherwise the user may be mislead into thinking
that the namespace is part of a mesh despite
forgetting to run the install command.
Resolves #2494
- …
=> fix(cli): check mesh exists before namespace add

charts/osm/README.md, charts/osm/templates/cleanup-hook-rbac.yaml, charts/osm/templates/grafana-deployment.yaml, charts/osm/templates/grafana-rbac.yaml, charts/osm/templates/osm-deployment.yaml, charts/osm/templates/osm-injector-deployment.yaml, charts/osm/templates/osm-rbac.yaml, charts/osm/templates/prometheus-deployment.yaml, charts/osm/templates/prometheus-rbac.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, docs/content/docs/install/_index.md
Adds PSPs for existing RBACs (prometheus, grafana, osm, clean up job). This allows the chart to be installed and uninstalled in PSP enabled clusters.
Fluentbit and Jaeger to follow.
Fixes #1941 …
=> OSM PodSecurityPolicy

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml
This commit updates version and reference numbers to v0.8.4-rc.1.
2. Updated the chart **and** app version in charts/osm/Charts.yaml
4. Updated the image tags used in demo manifests
5. Regenerated Helm chart README.md
yes
=> chore(release): Creating release v0.8.4-rc.1

Makefile, docs/content/docs/dev_guide/_index.md
Some things that were not obvious to me while building the project on an Ubuntu machine.
1. Since https://github.com/openservicemesh/osm/pull/2389, the required version of is 1.16.7 so I explicitly state it in the docs.
2. The `MAKEFILE` error message in `check-go-version` did not work for me with error `@echo command not found `. I think that the extra `@` is not needed since the command is just a one liner.
3. Document that Docker is a dependency to build the project.
- Metrics                [ …
=> Updates docs regarding golang usage and deps

pkg/endpoint/providers/kube/client.go, pkg/endpoint/providers/kube/client_test.go
This commit fixes a bug in the method GetResolvableEndpointsForService.
It returns the service endpoints when the clusterIP is set to none …
=> fix(pkg/endpoint/providers/kube): fix GetResolvableEndpointsForService

pkg/catalog/egress.go, pkg/constants/constants.go, pkg/envoy/lds/egress.go, pkg/envoy/lds/listener.go, pkg/envoy/lds/listener_test.go
This change adds support to enable egress for server-first
protocols such as MySQL, PostgreSQL etc. by bypassing the
listener filters that wait on client data,  which would
otherwise time out for such protocols.
An egress policy for TCP based server-first protocols must
set the protocol to `tcp-server-first` to indicate that
protocol detection must be skipped for such a port.
Verified this change with mySQL based egress and confirmed
that such traffic no longer times out the listener filter
that wait on data from the client.
Part of #3045
- Certificate …
=> egress: add support for server-first TCP protocols

pkg/configurator/client.go, pkg/configurator/client_test.go, pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/configurator/mock_client_generated.go, pkg/configurator/types.go, pkg/injector/envoy_config_test.go, pkg/injector/envoy_container.go, pkg/injector/patch_test.go, tests/e2e/e2e_proxy_resource_limits.go
Uses the available, recently introduced configuration options in MeshConfig to configure
proxy resources `requests` and `limits`.
- Includes various unit tests on related packages for relevant functions
- Includes an e2e test
- New Functionality      [x]
No
=> feat(proxyResLimits): Add proxy resource configuration through MeshConfig

charts/osm/crds/meshconfig.yaml, charts/osm/crds/policy.yaml
Uses a min-max validation for port ranges instead of regex.
`No`
=> charts/crds: use min-max port range validation instead of regex

charts/osm/README.md, charts/osm/crds/meshconfig.yaml, charts/osm/templates/preset-mesh-config.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, cmd/init-osm-controller/init-osm-controller.go, cmd/init-osm-controller/init-osm-controller_test.go, docs/example/manifests/mesh-config.yaml, tests/e2e/e2e_debug_server_test.go, tests/e2e/e2e_egress_test.go, tests/e2e/e2e_init_controller_test.go, tests/e2e/e2e_ip_exclusion_test.go, tests/e2e/e2e_permissive_test.go, tests/e2e/e2e_tcp_client_server_test.go, tests/e2e/e2e_tcp_egress_test.go, tests/framework/common.go
This PR creates a MeshConfig resource `preset-mesh-config` using Helm. The init-osm-controller container will check for this resource and create the `osm-mesh-config` MeshConfig if it does not exist.
This change is necessary as we need to support setting mesh configurations from CLI during installation, which was removed when migrating from osm-config configmap to MeshConfig CRD  PR #3276 
As there is logic that ensures MeshConfig is updated from the preset only if it doesn't exit, the config values that a user applies will persist through upgrades. There will be no custom logic needed to retain them in upgrades, there will be a follow up PR to delete upgrade code that depends on configmap (redundant now) .
Fixes #3301
Part of #3039 
Signed-off-by: Sneha Chhabria …
=> feat(meshConfigCRD): Retain install configurability

charts/osm/crds/policy.yaml
The Egress policy API allows specifying object
references as matches, enable this in the CRD
definition since the code supports it.
Part of #3045 …
=> charts/crds: allow object references as matches

cmd/cli/mesh_upgrade.go, cmd/cli/mesh_upgrade_test.go, demo/README.md, demo/join-namespaces.sh, demo/unjoin-namespaces.sh
The commit removed dpependency on configuration updates from osm on the
mesh upgrade cli, as configmap has been replaced by meshConfig.
Configuration changes to meshConfig will persist across upgrades as this
resource is no longer managed my Helm.
Fixes #3212
Part of #3040 …
=> MeshConfig: Decouple mesh upgrade from updating configmap

charts/osm/templates/cleanup-hook-rbac.yaml, charts/osm/templates/osm-rbac.yaml
The PR adds rbac to delete meshconfig resources in osm, while using the helm cleanup hooks. This was causing issues in the CI
Signed-off-by: Sneha Chhabria snchh@microsoft.com
| Upgrade                    | [ …
=> fix(MeshConfig): adding rbac for deleting meshConfig

.github/workflows/main.yml, tests/e2e/README.md, tests/e2e/e2e_certmanager_test.go, tests/e2e/e2e_debug_server_test.go, tests/e2e/e2e_egress_test.go, tests/e2e/e2e_fluentbit_deployment_test.go, tests/e2e/e2e_fluentbit_output_test.go, tests/e2e/e2e_grpc_insecure_origination_test.go, tests/e2e/e2e_hashivault_test.go, tests/e2e/e2e_health_probe_test.go, tests/e2e/e2e_helm_install_test.go, tests/e2e/e2e_http_ingress_test.go, tests/e2e/e2e_init_controller_test.go, tests/e2e/e2e_ip_exclusion_test.go, tests/e2e/e2e_k8s_version_test.go, tests/e2e/e2e_metrics_test.go, tests/e2e/e2e_multiple_services_per_pod_test.go, tests/e2e/e2e_permissive_test.go, tests/e2e/e2e_pod_client_server_test.go, tests/e2e/e2e_port_exclusion_test.go, tests/e2e/e2e_proxy_resource_limits.go, tests/e2e/e2e_smi_traffic_target_test.go, tests/e2e/e2e_tcp_client_server_test.go, tests/e2e/e2e_tcp_egress_test.go, tests/e2e/e2e_trafficsplit_recursive_split.go, tests/e2e/e2e_trafficsplit_same_sa_test.go, tests/e2e/e2e_trafficsplit_test.go, tests/e2e/e2e_upgrade_test.go
Runs the entire suite of e2e tests pre-merge. Increases
the number of buckets to keep the suite duration reasonable.
Also removes the test table from the readme since this gets 
stale pretty fast. Tests can be easily found by inspecting
the test directory.
=> e2e: run all tests before merge

charts/osm/README.md, charts/osm/crds/meshconfig.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, cmd/init-osm-controller/init-osm-controller_test.go, docs/example/manifests/meshconfig/mesh-config.yaml, pkg/configurator/methods_test.go, pkg/configurator/validating_webhook_test.go, pkg/constants/constants.go
See #3343
Updates OSM to user Envoy version 1.18.3.
I will do a follow up PR to change the generated config to use some newer features.
I validated through `./demo/run-osm-demo.sh` and `./bin/osm proxy get config_dump bookbuyer-85d5c5f4f4-l7bgs -n bookbuyer > envoy-new.json`
```
"node": {
"hidden_envoy_deprecated_build_version": "98c1c9e9a40804b93b074badad1cdf284b47d58b/1.18.3/Clean/RELEASE/BoringSSL",
"user_agent_name": "envoy",
"user_agent_build_version": {
"version": {
"major_number": 1,
"minor_number": 18,
"patch": 3
},
"metadata": {
"revision.sha": "98c1c9e9a40804b93b074badad1cdf284b47d58b",
"build.type": "RELEASE",
"revision.status": "Clean",
"ssl.version": "BoringSSL"
}
```
- New …
=> update envoy to 1.18.3

cmd/osm-controller/osm-controller.go, pkg/kubernetes/announcement_handlers.go, tests/e2e/e2e_garbage_collector_test.go, tests/framework/common.go
Creates a handler that subscribes to the PodAdded announcement.
When a pod is added to a namespace that is observed by the OSM
service mesh, the OwnerReference of the envoy bootstrap config
secret mounted to the pod is set to reference the pod. When the
pod terminates, the Kubernetes garbage collector will delete the
secret since its owner no longer exists. This change will prevent
the persistence of unused Kubernetes secrets.
Resolves #2795 
- New Functionality      [ X ]
- Control Plane          [ X ]
- Tests …
=> feat(*): garbage collector for OSM pod secrets

docs/example/manifests/opa/deploy-opa-envoy.yaml, pkg/auth/types.go, pkg/configurator/client.go, pkg/configurator/client_test.go, pkg/configurator/methods.go, pkg/configurator/mock_client_generated.go, pkg/configurator/types.go, pkg/envoy/ads/response_test.go, pkg/envoy/lds/auth.go, pkg/envoy/lds/connection_manager.go, pkg/envoy/lds/ingress.go, pkg/envoy/lds/ingress_test.go, pkg/envoy/lds/inmesh.go, pkg/envoy/lds/inmesh_test.go, pkg/envoy/lds/listener_test.go, pkg/envoy/lds/response_test.go
Commit adds external authorization.
Current version of the feature allows configuring external authorization
through MeshConfig's `inboundExternalAuthorization`.
When `enabled`, external authorization is enforced for all inbound and
ingress for all pods in the mesh.
patchset[1]:
- moved auth-only configuration definition to standalone `auth` package.
- Moved doc out, will push to osm-docs.
- s/incoming/inbound s/outgoing/outbound
no
no
=> feat(extAuthz): Add inbound external authorization

cmd/cli/mesh_list.go, cmd/cli/mesh_list_test.go, cmd/cli/uninstall.go, cmd/cli/uninstall_test.go, cmd/cli/util.go, cmd/cli/util_test.go
The current `osm uninstall` experience is
ambiguous as to which mesh it uninstall.
This modifies `osm uninstall` so that it
lists out all mesh deployments in the cluster
for better clarity as to which mesh is being
uninstalled.
Also refactors several cli helpers to
better serve the cli portion of the codebase.
Resolves #1839.
- Performance …
=> feat(cli): show mesh list on uninstall

charts/osm/README.md, charts/osm/templates/osm-deployment.yaml, charts/osm/templates/osm-injector-deployment.yaml, charts/osm/values.schema.json, charts/osm/values.yaml
Allows specifying pod tolerations for control plane pods so
that they are allowed to be scheduled onto nodes with
matching taints.
Can be set using `helm install --set` or `osm install --set`
by passing toleration params such as:
```
--set=OpenServiceMesh.controlPlaneTolerations[0].key=foo \
--set=OpenServiceMesh.controlPlaneTolerations[0].operator=Equal \
--set=OpenServiceMesh.controlPlaneTolerations[0].value=bar \
--set=OpenServiceMesh.controlPlaneTolerations[0].effect=NoSchedule
```
Also indents the schema properties for consistency.
Part of #3253
Please …
=> charts/osm: allow specifying tolerations for control plane pods

pkg/kubernetes/announcement_handlers.go, pkg/kubernetes/announcement_handlers_test.go
Adds a unit test that verifies the OwnerReference property on the
envoy bootstrap config secret is properly updated to reference the
owning pod.
| Tests …
=> test(pkg/kubernetes): add garbage collector unit test

.github/workflows/release.yml, Makefile
This change skips defining the build date string embedded in compiled
binaries alongside version info by default, only overriding it for
releases. Because the build date is defined to the minute, builds one
minute apart with no other source changes would cause the binary to
change, and in the event of a `docker push`, a new 40+ MB image layer
being pushed.
I tested this with a release on my fork: https://github.com/nojnhuh/osm/releases/tag/v0.000.0%2Bjon
| …
=> ref(build): only include build date for releases

pkg/envoy/ads/response_test.go, pkg/envoy/ads/secrets.go, pkg/envoy/cds/response_test.go, pkg/envoy/sds/response.go, pkg/envoy/sds/response_test.go, pkg/envoy/secrets/errors.go, pkg/envoy/secrets/secrets.go, pkg/envoy/secrets/secrets_test.go, pkg/envoy/secrets/types.go, pkg/envoy/xdsutil.go, pkg/envoy/xdsutil_test.go, pkg/service/errors.go, pkg/service/service.go, pkg/service/service_test.go
Reduces complexity and potential errors caused by passing a non
SDSCert name to the method. UnmarshalMeshService is only used to
parse SDS secrets. This PR makes UnmarshalMeshService a method
on SDSCert and refactors SDSCert types and methods into a new
package.
| Control Plane              | [  X ] |
| Sidecar …
=> ref(pkg/*): make UnmarshsalMeshService a method on SDSCert

pkg/configurator/client.go, pkg/configurator/client_test.go, pkg/configurator/methods.go, pkg/configurator/methods_test.go
Remove intermediate struct `osmConfig`. It was previously used to represent the data of osm-config configmap. As OSM migrates to MeshConfig, `osmConfig` is not useful.
| Security …
=> ref(controller): remove osmConfig struct

pkg/envoy/rds/route/route_config.go, pkg/envoy/rds/route/route_config_test.go
The ':' character does not render uniformly in the stats
emitted by envoy because it is used as the delimiter for
the key and its value. As a result, the stats corresponding
to an egress route config is inconsistent:
```
http.mesh-http-conn-manager.rds-egress:80.tracing.service_forced: 0
http.mesh-http-conn-manager.rds-egress_80.rds.rds-egress_80.config_reload: 1
```
With this change, the stats corresponding to a route config are
uniformly rendered:
```
http.mesh-http-conn-manager.rds-egress.80.tracing.service_forced: 0
http.mesh-http-conn-manager.rds-egress.80.rds.rds-egress.80.config_reload: 1
```
Consistent formatting makes it easier to debug issues when
inspecting the stats.
This is similar to the change done in 1f10701f as a part of
issue #2156.
Signed-off-by: …
=> envoy/rds: remove colon from egress route config name

.gitattributes, pkg/envoy/proxy_test.go
Make checkout of yaml files to be the same on both platforms and adds a small delay to test to accommodate for Windows which has lower accuracy in `time.Now()`
=> Makes unit test pass on Windows

charts/osm/templates/osm-deployment.yaml, charts/osm/templates/osm-service.yaml, cmd/osm-controller/osm-controller.go, pkg/constants/constants.go, pkg/injector/envoy_config.go
Resolves #2190 by using a constant port number for the
ADS server in osm-controller. The port number was partially
configurable via the controller's command line flags but
this isn't enough to make the port number configurable.
Since there is no use case for this port to be configurable,
use a fixed port number. Also, renames the name of the port
for clarity.
Resolves #2190
=> osm-controller: use fixed port number for ADS server

charts/osm/templates/osm-service.yaml, demo/deploy-smi-policies.sh, pkg/constants/constants.go
Changes in this PR:
* Remove osm-config-validator service
* Create MeshConfig when deploying SMI policy, rather than osm-config ConfigMap
| SMI Policy                 | [X] |
| Upgrade …
=> ref(config): remove osmconfig footprint

tests/e2e/e2e_health_probe_test.go, tests/framework/common.go, tests/framework/common_apps.go
This PR resolves issue #3395.
Registry secret is set when using non-default registry for most of the images, such as osm-controller, init, client and server. But for this specific case, setting registry secret process is missing.
| …
=> bug(test): set registry secret when necessary

cmd/osm-controller/osm-controller.go, pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/configurator/mock_client_generated.go, pkg/configurator/types.go, pkg/debugger/policy.go
This PR changes the return value of method `GetMeshConfigJSON()` to `string` rather than `[]byte`.
All usages of `GetMeshConfigJSON()` converts the byte array to string after receiving the return value. To make it more convenient, the method should return string value directly.
| …
=> Refactor: GetMeshConfigJSON returns string

go.mod, go.sum, pkg/envoy/cds/cluster.go, pkg/envoy/cds/cluster_test.go, pkg/envoy/cds/response.go, pkg/envoy/cds/response_test.go, pkg/envoy/types.go, pkg/envoy/xdsutil.go, pkg/envoy/xdsutil_test.go, pkg/injector/envoy_config.go, pkg/injector/envoy_config_health_probes.go, pkg/injector/test_fixtures/expected_envoy_bootstrap_config.yaml, pkg/injector/test_fixtures/expected_xds_cluster_with_probes.yaml, pkg/injector/test_fixtures/expected_xds_cluster_without_probes.yaml, pkg/injector/test_fixtures/expected_xds_static_resources_with_probes.yaml, tests/envoy_xds_expectations/expected_output_getHTTPAccessLog.yaml, tests/envoy_xds_expectations/expected_output_getLivenessListener.yaml, tests/envoy_xds_expectations/expected_output_getLivenessListenerNonHTTP.yaml, tests/envoy_xds_expectations/expected_output_getProbeListener.yaml, tests/envoy_xds_expectations/expected_output_getReadinessListener.yaml, tests/envoy_xds_expectations/expected_output_getStartupListener.yaml, tests/envoy_xds_expectations/expected_output_getTCPAccessLog.yaml
This patch makes the following updates:
1. Use `type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog` in admin
2. Use `type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog` in listeners
3. Use explicit http2 config
=> Update Envoy config to comply with 1.18.3 api

charts/osm/templates/jaeger-deployment.yaml, charts/osm/templates/jaeger-rbac.yaml
Adds SecurityContext and PSP for jaeger deployment.
Tested with both PSP enabled and PSP disabled clusters.
SecurityContext is added regardless of pspEnabled as a best practice.
Partially fixes #1941 …
=> feat(rbac): Add Jaeger SecurityContext and PSP

charts/osm/templates/grafana-deployment.yaml, charts/osm/templates/prometheus-deployment.yaml
Adds Grafana and Prometheus SecurityContexts by default (enablePsp not required)
Fixes #3054 
| Tests …
=> feat(rbac): Add Grafana and Prometheus SecurityContexts by default

charts/osm/README.md, charts/osm/templates/osm-controller-pod-disruption-budget.yaml, charts/osm/templates/osm-injector-pod-disruption-budget.yaml, charts/osm/values.schema.json, charts/osm/values.yaml
Adds pod disruption budgets for osm-controller and osm-injector
that can be optionally enabled. This is an HA feature that
ensures replicated control plane apps always maintain a certain
number of healthy replicas at any given time, to account for
voluntary outages such as a node being drained.
Refer to the [HA doc](https://docs.google.com/document/d/1gpNbsghOTmKx0rVh4TL1kzpH6UnlWL3Hkw7lce7WlYM/edit#heading=h.ap5u1c8i7rvb) for more reference.
Part of #3390
1. Is …
=> charts/osm: add pod disruption budgets for control plane

demo/tail-fluentbit-logs.sh
Adds helper script to quickly tail fluentbit logs
| CI System …
=> tools(demo): Add fluentbit logs script

pkg/smi/health.go
SMI client implements the `health.Probes` interface for
readiness and liveness probes. This change checks for
the existence of SMI CRDs as a part of the liveness
probe.
=> smi: check SMI CRDs during liveness probe

charts/osm/templates/_helpers.tpl, charts/osm/templates/osm-deployment.yaml, charts/osm/templates/osm-rbac.yaml
Adds PodSecurityPolicy for Jaeger and modifies OSM PSP to include hostPath when FluentBit is enabled.
Fixes #1941  …
=> feat(rbac): Add FluentBit PodSecurityPolicy

pkg/envoy/eds/cluster_load_assignment_test.go
This pr improves test coverage for the method newClusterLoadAssignment
and converts the test to use go library
Fixes #3410
=> test(pkg/envoy/eds): improve test coverage for clusterLoadAssignment

docs/dev_guide/_index.md
A community member on Slack asked about a broken link to the manual demo. This PR fixes the link and clarifies that it points to the manual demo. It also fixes other broken and ambiguously labeled links.
no
no
=> Fix links in dev guide

charts/osm/values.schema.json
Currently, the schema prevents additional
Helm chart properties other than OpenServiceMesh
which is the root property for all values.
This change enforces strict validation only
for the OpenServiceMesh root property. Other
root properties that might be leveraged by
Helm charts using the OSM chart as a dependency
will not be subjected to schema validations.
=> charts/osm: allow additional root properties

pkg/catalog/catalog.go, pkg/catalog/mock_catalog_generated.go, pkg/catalog/types.go
XDS verticals have no way to call some of the existing functions
or helpers for XDS (namely, GetPodFromCertificate).
To avoid creating an API everytime we have a use-case that needs
special massaging of data, this commit allows packages to get
visibility on the kubecontroller instance to allow verticals see
kubernetes resources directly if they need to.
No
No
=> catalog: add GetKubecontroller interface

tests/framework/common.go
=> test(e2e): Enable priv init container for OpenShift

cmd/osm-controller/osm-controller.go, pkg/envoy/ads/grpc.go, pkg/envoy/ads/response_test.go, pkg/envoy/ads/server.go, pkg/envoy/ads/stream.go, pkg/envoy/ads/types.go
Moves using Proxy UUID, and instead uses available kubecontroller
interface to gather information about the pod for a given proxy.
This is needed to be able to reuse the Node ID for snapshot cache.
No
No
=> PodMetadata: Use kubecontroller to gather PodMetadata

pkg/injector/envoy_config.go, pkg/injector/envoy_config_test.go, pkg/injector/envoy_container.go, pkg/injector/test_fixtures/expected_envoy_bootstrap_config.yaml, pkg/injector/types.go
- Node ID was currently used for metadata purposes, this commit
makes Common Name (CN) of an envoy's certificate as its node identifier.
- The change of Node ID is in order to prepare adoption of
go-control-plane's XDS caches mechanisms.
- Node ID can be consolidated as part of envoy's bootstrap config yaml,
which seems a better than envoy cli args.
No
No
=> envoy: changing node ID to CN

pkg/envoy/lds/response_test.go
Partially fixed #3419.
Added tests to cover this line:
https://github.com/openservicemesh/osm/blob/d68983d98007942f4bb9e419cce691e559b90a6d/pkg/envoy/lds/response.go#L24
| Security …
=> test: add test case to pkg/envoy/lds

pkg/injector/envoy_config.go, pkg/injector/envoy_config_health_probes.go, pkg/injector/envoy_config_health_probes_test.go, pkg/injector/envoy_config_test.go, pkg/injector/test/test_helpers.go, pkg/injector/test_fixtures/expected_envoy_bootstrap_config.yaml, pkg/injector/test_fixtures/expected_xds_cluster_with_probes.yaml, pkg/injector/test_fixtures/expected_xds_cluster_without_probes.yaml, pkg/injector/test_fixtures/expected_xds_static_resources_with_probes.yaml, pkg/injector/types.go, tests/envoy_xds_expectations/expected_output_getHTTPAccessLog.yaml, tests/envoy_xds_expectations/expected_output_getLivenessCluster.yaml, tests/envoy_xds_expectations/expected_output_getLivenessListener.yaml, tests/envoy_xds_expectations/expected_output_getProbeCluster.yaml, tests/envoy_xds_expectations/expected_output_getProbeListener.yaml, tests/envoy_xds_expectations/expected_output_getReadinessCluster.yaml, tests/envoy_xds_expectations/expected_output_getReadinessListener.yaml, tests/envoy_xds_expectations/expected_output_getStartupCluster.yaml, tests/envoy_xds_expectations/expected_output_getStartupListener.yaml, tests/envoy_xds_expectations/expected_output_getTCPAccessLog.yaml, tests/envoy_xds_expectations/expected_output_getVirtualHosts.yaml
Updates the envoy bootstrap config to be constructed using XDS
structs directly instead of maps. The XDS objects are marshaled
to JSON and then to YAML. Using the XDS structs directly will help
ensure the objects are configured correctly and all required
fields are set. Additionally, this change will make it easier to
enforce the use of the same API version across the injector and
controller.
| Egress                     | [ ] …
=> ref(pkg/injector): use XDS structs for envoy bootstrap config

pkg/envoy/ads/stream.go
Theres a misshandle of XDS resources as our full config push could record we sent some
resources that could be ignored by envoy if envoy is still not interested in them.
Later requests from envoy for that resource and that nonce could ask for resources we have
already sent but were ignored at a previous time, hence making a request an ACK which is not.
This commit prevents pushing certificates on full config updates, which will make SDS almost
entirely envoy-driven; it will prevent us pushing unnecessary certificates that envoy did not
request, hence never potentially allowing us to send ignored resources at a response.
Certificate rotation can still cause issues if a MakeAllSecrets is called and a new certificate that
was not present in resources is added during that time (say, a config …
=> Do not send SDS on full config updates

pkg/envoy/eds/response.go, pkg/envoy/eds/response_test.go
Optimizes EDS to only respond with the endpoints for
requested clusters. Per the XDS protocol, additional
responses for resources that have not been requested
will be ignored.
| Control Plane              | [ X] |
=> envoy/eds: only respond to requested clusters

pkg/envoy/eds/response.go
Allow generating all endpoints for a proxy if request requests none
as resource names / nil request.
This is to allow SnapshotCache proper functioning.
No
No
=> envoy/eds: allow generation of all endpoints on empty request

cmd/cli/trafficpolicy_check.go
Removes dump of TrafficTarget resource from trafficPolicyCheckCmd
output. The inclusion of the resource in the output causes
unnecessary noise due to the managed fields and binary data.
Resolves #3512 
| CLI Tool                   | [ X ] |
| …
=> ref(cmd/cli): simplify trafficPolicyCheckCmd output

pkg/envoy/ads/response_test.go, pkg/envoy/ads/secrets_test.go, pkg/envoy/ads/stream_test.go, pkg/envoy/cds/response_test.go, pkg/envoy/eds/response_test.go, pkg/envoy/lds/response_test.go, pkg/envoy/proxy.go, pkg/envoy/proxy_test.go, pkg/envoy/registry/services_test.go, pkg/envoy/sds/response_test.go, pkg/envoy/types.go, pkg/envoy/xdsutil.go, pkg/injector/patch.go, tests/scenarios/traffic_split_with_apex_service_test.go, tests/scenarios/traffic_split_with_zero_weight_test.go
Adds additional metadata in the proxy's XDS cert
to identify the proxy's kind.
Currently, osm-controller only supports programming proxies
that run as a sidecar on app pods. As a part of the effort
to implement a proxy gateway, osm-controller will also
require to identify and program a proxy gateway. The
config for a gateway proxy will be completely different
compared to that of a sidecar proxy, and this change will
allow identifying the kind of the proxy to do so.
Existing code and tests have been updated to set the
proxy's kind to `sidecar`.
Part of #3501 …
=> envoy: add additional metadata for the proxy's kind

charts/osm/crds/meshconfig.yaml
**Description**: Edit the envoy meshconfig pattern so that downstream charts can pull different envoy images.
| Tests …
=> fix(crds/meshconfig): change envoy image pattern

tests/e2e/e2e_fluentbit_deployment_test.go, tests/e2e/e2e_fluentbit_output_test.go
Related to #3097 
Skip FluentBit on OpenShift as OpenShift needs additional resources in order for it to work.
| …
=> test(e2e): Skip FluentBit tests on OpenShift

pkg/envoy/ads/profile_test.go, pkg/envoy/ads/response_test.go, pkg/envoy/ads/secrets_test.go, pkg/envoy/ads/stream.go, pkg/envoy/ads/stream_test.go, pkg/envoy/cds/response_test.go, pkg/envoy/eds/response_test.go, pkg/envoy/lds/response_test.go, pkg/envoy/proxy.go, pkg/envoy/proxy_test.go, pkg/envoy/rds/response_test.go, pkg/envoy/registry/announcement_handlers_test.go, pkg/envoy/registry/debugger_test.go, pkg/envoy/registry/services_test.go, pkg/envoy/sds/response_test.go, tests/scenarios/traffic_split_with_apex_service_test.go, tests/scenarios/traffic_split_with_zero_weight_test.go
Returns an error if the proxy does not have
a valid CN, so the connection can be terminated
much earlier rather than during the XDS request-
response phase.
Also adds a Kind attribute to the Proxy.
=> envoy: error if proxy is not valid

charts/osm/crds/meshconfig.yaml
**Description**: Remove envoy pattern in meshconfig to allow user to point to envoy image in any registry, not just the osm dockerhub image. 
| Upgrade                    | [ …
=> fix(crds/meshconfig): remove envoy image pattern

pkg/injector/envoy_config.go, pkg/injector/envoy_config_test.go, pkg/utils/proto.go
Consolidates helpers into a separate file in the
utils pkg for reusability. The proto marshalling
to YAML will be required in a subsequent change
that builds the envoy bootstrap config in a generic
way for code reuse between the injector and OSM
gateway.
=> utils/proto: consolidate proto helpers

cmd/osm-controller/osm-controller.go, pkg/catalog/catalog.go, pkg/catalog/fake.go, pkg/catalog/helpers_test.go, pkg/catalog/types.go, pkg/endpoint/providers/kube/client.go, pkg/endpoint/providers/kube/client_test.go, pkg/endpoint/providers/kube/types.go
the kubeclient object is passed around in many
places its never used, this PR removes it.
Small refactor.
| Tests …
=> chore(*/*): Remove unused references to kubeclient.

.mergify.yml
Removes the `bot_account` field to allow the `autorebase` feature to work. Originally, the feature (to specify the account being used to do the rebasing under) was free, but now it is a subscription-only feature. Now the `autorebase` feature will use any OSM account in the Mergify dashboard to perform the rebasing, which is not an issue because there's only one OSM account in Mergify.
Resolves #3544
| Egress …
=> fix(.mergify.yml)Fixes autorebase label

charts/osm/README.md, charts/osm/templates/osm-controller-hpa.yaml, charts/osm/templates/osm-injector-hpa.yaml, charts/osm/values.schema.json, charts/osm/values.yaml
Adds horizontal pod autoscaler for osm-controller and osm-injector
Refer to the [HA doc](https://docs.google.com/document/d/1gpNbsghOTmKx0rVh4TL1kzpH6UnlWL3Hkw7lce7WlYM/edit#heading=h.ap5u1c8i7rvb) for more reference.
Part of #3390
| New Functionality          | [ X ] |
| Security …
=> feat(*): Add hpa to osm controller and injector

pkg/validator/server.go, pkg/validator/server_test.go, pkg/validator/validators.go, pkg/validator/validators_test.go
Add a validating webhook library to the code base. This is an extensible API to allow for registering future validations as well.
It contains a validator for the egress and the MeshConfig CRD's
| Egress                     | [ x] |
| Upgrade                    | …
=> feat(pkg/validators): add the main body for the validators libraries

pkg/envoy/bootstrap/config.go, pkg/envoy/bootstrap/config_test.go, pkg/envoy/xdsutil.go, pkg/injector/envoy_config_health_probes.go, pkg/injector/test_fixtures/expected_envoy_bootstrap_config.yaml, tests/envoy_xds_expectations/expected_output_getHTTPAccessLog.yaml, tests/envoy_xds_expectations/expected_output_getLivenessListener.yaml, tests/envoy_xds_expectations/expected_output_getLivenessListenerNonHTTP.yaml, tests/envoy_xds_expectations/expected_output_getProbeListener.yaml, tests/envoy_xds_expectations/expected_output_getReadinessListener.yaml, tests/envoy_xds_expectations/expected_output_getStartupListener.yaml, tests/envoy_xds_expectations/expected_output_getTCPAccessLog.yaml
Access loggers were using incosistent names accross the project.
Consolidate all of them into a single one named `envoy.access_loggers.stream`
| Ingress                    | [x] |
| Egress                     | [x] |
| …
=> Improves Access Logger names

tests/framework/common.go
**Description**: Add default meshconfig, and update the meshconfig with default for the noInstall option in e2e tests. 
| Tests …
=> fix(e2e): Add default meshconfig

tests/e2e/e2e_init_controller_test.go
**Description**: Skip the e2e_init_controller_test if the test suite is run with "NoInstall" 
| CI …
=> fix(e2e): skip e2e_init_controller_test for noInstall

tests/framework/common.go, tests/framework/common_apps.go
Adds a ServiceAccount for when vault is deployed in e2es. This allows the vault to be deployed with the privileged SCC on OpenShift which is necessary since it requires the IPC_LOCK capability.
The OpenShift docs recommend the privileged SCC here: https://www.openshift.com/blog/integrating-vault-with-legacy-applications
Related to #3097
| Egress                     | [ ] …
=> tests(e2e): Create ServiceAccount for Vault

pkg/certificate/providers/tresor/certificate_manager_test.go
Signed-off-by: shuheiktgw <shuheiktgw@users.noreply.github.com>
Close https://github.com/openservicemesh/osm/issues/3439
I added some missing tests for pkg/certificate/providers/tresor/certificate_manager.go. Thank you for your review!
| …
=> tests(pkg/certificate/providers/tresor): add missing tests

charts/osm/crds/meshconfig.yaml, charts/osm/templates/osm-deployment.yaml, charts/osm/templates/osm-gateway-deployment.yaml, charts/osm/templates/osm-gateway-secret.yaml, charts/osm/templates/osm-rbac.yaml, charts/osm/templates/osm-service.yaml, charts/osm/templates/preset-mesh-config.yaml, cmd/osm-controller/gateway.go, cmd/osm-controller/gateway_test.go, cmd/osm-controller/osm-controller.go, pkg/envoy/ads/stream.go, pkg/envoy/cds/response.go, pkg/envoy/lds/response.go
Adds support to bootstrap osm-gateway.
This change allows osm-gateway to connect to
osm-controller over XDS gRPC while returning nil
LDS and CDS configs so that further processing
of XDS requests are not exercised.
Part of #3501
=> osm-gateway: add support for gateway bootstrapping

pkg/catalog/inbound_traffic_policies.go, pkg/catalog/inbound_traffic_policies_test.go, pkg/catalog/mock_catalog_generated.go, pkg/catalog/outbound_traffic_policies.go, pkg/catalog/outbound_traffic_policies_test.go, pkg/catalog/service.go, pkg/catalog/service_test.go, pkg/catalog/types.go, pkg/kubernetes/util.go, pkg/kubernetes/util_test.go, pkg/service/types.go, tests/scenarios/traffic_split_with_apex_service_test.go, tests/scenarios/traffic_split_with_zero_weight_test.go
Multi cluster gateway configurations will have multiple routes
with the same service name. This PR introduces a cluster field
to the MeshService, which currently always returns true for local.
We also change TrafficPolicy names to *always* include the cluster id
and the namespace, export a few functions, and introduce a Locality
type to  determine if a service is being reached from which locality.
#3456 
| Ingress …
=> feat(pkg/*): Lay some groundwork for multi cluster gateways.

charts/osm/README.md, charts/osm/crds/meshconfig.yaml, charts/osm/templates/preset-mesh-config.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, cmd/osm-controller/osm-controller.go, pkg/apis/config/v1alpha1/mesh_config.go, pkg/configurator/methods_test.go, pkg/envoy/registry/services.go, pkg/envoy/registry/services_test.go
This change adds an `AsyncKubeProxyServiceMapper` used by the proxy
registry to maintain its own cache that maps proxies to which services
they back. It responds to add/update/delete events on k8s pods and
services, updates its cache, then schedules a new proxy update
broadcast. The `AsyncProxyServiceMapper` is disabled by default (with
the existing `KubeProxyServiceMapper` used instead) and can be enabled
with the `enableAsyncProxyServiceMapping` feature flag.
Fixes #3273
| Control Plane …
=> ref(proxy registry): track proxy-service relations async

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/crds/meshconfig.yaml, charts/osm/values.yaml, cmd/cli/mesh_upgrade.go, cmd/init-osm-controller/init-osm-controller_test.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml, docs/example/manifests/meshconfig/mesh-config.yaml, pkg/configurator/methods_test.go, pkg/constants/constants.go
Update osm version to 0.9.0
| Demo …
=> release: Update versions to 0.9.0

charts/osm/README.md, charts/osm/crds/meshconfig.yaml, charts/osm/templates/preset-mesh-config.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, docs/example/manifests/meshconfig/mesh-config.yaml, pkg/apis/config/v1alpha1/mesh_config.go, pkg/apis/config/v1alpha1/zz_generated.deepcopy.go, pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/configurator/mock_client_generated.go, pkg/configurator/types.go, pkg/injector/init_container.go, pkg/injector/init_container_test.go, pkg/injector/iptables.go, pkg/injector/iptables_test.go, pkg/injector/patch.go, pkg/injector/patch_test.go, pkg/injector/webhook.go, pkg/injector/webhook_test.go
Similar to outbound port exclusions (global and pod
scoped), this change adds support to exclude specified
ports from inbound sidecar redirection.
This is required in certain scenarios when traffic
destined to certain ports should not be proxied
to the sidecar (ex. ports that terminate TLS
connections in the app).
Required for #3582
=> injector: support inbound port exclusions

pkg/certificate/providers/tresor/ca_test.go
Signed-off-by: shuheiktgw <shuheiktgw@users.noreply.github.com>
Closes https://github.com/openservicemesh/osm/issues/3445
Added missing tests for pkg/certificate/providers/tresor/ca.go - NewCertificateFromPEM(). Thank you for your review!
| …
=> tests(pkg/certificate/providers/tresor): add missing tests for ca.go

pkg/kubernetes/event_handlers.go
Removes logging of unnecessary k8s events that are
not monitored. This was only required during the
initial development phase to debug all events.
=> kubernetes/events: remove noise from logging

.mergify.yml
Removes deprecated feature `strict`, but by adding labels to the `rebase` action the `automerge` and `automerge-squash` labels will still autorebase the PR.
| Security                   | [ ] …
=> fix(.mergfiy.yaml): Remove deprecated Mergify feature

pkg/envoy/lds/gateway.go, pkg/envoy/lds/gateway_test.go, pkg/envoy/lds/listener.go, pkg/envoy/lds/response.go, pkg/envoy/lds/response_test.go
Add LDS configs for the multi cluster gateway. The gateway should be setup
for SSL Passthrough, and be able to discover all upstream services.
part of #3444
| Control Plane              | [x ] |
| Upgrade …
=> feat(pkg/envoy): Add multi cluster gateway LDS 

charts/osm/templates/grafana-deployment.yaml, charts/osm/templates/jaeger-deployment.yaml, charts/osm/templates/osm-gateway-deployment.yaml, charts/osm/templates/prometheus-deployment.yaml, cmd/cli/testdata/test-chart/templates/deployment.yaml, demo/deploy-bookbuyer.sh, demo/deploy-bookstore-with-same-sa.sh, demo/deploy-bookstore.sh, demo/deploy-bookthief.sh, demo/deploy-bookwarehouse.sh, demo/deploy-tcp-client.sh, demo/deploy-tcp-echo-service.sh, demo/deploy-vault.sh, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml, docs/example/manifests/opa/deploy-opa-envoy.yaml, docs/example/manifests/samples/curl/curl.yaml, docs/example/manifests/samples/httpbin/httpbin.yaml
Fixes #3509 
Adds nodeSelectors to control plane components and demo apps so that they are not scheduled on the wrong nodes in mixedOS clusters
| …
=> fix(install): Add nodeSelectors for install and demo

cmd/cli/namespace_ignore.go, cmd/cli/namespace_list.go, cmd/cli/namespace_list_test.go, cmd/cli/namespace_test.go, pkg/constants/constants.go, pkg/ingress/client.go, pkg/ingress/client_test.go, pkg/ingress/types.go
As a part of #3582, specific ingress resources
need to be ignored. This change adds support
for this using the existing `openservicemesh.io/ignore`
label.
Also addresses an unnecessary type export and makes
unusued variable usage explicit.
=> ingress: support ignoring an ingress resource

charts/osm/templates/cleanup-hook.yaml
Ensure that cleanup-hook is not scheduled on a Windows node
| Install                    | [x] |
| CI System …
=> fix(cleanup): Add nodeSelectors for cleanup-hook

README.md, charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/README.md.gotmpl, docs/demos/first_steps.md, tests/e2e/e2e_k8s_version_test.go
=> Deprecate support for k8s 1.18

charts/osm/README.md, charts/osm/crds/meshconfig.yaml, charts/osm/templates/preset-mesh-config.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, cmd/cli/namespace_ignore.go, cmd/cli/namespace_list.go, cmd/cli/namespace_list_test.go, cmd/cli/namespace_test.go, docs/example/manifests/meshconfig/mesh-config.yaml, pkg/apis/config/v1alpha1/mesh_config.go, pkg/apis/config/v1alpha1/zz_generated.deepcopy.go, pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/configurator/mock_client_generated.go, pkg/configurator/types.go, pkg/constants/constants.go, pkg/ingress/client.go, pkg/ingress/client_test.go, pkg/ingress/types.go, pkg/injector/init_container.go, pkg/injector/init_container_test.go, pkg/injector/iptables.go, pkg/injector/iptables_test.go, pkg/injector/patch.go, pkg/injector/patch_test.go, pkg/injector/webhook.go, pkg/injector/webhook_test.go
Cherry-picks 6664c75e and 9c7a2d9f for v0.9.1,
required to address #3582 with v0.9.
=> Backport inbound port exclusion and ingress ignore features

pkg/envoy/cds/cluster.go, pkg/envoy/cds/cluster_test.go, pkg/envoy/cds/response.go, pkg/envoy/cds/response_test.go
Add cluster SNI passthrough for the multicluster gateway, which should
have every upstream cluster in the local mesh.
part of #3444
-->
| Control Plane              | [ x] |
| Security …
=> feat(pkg/envoy/cds):  add CDS for multi cluster gateway

charts/osm/templates/cleanup-hook.yaml, charts/osm/templates/grafana-deployment.yaml, charts/osm/templates/jaeger-deployment.yaml, charts/osm/templates/prometheus-deployment.yaml, cmd/cli/testdata/test-chart/templates/deployment.yaml, demo/deploy-bookbuyer.sh, demo/deploy-bookstore-with-same-sa.sh, demo/deploy-bookstore.sh, demo/deploy-bookthief.sh, demo/deploy-bookwarehouse.sh, demo/deploy-tcp-client.sh, demo/deploy-tcp-echo-service.sh, demo/deploy-vault.sh, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml, docs/example/manifests/opa/deploy-opa-envoy.yaml, docs/example/manifests/samples/curl/curl.yaml, docs/example/manifests/samples/httpbin/httpbin.yaml
Cherry-picks f5c66c2 and bdd664c for v0.9.1,
required to address #3509 with v0.9.
| Demo …
=> Backport nodeSelectors for install and demo

charts/osm/README.md, charts/osm/templates/osm-controller-hpa.yaml, charts/osm/templates/osm-controller-pod-disruption-budget.yaml, charts/osm/templates/osm-injector-hpa.yaml, charts/osm/templates/osm-injector-pod-disruption-budget.yaml, charts/osm/values.schema.json, charts/osm/values.yaml
Backports 30a6ec0b and 3f794156 for HA/scale with v0.9.1.
=> Backport control plane HPA and PDB changes for v0.9.1

pkg/catalog/gateway.go, pkg/catalog/helpers_test.go, pkg/catalog/outbound_traffic_policies.go, pkg/catalog/outbound_traffic_policies_test.go
Prep multi cluster gateway, by adding logic to the MeshCatalog
for the gateway
part of #3444
-->
| New Functionality          | [x ] |
| Control Plane              | [x ] |
| Upgrade …
=> feat(pkg/catalog):  Gateway gets all in-cluster services for ListAllowedOutbound

charts/osm/values.schema.json
Adds enablePrometheusScraping back to values.schema.json. Since
osm mesh upgrade reuses values from previous releases, the
enablePrometheusScraping flag must remain in the values schema to
avoid errors on upgrade even though it is no longer used in the
codebase. …
=> fix: patch backporting PR for meshconfig changes

Makefile
The dependencies listed for the cmd/cli/chart.tgz target previously
only included files in a subdirectory of the chart and was missing the
files at its root, like values.yaml. This change includes all files
underneath charts/osm at any depth as a dependency for the generated
chart embedded in the CLI.
| SMI Policy …
=> fix(build): rebuild chart when its root files change

demo/deploy-traffic-specs.sh, docs/example/manifests/access/traffic-access-v1-allow-bookthief.yaml, docs/example/manifests/access/traffic-access-v1.yaml
fix(demo): remove host headers in SMI policies
The `:authority` header sent by the bookbuyer to the bookstore is
actually `bookstore.bookstore:14001` where the bookstore's
HTTPRouteGroup used in the manual demo specified a `host` header match
of `bookstore.bookstore`, resulting in
"response_code_details": "route_not_found"
in the bookstore's logs for requests from the bookbuyer.
This change removes the `host` header matches all of the demo manifests.
Fixes #3616 …
=> fix(demo): remove host headers in SMI policies

pkg/catalog/outbound_traffic_policies.go, pkg/catalog/outbound_traffic_policies_test.go
In permissive mode, when client belongs to the same namespace
as the upstream service, the shorthand FQDN <service>,
<service>:<port> should be configured as domains in the
virtual_host for the corresponding service. This change
addresses this bug specific to permissive mode.
=> catalog/route: fix missing hostnames for permissive mode

charts/osm/README.md, charts/osm/templates/mutatingwebhook.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, tests/e2e/e2e_certmanager_test.go, tests/e2e/e2e_hashivault_test.go
Allows the timeout for the injector's mutating webhook to be
configured using Helm's set flag. Increases the timeout for tests
using external certificate providers due to the potential for
slowness in issuing certs.
Resolves #3634 
| Install                    | [ X ] |
| Sidecar Injection          | [ X ] |
| …
=> fix(injector): increase injector webhook timeout

charts/osm/crds/meshconfig.yaml, cmd/osm-controller/log_handler.go, cmd/osm-controller/log_handler_test.go, cmd/osm-controller/osm-controller.go, pkg/apis/config/v1alpha1/mesh_config.go, pkg/configurator/client_test.go, pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/configurator/mock_client_generated.go, pkg/configurator/types.go, pkg/constants/constants.go
New `osmLogLevel` option has been added under observability meshconfig
spec (seems the most related and relevant to the available categories)
to allow changing the log level of OSM at runtime.
The initial log level flag has been kept as it still mandates boot log
level up to the point configurator and the log level handler are both
up, which then meshconfig value takes over.
The handler can't be easilly moved to the `logger` package as it
introduces a hard dependency cycle between logger<->configurator, hence
the handler has been left on osm-controller main.
Adds a unit test, and see below a working example on a running deployment.
Fixes #3646
| …
=> logs: make log level configurable through meshconfig

pkg/certificate/encode.go, pkg/certificate/errors.go, pkg/certificate/providers/certmanager/certificate_manager.go, pkg/certificate/providers/certmanager/certificate_manager_test.go, pkg/certificate/providers/certmanager/errors.go
Adds unit tests to functions in `certificate_manager.go`
and resolves #3435.
| Tests                      | [x ] |
| …
=> test(*): Adds test to certificate_manager.go

pkg/envoy/eds/response.go, pkg/envoy/eds/response_test.go
Change db538a1f8 introduced a regression where the cluster
name is not correctly parsed to retrieve the mesh service.
This causes EDS to error and endpoints to not be
programmed.
Error log:
```
{"level":"error","component":"envoy/eds","error":"Invalid cluster name. Expected: <namespace>/<name>, Got: server/server/local","time":"2021-06-24T19:09:41Z","file":"response.go:52","message":"Error retrieving MeshService from Cluster server/server/local"}
```
1. Is this …
=> envoy/eds: fix cluster name to mesh service parsing

charts/osm/crds/meshconfig.yaml, cmd/osm-controller/log_handler.go, cmd/osm-controller/log_handler_test.go, cmd/osm-controller/osm-controller.go, pkg/apis/config/v1alpha1/mesh_config.go, pkg/configurator/client_test.go, pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/configurator/mock_client_generated.go, pkg/configurator/types.go, pkg/constants/constants.go
New `osmLogLevel` option has been added under observability meshconfig
spec (seems the most related and relevant to the available categories)
to allow changing the log level of OSM at runtime.
The initial log level flag has been kept at it still mandates boot log
level up to the point configurator and the log level handler are both
up, which then meshconfig value takes over.
The handler can't be easilly moved to the `logger` package as it
introduces a hard dependency cycle between logger<->configurator, hence
the handler has been left on osm-controller main.
Adds a unit test, and see below a working example on a running deployment.
Fixes #3646
-->
| …
=> (backport) logger: making log level configurable through meshconfig

cmd/osm-controller/gateway.go, pkg/envoy/ads/cache_stream.go, pkg/envoy/ads/cache_test.go, pkg/envoy/ads/response_test.go, pkg/envoy/ads/secrets.go, pkg/envoy/ads/secrets_test.go, pkg/envoy/ads/stream.go, pkg/envoy/cds/response.go, pkg/envoy/cds/response_test.go, pkg/envoy/eds/response.go, pkg/envoy/lds/response.go, pkg/envoy/proxy.go, pkg/envoy/proxy_test.go, pkg/envoy/rds/response.go, pkg/envoy/registry/services.go, pkg/envoy/registry/services_test.go, pkg/envoy/sds/response.go, pkg/envoy/xdsutil.go, pkg/injector/patch.go
This change refactors the code to encode the
proxy's identity in its XDS cert, which
can be used to derive its service identity
that is encoded in certs for proxy->proxy
communication.
The goal of this change is to avoid leaking
k8s service account across the XDS code, which
abstracts the proxy identity using the identity
pkg. As a part of this, unnecessary conversions
from CN -> service-account -> service-identity
are avoided when invoking APIs on the MeshCataloger
interface. Within XDS, service-identity ->
service-account conversions are only needed in
situations where k8s code has already leaked, such
as when inspecting the associated pod's spec.
Also renames some functions for clarity.
Part of #3168
| …
=> envoy: encode proxy identity in XDS cert

cmd/osm-controller/osm-controller.go, pkg/providers/kube/client.go, pkg/providers/kube/client_test.go, pkg/providers/kube/types.go
The new config client will be used to incorporate the k8s MultiClusterService objects
Issue: #3444 
| Demo                       | [ …
=> feat(pkg/providers) Plumb through config client to the k8s provider

pkg/envoy/cds/cluster.go, pkg/envoy/cds/cluster_test.go
This change formats the altStatName of Envoy clusters created based on the applied egress policies so that egress traffic can be observed with Prometheus. The change only applies to egress traffic enabled using egress policies, not globally enabled egress. The AltStatName of the cluster is formatted so that the stats for the cluster are grouped with Envoy metrics we are already scraping for. Prior to this change, the egress cluster name would be interpreted incorrectly due to periods and colons in the name and the stats would be grouped under a unique metric. We were not scraping for this metric and it would be difficult for customers to interpret.
Addresses issue #3164.
This change can be demonstrated using the [egress policy …
=> fix(pkg/envoy/cds): configure egress Envoy cluster altStatName for prometheus

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/crds/meshconfig.yaml, charts/osm/values.yaml, cmd/cli/mesh_upgrade.go, cmd/init-osm-controller/init-osm-controller_test.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml, docs/example/manifests/meshconfig/mesh-config.yaml, pkg/configurator/methods_test.go, pkg/constants/constants.go
Signed-off-by: jaellio <jaellio@microsoft.com>
Yes
=> chore(release): update charts and tags for v0.9.1-rc.1

charts/osm/templates/preset-mesh-config.yaml, cmd/init-osm-controller/init-osm-controller.go, cmd/init-osm-controller/init-osm-controller_test.go
This commit changes the kind of preset-mesh-config from MeshConfig to
ConfigMap
Fixes #3654
| Tests …
=> ref(preset-mesh-config): Change kind of preset-mesh-config to ConfigMap

tests/framework/common.go, tests/framework/namespace.go
This PR moves, without changing, the following functions from `common.go` to `namespace.go`:
- `AddNsToMesh(shouldInjectSidecar bool, ns ...string)`
- `WaitForNamespacesDeleted(namespaces []string, timeout time.Duration)`
- `GetTestNamespaceSelectorMap()`
No functional code changes!
The goal of this PR is to make `common.go` smaller and easier to navigate.  As of this writing it has over 1600 lines of code.
=> e2e: Refactoring namespace-related test functions into a new file - namespace.go

tests/framework/common.go
This PR removes `string(...)` type conversions where stringer can be used; introduces `fmt.Sprintf` for readability.
=> e2e: Fix string type conversions

tests/framework/common.go
This PR renames a variable from `json` to `jsonConfig` - since `json` is the name of a package: `json, _ := json......`
No functional code changes!
=> e2e: Renaming json variable so it does not conflict with imported package

cmd/osm-controller/osm-controller.go
Since osm-controller builds the kube config using the
in-cluster config and not the kubeconfig file, this
change removes the unused dependency on the kubeconfig
file. The kubeconfig file was used during the initial development
phase.
=> osm-controller: remove unused kubeconfig file dependency

tests/framework/common.go, tests/framework/helm.go
This PR moves a few helm related functions into a new file - 'helm.go'
The goal is to lower the number of lines in `common.go`, which as of this writing is around 1600 lines.
=> e2e: Move helm related functions into helm.go

tests/framework/common.go
This PR fixes a few typos in comments and environment variables in e2e test's `common.go`.
=> e2e: Fixing typos in e2e test framework

tests/framework/common.go
This PR simplifies the concatenation of a few strings into a file path.  The goal is to make it easier to comprehend at first glance what the file path would be. 
Also - by using the variable name `filePath` we indicate what the string is.
=> e2e: Simplify file path constructor

pkg/config/client.go, pkg/config/types.go, pkg/configurator/client.go, pkg/configurator/types.go, pkg/ingress/client.go, pkg/ingress/types.go, pkg/k8s/client.go, pkg/k8s/types.go, pkg/policy/client.go, pkg/policy/types.go, pkg/smi/client.go, pkg/smi/types.go
The code waits for caches to sync synchronously
using the `WaitForCacheSync()` API. The unused
`cacheSynced` channel is not necessary.
=> pkg/*: remove unused cacheSynced channel

DESIGN.md, pkg/smi/client.go, pkg/smi/fake.go, pkg/smi/types.go
Removes the unused announcement channel which
was deprecated in favor of pubsub event framework.
=> smi/client: remove unused announcement channel

pkg/config/client.go, pkg/ingress/client.go, pkg/k8s/client.go, pkg/k8s/event_handlers_test.go, pkg/policy/client.go, pkg/smi/client.go
The existing check using reflect can panic if the
event object is not as expected. This change
safely converts the interface to an API object
before retrieving its namespace.
=> pkg/*: safely filter events for monitored namespaces

pkg/injector/iptables.go
Removes an unnecessary TODO comment carried
over from the initial init-iptables.sh script.
This TODO was meant to address a case where
a client sends traffic to itself using the
service IP, which would get routed back to
itself, and if such traffic needed to be
bypassed then an additional iptables rule
would be necessary. Since we do not have
any requirement to bypass additional traffic,
this change removes the ambiguous TODO comment.
Resolves #1266
| Networking                 | [X] |
1. Is this a …
=> injector/iptables: resolve unnecessary TODO comment

pkg/certificate/providers/config_test.go
Unit test for `ValidateCertManagerOptions` and `ValidateVaultOptions`
part of #3425
No
No
=> pkg/cert/providers: add cert provider validators test

go.mod, go.sum
There's a CI breakage due to kube-proxy failing to start on the kind node.
```
2021-06-30T22:05:30.81895558Z stderr F I0630 22:05:30.818289       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
2021-06-30T22:05:30.818968181Z stderr F F0630 22:05:30.818310       1 server.go:495] open /proc/sys/net/netfilter/nf_conntrack_max: permission denied
```
node stays in forever down:
```
Jun 30 22:05:04 osm-e2e-control-plane kubelet[682]: E0630 22:05:04.733414     682 pod_workers.go:191] Error syncing pod a9df50c9-a5cc-4418-a219-cc4b31c3dab6 ("kube-proxy-8bshx_kube-system(a9df50c9-a5cc-4418-a219-cc4b31c3dab6)"), skipping: failed to "StartContainer" for "kube-proxy" with CrashLoopBackOff: "back-off 20s restarting failed container=kube-proxy …
```
=> CI: Updating kind go library to 0.11.1

cmd/osm-controller/osm-controller.go, pkg/errcode/errcode.go, pkg/errcode/errcode_test.go
Introduces a pkg to manage error codes. Documentation
and tooling to inspect errors will be built around
the error code and description mapping provided by
this pkg.
Sample error log with error code:
```
{"level":"error","component":"errcode","error":"some error","error_code":"E1000","time":"2021-06-30T12:52:14-07:00","file":"errcode_test.go:14","message":"some error was seen"}
```
Part of #2866
1. Is this a …
=> errcode: introduce error code management

pkg/catalog/inbound_traffic_policies.go, pkg/catalog/outbound_traffic_policies.go, pkg/errcode/errcode.go
Adds error codes for inbound and outbound
traffic policy related errors.
Also makes the logging of resource names consistent.
Part of #2866
=> catalog/traffic-policies: add error codes

.github/workflows/main.yml, Makefile, charts/osm/README.md, charts/osm/crds/meshconfig.yaml, charts/osm/templates/osm-crd-converter-deployment.yaml, charts/osm/templates/osm-crd-converter-service.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, cmd/osm-crd-converter/osm-crd-converter.go, dockerfiles/Dockerfile.osm-crd-converter, pkg/constants/constants.go, pkg/crdconversion/crdconversion.go, pkg/crdconversion/crdconversion_test.go, pkg/crdconversion/types.go, tests/framework/common.go, tests/framework/common_apps.go
This commit add a conversion webhook server to OSM's control plane. The
purpose to this server is to patch all the CRD's that OSM manages with
the required conversion webhook configuration and to serve the
conversion requests.
The handler for each of the CRD's conversion requests will be in a follow up pr.
Part of #3396
**Note:** The deployment of the conversion webhook is currently controlled by a feature flag, which will be removed once issue https://github.com/openservicemesh/osm/issues/3716 is resolved 
| CLI Tool …
=> feat(upgrade): Add a conversion webhook server to OSM control plane

go.mod, go.sum
Backports c4d7eabb.
Updates the Kind version due to issues seen in the
CI with using an older Kind version.
=> [backport] go module: update kind go library to 0.11.1

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/crds/meshconfig.yaml, charts/osm/values.yaml, cmd/cli/mesh_upgrade.go, cmd/init-osm-controller/init-osm-controller_test.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml, docs/example/manifests/meshconfig/mesh-config.yaml, pkg/configurator/methods_test.go, pkg/constants/constants.go
Is this a release candidate? `no`
=> chore(release): create release v0.9.1

cmd/cli/osm.go, cmd/cli/support.go, cmd/cli/support_err.go, cmd/cli/support_err_test.go, pkg/errcode/errcode.go, pkg/errcode/errcode_test.go
Adds a new command `osm support error-info` that lists
the mapping of one or all error codes to their description.
The mapping will be used for troubleshooting as well
as documentation that will be a part of the osm-docs
repo.
Part of #2866 
Sample output:
```console
$ osm support error-info E1000
+------------+-----------------------------------------------------------------+
| ERROR CODE |                           DESCRIPTION                           |
+------------+-----------------------------------------------------------------+
| E1000      |  An invalid command line argument was passed to the             |
|            | application.                                                    |
+------------+----------------------------------------------------------------- …
```
=> cli: add support command to list error code description mapping

.github/workflows/nightly-noinstall.yml
**Description**: Add a no-install nightly job that creates a kind cluster, installs OSM via OSM CLI, and runs the e2e suite with the "NoInstall" flag enabled. These will run off of main.  …
=> Create noinstall nightly job

cmd/cli/osm.go, cmd/cli/osm_test.go
Adds a generic unit test for command initialization.
This is the simplest way to verify that the cobra commands
are created correctly for each subcommand.
It improves the coverage under `cmd/cli` from 49.75% to
64.52%. 
Resolves #3417
---
Previously:
Now:
=> cli/test: add unit test for command initialization

tests/framework/common.go
Cherry-picks ed30fa8 for release-v0.9 tests,
required for e2e tests to work on OpenShift.
| Install                    | [] |
| Demo …
=> backport: enablePriviligedInitContainer for e2es on OpenShift

tests/e2e/e2e_http_ingress_test.go
**Description**: Increase time limit for http ingress test. While testing locally, it sometimes took around 40-50 seconds or so for the request failures to fail expectedly after experiencing a timeout. 
| …
=> test(e2e/http_ingress): Increase time limit

charts/osm/crds/multiclusterservice.yaml, pkg/config/client.go, pkg/config/mock_client_generated.go, pkg/config/types.go, pkg/providers/kube/client.go, pkg/providers/kube/client_test.go, pkg/providers/kube/types.go
kube provider includes remote gateway addresses in service endpoints
list.
TODO after this PR:
* Assign different weight to remote gateways
| Tests                      | …
=> feat(multicluster): kube provider support multicluster

tests/e2e/e2e_upgrade_test.go
**Description**: Sets `enablePrivilegedInitContainer` to true if test is run on an OpenShift cluster
| Demo …
=> tests: enable priv init container for tests on openshift

DESIGN.md, pkg/catalog/endpoint.go, pkg/catalog/mock_catalog_generated.go, pkg/catalog/outbound_traffic_policies.go, pkg/catalog/outbound_traffic_policies_test.go, pkg/catalog/traffictarget.go, pkg/catalog/traffictarget_test.go, pkg/catalog/types.go, pkg/envoy/ads/secrets.go, pkg/envoy/ads/secrets_test.go, pkg/envoy/cds/response.go, pkg/envoy/cds/response_test.go, pkg/envoy/eds/response.go, pkg/envoy/sds/response.go, pkg/envoy/sds/response_test.go
This PR aims to resolve issue #3190 .
It mainly drops the word `allowed` from cataloger endpoints methods.
| Tests …
=> ref: method renaming for cataloger endpoint methods

tests/e2e/constants.go, tests/e2e/e2e_trafficsplit_same_sa_test.go
Use port 14001 for e2e traffic split test so that server/client communication works on OpenShift which reserves port 80.
Partially addresses #3097
| …
=> test(e2e): Configure e2e ports for OpenShift

charts/osm/README.md, charts/osm/templates/osm-deployment.yaml, charts/osm/templates/osm-injector-deployment.yaml, charts/osm/values.yaml
When HPA is enabled, the deployment will be auto-scaled
based on the configured HPA resource. Updating the deployment
with HPA enabled will invalidate the replicas set by HPA.
Per kubernetes/kubernetes#25238, it is recommended to
not set the replicaCount when HPA is enabled.
=> charts/osm: don't set the replicaCount with HPA

tests/e2e/e2e_port_exclusion_test.go
**Description**: There appears to be an issue in the port exclusion test where the pod level port exclusion test fails when run immediately after the global port exclusion test with the "noInstall" flag on kind clusters. From testing locally, changing the namespace names in the pod level port exclusion test addresses this issue, perhaps due to a problem with how the namespaces are being cleaned up. 
| Ingress                    | …
=> test(e2e/port_exclusion): change ns name

tests/e2e/constants.go, tests/e2e/e2e_deployment_client_server_test.go, tests/e2e/e2e_metrics_test.go, tests/e2e/e2e_trafficsplit_recursive_split.go, tests/e2e/e2e_trafficsplit_same_sa_test.go, tests/e2e/e2e_trafficsplit_test.go, tests/framework/common.go
**Description**: Changes port used in tests to 14001 since OpenShift uses port 80 itself
| Demo …
=> tests(e2e): fix port issues for remaining e2es on OpenShift

pkg/injector/health_probes_test.go
Relates to https://github.com/openservicemesh/osm/issues/3432
I've added missing unit tests for pkg/injector/health_probes. Thank you for your review!
| Tests …
=> tests: add unit tests for pkg/injector/health_probes

cmd/cli/mesh_list.go, cmd/cli/mesh_list_test.go, cmd/cli/uninstall.go, cmd/cli/uninstall_test.go, cmd/cli/util.go, cmd/cli/util_test.go
This removes verbose output from the osm mesh list
command. The removed output includes osm mesh controller
pod output and supported smi versions.
In lieu of printing verbose output, the command
instead prints out instructions for the user
to obtain supported smi versions through cli commands.
Resolves #3648.
| …
=> chore(cli): Remove verbose osm mesh list output

pkg/apis/config/v1alpha1/multi_cluster_service.go, pkg/apis/config/v1alpha1/multi_cluster_service_test.go
This PR implements and tests `.String()` on `MultiClusterService` struct.
=> multicluster: Implement Stringer interface on MultiClusterService struct

demo/run-osm-multicluster-demo.sh
This PR removes optionality of running OSM Multicluster w/ other cert issues.
This PR hard-codes `tresor` as the only Multicluster demo cert issuer.
The goal is to simplify.
=> multicluster: Defaulting demo to Tresor certificate issuer

pkg/catalog/dispatcher.go
This PR adds the `MultiClusterService` events (add, update, delete) to the catalog/dispatch system so these events cause Envoy config refreshes as well.
=> dispatcher: Add MultiClusterService events to the dispatch system

pkg/apis/config/v1alpha1/multi_cluster_service_test.go, pkg/providers/kube/client.go
This PR renames a variable so that it does not collide with an imported package name.
=> Renaming variable colliding with imported package name

demo/deploy-MultiClusterService.sh, demo/run-osm-multicluster-demo.sh, pkg/apis/config/v1alpha1/multi_cluster_service_test.go
Adding a small script to create a `MultiClusterService` object for the OSM Multicluster demo.
=> multicluster: Add (and use) deploy-MulticlusterService.sh

demo/run-osm-multicluster-demo.sh
This PR moves the `make docker-push` command out of the kubectx loop. This needs to be run only once per running the script; no need to rebuild and push for every cluster in the demo.
=> multicluster: Demo script needs to 'make docker-push' only once

demo/deploy-bookstore-with-same-sa.sh, demo/deploy-bookstore.sh, demo/deploy-bookwarehouse.sh
This PR adds the current kube context to the `IDENTITY` environment variable for `bookstore` and `bookwarehouse` pods for **the demo**.
This is going to be very useful in multicluster environments, where we may have `bookstore` in a cluster `alpha` and a cluster `beta` (kubectx).
=> multicluster: Augment IDENTITY envirenment variable in demos with current kubectx

pkg/apis/config/v1alpha1/multi_cluster_service.go
I believe it is reasonable to make `MultiClusterServiceSpec` a required struct when `MultiClusterService` is created.  Without the `spec` the rest of the CRD would me meaningless.
=> MultiClusterServiceSpec in MultiClusterService CRD is not optional

pkg/config/client.go, pkg/config/mock_client_generated.go, pkg/config/types.go, pkg/gen/client/config/listers/config/v1alpha1/multiclusterservice.go, pkg/providers/kube/client.go, pkg/providers/kube/client_test.go
This PR changes the multicluster implementation from using `[]*v1alpha1.MultiClusterService` to using `[]v1alpha1.MultiClusterService`. In other words - removes usage of slice of pointers.
A good write-up on why:  https://philpearl.github.io/post/bad_go_slice_of_pointers
=> multicluster: Use []v1alpha1.MultiClusterService (not a slice of pointers)

pkg/catalog/outbound_traffic_policies.go
This PR changes
- from `if !mc.isTrafficSplitApexService(destService) {` 
- to `if mc.isTrafficSplitApexService(destService) {` + `continue`
** no functional code changes**
This PR simply removes a level of indentation!
=> catalog: Refactor buildOutboundPolicies()

pkg/providers/kube/client.go, pkg/providers/kube/client_test.go, pkg/providers/kube/multicluster.go, pkg/providers/kube/multicluster_test.go
This PR moves multicluster-related code into new functions and a separate file: `pkg/providers/kube/multicluster.go`
=> multicluster: Carve out multicluster code out into functions and into multicluster.go file

.gitignore, demo/get-multicluster-envoy-configs.sh
This PR adds a script, which attempts to automate the collection of __Envoy configuration__ during Multicluster development and demo/troubleshooting.
=> multicluster: Script to easily capture Envoy configs for multicluster development

demo/deploy-bookbuyer.sh
This is a _hack_, which allows services not DNS resolvable by Kube DNS to pass the gethostbyname stage of `cURL`, and offload the rest to Envoy, which will know how to handle the call.
The IP address for the hosts `bookstore.bookstore.svc.cluster.alpha` and `bookstore.bookstore.svc.cluster.beta` does not really matter.
=> multicluster: Resolve multicluster services via /etc/hosts

charts/osm/templates/cleanup-hook.yaml, charts/osm/templates/osm-crd-converter-deployment.yaml, charts/osm/templates/osm-crd-converter-service.yaml, charts/osm/templates/osm-deployment.yaml, pkg/crdconversion/crdconversion.go
Add another http server to the crd converter which servers as the health
endpoint which is used to sync the readiness of osm-controller based on this port.
Update the cleanup hook as pre-delete to ensure proper deletion order
of CRD's and services via Helm.
Part of #3396
| Observability              | [ …
=> feat(upgrade): Add new http server to crd converter

pkg/envoy/ads/response_test.go, pkg/envoy/ads/secrets.go, pkg/envoy/ads/secrets_test.go, pkg/envoy/sds/response.go, pkg/envoy/sds/response_test.go, pkg/envoy/secrets/secrets_test.go, pkg/envoy/secrets/types.go, pkg/envoy/xdsutil.go, pkg/envoy/xdsutil_test.go
This change fixes an existing bug where when mTLS is disabled,
the root certificate is still being configured to validate the
client cert. In TLS mode (non-mTLS), the certificate presented
by the client should not be validated and hence there is no
reason to publish this peer cert validation context along with
the server cert.
A non-mTLS root certificate should never be requested by the proxy.
Required by #3779 to enable TLS based ingress to backends.
-   Did you notify the …
=> envoy: remove unnecessary peer validation cert for TLS (non-mTLS)

demo/run-osm-multicluster-demo.sh
This PR adds the `enableOSMGateway` feature flag to the Multicluster demo script.
This will ensure that we deploy a multicluster gateway when this demo us ran.
=> multicluster: Enable Multicluster Gateway feature flag for multicluster demo

demo/get-multicluster-envoy-configs.sh
This PR changes the helper script so it includes Endpoints as well.
Example:
```bash
$ ./demo/get-multicluster-envoy-configs.sh
$ cat envoy__config___bookbuyer___bookbuyer-586dd84d8c-bf2q7.json | grep 10.244
"address": "10.244.0.71",
"address": "10.244.2.122",
"address": "10.244.0.71",
"address": "10.244.1.87",
"address": "10.244.1.87",
"address": "10.244.1.87",
"address": "10.244.0.71",
"address": "10.244.2.122",
```
=> multicluster: Adding ?include_eds to script getting Envoy configs

go.mod, go.sum, pkg/crdconversion/config_meshconfig_conversion.go, pkg/crdconversion/config_multiclusterservice_conversion.go, pkg/crdconversion/crdconversion.go, pkg/crdconversion/framework.go, pkg/crdconversion/policy_egress_conversion.go, pkg/crdconversion/policy_ingressbackends_conversion.go, pkg/crdconversion/smi_httproutegroup_conversion.go, pkg/crdconversion/smi_tcproutes_conversion.go, pkg/crdconversion/smi_trafficaccess_conversion.go, pkg/crdconversion/smi_trafficsplit_conversion.go
This commit adds a handler for all the CRD's that OSM manages. The
actual business logic for conversion will be added once a CRD has
multiple versions.
Fixes #3396
| Upgrade                    | [X] |
Please answer the following questions with yes/no. `no`
1. Does this change contain code from or inspired by another project? `yes`
-   The code in `framework.go` is borrowed from k8s sample code on converters reference here : https://github.com/kubernetes/kubernetes/blob/release-1.21/test/images/agnhost/crd-conversion-webhook/converter/framework.go 
=> feat(upgrade): add handlers for conversion of CRD's in OSM

demo/get-multicluster-envoy-configs.sh
This PR extends the helper script, which fetches Envoy configs, so that it can get Envoy configs from all clusters in a Multicluster setup including Multicluster Gateways' config.
=> multicluster: Get Envoy config from both clusters including Multicluster Gateways

pkg/envoy/lds/gateway.go, pkg/envoy/lds/gateway_test.go, pkg/envoy/xdsutil.go
This PR configures a `sni_cluster` filter for the Multicluster Gateway listener.
> Note `envoy.filters.network.sni_cluster`
```json
{
"@type": "type.googleapis.com/envoy.admin.v3.ListenersConfigDump",
"version_info": "1",
"dynamic_listeners": [
{
"name": "multicluster-listener",
"active_state": {
"version_info": "1",
"listener": {
"@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
"name": "multicluster-listener",
"address": {
"socket_address": {
"address": "0.0.0.0",
"port_value": 15003
}
},
"filter_chains": [
{
"filter_chain_match": {
"transport_protocol": "tls",
"application_protocols": [
"osm"
],
"server_names": [
"*.local"
]
},
"filters": [
{
"name": "envoy.filters.network.sni_cluster"
},
{
"name": "envoy.filters.network.tcp_proxy",
"typed_config": {
"@type": …
```
=> multicluster: Create sni_cluster filter for the Multicluster Gateway listener

pkg/envoy/xdsutil.go
This PR removes variable declaration and with that removes a variable name colliding with an imported package (`identity`).
=> Removing unnecessary variable & collision of variable w/ import

demo/populate-MulticlusterService.sh, demo/run-osm-multicluster-demo.sh
This PR adds a script to automate the population of the `other` cluster's IP address and name in the MulticlusterService CRO.
=> multicluster: Populate MulticlusterService

pkg/config/client.go, pkg/config/multicluster.go
This PR moves multicluster-related functions to a new file - `pkg/config/multicluster.go`
I wish I could say "no functional code changes", but I took the liberty to add `log.Trace()....` statements
=> multicluster: Carve out multicluster-related functions in a separate file

pkg/providers/kube/multicluster.go, pkg/providers/kube/multicluster_test.go
This PR simplifies the `getMulticlusterEndpoints()` function. It adds `getIPPort()` to separate concerns, and a test for it.
=> multicluster: Simplify and test

pkg/envoy/ads/stream.go
This PR adds the word `Multicluster` to a log line.  This makes it easy to grep log lines for Multicluster specific messages -- easier development.
=> multicluster: For ease of debugging - log lines related to Multicluster capability should contain 'Multicluster' word

pkg/envoy/lds/gateway.go
This PR changes the function `buildGatewayListeners()` so that in case of an error it returns nil (empty slice of `[]types.Resource`).
=> multicluster: In case of an error buildGatewayListeners() should return nil

pkg/config/client.go
This PR augments log lines w/ the name of the informers (corrects `RemoteService` w/ `MulticlusterService`).
Simplifies some blocks of code.
=> multicluster: Small tweaks to pkg/config/client for clarity and better logging

pkg/apis/policy/v1alpha1/ingress_backend.go, pkg/catalog/ingress.go, pkg/catalog/ingress_test.go, pkg/catalog/mock_catalog_generated.go, pkg/catalog/types.go, pkg/envoy/lds/ingress.go, pkg/envoy/lds/ingress_test.go, pkg/envoy/lds/response.go, pkg/envoy/rds/response.go, pkg/envoy/rds/response_test.go, pkg/errcode/errcode.go, pkg/trafficpolicy/ingress_types.go, tests/scenarios/traffic_split_with_zero_weight_test.go
This change refactors the ingress code in catalog, envoy/lds|rds
to make it generic enough to work with both the k8s Ingress API
as well as the newly introduced IngressBackend API.
The resulting Envoy config before and after this change should
be the same (with the exception of the filter chain name).
Required for #3779 
=> ingress: refactor code to make it extendable for IngressBackend API

pkg/service/types.go, pkg/service/types_test.go
This PR is an attempt to improve the readability of FQDN().  But most importantly - test it and show what it produces.
=> service: Simplify and test MeshService.FQDN()

charts/osm/README.md, charts/osm/templates/osm-gateway-deployment.yaml, charts/osm/values.schema.json, charts/osm/values.yaml
Add support to customize the multicluster gateway port number.
Issue #3804 
| CI …
=> feat(multicluster): customize multicluster gateway port

.github/workflows/main.yml, Makefile
Adds a build target and check in the CI to ensure
autogenerated Go clients for APIs are always up to
date to avoid issues similar to the one fixed in 60fa3075.
Also collapses the check for `go mod tidy` into the
`codegen` job.
=> codegen: add build target and CI check

pkg/envoy/sds/response_test.go
This change fixes the following test bugs:
1. Requested SDS secrets do not correspond to the proxy's
namespaced service account name.
2. XDS cert CN is not fully qualified with the trust domain.
As a result of these bugs, the test expectation was also incorrect,
which is resolved in this change.
=> sds/test: fix test bug and expectation

.github/workflows/nightly-noinstall.yml, scripts/kind-with-registry.sh, tests/e2e/e2e_http_ingress_test.go, tests/framework/common.go
This commit increase the node count for kind cluster used in the CI.
=> Update node count for kind cluster on CI

CONTRIBUTING.md
We have already been allowing the squash & merge
option to maintainers and contributors via
the github merge option or using the automerge-squash
label. This has been working fine so document this
as an option available to users.
Previously there was a concern about the original author's
signature being altered, but this is not
a problem given the DCO check ensures the commit was
created with a valid signature. Maintainers only
need to ensure they preserve the signatures of the
original authors when squashing and merging. …
=> contributing: update merging guideline

pkg/injector/test/test_helpers.go
Removes an unused pkg variable and changes the prefix
for the output test directory so it can be easily removed.
/tmp might contain other dirs starting with `envoy`, so deleting
by the existing prefix is not desirable.
=> injector/test: remove unused var and change test dir prefix

cmd/cli/install.go, cmd/cli/install_test.go
Makes error messages more clear about existing meshes when there is an existing mesh that conflicts with the new install.
| Upgrade …
=> ref(install): Log namespace for existing mesh

DESIGN.md
This change fixes a broken link from DESIGN.md to the high-level
OSM architecture diagram.
Fixes #3833
| CI System                  | …
=> docs(DESIGN.md): fix broken link

charts/osm/README.md, charts/osm/crds/config_meshconfig.yaml, charts/osm/templates/preset-mesh-config.yaml, charts/osm/templates/prometheus-configmap.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, cmd/init-osm-controller/init-osm-controller_test.go, pkg/apis/config/v1alpha1/mesh_config.go, pkg/envoy/cds/cluster.go, pkg/envoy/cds/cluster_test.go, pkg/envoy/cds/response.go, pkg/envoy/cds/response_test.go, pkg/envoy/lds/healthcheck.go, pkg/envoy/lds/http_connection.go, pkg/envoy/lds/http_connection_test.go, pkg/envoy/lds/inmesh.go, pkg/envoy/types.go
This change adds a new `enableEnvoyActiveHealthChecks` feature flag that
enables OSM to program upstream clusters with health checks. When
enabled, it will also add the health check HTTP filter to upstream
proxies which will respond to health check requests.
The actual health check configuration is not currently parameterized, so
all health checks will have this configuration:
{
"health_checks": [
{
"timeout": "1s",
"interval": "10s",
"unhealthy_threshold": 3,
"healthy_threshold": 1,
"http_health_check": {
"host": "<upstream cluster>",
"path": "/healthz/osm",
"request_headers_to_add": [
{
"header": {
"key": "x-osm-envoy-healthcheck",
"value": "1"
}
}
]
}
}
]
}
Fixes #3042
| New …
=> feat(*): add Envoy active health checks

.github/workflows/openshift-nightly.yml
Fixes #3805
Adds the demo to the OSM OpenShift nightly job.
After verifying that this passes for a few days, I will create a follow up PR to use Github Actions [templates](https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization) so that the nightly job stays in sync with the PR gates.
| …
=> test(openshift): Add demo to OpenShift nightly job

cmd/osm-controller/osm-controller.go, pkg/envoy/ads/stream.go, pkg/metricsstore/metricsstore.go
**Description**: Add metric for number of reconnects from known proxies to OSM controller
| CI …
=> feat(metrics): proxy reconnect count

.github/workflows/openshift-nightly.yml, demo/run-osm-demo.sh
**Description**: Add a "PUBLISH_IMAGES" flag for the osm demo, and skip the step to publish images for the OpenShift nightly job. 
| …
=> feat(demo): add 'publish_images' flag

tests/e2e/README.md
**Description**: Add section to e2e readme detailing the different installType values. 
| CI System …
=> docs(e2e): Add installType section

cmd/osm-controller/gateway.go, pkg/envoy/xdsutil.go, pkg/envoy/xdsutil_test.go, pkg/multicluster/gateway.go, pkg/multicluster/gateway_test.go
This PR creates `GetMulticlusterGatewaySubjectCommonName()` to centralize the creation of Common Names for certificates for Multicluster Gateways.
In this PR - adding `GetKindFromProxyCertificate()` to get the proxy kind from said certificate.
=> multicluster: Adding GetMulticlusterGatewaySubjectCommonName()

.github/workflows/main.yml, pkg/envoy/xdsutil_test.go, pkg/multicluster/gateway_test.go, tests/scenarios/helpers.go, tests/scenarios/multicluster_gateway__lds__test.go, tests/scenarios/traffic_split_with_apex_service_test.go
This PR adds a test for the LDS portion of OSM's Multicluster implementation.
This PR is stacked on #3857 (`GetMulticlusterGatewaySubjectCommonName`)
This PR also moves the following functions out `tests/scenarios/traffic_split_with_apex_service_test.go` of and into the new `tests/scenarios/helpers.go`:
-  `func toInt(val uint32) *wrappers.UInt32Value {`
- `func weightedCluster(serviceName string, weight uint32) *xds_route.WeightedCluster_ClusterWeight {`
- `func getProxy(kubeClient kubernetes.Interface) (*envoy.Proxy, error) {`
=> multicluster: Test LDS

pkg/catalog/service.go, pkg/catalog/traffictarget.go, pkg/envoy/rds/response.go, pkg/envoy/rds/route/route_config.go, pkg/envoy/sds/response.go, pkg/errcode/errcode.go
Adds error codes for errors related to Envoy RDS and SDS.
Part of #2866
| Demo …
=> pkg/envoy/*: add error codes for Envoy RDS and SDS

.github/workflows/main.yml, .golangci.yml, Makefile
This rule appeared to have had two issues prior to this PR.
1. It did not run correctly/successfully:
```
$ make go-lint
go run github.com/golangci/golangci-lint/cmd/golangci-lint run --config .golangci.yml
../../go/pkg/mod/github.com/golangci/golangci-lint@v1.32.2/pkg/golinters/unused.go:16:7: undefined: unused.NewChecker
make: *** [Makefile:140: go-lint] Error 2
```
2. The version of golangci-lint that this was using (1.32) was not the same as the version for CI (1.30). These versions should be the same so that the local experience matches the CI pipeline.
This PR fixes both of these points by checking the currently installed golangci-lint bin. If it does not exist or if it is not the CI version (1.30) then it will install it. After that, it will lint with the same …
=> Fix broken lint make rule and target the CI golangci-lint version

cmd/osm-controller/osm-controller.go, pkg/ingress/client_test.go, pkg/k8s/fake.go, pkg/smi/health.go, pkg/smi/health_test.go
This change fixes a bug where a pkg scoped map is being
concurrently modified to check if SMI API resources are
available.
Additionally, it refactors the code for clarity and better
unit testing.
Panic trace:
```
goroutine 295 [running]:
runtime.throw(0x1f7c257, 0x15)
/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc000c83740 sp=0xc000c83710 pc=0x438272
runtime.mapdelete_faststr(0x1c43520, 0xc0000aa420, 0xc0006ac1e0, 0xe)
/usr/local/go/src/runtime/map_faststr.go:382 +0x3a8 fp=0xc000c837a8 sp=0xc000c83740 pc=0x414c48
github.com/openservicemesh/osm/pkg/smi.checkSMICrdsExist(0x221cb50, 0xc00094fc98, 0xc0000aa420, 0x30b9a80, 0x4, 0x4, 0x21dc0c0)
/src/projects/osm/pkg/smi/health.go:54 +0x42e fp=0xc000c839b0 sp=0xc000c837a8 pc=0x17f860e …
```
=> smi/health: fix race condition leading to controller crash

charts/osm/README.md, charts/osm/templates/_helpers.tpl, charts/osm/templates/osm-deployment.yaml, charts/osm/templates/osm-validator-service.yaml, charts/osm/templates/osm-validator-webhook.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, cmd/osm-controller/osm-controller.go, cmd/osm-controller/validate.go, cmd/osm-controller/validate_test.go, pkg/constants/constants.go, pkg/health/health.go, pkg/injector/webhook.go, pkg/validator/patch.go, pkg/validator/server.go, pkg/validator/types.go, pkg/validator/validators.go, pkg/validator/validators_test.go, pkg/webhook/webhook.go
This change enables osm-validator, a validating webhook
to validate k8s resources. It addresses existing issues
with the webhook being broken, and updates the name of
the validating webhook and associated flag for clarity
and correctness.
It also updates the min service cert validity duration
to 2 minutes which takes into account the noise added
while performing certificate rotation.
The validations are only enabled for features that have
been tested to work with the validator.
Part of #3281
-   Did you notify the …
=> osm-validator: enable webhook to validate resources

pkg/metricsstore/metricsstore.go, pkg/metricsstore/metricsstore_test.go
Have Help strings start with a capital letter to match with Prometheus default metric Help strings.
| Tests …
=> chore(pkg/metricsstore): make Help string formatted consistently

cmd/cli/support_bugreport.go, pkg/bugreport/archive.go, pkg/bugreport/run.go
Uses tar.gz as the archive format and adds to the existing
help text regarding sensitive information in the bug report.
=> bugreport: use tar.gz archive and expand help text

.github/workflows/openshift-nightly.yml
**Description**: Forgot to add this in my previous PR to run the cleanup script, but we want the cleanup step to run even if the e2es or the demos fail for the OpenShift nightly job. 
| Security …
=> test(openshift/nightly): Always clean up resources

cmd/osm-controller/osm-controller.go, pkg/catalog/dispatcher.go, pkg/metricsstore/metricsstore.go
Adds metrics for the number of ProxyBroadcast events published by
the OSM controller.
| Demo …
=> feat(metrics): proxy broadcast event count

pkg/envoy/ads/stream.go
Unsubscriptions might be requesting less resources from a given number
of resources previously requested:
```
Original logic:
req: [N:-, A, B]
response: [N:1, A, B]
req: [N:1, A, B] (ACK)
envoy unsubscribes from B:
req: [N:1, A]
response: // OSM Never replies as nonce 1 should have already fulfilled this request, as it
// is a superset (already had 'A') from the new resources being requested
```
This is causing issues as it seems that envoy does expect to be replied to.
Changing superset logic to equals will make OSM reply as long as the requested
resources are different from the last sent.
This fix is sitting on top of #3803, as it is needed to properly account for the subscribed and
sent resources in a proper way, for every proxy.
Related to #3775
=> ads: Convert superset logic to equals when computing ACK

pkg/envoy/cds/cluster.go, pkg/envoy/cds/cluster_test.go, pkg/envoy/cds/response_test.go, pkg/injector/envoy_config_health_probes.go, pkg/injector/test_fixtures/expected_envoy_bootstrap_config.yaml, tests/envoy_xds_expectations/actual_output_getProbeCluster.yaml, tests/envoy_xds_expectations/expected_output_getLivenessCluster.yaml, tests/envoy_xds_expectations/expected_output_getProbeCluster.yaml, tests/envoy_xds_expectations/expected_output_getReadinessCluster.yaml, tests/envoy_xds_expectations/expected_output_getStartupCluster.yaml
Windows (unlike linux) does not allow sockets to connect to wildcardIP (0.0.0.0).
So Envoy clusters that use address 0.0.0.0 will fail on Windows workers. With this PR
we change those tests to use localhostIP.
Validated through unit tests and the CI. Fixes #3882
=> feat(windows): Make local clusters use localhostIP instead of wildcardIP

demo/cmd/common/books.go, demo/deploy-bookbuyer.sh, demo/run-osm-multicluster-demo.sh
cluster ID is used in the demo in multicluster mode, which breaks the demo. This is a continuation of #3854 .
| Tests …
=> fix: cluster ID used in demo application

tests/e2e/e2e_permissive_smi_switching.go
Adds an e2e to comprehensibly test switching from SMI to permissive.
Note: This PR is sitting on other PRs. PRs will be individually merged and PRs will be rebased.
This is part of the series of commits for #3775
No
No
=> ads: add e2e for permissive-smi switching

pkg/cli/proxy_get_test.go
This PR fixes a test that was broken (and I merged) with https://github.com/openservicemesh/osm/pull/3881
@shashankram pointed out the fix: https://github.com/openservicemesh/osm/pull/3881/files#r679558826
=> cli: Fixing a broken test

demo/run-osm-multicluster-demo.sh, scripts/create-container-registry-creds.sh
**Description**: Use PRIVATE_REGISTRY flag to skip credential creation step in demo if images are being pulled from a public registry. 
| …
=> chore(demo): Only create creds for private registry

pkg/constants/constants.go, pkg/envoy/proxy_test.go, pkg/injector/envoy_config_test.go, pkg/injector/envoy_container.go, pkg/injector/patch.go, pkg/injector/patch_test.go, pkg/tests/fixtures.go
Addressing PR comments from #3861 we have the two follow ups:
1. Make literal strings "windows" and "linux" into a constant
2. Make the return variables of `getPlatformSpecificSpecComponents` named to
improve readability.
=> chore(injector): Reduce tech debt in osm `/pkg/injector`

pkg/envoy/ads/response_test.go, pkg/envoy/ads/stream.go
PR #3803 introduced a mapset (backed by golang map) to slice conversion,
which does not guarantee same output ordering for the same input,
thus was making a unit test fail from time to time.
This commit forces output of the slice to be alphabetically ordered,
ensuring determinism of the output slice for the same input mapset.
No
No
=> test/ads: fix unit test flakyness

pkg/catalog/service.go
Under the condition of the service disappearing (or not being
present yet due to informer latency), there was a condition
that could try to dereference a nil pointer.
Fixes #3902
No
No
=> GetServiceHostnames: Fix nil pointer dereference

pkg/certificate/providers/tresor/ca.go, pkg/certificate/providers/tresor/ca_test.go, pkg/certificate/providers/tresor/types.go, pkg/constants/constants.go
This change addresses 2 things:
1. Encodes the correct CN used for the root CA cert
when creating a `Certificate` for it.
2. Uses a fully qualified domain name for the root
cert CN instead of an arbitrary string.
| Certificate Management     | [X] |
=> certificate/tresor: fix root CA cert CN

charts/osm/grafana/dashboards/osm-mesh-envoy-details.json
Add grafana metric for maximum and average envoy update time per xDS Path to Mesh and Envoy Details Dashboard under Mesh Statistics
| Observability              | [x ] |
| Upgrade …
=> feat(metrics): max/average proxy config update time

Makefile, charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/templates/preset-mesh-config.yaml, charts/osm/values.schema.json, charts/osm/values.yaml
Allows Contour's ingress gateway and control plane
to be deployed.
Part of #3501 
Tested end-to-end HTTP and HTTPS ingress with Contour using:
```bash
osm install --set OpenServiceMesh.image.tag=$CTR_TAG --set OpenServiceMesh.image.registry=$CTR_REGISTRY --set OpenServiceMesh.image.pullPolicy=Always --set OpenServiceMesh.featureFlags.enableIngressBackendPolicy=true --set contour.enabled=true --set contour.configInline.tls.envoy-client-certificate.name=osm-contour-envoy-client-cert --set contour.configInline.tls.envoy-client-certificate.namespace=osm-system
``` …
=> charts: allow deploying Contour ingress gateway

demo/run-osm-multicluster-demo.sh
Tiny tweak to the Multicluster demo script (`demo/run-osm-multicluster-demo.sh`) to make it a zero-config demo.
=> multicluster: Hardcode env vars in the demo script

docs/example/manifests/samples/httpbin/httpbin.yaml
Simplifies the httpbin spec and makes the port used
consistent across e2e and manual demos.
Ingress to `httpbin` worked as expected
```
curl -sI http://"$ingress_host":"$ingress_port"/get -H "Host: httpbin.org"
HTTP/1.1 200 OK
```
=> example/manifests: update httpbin listen port to 14001

pkg/envoy/rds/response.go, pkg/envoy/rds/route/route_config.go, pkg/envoy/rds/route/route_config_test.go
This is a follow-up to b333f451 where the internal
mesh headers added to the HTTP response for ingress
are removed, so mesh information such as pod names
are not leaked externally.
For example, the following info should not be leaked 
externally with ingress HTTP response.
```
osm-stats-pod: httpbin-7c6464475-bn6x2
osm-stats-namespace: httpbin
osm-stats-kind: Deployment
osm-stats-name: httpbin
```
Tested ingress. …
=> rds/ingress: remove WASM mesh headers

charts/osm/templates/crds-upgrade-hook.yaml
This commit changes the order of hook deletion as helm evaluated them in
ascending order based on weights.
Also the hook has been converted to a job as helm kills the pod before
kubectl exec is run. With job, helm waits until the pod is run and
reached completion.
| …
=> ref(cdrUpgradeHook) : change crd upgrade hook from pod to job

demo/cmd/common/books.go
Due to a limitation of Kubernetes on Windows we need to use the FQDN
otherwise DNS will not be able to resolve the address.
Part of #3886
=> chore(demo): Switch demo to use FQDN

Makefile, demo/cmd/bookbuyer/bookbuyer.go, demo/cmd/bookstore/bookstore.go, demo/cmd/bookthief/bookthief.go, demo/cmd/bookwatcher/bookwatcher.go, demo/cmd/common/books.go
When I'm testing or demo'ing OSM, I am in the terminal. The demo app requires you to use the browser or curl the markup of the different services (bookbuyer, bookthief, etc.). This is very manual and requires some visual grep'ing as well as manual refreshing.
This PR adds a `/raw` route to bookbuyer, bookthief, and bookstore to get their JSON data. It also adds a bookwatcher bin that polls the different raw endpoints and displays the output. The text color is as follows:
* Yellow - data hasn't changed since last poll iteration
* Green - data for bookbuyer and bookstore has changed
* Red - books were stolen by the bookthief since last poll iteration
This refreshes the terminal every second. Below are screenshots showing the experience.
| Functional Area …
=> Add demo book app watcher for terminal and raw JSON from web API

tests/e2e/e2e_k8s_ingress_http_test.go, tests/framework/common.go, tests/framework/types.go
**Description**: Reset the EnableIngressBackendPolicy variable as a part of the setMeshConfigToDefault method. This should address the ingressbackend test failures when NoInstall is enabled. 
| Security …
=> test(e2e): Reset ingressBackend for noInstall

.github/workflows/openshift-nightly.yml
Clean up stage of openshift nightly job fails if e2e fails since there is no .env file for the clean-kubernetes script. This does not occur if the demo step fails since that already performs the `touch .env` step.
Example of failing step: https://github.com/openservicemesh/osm/runs/3236304092?check_suite_focus=true
| Networking …
=> fix(openshift): Create env file for cleanup

charts/osm/templates/cleanup-hook.yaml, charts/osm/templates/crds-upgrade-hook.yaml
Update the pre-delete clean up hook in osm to patch the crds, removing
the conversion webhook instead of deleting them on uninstall.
Fixes #3760
| Upgrade …
=> crdUpgrades: Update osm clean up hook to patch osm crds instead of deleting them

charts/osm/README.md, charts/osm/templates/osm-bootstrap-deployment.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, cmd/osm-bootstrap/osm-bootstrap.go, pkg/constants/constants.go, tests/framework/common_apps.go
Updated naming for `crdConverter` to `osmBootstrap` as needed.
| CI System …
=> chore(crdConverter): Rename crd converter to osm bootstrap

cmd/osm-controller/osm-controller.go, pkg/validator/server.go, pkg/validator/server_test.go, pkg/validator/validators.go, pkg/validator/validators_test.go
- Fixes the scoping of types only required within the
pkg to not be exported.
- Removes unused code for MeshConfig which is not being
validated and cannot because of being in the same namespace
as the validating webhook, which would result in race
conditions similar to the ones observed with osm-config
ConfigMap and it's corresponding validating webhook.
- Removes unnecessary complexity with default validators.
=> validator: fix scoping and remove unused code

cmd/cli/proxy_get.go
Currently, `osm proxy get` is truncating output after around 160K on my
Mac. While trying to figure out where the problem was, I found using
`Write` instead of `WriteString` fixed it for reasons I don't
understand. Removing the intermediate `bufio.Writer` is just an extra
simplification.
| SMI Policy                 | …
=> fix(cli): fix proxy get command truncating output

README.md
Fix deprecated urls in readme. All the previous urls with `tasks_usage` are deprecated due to the changes in https://github.com/openservicemesh/osm-docs
| Tests …
=> docs(README.md): fix deprecated urls in readme

.github/workflows/nightly-images.yml, .github/workflows/nightly-noinstall.yml, .github/workflows/openshift-nightly.yml
**Description**: Create a nightly images job to push OSM images to dockerhub with tag `latest-main`. After this succeeds, it will trigger the nightly-noinstall job and openshift-nightly job. 
Resolves https://github.com/openservicemesh/osm/issues/3961
| SMI Policy                 | [ …
=> test(pipeline): Push latest-main images nightly

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/templates/osm-deployment.yaml, charts/osm/templates/osm-injector-deployment.yaml, charts/osm/values.yaml, pkg/catalog/outbound_traffic_policies.go, pkg/catalog/outbound_traffic_policies_test.go
This change backports ada49d0d, d2e01b0f, and a4c20d8e
for release v0.9.2.
=> [backports] Fixes for permissive mode, replicas, k8s version check

charts/osm/crds/config_multicluster_service.yaml, pkg/apis/config/v1alpha1/multi_cluster_service.go
Add `weight` attribute to remote cluster spec. This PR prepares for implementing locality based routing. 
| New Functionality          | X |
| Tests …
=> feat(multicluster): add weight to RemoteCluster

pkg/envoy/ads/stream.go
Description:
Backport commit : c32f3c5
Theres a misshandle of XDS resources as our full config push could record we sent some
resources that could be ignored by envoy if envoy is still not interested in them.
Later requests from envoy for that resource and that nonce could ask for resources we have
already sent but were ignored at a previous time, hence making a request an ACK which is not.
This commit prevents pushing certificates on full config updates, which will make SDS almost
entirely envoy-driven; it will prevent us pushing unnecessary certificates that envoy did not
request, hence never potentially allowing us to send ignored resources at a response.
Signed-off-by: Eduard Serra eduser25@gmail.com
-   Did you …
=> [backport] Do not send SDS on full config updates

Makefile
Avoids a prompt if the file already exists.
```
LITE=1 -I/sdk -I/usr/local/include --js-library /sdk/proxy_wasm_intrinsics.js stats.cc /sdk/proxy_wasm_intrinsics_lite.pb.cc /sdk/struct_lite.pb.cc /sdk/proxy_wasm_intrinsics.cc /sdk/libprotobuf-lite.a -o stats.wasm
mv: replace 'pkg/envoy/lds/stats.wasm', overriding mode 0755 (rwxr-xr-x)?
```
=> Makefile: avoid prompt while overwriting file

charts/osm/README.md, charts/osm/values.schema.json, charts/osm/values.yaml, cmd/osm-bootstrap/osm-bootstrap_test.go, docs/example/manifests/meshconfig/mesh-config.yaml, pkg/configurator/methods_test.go, pkg/constants/constants.go
Updates the envoy version to v1.19.0 for both
OSM's sidecar and Contour's edge proxy.
Contour 1.18 uses Envoy v1.19.0 by default, but
the Bitnami Helm charts weren't updated to reflect
this change yet. This change also overrides Contour's
envoy image to match the [default upstream version](https://github.com/projectcontour/contour/blob/v1.18.0/examples/render/contour.yaml#L3107) so
that the same version of envoy is used for both the
sidecar and ingress gateway.
Tested ingress with Contour.
-   Did you …
=> envoy: update version to v1.19.0

charts/osm/README.md, charts/osm/values.yaml
By default, the Bitnami Helm chart for Contour
uses an image from the Bitnami repo, which is
not the image officially used by projectcontour
upstream. This change uses the [default upstream
image](https://github.com/projectcontour/contour/blob/release-1.18/examples/render/contour.yaml#L2721) and registry for the Contour controller.
```
$ helm template charts/osm/ --set contour.enabled=true  | grep image.*contour
image: docker.io/projectcontour/contour:v1.18.0
```
- …
=> charts/osm: use official Contour image

pkg/envoy/ads/stream.go
This PR backports 9507072.
In SotW protocol variants, unsubscriptions are communicated by the client
(proxy) by removing the specific resource from the resources requested list.
https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#unsubscribing-from-resources
This seems to not work well with our superset diff logic as it seems that
envoy does expect to be replied to anytime the set of resources change from,
even if the previous reply could have already covered the new set of requested
resources.
Changing superset logic to equals will make OSM reply as long as the requested
resources are different from the last sent under any circumstance (adding or removing
subscribed resources).
**Affected …
=> [backport] ads: change resource difference condition from superser to equals

tests/e2e/e2e_permissive_smi_switching.go
Backport commit : https://github.com/openservicemesh/osm/pull/3887/commits/2ec925fd698b54c159985b92e450d0f32deb2869
Adds an e2e to comprehensibly test switching from SMI to permissive.
This is part of the series of commits for #3775
=> [backport] ads: add e2e for permissive-smi switching

pkg/configurator/client.go, pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/configurator/types.go, pkg/k8s/client.go, pkg/k8s/types.go, pkg/providers/kube/client.go, pkg/providers/kube/client_test.go, pkg/providers/kube/multiclusterservice.go, pkg/providers/kube/multiclusterservice_test.go, pkg/providers/kube/types.go
Un-exports the struct types that are implementing
an interface because consumers should not be directly
interacting with the internal interface implementation.
=> pkg/*: un-export k8s client implementing interface

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/crds/meshconfig.yaml, charts/osm/values.yaml, cmd/cli/mesh_upgrade.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml, docs/example/manifests/meshconfig/mesh-config.yaml, pkg/configurator/methods_test.go, pkg/constants/constants.go
Is this a release candidate? `yes`
=> chore(release): update image version to v0.9.2-rc.1

charts/osm/README.md, charts/osm/templates/preset-mesh-config.yaml, charts/osm/values.yaml
Removed `tracing.address` field from values.yaml. Tracing address should be generated by `osm.tracingAddress` helper function.
| Upgrade                    | [ …
=> chore: use osm.tracingAddress in preset-mesh-config

charts/osm/templates/crds-upgrade-hook.yaml
Adds a PSP for the crds-upgrade-hook. This change allows OSM to be
installed on a PSP-enabled cluster.
| Install                    | [ x ] |
| Security                   | [ x ] |
| CI System …
=> fix(crds-upgrade): add psp for crds-upgrade-hook

pkg/errcode/errcode.go, pkg/ingress/client.go, pkg/ingress/client_test.go
If a candidate API GroupVersion (ex. networking.k8s.io/v1beta1) is not
available, don't error. Only error if none of the candidates are
available (already the case).
This is required for OSM to work in k8s v1.22, where the
networking.k8s.io/v1beta1 is deprecated.
=> ingress: don't error if candidate group version is not available

pkg/ingress/client.go, pkg/ingress/client_test.go
Backports f96e93d9 to allow v0.9.2 to work with v1.22
of k8s.
=> [backport] ingress: don't error if candidate group version is not available (#4007)

pkg/certificate/providers/tresor/certificate_manager_test.go
Added test for cert manager for a nil ca Fixes #3437
**Testing done**: yes
| …
=> Added test for cert manager

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/crds/meshconfig.yaml, charts/osm/values.yaml, cmd/cli/mesh_upgrade.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml, docs/example/manifests/meshconfig/mesh-config.yaml, pkg/configurator/methods_test.go, pkg/constants/constants.go
Is this a release candidate? `no`
=> chore(release): update image version to v0.9.2

tests/framework/common.go, tests/framework/common_apps.go
Removes dependency on oc binary by using the client-go API directly to program SecurityContextConstraints for OpenShift
Fixes #3999  …
=> feat(e2e): Remove dependency on oc for SCC

cmd/cli/env.go, cmd/cli/mesh.go, cmd/cli/osm.go, pkg/cli/environment.go, pkg/cli/environment_test.go
Provides the capability to override default namespace
and commands in osm cli. This is required to provide
a better experience of osm cli in managed environments,
where users can be advised to use a config file to to override
defaults.
It works as follows:
1. If osm config file is present, either in $HOME/.osm/config
or specified via the OSM_CONFIG env var, this file will be
used for environment defaults. This works similar to
KUBECONFIG where the env variable overrides the static
file if present.
2. If osm config file is not present, defaults values are
used for the environment configurations.
3. If the install kind is set to `managed` in the config file,
then install/uninstall/upgrade/dashboard commands which
are only meant for self-hosted environments are disabled. …
=> cli: provide environment override capability

cmd/cli/policy_check_pods.go, pkg/cli/policy_check.go
**Description**: Extracts helpers to be reused by osm-health: https://github.com/openservicemesh/osm-health/pull/69
| Sidecar …
=> ref(cli): extract policy check-pod helpers into pkg/cli for reuse

pkg/apis/policy/v1alpha1/ingress_backend.go, pkg/catalog/ingress.go, pkg/catalog/ingress_test.go, pkg/validator/validators.go, pkg/validator/validators_test.go
To secure ingress traffic, OSM requires a source to be
specified in an IngressBackend configuration, which
can reference a k8s service within the cluster whose
endpoints are authorized to connect to the backend.
Some ingress solutions such as Azure Application Gateway
do not create a k8s service object to represent the gateway
instance. This change provides the facility to specify an
IP address range as a source so that a source IP range
can be specified to connect to a backend.
Part of #3779
Unit testing …
=> ingress: allow IPRange as a source in IngressBackend

pkg/certificate/providers/config_test.go
Adds unit tests to config.go
and resolves #3425
**Testing done**: N/A
| Sidecar …
=> test(pkg/certificate/providers): add tests to config file

tests/framework/common.go
Make enablePrivilegedInitContainer configurable so that release-v0.9 tests can run on openshift
Ran 
```
go test ./tests/e2e -test.v -ginkgo.v -ginkgo.progress -ginkgo.focus="\bDeploymentsClientServer\b" -deployOnOpenShift=true
```
| Networking …
=> backport(e2e): Configure privileged init container

charts/osm/README.md, charts/osm/crds/config_meshconfig.yaml, charts/osm/templates/preset-mesh-config.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, pkg/envoy/bootstrap/config.go, pkg/envoy/bootstrap/config_test.go, pkg/injector/test_fixtures/expected_envoy_bootstrap_config.yaml, tests/e2e/e2e_egress_test.go, tests/framework/common.go, tests/framework/common_apps.go, tests/framework/common_traffic.go, tests/framework/constants.go, tests/framework/types.go
This PR modifies the `e2e_egress_test` to be able to run on Windows nodes
Verified locally in an AKS cluster:
```
Ran 1 of 42 Specs in 471.548 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 41 Skipped
--- PASS: TestSuite (471.56s)
``` …
=> feat(windows): Make Egress test pass on Windows

pkg/catalog/outbound_traffic_policies.go, pkg/catalog/outbound_traffic_policies_test.go, pkg/envoy/rds/route/route_config.go, pkg/envoy/rds/route/route_config_test.go, pkg/trafficpolicy/trafficpolicy.go, pkg/trafficpolicy/types.go
Gets annotations from TrafficTargets policy to create retry policy
and resolves #3339
| New Functionality          | [ x] |
| Tests                      | …
=> feat(*): get annotations for retry policy

cmd/cli/install.go, cmd/cli/osm.go, pkg/cli/environment.go
**Description**: Add debug flag to OSM cli to log verbose output when enabled. 
| CI System …
=> feat(cli): add verbose flag

pkg/catalog/service.go, pkg/certificate/providers/tresor/ca.go, pkg/envoy/ads/debugger.go, pkg/envoy/ads/stream.go, pkg/envoy/lds/gateway.go, pkg/injector/envoy_config_test.go, pkg/injector/health_probes.go, pkg/injector/test/test_helpers.go, pkg/providers/kube/client.go, pkg/providers/kube/multiclusterservice.go
`log.Err(err).Msg()` results in Info
`log.Error().Err(err).Msg()` does the right thing and emits an Error()
Script to fix this:
```bash
perl -p -i -e 's/log\.Err\(/log.Error().Err(/g' $(grep -Iir "log.Err(" $(find . -name "*.go") | awk -F: '{print $1}')
```
Before:
After:
=> log: Fixing Err() statements - change from Info to Error

charts/osm/templates/osm-multicluster-gateway-service.yaml, demo/deploy-MultiClusterService.sh
Update multicluster demo to use the external ip of
osm-multicluster-gateway service rather than the pod ip. This removes
the limitation of the clusters being in the same vnet
Part of #3456
Manually ran the multicluster demo on two clusters that are not in the same Vnet and verified that the demo ran as expected.
| Ingress …
=> (multicluster) : update gateway ip to osm-multicluster-gateway external ip

tests/e2e/e2e_permissive_test.go
Adds an e2e test to validate a random pod outside of the mesh cannot 
successfully communicate with a pod running within a mesh in permissive
mode.
Resolves #3910
| SMI Policy …
=> test(e2e): ensure only meshed pods can communicate in permissive mode

cmd/osm-controller/validate_test.go, pkg/catalog/debugger.go, pkg/catalog/debugger_test.go, pkg/debugger/mock_debugger_generated.go, pkg/debugger/types.go, pkg/envoy/ads/secrets.go, pkg/envoy/xdsutil.go, pkg/k8s/client.go, pkg/k8s/event_handlers_test.go, pkg/service/types.go, pkg/service/types_test.go, pkg/smi/health_test.go
Update the existing tests to use go testing and improve coverage to 80%
Part of #1704 and #1489
Unit tests updated 
| SMI Policy …
=> tests: Update tests to use Go Testing

pkg/smi/client.go, pkg/smi/client_test.go, pkg/smi/fake.go, pkg/smi/mock_meshspec_generated.go, pkg/smi/types.go
There is a use case to only get a subset of items in the
cache for TrafficTarget and TrafficSplit resources based
on certain fields being set on the resources. This change
implements optional filters that clients can use to filter
the returned items from the cache without needing to define
additional functions. With this change, the TrafficTarget
cache can be filtered based on the destination identity,
and the TrafficSplit cache can be filtered based on the
apex and backend service.
Required for #4052
Unit tests
1. Does this change contain …
=> pkg/smi: allow filter options while listing items in cache

pkg/catalog/endpoint.go, pkg/catalog/endpoint_test.go, pkg/catalog/mock_catalog_generated.go, pkg/catalog/types.go, pkg/envoy/eds/response.go
Currently, permissive mode bypasses EDS and uses Envoy's
OriginalDestination cluster for service discovery.
As a part of implementing support for TrafficSplit in
permissive mode, permissive mode will also leverage
EDS for endpoint discovery. The existing API leveraged
by EDS to discover the endpoints of a service are
not usable for permissive mode, so this change adds
support for the same.
This change also renames the function for clarity
and removes an implicit comment.
Required by #4052 and #2527.
Unit tests and verified permissive mode with local changes.
1. Does this …
=> endpoints: don't filter service endpoints in permissive mode

demo/deploy-mysql.sh, docs/example/manifests/apps/mysql.yaml
Files in docs/example/manifests are to be used by following
documentation for manual demo, rather than be exectued by automated
demo. Thus the content in the manifest files need to be complete.
This change completes the MySQL deployment manifest file, and updates
the automated demo script accordingly.
The updated docs/example/manifests/apps/mysql.yaml will be referred from manual demo doc page.
Related issue #3932 
CI test to ensure automated demo is not broken.
| Demo …
=> chore: rearrange content in mysql deployment script

demo/cmd/bookbuyer/bookbuyer.go
This PR fixes a small log issue, where the `bookbuyer` pod claims it is `bookstore`, which is not true.
The fix generalized the message to announce that a 'Web server' is running, not specifically bookbuyer or a booskstore.
Example:
=> demo: Fixing incorrect log line - should be generalized to 'web server'

cmd/osm-controller/osm-controller.go, pkg/catalog/endpoint.go, pkg/catalog/endpoint_test.go, pkg/catalog/errors.go, pkg/catalog/ingress.go, pkg/catalog/mock_catalog_generated.go, pkg/catalog/outbound_traffic_policies.go, pkg/catalog/outbound_traffic_policies_test.go, pkg/catalog/service.go, pkg/catalog/service_test.go, pkg/catalog/traffictarget.go, pkg/catalog/traffictarget_test.go, pkg/catalog/types.go, pkg/constants/constants.go, pkg/endpoint/mock_endpoint_provider_generated.go, pkg/endpoint/types.go, pkg/envoy/eds/response.go, pkg/envoy/sds/response.go, pkg/envoy/sds/response_test.go, pkg/providers/kube/client.go, pkg/providers/kube/client_test.go, pkg/providers/kube/errors.go, pkg/providers/kube/fake.go, pkg/providers/kube/multiclusterservice.go, pkg/providers/kube/multiclusterservice_test.go, pkg/providers/kube/types.go, pkg/service/mock_service_provider_generated.go, pkg/service/types.go
This change simplifies function signatures when a slice
is being returned to the caller by letting the caller
of the function decide on error conditions. In a lot
of cases, nil error values are always being returned
by many functions, and in cases where an error is returned
results in duplicate errors being propagated and logged 
across the call stack. 
Removing unnecessary error paths simplifies
the code and makes it easier to test.
2. Is this a breaking …
=> pkg/*: simplify interface function signatures

pkg/envoy/eds/response.go, pkg/errcode/errcode.go
A lot of unused error paths were cleaned up as a
part of refactoring efforts. This change removes
unused error codes.
=> errcode: remove unused error codes

pkg/envoy/lds/egress.go, pkg/envoy/lds/ingress.go, pkg/envoy/lds/inmesh.go, pkg/envoy/xdsutil.go, pkg/envoy/xdsutil_test.go
Adds a helper to convert IP CIDR represented as a string
to an XDS CidrRange object, to avoid code duplication.
=> envoy: add helper to convert IP CIDR string to XDS object

charts/osm/templates/preset-mesh-config.yaml
The preset-mesh-config resource was not namespaced.
Resolves #4083
=> charts/osm: add namespace to preset-mesh-config resource

tests/e2e/e2e_ignore_namespace_test.go
This test verifies that the ignore label on a namespace resource
takes precedence over the values of the monitored-by label and the
sidecar injection annotation if they have been applied to a Ns.
The ignore label prevents sidecar injection from occurring in the
namespace the label is applied to.
| …
=> feat(e2e): ensures namespace ignore label takes precedence

pkg/envoy/eds/cluster_load_assignment.go, pkg/envoy/eds/cluster_load_assignment_test.go, pkg/envoy/eds/response.go
It's possible for a cluster created via CDS to have no endpoints,
such as an apex service referenced in a traffic split resource
that is not backed by any pods. Respond to the EDS request
for such a cluster with no endpoints so that Envoy does
not keep requesting for it.
Also updates the test to check for all fields in the expected
cluster load assignment.
Without this change, Envoy will keep requesting for the missing
EDS resource and the following log will be seen repeatedly:
```
":"response.go:55","message":"Endpoints not found for upstream cluster bookstore/bookstore|14001 for proxy identity bookbuyer.bookbuyer.cluster.local, skipping cluster in EDS response"}
```
Locally verified the change.
| …
=> envoy/eds: respond to EDS request for cluster with no endpoints

Makefile, demo/run-osm-demo.sh, demo/run-osm-multicluster-demo.sh, dockerfiles/Dockerfile.bookbuyer.windows, dockerfiles/Dockerfile.bookstore.windows, dockerfiles/Dockerfile.bookthief.windows, dockerfiles/Dockerfile.bookwarehouse.windows, dockerfiles/Dockerfile.tcp-client.windows, dockerfiles/Dockerfile.tcp-echo-server.windows, scripts/publish-image.sh
Adds the makefile definitions and the checks to build Windows based
demo containers on the CI.
Fixes #3880
=> feat(windows): Adds demo containers based on Windows

demo/cmd/common/books.go
This PR fixes the URL of the `warehouse` pod, which currently has the name and namespace of the warehouse service transposed.
Example of the error observed on `bookstore` pod (which connects to bookwarehouse):
```bash
12:45AM ERR RestockBooks: Error posting to http://sim-run-bd6eace2-2398-4b73-8182-d20880aa2e10-warehouse.bookwarehouse.svc.cluster.local:14001/restock-books error="Post \"http://sim-run-bd6eace2-2398-4b73-8182-d20880aa2e10-warehouse.bookwarehouse.svc.cluster.local:14001/restock-books\": dial tcp: lookup sim-run-bd6eace2-2398-4b73-8182-d20880aa2e10-warehouse.bookwarehouse.svc.cluster.local on 10.0.0.10:53: no such host" component=demo file=books.go:114
```
In `http://sim-run-bd6eace2-2398-4b73-8182-d20880aa2e10-warehouse.bookwarehouse.svc.cluster.local`:
- …
=> demo: Correct Warehouse service name and namespace (order in URL)

charts/osm/templates/preset-mesh-config.yaml
Backports 22f70495 from main.
...
The preset-mesh-config resource was not namespaced.
Resolves #4083
=> [backport] charts/osm: add namespace to preset-mesh-config resource (#4084)

pkg/envoy/eds/response.go
When generating the EDS response for all upstream
endpoints that the downstream proxy is allowed to
access, create an EDS response for a service without
endpoints as well. This is similar to 78455da0 which
allowed the XDS state machine to converge when there
are CDS clusters that use EDS for endpoint discovery.
Locally tested the demo.
=> envoy/eds: respond with endpoints for all services

tests/framework/common.go, tests/framework/common_apps.go, tests/framework/types.go
Optionally retries on app pod creation failure when the
webhook configuration is not processed by the API server
on time. This is required as a workaround due to potential
delays in the k8s API server to process the updated webhook
configuration after osm-injector patches the webhook.
If this change does not address #3973, it should be reverted.
A large number of test iterations is required to verify this
change in the CI.
Potential fix for #3973. 
-   Did you notify the maintainers …
=> tests/framework: optionally retry on pod creation failure

charts/osm/crds/config_multicluster_service.yaml, demo/deploy-MultiClusterService.sh, demo/multicluster-fault-injection.sh, demo/run-osm-multicluster-demo.sh, pkg/apis/config/v1alpha1/multi_cluster_service.go, pkg/endpoint/types.go, pkg/envoy/eds/cluster_load_assignment.go, pkg/envoy/eds/cluster_load_assignment_test.go, pkg/providers/kube/client_test.go, pkg/providers/kube/multiclusterservice.go, pkg/providers/kube/multiclusterservice_test.go
Multicluster mode support locality based load balancing. [Here is the POC](https://github.com/openservicemesh/osm/issues/3557). Traffic will be balanced to remote clusters when local cluster starts to lose available workloads.
[Here is the design doc for this feature](https://docs.google.com/document/d/1OxDPYkdffEJmraSMZpl83JOt3Kjxjfmoehp4T1ebpfs/edit#).
In this PR, we have some assumptions.
* Local endpoints have priority of 0, which is the highest priority
Related issue: #3043 
After adding this feature, in the original multicluster demo, traffic will be 100% routed to alpha cluster.  Locality based LB starts to work when the workload availability of the highest priority subset drops to below 71% (by Envoy default). To …
=> feat(multicluster): config cluster LB weight

cmd/cli/util.go, cmd/cli/util_test.go
chore(cli): Refactor, add tests, & export for osm-health
Refactors common code that will be used by osm-health.
| SMI Policy …
=> chore(cli): Refactor, add tests, & export for osm-health

tests/e2e/e2e_osm_reinstall_test.go
This change adds a new e2e test that installs OSM, deletes it, then
reinstalls OSM in the same namespace with the same mesh name to verify
deleting OSM doesn't prevent a new control plane from successfully
coming up.
Fixes #1851
Ran the test locally
| …
=> tests(e2e): add cleanup test

pkg/envoy/eds/cluster_load_assignment.go, pkg/envoy/eds/cluster_load_assignment_test.go
Remove weight assignment to local endpoints. 
By default without any assignment, traffic will be equally balanced among local cluster.
Resolves issue #4092
Deployed books demo to testing cluster. Scaled bookstore-v1 deployment to 10 pods. 
Traffic is balanced among 10 pods, observed from logs.
Also fetched endpoints information from booksbuyer:
```
> osm proxy get clusters bookbuyer-684b97dfb5-f7kqc -n bookbuyer | grep weight
bookstore/bookstore-v1|14001::10.244.1.19:14001::weight::1
bookstore/bookstore-v1|14001::10.244.0.25:14001::weight::1
bookstore/bookstore-v1|14001::10.244.0.26:14001::weight::1
bookstore/bookstore-v1|14001::10.244.0.28:14001::weight::1 …
```
=> fix: remove weight assignment to local endpoints

charts/osm/README.md, charts/osm/values.yaml
**Description**: Increase memory limit for the osmBootstrap container. On OpenShift, the memory limit was not sufficient for the bootstrap container, which was causing it to crash. 
Resolves issue #4099 
**Testing done**: Tested locally on OpenShift and pod was no longer crashing. 
| …
=> chore(bootstrap): increase memory limit

cmd/osm-bootstrap/osm-bootstrap.go, pkg/errcode/errcode.go, pkg/injector/webhook.go, pkg/reconciler/client.go, pkg/reconciler/crd_handler.go, pkg/reconciler/crd_handler_test.go, pkg/reconciler/errors.go, pkg/reconciler/mutating_webhook.go, pkg/reconciler/mutating_webhook_handler.go, pkg/reconciler/mutating_webhook_handler_test.go, pkg/reconciler/types.go
Add a reconciler client that initializes infromers to track changes to
the crds and mutating webhook that osm manages.
Add handlers to manage the reconcilialtion of crds and mutating webhook
in osm.
Note: This PR doesn't integrate the reconciler with OSM yet, there will up a follow up PR for this and it will be feature flagged.
Part of #4065
**Testing done**: unit tests added 
| Control Plane              | [] | …
=> feat(reconciler): Add reconciler client, informers and reconcile logic to osm

.github/workflows/windows-nightly.yml, tests/e2e/e2e_egress_test.go, tests/framework/common.go, tests/framework/types.go
Fixes #3883 Adds a nightly job for Windows tests.
Cluster is installed via AKS-engine on the CNCF subscription.
| SMI Policy …
=> feat(Windows): Add Windows nightly job

CONTRIBUTING.md
+ add table of contents
+ add language identifiers to code blocks
+ add blank lines around code blocks to make code blocks easier to read (best practice)
+ add blank lines around headings (best practice)
resolves #1764
| Documentation              | [X ] |
| Networking …
=> add section on attribution to CONTRIBUTING.md

cmd/cli/uninstall.go
This change removes the `-p/--local-port` flag on the `osm uninstall`
command which was never referenced.
ran cmd/cli unit tests
| Security …
=> ref(cli): remove unused port parameter on osm uninstall

.github/workflows/windows-nightly.yml
Fix typo that caused the pipeline to not be scheduled yesterday
=> chore: Fix typo in windows-nightly

cmd/osm-controller/osm-controller.go
Removes metrics store initialization of certificate
issuance metrics for the osm-controller. Cert issuance
metrics are currently initialized by osm-controller but
never updated. Thus, the cert issuance metrics are always
zero.
Certificate issuance metrics are instead maintained by
osm-injector.
| Ingress …
=> chore: remove osm-controller cert issuance metrics

charts/osm/README.md, charts/osm/values.yaml, pkg/apis/config/v1alpha1/mesh_config.go
Adds a note to the description of the LogLevel value. This change
clarifies that the envoy log level should not be set by non-developers.
In production environments, the LogLevel should be set to `error`.
Addresses #2754
| Documentation              | [ x ] |
| …
=> docs(envoy): update docs for sidecar LogLevel

pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/constants/constants.go, pkg/injector/patch.go, pkg/injector/patch_test.go, pkg/injector/webhook_test.go
This change enforces that images configured by
the user or install time defaults are always
used at the time of sidecar injection.
Previously, default images were encoded in the
configurator which posed a security risk of
not using configured images in case those
values are unavailable in MeshConfig and the user
overrides the defaults. It's common practice for
users to use their own images from secure registries
of their choice, so OSM must enforce that. This problem
is made worse by the fact that OSM could silently use
defaults that the user is unaware of without raising
any warnings or approval from the user, which can
compromise their security requirements.
This change is also required to address #3715 where
default image digests will be encoded in the CLI
as a part of …
=> injector: enforce using configured images

demo/clean-kubernetes.sh
Add `$TIMEOUT` variable so that the script can be run independently 
| Sidecar …
=> chore(clean-kubernetes.sh): add timeout variable to run script independently

Makefile, dockerfiles/Dockerfile.osm-bootstrap
The initial reconciler design needed the original crds to compare for
the reconciler logic, given that the current implementation no longer
needs this it is being removed.
Part of #4065 
=> feat(reconciler): remove copying of crds in osm-bootstrap image

cmd/osm-bootstrap/crds/config_meshconfig.yaml, cmd/osm-bootstrap/crds/config_multicluster_service.yaml, cmd/osm-bootstrap/crds/policy_egress.yaml, cmd/osm-bootstrap/crds/policy_ingress_backend.yaml, cmd/osm-bootstrap/crds/smi_http_route_group.yaml, cmd/osm-bootstrap/crds/smi_tcp_route.yaml, cmd/osm-bootstrap/crds/smi_traffic_access.yaml, cmd/osm-bootstrap/crds/smi_traffic_split.yaml, pkg/constants/constants.go, pkg/reconciler/client.go, pkg/reconciler/crd_handler.go, pkg/reconciler/crd_handler_test.go, pkg/reconciler/mutating_webhook_handler.go, pkg/reconciler/mutating_webhook_handler_test.go
Add a new reconcile label to the crds and mutating webhook in osm for
the reconciler to reconcile on.
Also added an app label for the crds in osm, as the reconciler will only
reconcile osm specific resources
Part of #4065
**Testing done**: Unit tests updated
| …
=> feat(reconciler): add labels to osm-crds and mutating webhook required for reconciliation

.env.example, .github/workflows/main.yml, .github/workflows/openshift-nightly.yml, charts/osm/README.md, charts/osm/templates/osm-bootstrap-deployment.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, cmd/osm-bootstrap/osm-bootstrap.go, demo/run-osm-demo.sh, demo/run-osm-multicluster-demo.sh, pkg/crdconversion/crdconversion.go, pkg/crdconversion/crdconversion_test.go, pkg/reconciler/client.go, pkg/reconciler/types.go, tests/e2e/e2e_reconciler_test.go, tests/framework/common.go, tests/framework/types.go
Enables the reconciler in osm bootstrap to reconcile the crds in osm.
This can be enabled/disabled on install by specifying the required helm
value. By default the reconciler is disabled.
e2e test has been added for the same.
part of #4065
**Testing done**:  An e2e test had been added to validation the new functionality
| Ingress …
=> feat(reconciler): Enable reconciler for crds in osm

charts/osm/templates/osm-deployment.yaml, charts/osm/templates/osm-injector-deployment.yaml
**Description**: Set a connect timeout for the curl request in init-osm-controller and init-osm-injector. In some environments and distributions, the curl request was hanging, which delayed the osm installation process and led to failures in e2es which had a 1m30s timeout. 
**Testing done**: Tested on kind with k8s v1.22.0, and installation succeeded consistently. 
| Egress …
=> fix(healthcheck): set curl connect timeout

.golangci.yml, mockspec/generate.go, pkg/bugreport/run.go, pkg/cli/environment_test.go, pkg/providers/kube/client.go, pkg/ticker/ticker.go, tests/e2e/e2e_permissive_test.go, tests/e2e/e2e_trafficsplit_recursive_split.go, tests/e2e/e2e_trafficsplit_test.go, tests/framework/common_apps.go, tests/framework/common_traffic.go
go-lint has been deprecated. This change removes go-lint from the list of enabled linters in `golangci.yml`. 
The following warnings will beresolved:
`  level=warning msg="[runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive."`
`"[runner/nolint] Found unknown linters in //nolint directives: #nosec g307, go-lint"`
Replaces go-lint with[ revive](https://revive.run/). The default behavior of revive is compatible with go-lint.
| CI System                  | [ x ] | …
=> fix(lint): remove deprecated golint

ci/cmd/maestro/kubernetes_tools.go, cmd/cli/proxy_get.go, demo/cmd/common/books.go, demo/cmd/tcp-client/tcp-client.go, demo/cmd/tcp-echo-server/tcp-echo-server.go, mockspec/generate.go, pkg/cli/chart_source.go, pkg/health/health.go, tests/e2e/e2e_fluentbit_output_test.go, tests/framework/common.go
Replaces gosec in the nolint directive with a nosec annotation to
disable a specific gosec rule.
Note: The nolint and nosec directives need to be on separate lines.
If they are on the same line, nolint will see nosec as an unknown
linter and a warning will be generated when running golangci-lint.
| …
=> chore(lint): disable specific gosec rules with nosec

cmd/osm-controller/log_handler_test.go, pkg/announcements/types.go, pkg/catalog/dispatcher.go, pkg/certificate/providers/certmanager/certificate_manager.go, pkg/certificate/providers/tresor/certificate_manager.go, pkg/certificate/providers/vault/certificate_manager.go, pkg/configurator/client.go, pkg/envoy/registry/announcement_handlers.go, pkg/envoy/registry/announcement_handlers_test.go, pkg/envoy/registry/services.go, pkg/envoy/registry/services_test.go, pkg/ingress/gateway_test.go, pkg/k8s/announcement_handlers_test.go, pkg/k8s/event_handlers.go, pkg/k8s/event_handlers_test.go, pkg/k8s/events/event_pubsub.go, pkg/k8s/events/event_pubsub_test.go, pkg/k8s/events/types.go, pkg/ticker/ticker.go, pkg/ticker/ticker_test.go
Renames the type to so that it reads better when
used by other pkgs - announcements.Kind vs
announcements.AnnouncementType.
=> events: rename AnnouncementType to Kind

.github/workflows/pre-release.yml, Makefile, scripts/publish-image.sh
This change refactors how images are pushed by using the
publish-image.sh script to do all `docker push` operations and enforcing
`VERIFY_TAGS` there, exiting with a non-zero exit code when appropriate.
In addition, `VERIFY_TAGS` uses the strings `true`/`false` instead of `1`/`0`.
Fixes #4144
**Testing done**: manual local testing
| Install …
=> ref(build): clean up VERIFY_TAGS

tests/e2e/e2e_controller_restart_test.go, tests/e2e/e2e_egress_test.go, tests/e2e/e2e_pod_client_server_test.go, tests/e2e/e2e_tcp_client_server_test.go, tests/e2e/e2e_tcp_egress_test.go, tests/framework/common.go, tests/framework/common_apps.go, tests/framework/common_traffic.go, tests/framework/constants.go, tests/framework/types.go
Despite issue #4141 I was able to validate and enable a bunch of tests on Windows
1. Add a Windows pod for tcp requests
2. Add a Windows pod for httpbin
3. Aggregate timeouts accross platform on a single variable
| Networking …
=> test(windows): Enable more Windows tests

Makefile
This change modifies the Makefile targets for building Windows images
with buildx to use the `img-builder` builder explicitly because the
effects of the `--use` flag on `docker buildx create` will not persist
if a user changes the default builder. This way we still ensure a
builder that can build windows/amd64 images exists and use that each
time no matter what the default builder is.
**Testing done**: local manual testing
| …
=> ref(build): build windows images with explicit buildx builder

pkg/k8s/events/event_pubsub.go, pkg/ticker/ticker_test.go
Fixes a data race in PubSub singleton instantiation
where the singleton object creation is not protected
from concurrent initialization.
Fixes a data race in the ticker test where a variable
is written/read to/from without protected access from
multiple goroutines.
Verified `go test -race ./pkg/...` succeeds with this change. Previously
the tests would fail on data races in PubSub initialization and ticker test. …
=> pkg/*: fix data races in PubSub and ticker test

scripts/test-w-coverage.sh
Adds race detection for Go unit tests.
=> CI/test: add race detection check

docs/release_guide.md
Clarifies the process to update the docs as a part
of the release workflow.
=> docs/release_guide: clarify updates required for docs

charts/osm/templates/cleanup-hook.yaml, charts/osm/templates/osm-deployment.yaml, charts/osm/templates/osm-validator-webhook.yaml, cmd/osm-bootstrap/osm-bootstrap.go, cmd/osm-controller/osm-controller.go, cmd/osm-injector/osm-injector.go, pkg/errcode/errcode.go, pkg/reconciler/client.go, pkg/reconciler/crd_handler.go, pkg/reconciler/crd_handler_test.go, pkg/reconciler/mutating_webhook_handler.go, pkg/reconciler/types.go, pkg/reconciler/validating_webhook_handler.go, pkg/reconciler/validating_webhook_handler_test.go, pkg/validator/patch.go, pkg/validator/patch_test.go, pkg/validator/server.go, pkg/validator/server_test.go, pkg/validator/types.go, tests/e2e/e2e_reconciler_test.go
- Enable a reconciler in osm-controller for the validating webhook
- Deployment of the validating webhook is via helm or osm-controller
depending on if the reconciler has been enabled. The cleanup script has
been updated to ensure that the validating webhook gets deleted.
- e2e tests for the reconciler has been extended to include a test for
the validating webhook.
Part of #4065
**Testing done**: e2e and unit tests have been updated
| Demo …
=> feat(reconciler) : enable validating webhook reconciler in osm

pkg/config/client.go, pkg/configurator/client.go, pkg/ingress/client.go, pkg/k8s/client.go, pkg/k8s/event_handlers.go, pkg/k8s/event_handlers_test.go, pkg/k8s/types.go, pkg/policy/client.go, pkg/smi/client.go
As it turns out the first 2 parameters of `GetKubernetesEventHandlers()` are no longer used.
This PR removes `informerName`, `providerName` and all places where these are passed to `GetKubernetesEventHandlers()`.
=> k8s: Simplify GetKubernetesEventHandlers()

pkg/k8s/event_handlers.go, pkg/k8s/events/event_pubsub.go
This change adds additional logging in the Kubernetes event handlers
passed to informers and to all pubsub operations.
**Testing done**: Manual testing with the automated demo.
| SMI Policy                 | …
=> ref(pkg/k8s): add more logging

charts/osm/README.md, charts/osm/templates/cleanup-hook.yaml, charts/osm/templates/grafana-rbac.yaml, charts/osm/templates/jaeger-rbac.yaml, charts/osm/templates/osm-bootstrap-deployment.yaml, charts/osm/templates/osm-injector-deployment.yaml, charts/osm/templates/osm-rbac.yaml, charts/osm/templates/prometheus-rbac.yaml, charts/osm/values.yaml
Removes PSP code.
PSP was deprecated in OSM in 0.10.0 with removal scheduled for 1.0.0
Fixes #4122 
| SMI Policy                 | [ …
=> revert(psp): Remove PSP code for 1.0.0

cmd/cli/namespace_test.go, cmd/osm-bootstrap/osm-bootstrap.go, pkg/constants/constants.go, pkg/crdconversion/crdconversion.go, pkg/crdconversion/crdconversion_test.go, pkg/envoy/bootstrap/config_test.go, pkg/injector/envoy_config_test.go, pkg/k8s/events/events.go, tests/e2e/e2e_fluentbit_deployment_test.go, tests/e2e/e2e_fluentbit_output_test.go, tests/framework/common.go, tests/framework/common_apps.go, tests/scale/osm_common_profile_resources.go
Remove duplicate references of osm control plane pod names by creating a
constant and updating all code to use this.
| …
=> ref(*): Unify all osm control pane pod names as one constant

charts/osm/README.md, charts/osm/templates/osm-deployment.yaml, charts/osm/templates/osm-validator-webhook.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, cmd/osm-controller/osm-controller.go, pkg/validator/patch.go, pkg/validator/patch_test.go, pkg/validator/server.go, pkg/validator/server_test.go, pkg/validator/validators.go, pkg/validator/validators_test.go, tests/e2e/e2e_certmanager_test.go, tests/e2e/e2e_controller_restart_test.go, tests/e2e/e2e_deployment_client_server_test.go, tests/e2e/e2e_grpc_insecure_origination_test.go, tests/e2e/e2e_grpc_secure_origination_test.go, tests/e2e/e2e_hashivault_test.go, tests/e2e/e2e_k8s_version_test.go, tests/e2e/e2e_multiple_services_per_pod_test.go, tests/e2e/e2e_permissive_smi_switching.go, tests/e2e/e2e_pod_client_server_test.go, tests/e2e/e2e_smi_traffic_target_test.go, tests/e2e/e2e_tcp_client_server_test.go, tests/e2e/e2e_trafficsplit_recursive_split.go, tests/e2e/e2e_trafficsplit_same_sa_test.go, tests/e2e/e2e_trafficsplit_test.go, tests/e2e/e2e_validate_smi_traffic_target_test.go, tests/scale/scale_trafficSplit_test.go
feat(*): add traffic target validation
+ Adds a validator for traffic target specifically
requiring that the namespace of a traffic target matches the
destination namespace.
+ Updates chart template for validating webhook configuration to optionally enable
validation of SMI Traffic Targets
+ Adds value for toggling validating SMI traffic target in values.yaml
+ Updates chart README
+ Updates e2es to create traffic targets in destination namespace
+ Adds e2e for SMI traffic target validation
- Unit testing
- Manual testing
- Update e2es
| CI System                  | [ ] …
=> feat(*): ensure traffic target in dest namespace

cmd/osm-bootstrap/osm-bootstrap.go, cmd/osm-bootstrap/osm-bootstrap_test.go
+ adds unit tests for mesh config logic …
=> test(osm-bootstrap): add unit tests for mesh config

cmd/osm-controller/osm-controller.go, pkg/constants/constants.go, pkg/injector/webhook.go, pkg/validator/server.go, pkg/validator/server_test.go
Update the logic of validating webhook secret creation to avoid race
conditions when multiple replicas of osm-controller are created.
**Testing done**:  Prior to this change, increasing the replica count of osm-controller gave the following error on running the demo locally
`Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "osm-validator.k8s.io": Post "https://osm-validator.osm-system.svc:9093/validate?timeout=10s": x509: certificate signed by unknown authority`
After this change the error no longer occurs 
| CI System …
=> fix(validatingWebhookCert): Update validating webhook secret creation to support multiple control plane instances

charts/osm/templates/osm-bootstrap-deployment.yaml, cmd/osm-bootstrap/osm-bootstrap.go, cmd/osm-controller/osm-controller.go, cmd/osm-injector/osm-injector.go, pkg/reconciler/client.go
This PR adds the missing osmVersion to the reconciler client to ensure correct reconciliation 
**Testing done**: manually verified the change 
| SMI Policy …
=> fix(reconciler): Add missing osmVersion to reconciler client

demo/deploy-mysql.sh
Allows users to run the demo with a private registry
| …
=> chore(demo): Add CTR_REGISTRY_CREDS_NAME to mysql demo container

.github/workflows/pre-release.yml
Defines VERSION and BUILD_DATE environment variables in the
pre-release.yaml. When the osm build occurs for a release the
VERSION and BUILD_DATE variables in the makefile will be
populated with the values of the env vars rather than the default
value of dev for VERSION and nothing for BUILD_DATE. This change
fixes the incorrect VERSION and BUILD_DATE logged in the osm control
plane components.
Resolves #2818
Unable to test in osm repo.
| CI System                  | [ x ] |
| …
=> fix(release): set version and build date for release builds

charts/osm/README.md, charts/osm/values.yaml, cmd/cli/install.go
Enforcing single mesh in a cluster by defalut for OSM.
part of #4162
| Sidecar …
=> Ensure single mesh deployment is enforced in OSM by default

charts/osm/templates/osm-bootstrap-deployment.yaml, charts/osm/templates/osm-bootstrap-service.yaml, cmd/osm-bootstrap/osm-bootstrap.go
Update the crd conversion webhook port on osm-bootstrap  to 9443 as port 443
cannot be used.  
Reason : k8s fails to open the port 443 because it is a privileged port. All ports <1024 require special permissions, hence the port was updated to 9443. An alternative is to keep 443 and update the target port, the former was chose for consistency.
Fixes #4178
**Testing done**: Manually verified that the error message as described in issue 4178 no longer appears
=> fix(bootstrapPort): Update the crd conversion webhook port on osm-bootstrap

scripts/publish-image.sh
Currently, when checking if a tag on a windows image exists, the linux
image is checked. This change fixes it so the windows image is checked
instead.
| Security …
=> fix(build): check if windows tag exists correctly

pkg/catalog/ingress.go, pkg/catalog/ingress_test.go
Checks that the IngressBackend's port matches the TargetPort
of the service. This is important in deployments where there
are multiple MeshServices with the same name, in which case
the IngressBackend configuration corresponding to the service
name and port must be used. Multiple MeshService objects with
the same name and different port number will exist when there
is a k8s service with multiple ports per service.
Without this change, IngressBackend configuration for a service
with multiple ports can result in conflicts where duplicate
configs are generated per MeshService.
Tested IngressBackend with multiple port per service. …
=> catalog/ingress: check backend's port in addition to name

pkg/catalog/ingress.go, pkg/catalog/ingress_test.go
Backports 37c3d65f from main to release-v0.11
---
Checks that the IngressBackend's port matches the TargetPort
of the service. This is important in deployments where there
are multiple MeshServices with the same name, in which case
the IngressBackend configuration corresponding to the service
name and port must be used. Multiple MeshService objects with
the same name and different port number will exist when there
is a k8s service with multiple ports per service.
Without this change, IngressBackend configuration for a service
with multiple ports can result in conflicts where duplicate
configs are generated per MeshService.
Tested changes locally.
| Ingress                    | …
=> [backport] catalog/ingress: check backend's port in addition to name (#4202)

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/templates/_helpers.tpl, charts/osm/values.yaml, cmd/cli/mesh_upgrade.go, docs/example/manifests/apps/bookbuyer.yaml, docs/example/manifests/apps/bookstore-v2.yaml, docs/example/manifests/apps/bookstore.yaml, docs/example/manifests/apps/bookthief.yaml, docs/example/manifests/apps/bookwarehouse.yaml, docs/example/manifests/meshconfig/mesh-config.yaml
Signed-off-by: jaellio <jaellio@microsoft.com>
**Changes to note:**
The logic in `_helpers.tpl` to determine the control plane and demo app image names was modified. If the `OpenServiceMesh.image.tag` is set in `charts/osm/values.yaml` it will be used by default to configure the image names. If the image tag is not set, the image digests defined by `OpenServiceMesh.image.digest` will be used. 
Prior to this change, setting the image digests in `charts/osm/values.yaml` was causing the demo to fail. By default, the image digests were used to configure the image names.  In the demo, the new images that were pushed to the local container registry did not have the same digests as the digests generated from the pre-release workflow. When attempting to pull the images from the local registry …
=> chore(release): update version to v0.11.0-rc.1

charts/osm/templates/osm-bootstrap-deployment.yaml, charts/osm/templates/osm-deployment.yaml, charts/osm/templates/osm-injector-deployment.yaml
Marks osm-controller, osm-injector, and osm-bootstrap pods as critical.
https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
See also PR #4201 for more details
| New Functionality          | [ x] |
no
=> feat(charts): Adding priorityClassName to the OSM deployments

pkg/announcements/types.go, pkg/messaging/broker.go, pkg/messaging/broker_test.go, pkg/messaging/types.go, pkg/messaging/workqueue.go, pkg/messaging/workqueue_test.go
Introduces message broker functionality to
handle messaging in OSM control plane. The broker
will handle proxy update events and k8s events
required by other components within the control plane.
The broker comprises of a workqueue to process events
and pub-sub instances to implement the messaging
channels. The message broker will replace the global
pub-sub functionality.
Testing done:
- 100% unit test coverage
- Verified fixes for #4167 with the use of
message broker
Required by #4167 …
=> messaging: introduce message broker

tests/e2e/e2e_validate_smi_traffic_target_test.go
This PR disables the SMI traffic target validation disable test when test type is NoInstall because it requires updating the validation configuration which is not possible at this point through the MeshConfig object.
resolves #4208 
Co-authored-by: Niranjan Shankar nshankar@microsoft.com
| Ingress …
=> fix(tests): disable smi validate test for NoInstall

pkg/debugger/proxy.go, pkg/envoy/registry/debugger.go, pkg/envoy/registry/debugger_test.go, pkg/envoy/registry/registry.go, pkg/envoy/registry/types.go
Proxies are expected to disconnect when the corresponding
pods are recycled.
Since the cluster can go through a lot of churn, keeping
track of disconnected proxies results in additional
memory consumption and bookkeeping which is better avoided.
It is easy enough to know how many times a proxy has
reconnected to a control plane after a disconnect using
the osm_proxy_reconnect_count metric.
=> envoy/registry: do not track disconnected proxies

cmd/osm-controller/osm-controller.go, pkg/envoy/ads/response.go, pkg/metricsstore/metricsstore.go
Adds metrics counters for successful and failed sends
to proxies.
Resolves #4191
```
osm_proxy_response_send_error_count 0
osm_proxy_response_send_success_count 555
```
=> metrics: add counters related to proxy response send

ci/cmd/maestro.go, ci/cmd/maestro/kubernetes_tools.go
These changes add a new check in the maestro that the MySQL pod  in the
bookwarehouse namespace is ready. It also updates
`WaitForPodToBeReady()` to check the `Ready` condition on the Pod which
is more complete than the existing check that each container in the Pod
is ready.
This should at least partially address the recent flakiness of the automated demo in CI.
**Testing done**: Ran the automated demo and maestro locally.
| …
=> fix(maestro): update pod readiness checks

charts/osm/templates/osm-deployment.yaml, charts/osm/templates/osm-injector-deployment.yaml
The args for the culr job on the init containers in osm-controller and
osm-injector has beeen updated to use curl params rather than bash
**Testing done**: Manually verified the demo and everything works as expected 
| …
=> update curl command for init containers

CODEOWNERS, CONTRIBUTOR_LADDER.md
Expands the osm-approvers list to be explicit
and transparent while updating the list of
code approvers.
=> codeowners: expand approvers to be explicit

charts/osm/grafana/dashboards/osm-pod.json
Removes the irate function from the envoy cluster upstream active
connection query used in the OSM Pod to Service dashboard. The
irate function is meant to be used on counters, not gauges. 
Resolves #4323
Verified the updated query generated the expected data on the active connections graph.
**New Dashboard**:
| Install …
=> fix(grafana): remove irate from active connection query

demo/deploy-mysql.sh, pkg/catalog/inbound_traffic_policies.go, pkg/catalog/inbound_traffic_policies_test.go, pkg/catalog/outbound_traffic_policies.go, pkg/catalog/outbound_traffic_policies_test.go, pkg/envoy/lds/inmesh.go, pkg/envoy/lds/listener.go, pkg/envoy/lds/listener_test.go, pkg/k8s/util.go, pkg/k8s/util_test.go, tests/e2e/e2e_tcp_server_first_test.go
This change adds the capability for OSM to handle ports with
`appProtocol: tcp-server-first` on services within the mesh.
Specifically, the main change is to add handling for `tcp-server-first`
ports in the mesh when we calculate the predicate function used to
disable the TLS and HTTP inspector listener filters. Previously, this
was only done for `tcp-server-first` ports specified in an Egress
policy resource.
Fixes #4313
**Testing done**: Tested manually with the example in #4313 and with the automated demo to ensure that still works as expected.
| Certificate Management …
=> ref(tcp): support tcp-server-first inside the mesh

.github/workflows/main.yml, cmd/cli/mesh_upgrade.go, cmd/cli/mesh_upgrade_test.go, docs/release_guide.md, docs/release_notes.md, tests/e2e/e2e_upgrade_test.go
Currently, upgrading OSM with `osm mesh upgrade` fails when the newer
chart version removes or renames values from the installed chart because
values.schema.json defines `"additionalProperties": false` on each
object and `osm mesh upgrade` uses all the values from the installed
chart.
Now, the `osm mesh upgrade` command will not use any values from the old
release. Users can specify them with the new `--set` flag.
Fixes #4330
**Testing done**: Manually ran affected tests and other upgrade scenarios based on the existing e2e test.
| …
=> fix(upgrade): handle removed values

charts/osm/README.md, charts/osm/templates/osm-controller-hpa.yaml, charts/osm/templates/osm-injector-hpa.yaml, charts/osm/values.schema.json, charts/osm/values.yaml
Allows HPA to react to memory utilization(not only CPU)
| New Functionality          | [x ] |
1. Does this change contain code from or inspired by another project?no
2. Is this a breaking change?no
=> feat(hpa): Adds memory targetAverageUtilization

docs/development_guide/README.md
Fixes #4281 
As @clarenceb points out in https://github.com/openservicemesh/osm/issues/4281, we have a typo in the dev guide README. 
-   Did you notify the maintainers and provide attribution? not applicable
=> Typo fix for dev guide README

pkg/injector/webhook.go, pkg/validator/patch.go
This PR fixes a couple of typos in the webhook creator code paths.
| Other                      | [x] |
=> Fix typos in webhook creators

pkg/injector/init_container.go, pkg/injector/init_container_test.go
**Description**: Currently, pods having pod-level security contexts are causing the init container to not be able to program iptables. Setting `runAsNonRoot` and `runAsUser: 0` security context for the init container fixes this.
For example, the following security context in a bookstore demo pod causes an xtables permission denied error where the pod never finishes initializing/goes into crashLoopBackoff
```
securityContext:
fsGroup: 1000
runAsGroup: 1000
runAsUser: 1000
```
| Demo …
=> fix(init): set init container level security context

charts/osm/grafana/dashboards/osm-mesh-envoy-details.json
Remove avg and max envoy update time metrics from grafana dashboard
and resolves #3987
| Observability              | [ x] |
Testing done:
- Ran osm demo script (demo/run-osm-demo.sh) with grafana enabled
- Ran port forward script for grafana (scripts/port-forward-grafana.sh) 
=> fix(charts/osm/grafana/dashboards): remove avg and max envoy update time metrics from grafana dashboard

.github/workflows/pre-release.yml, dockerfiles/Dockerfile.init
This change adds the `version` job as a dependency of the `imagescan`
job in the pre-release workflow which is required for
`${{ needs.version.outputs.version }}` to correctly evaluate.
The base image of the `init` container has also been updated to fix a
vulnerability.
**Testing done**: Ran image scan locally
| …
=> fix(ci): fix image scan

pkg/injector/webhook.go, pkg/injector/webhook_test.go
Skips sidecar injection for pods that belong to the host
network. Without this, the iptable rules installed
will result in routing failures in the host, rendering
the cluster unusable.
Part of #4359
- Unit test
=> injector: skip injection when pod belongs to host network

pkg/injector/webhook.go, pkg/injector/webhook_test.go
Backports 0fcedaa7 to release v1.0.
---
Skips sidecar injection for pods that belong to the host
network. Without this, the iptable rules installed
will result in routing failures in the host, rendering
the cluster unusable.
Part of #4359
=> [backport] injector: skip injection when pod belongs to host network (#4360)

tests/e2e/e2e_upgrade_test.go
Now that the upgrade test is basing off of v1.0.0-rc.2, we need to
install with values under `osm.*` instead of `OpenServiceMesh.*`.
**Testing done**: Ran the upgrade e2e test locally
| SMI Policy …
=> fix(e2e): update upgrade test

.github/workflows/pre-release.yml, dockerfiles/Dockerfile.init
**Description**: Backport of #4357
This change adds the `version` job as a dependency of the `imagescan`
job in the pre-release workflow which is required for
`${{ needs.version.outputs.version }}` to correctly evaluate.
The base image of the `init` container has also been updated to fix a
vulnerability.
| Networking                 | …
=> [backport] fix(ci): fix image scan

.github/workflows/pre-release.yml, dockerfiles/Dockerfile.init
**Description**: Backport of #4357
This change adds the `version` job as a dependency of the `imagescan`
job in the pre-release workflow which is required for
`${{ needs.version.outputs.version }}` to correctly evaluate.
The base image of the `init` container has also been updated to fix a
vulnerability.
| Networking                 | …
=> [v0.11 backport] fix(ci): fix image scan

pkg/bugreport/controlplane.go
This PR adds the check to `osm support bug-report` when it fetches control plane logs. It will look to see if the container was restarted, and if it was then it also pulls the previous container logs. This could help in the situation where we are troubleshooting an issue that causes restart.
Manual testing. Created the kind cluster `make kind-demo` and then docker exec'd into the `osm-worker` node container and killed the osm-controller process. Then I ran `osm support bug-report` and saw that the previous logs for osm-controller were retrieved.
1. Does this change contain …
=> Get bug-report previous control plane logs if containers were restarted

pkg/ingress/gateway_test.go
Adds a delay for subscription time and adds a delay after publishing
an event for `maxTimeForEventToBePublished`. The
original 2s delay for the secret to be created after publishing a
mesh config update event included the time to publish the event
and the time to issue a certificate. The max time alone for
publishing an event is 2s, so in some cases, this unit test may have
exceeded the timeout.
Resolves #4366
Unable to reproduce the timeout locally.
| Demo                       | …
=> test(ingress): increase timeout for TestHandleCertificateChange

pkg/envoy/registry/services.go, pkg/envoy/registry/services_test.go, pkg/k8s/client.go, pkg/k8s/client_test.go, pkg/k8s/mock_controller_generated.go, pkg/k8s/types.go, pkg/providers/kube/client.go, pkg/providers/kube/client_test.go
This change removes the `K8sServiceToMeshServices` method from the k8s
`Controller` interface. Since `K8sServiceToMeshServices` only relies on
the `GetEndpoints` method already in the interface and nothing specific
to the unexported `client` implementation, it has been converted to a
function that accepts a `Controller`.
**Testing done**: Ran affected unit tests locally.
| Ingress …
=> ref(k8s): remove K8sServiceToMeshServices from Controller

pkg/injector/init_container.go, pkg/injector/init_container_test.go, pkg/injector/iptables.go, pkg/injector/iptables_test.go
Makes the iptables rules idempotent by using
`iptables-restore --noflush`. With this change,
the init-container can be executed multiple times
without any side effects. The `--noflush` option
ensures the exising rules do not get flushed
during `iptables-restore`, which would otherwise
compromise the security.
The code has been updated to generate the
iptables rules in the format that `iptables-restore`
expects.
Also simplifies the init container test to avoid
redundancy.
Resolves #4307
Tested idempotency in local env by running the command executed
by the init container multiple times. Previously this would fail with the
`chain already exists` error, which is not the case with this change.
| …
=> injector: make iptables rules idempotent

pkg/catalog/fake.go, pkg/envoy/cds/response.go, pkg/envoy/cds/response_test.go, pkg/envoy/lds/response.go, pkg/k8s/client.go, pkg/k8s/client_test.go, pkg/k8s/mock_controller_generated.go, pkg/k8s/types.go
The `IsMetricsEnabled` method on the `k8s.Controller` interface does not
depend on any implementation details, only the `*v1.Pod` passed to it.
Making it a plain function removes this unnecessary dependency on
setting up a `k8s.Controller`.
**Testing done**: Ran affected unit tests locally
| Networking …
=> ref(k8s): remove IsMetricsEnabled from Controller

charts/osm/templates/osm-injector-deployment.yaml, charts/osm/templates/preset-mesh-config.yaml, cmd/osm-bootstrap/crds/config_meshconfig.yaml, pkg/configurator/methods.go
This fixes issue #4371. Prior to this fix if there was a change to the envoy sidecar image then this would not get reflected or upgraded in the mesh config. Upon further testing we cannot just patch that in because if there are missing required keys (as indicated by the CRD) then the patch itself will fail (see the *Testing done* section below on the missing required key error when attempting to patch).
This PR adds the functionality for a complete upgrade of the mesh config by doing two things:
1. Compare CRD required fields with the current MeshConfig. If there are missing required keys then patch them in.
2. Compare the envoy sidecar image. If the default has been upgraded between the old and the new version _and_ the user has not modified the default in their mesh …
=> Add MeshConfig upgrade when upgrading a mesh

cmd/cli/util.go, cmd/cli/version.go, cmd/cli/version_test.go, pkg/version/version.go
Adds remote version to `osm version` CLI command output. By default,
the CLI and Mesh version will be included in the output. A remote
flag (by default set to true) can be set to false to only output
the CLI version. If there is any failure getting the mesh version,
the CLI version is printed along with the failure message.
A different mesh can be specified by overriding the default osm namespace
via the OSM_CONFIG or the global `--osm-namespace` flag.
Part of #4289
**Previous `osm version` output:**
```shell
Version: v0.11.1; Commit: c01aefae509d59735d7908a32a359327ff3f2322; Date: 2021-10-20-20:33
```
**New `osm version` output:**
```shell
$ osm version
CLI Version: version.Info{Version:"v0.11.1", GitCommit:"c01aefae509d59735d7908a32a359327ff3f2322", …
```
=> feat(cli): add remote version to osm version output

pkg/injector/init_container_test.go, pkg/injector/iptables.go, pkg/injector/iptables_test.go
This change allows an app to invoke itself by enabling
the necessary iptables rules. It allows an app to direct
traffic to itself when:
1. app directs traffic to its pod IP
2. app directs traffic to its k8s service IP
which is then resolved to the local pod IP
by Envoy.
Resolves #4340
Tested app sending traffic to itself via k8s service
and pod IP.
=> injector: allow redirection of app traffic to itself

cmd/cli/support_bugreport.go, pkg/bugreport/ingress.go, pkg/bugreport/run.go, pkg/bugreport/types.go
This PR adds the ability to add ingress information into the bug report (with the `--ingress` param as well as included in `--all`). Having additional ingress information can help with troubleshooting issues.
Currently this supports automatically fetching diagnostics from nginx as well as Contour.
Resolves #4406.
```
$ go run ./cmd/cli support bug-report --ingress
...
[+] Collecting ingress information
✓ Collected report for ingress httpbin/httpbin
✓ Collected report for ingress backend httpbin/httpbin
✓ Collected report for ingress controller ingress-nginx/ingress-nginx-controller-54bfb9bb-8kvnv
✓ Finished generating report for ingress
...
$ tree ingress-nginx/
ingress-nginx/
└── pods
└── ingress-nginx-controller-54bfb9bb-8kvnv
└── commands
├── …
```
=> Add ingress information to bug report

CONTRIBUTOR_LADDER.md
Updates the contribution duration required
to become a maintainer to 3 months instead
of 6. 3 months is a more reasonable duration
to onboard new maintainers. Also updates the
inactivity duration to 3 months instead of 6.
**Maintainers action**:
If you agree with this change, kindly approve it. 
This change will only be merged if a majority
of maintainers approve. 
=> [RFC] contributing: update maintainer requirement

cmd/osm-bootstrap/crds/config_meshconfig.yaml
Validation added to the `subjectAltName` for the ingress gateway
certificate in the meshConfig. Going forward, this field (if specified) will have to contain
atleast one element.
Fixes #4353
**Testing done**: This change has been verified manually by updating the meshConfig by providing an empty array for the `subjectAltNames`. The crd update fails and provides the following error 
`meshconfigs.config.openservicemesh.io "osm-mesh-config" was not valid: # *spec.certificate.ingressGateway.subjectAltNames: Invalid value: 0: spec.certificate.ingressGateway.subjectAltNames in body should have at least 1 items`
thereby forcing users to provide a value whenever the ingressgateway certificate details are provided.
**Affected …
=> meshConfig: add validation for ingressgateway certificate

charts/osm/templates/osm-bootstrap-deployment.yaml, charts/osm/templates/osm-bootstrap-service.yaml, cmd/osm-bootstrap/osm-bootstrap.go, pkg/constants/constants.go, pkg/crdconversion/crdconversion.go
Explicitly set's the webhook's port to 9443
in the Go code. If unset, the port defaults
to 443 which results in a mismatch.
Without this, upgrade fails with the following error:
`{"level":"fatal","component":"osm-bootstrap","error":"conversion webhook for config.openservicemesh.io/v1alpha1, Kind=MeshConfig failed: Post \"https://osm-bootstrap.osm-system.svc:443/convert/meshconfig?timeout=30s\": no service port 443 found for service \"osm-bootstrap\"","time":"2022-01-11T18:11:05Z","file":"osm-bootstrap.go:150","message":"Error setting up default MeshConfig osm-mesh-config from ConfigMap preset-mesh-config"}`
- Upgrade
Please …
=> crd-conversion: fix webhook port number

charts/osm/templates/osm-bootstrap-deployment.yaml, charts/osm/templates/osm-bootstrap-service.yaml, cmd/osm-bootstrap/osm-bootstrap.go, pkg/constants/constants.go, pkg/crdconversion/crdconversion.go
Backports a70d654e from main to release-v1.0
---
Explicitly set's the webhook's port to 9443
in the Go code. If unset, the port defaults
to 443 which results in a mismatch.
- CI
| Upgrade                    | [X] |
=> [backport] crd-conversion: fix webhook port number (#4424)

pkg/injector/webhook.go
Fixed label assignment on the mwhc by reusing the locally created labels
for correct assignment of reconciler labels.
**Testing done**: Manually verified the change
| Performance …
=> [reconciler]: fix label assignment on mwhc

cmd/cli/version.go, cmd/cli/version_test.go
If a control plane is not installed in the specified namespace do
not throw an error for `osm version`. Currently, the command
returns an error in this scenario.
Resolves #4427 
```
$ ./osm version
CLI Version: version.Info{Version:"dev", GitCommit:"d9426600787ac77a413fc97601ad6eef420f0e3c", BuildDate:""}
Mesh Version: No control plane found in namespace [osm-system]
$ echo $?
0
```
Signed-off-by: jaellio <jaellio@microsoft.com>
- updated unit tests
- manually verified output
| …
=> fix(cli): do not throw error for osm version when no control plane found

charts/osm/templates/osm-controller-hpa.yaml, charts/osm/templates/osm-injector-hpa.yaml
Update HPA yamls from averageValue to averageUtilization
and resolves #4451
Ran HPA enabled for osmController and injector for bookstore demo and percentages are seen for both CPU and memory utilization.
| Other                      | [x ] |
=> bug(*): Fix memory targetAverageUtilization

charts/osm/grafana/dashboards/osm-mesh-envoy-details.json, charts/osm/templates/grafana-configmap.yaml
Removes the hardcoded default control plane namespace from the
Mesh and Envoy Details dashboard. Parameterizes the control plane
namespace. When installing OSM with automatic provisioning of
Prometheus and Grafana the control plane namespace variable will
be set to the namespace where OSM is being installed. When
importing the Mesh and Envoy Details dashboard, the user will have
the option to set the osm control plane namespace just as they are
able to set the datasource.
Resolves #4436 
**View when importing the Mesh and Envoy Details dashboard:**
- Installed locally built osm with automatic provisioning of Prometheus and Grafana in a namespace other than osm-system. Verified the Mesh and Envoy Details dashboard was accurately displaying data for the …
=> fix(grafana): remove hardcoded control plane namespace

cmd/cli/version.go, cmd/cli/version_test.go
Backports 95fb3420 from main to release-v1.0
---
If a control plane is not installed in the specified namespace do
not throw an error for `osm version`. Currently, the command
returns an error in this scenario.
- CI
| …
=> [backport] fix(cli): do not throw error for osm version when no control plane (#4433)

charts/osm/grafana/dashboards/osm-mesh-envoy-details.json, charts/osm/templates/grafana-configmap.yaml
Backports ec0da63a from main to release-v1.0
---
Removes the hardcoded default control plane namespace from the
Mesh and Envoy Details dashboard. Parameterizes the control plane
namespace. When installing OSM with automatic provisioning of
prometheus and grafana the control plane namespace variable will
be set to the namespace where OSM is being installed. When
importing the Mesh and Envoy Details dashboard, the user will have
the option to set the osm control plane namespace just as they are
able to set the datasource.
- CI
| Certificate Management …
=> [backport] fix(grafana): remove hardcoded control plane namespace (#4454)

charts/osm/templates/cleanup-hook.yaml
Fixes the CRD reset logic in the cleanup hook to:
1. Correctly `replace` the CRD modified by osm-boostrap
to its initial state. osm-boostrap updates the CRDs
to specify the CRD conversion spec referencing the
CRD conversion webhook. Upon uninstall, the CRD
conversion webhook is removed, and the cleanup
hook attempts to reset the CRD to its initial
state, albeit incorrectly. `kubectl apply`
results in a `patch` request and a field is
removed only if it is present in the
`last-applied-configuration` annotation added
by `kubectl` and not in the desired new config (see [this](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#merge-patch-calculation)).
As a result, the `conversion` field in the CRDs
was not being removed despite not being present …
=> charts/cleanup-hook: fix CRD reset logic

tests/framework/common.go
Waits for resources created by Helm to delete prior
to performing deletion of the entire namespace.
Without this, some dangling resources can be left
behind in the cluster such and the namespace could
be stuck in the terminating state.
Also dumps the namespaces that fail to terminate. This
is necessary to root cause namespace deletion issues.
Used this change to root cause a bug in uninstall that left
namespaces in a dangling state.
2. Is this …
=> tests/framework: wait for deletion and dump namespace

pkg/configurator/client.go, pkg/configurator/client_test.go, pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/configurator/mock_client_generated.go, pkg/configurator/types.go, pkg/ingress/gateway.go, pkg/ingress/gateway_test.go
Simplifies the signature of `GetMeshConfig()` in
the interface to return an object instead of a pointer.
MeshConfig is guaranteed to exist during controller
startup and there is already a fallback to return
a default MeshConfig object if not found in the
cache. Returning a pointer results in unnecessary
nil pointer handling on the caller side, which
makes the usage of this function indeterministic
when the implementation is deterministic.
This change guarantees to the caller of this function
that they will always receive a valid MeshConfig to
operate on.
1. Does this change contain code from or …
=> configurator: simplify MeshConfig API

pkg/configurator/methods.go, pkg/configurator/methods_test.go, pkg/configurator/mock_client_generated.go, pkg/configurator/types.go, pkg/injector/patch.go, pkg/injector/patch_test.go, pkg/injector/webhook_test.go
Simplifies the Configurator interface by leveraging
the `GetMeshConfig()` API instead of exposing iptables
related exclusion fields as separate APIs.
Note that this change only removes the APIs related
to IP/Port exclusions, to begin with, but the 
general concept applies to other fields as well.
=> configurator: remove ip/port exclusion APIs

.github/workflows/stale.yml
GitHub Action to daily (at midnight) label issues and PRs that have had
no activity (60 days). Once a stale PR/issue has been labeled, it will
then be closed after another span of inactivity (7 days). This will help
us minimize noise and automate the cleanup of inactive items.
Signed-off-by: Thomas Stringer <thstring@microsoft.com>
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? Not …
=> Automate stale issue and PR cleanup

.github/workflows/stale.yml
Change the behavior of the stale job to ignore items that belong to a
milestone. If we have set an item in a milestone then we do not want it
to be marked stale and closed.
Signed-off-by: Thomas Stringer <thstring@microsoft.com>
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? Not applicable.
=> Exempt milestone items from going stale

tests/e2e/e2e_upgrade_test.go
This change modifies the pullPolicy for OSM images for the upgrade e2e
test to match how it's handled for installs, where pre-deployed clusters
will use Always and kind clusters provisioned by the framework will use
IfNotPresent since then the images are assumed not to be pushed to a
registry.
**Testing done**: Ran the upgrade test locally with both `-installType=KindCluster` and `-installType=SelfInstall` and both behaved as expected.
| Documentation …
=> fix(e2e): specify pullPolicy for upgrade test

tests/framework/common.go
Removes the dependency on kubectl to dump the namespace
info. Previously this was done to unblock debugging
of CI failures in a timely manner.
=> tests: remove kubectl dependency for namespace info

.github/workflows/stale.yml
Add a message for both stale and closed issues and PRs. This gives the
user an explanation why it was marked as stale (or closed). It also
gives instructions (comment or update) on how to remove the stale label
and reset the stale day counter.
Signed-off-by: Thomas Stringer <thstring@microsoft.com>
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? Not applicable.
=> Add comment for stale and closed issues and PRs

pkg/certificate/providers/config.go, pkg/certificate/providers/config_test.go, pkg/certificate/providers/tresor/ca.go, pkg/certificate/providers/tresor/ca_test.go, pkg/constants/constants.go, pkg/ingress/gateway_test.go
Removes the use of the required expiration date data field in the
osm-ca-bundle. The certificate's expiration can be obtained
directly from the certificate rather than from the expiration
field.
This change also updates the logs in GetCertificateFromSecret to
reflect the broader use of the function.
Updates `ca_test.go` to use go testing package rather than ginko
and gomega. Adds checks for notAfter and expiration values on
the x509 certificate and the certificator respectively.
**Note:** It is no longer necessary to perform any formatting on
expiration time.
Resolves #4467
- Updated unit tests to verify the expiration is correctly set using the notAfter value obtained from the decoded x509 cert
- On a kind cluster ran the automated demo
- verified …
=> ref(cert): remove expiration field from osm-ca-bundle secret data

cmd/cli/version.go, cmd/cli/version_latest.go, cmd/cli/version_latest_test.go, go.mod
Gets the latest OSM release version and compares it to the current
CLI version. If the latest version is newer than the current
version, a notification is displayed. This notification is only
displayed in the `osm version` cmd output.
Adds a `version-only` flag that hides warnings and upgrade notifications.
Errors are grouped at the end of the cmd output.
**New `osm version` output:**
```shell
$ osm version
CLI Version: version.Info{Version:"v0.11.1", GitCommit:"c01aefae509d59735d7908a32a359327ff3f2322", BuildDate:"2021-10-20-20:33"}
Mesh [osm] Version: version.Info{Version:"v0.11.1", GitCommit:"c01aefae509d59735d7908a32a359327ff3f2322", BuildDate:"2021-10-20-20:33"}
OSM v1.0.0 is now available. Please see https://github.com/openservicemesh/osm/releases/latest.
WARNING: …
```
=> feat(cli): latest verion availability notification on osm version

pkg/injector/exclusions.go, pkg/injector/exclusions_test.go, pkg/injector/patch.go, pkg/injector/webhook.go
Adds support for specifying pod specific outbound
IP range exclusions similar to port exclusions.
The pod specific and global IP range exclusions
will both apply to a pod being injected.
Also makes the following changes:
- Fails patching on invalid annotations
- Moves OS specific init container code to
its own function
Related to #4396
Unit tests
3. Has documentation corresponding to this change been updated …
=> injector: support pod specific IP range exclusions

.gitignore, mockspec/generate.go
Mockgen errors are currently swalled by the generator:
```
2022/01/31 15:14:38 Error generating mocks for rule: [catalog pkg/catalog/mock_catalog_generated.go github.com/openservicemesh/osm/pkg/catalog MeshCataloger], err: exit status 1
```
This PR logs the error messages to stderr:
```
make check-mocks
../pkg/catalog/catalog.go:22:3: unknown field 'provider' in struct literal of type MeshCatalog (but does have Provider)
../pkg/catalog/fake.go:135:25: undefined: endpoint.Provider
../pkg/catalog/fake.go:138:24: undefined: service.Provider
../pkg/catalog/fake.go:226:23: too many arguments in call to NewMeshCatalog
Error generating mocks for rule: [catalog pkg/catalog/mock_catalog_generated.go github.com/openservicemesh/osm/pkg/catalog …
```
=> feat(mockgen): improve error messaging; add ability to run one mockgen

tests/e2e/e2e_trafficsplit_test.go
Currently, the upgrade e2e test fails when the MultiClusterService or
MeshConfig CRDs already exist on the cluster, which happens after any
other test runs right before it. This change puts the upgrade e2e test
in its own bucket to make sure that doesn't happen.
**Testing done**: Covered by CI.
| Networking …
=> fix(e2e): isolate upgrade test

pkg/crdconversion/config_meshconfig_conversion.go, pkg/crdconversion/config_meshconfig_conversion_test.go
Handles the conversion of the optional field in
v1alpha2 and adds a test for conversion between
v1alpha1 and v1alpha2 of MeshConfig.
Unit tests
=> crdconversion: handle MeshConfig optional field

charts/osm/README.md, charts/osm/templates/preset-mesh-config.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, pkg/injector/exclusions.go, pkg/injector/exclusions_test.go, pkg/injector/init_container.go, pkg/injector/init_container_test.go, pkg/injector/iptables.go, pkg/injector/iptables_test.go, pkg/injector/patch.go
Adds support to configure IP range inclusions globally
or scoped to pods, similar to the IP range exclusions
functionality.
- Makes IP range related functions generic to handle
exclusions and inclusions
- Updates iptables rules to order exclusions correctly
before inclusions
- Adds install option to specify global IP range
inclusions
Part of #4396
Ran the demo with inclusion ranges specified and verified it works
as expected.
```
./demo/run-osm-demo.sh --set="osm.outboundIPRangeInclusionList={10.244.0.0/16,10.96.0.0/16}"
```
1. Does this …
=> injector: add support to configure IP range inclusions

charts/osm/templates/osm-injector-deployment.yaml, cmd/osm-injector/osm-injector.go, pkg/injector/init_container.go, pkg/injector/init_container_test.go, pkg/injector/patch.go, pkg/injector/types.go, pkg/injector/webhook.go, pkg/injector/webhook_test.go
This change uses the `osm.image.pullPolicy` value in the Helm chart for
the pull policy configured for injected init containers to make the
behavior consistent with other OSM images. Previously, using
`osm.image.pullPolicy=IfNotPresent` and `osm.image.tag=latest` would
configure the init container with that tag but an empty pull policy
which would be implicitly `Always`, which fails in environments where
the image is not meant to be pulled.
Fixes #3809
Verified the command from the issue now works:
```
make test-e2e CTR_REGISTRY=localhost:5000 CTR_TAG=latest E2E_FLAGS="-installType=KindCluster -cleanupKindClusterBetweenTests -ginkgo.focus='SimpleClientServer egress TCP'"
```
| …
=> fix(injector): make init container pullPolicy configurable

tests/framework/common.go
**Description**: Use the `osm support bug-report` command to collect mesh related logs for e2e CI Failures. 
**Testing done**: Ensured that the `osm support bug-report` command was not run for successful tests. Then, I deliberately changed the test condition in one of the tests to fail, and saw that the command was run: 
`Collecting logs, using "/home/nshankar13/documents/new_osm_fork/osm/scripts/get-osm-namespace-logs.sh /tmp/test-1376025377"
Running locally '/home/nshankar13/documents/new_osm_fork/osm/scripts/get-osm-namespace-logs.sh /tmp/test-1376025377'
Running locally 'kubectl get events -A'
Running locally '../../bin/osm proxy get config_dump client --namespace client -f /tmp/test-1376025377/envoy_configs/client_client/config_dump.t …
=> Collect bug report for e2e failures

cmd/cli/uninstall_mesh.go
When `osm uninstall mesh -f` is run, the `force`
flag is intended for the user to skip the uninstall
confirmation prompt only.
Even if this code is specified, the code in uninstall
mesh does not supress diagnostic messages or errors
when it encounters an error during mesh uninstallation.
This proposed fix instead changes the force flag to
'--assume-yes' flag to make this behavior clear, only
skipping the confirmation prompt but not supressing
diagnostic messages and errors.
**Testing done**: Local testing + unit testing
| Certificate …
=> fix(cli): uninstall mesh assume yes flag

charts/osm/templates/osm-deployment.yaml, cmd/cli/install.go, cmd/cli/install_test.go
This change moves the validation for the `osm.vault.host` and
`osm.vault.token` values from the CLI to the chart so the same
validation is performed when using `helm` directly.
Part of #2147
**Testing done**: Unit tests updated.
| Performance …
=> ref(chart): push vault validation to chart

pkg/envoy/ads/cache_log.go, pkg/envoy/ads/server.go
Simply wrap our default logger around the snapshot cache's 
expected logging interface`
| …
=> feat(ads) implement a logger for the snapshot cache

charts/osm/templates/preinstall-hook.yaml, cmd/cli/install.go, cmd/cli/install_test.go, cmd/osm-preinstall/osm-preinstall.go, cmd/osm-preinstall/osm-preinstall_test.go
This change moves the validation that no meshes exist in the namespace
where OSM is to be installed from the CLI to the chart so using Helm
directly will have the same validation performed.
Part of #2147
- Added unit tests
| …
=> ref(install): move namespace controller check to chart

pkg/envoy/ads/health_test.go
This PR is a tiny simplification of a unit test. 
This uses `assert.True(x)` instead of `assert.Equal(x, true)`
=> envoy/ads: Simplify unit test

cmd/cli/namespace_remove.go, cmd/cli/namespace_test.go
Remove MetricsAnnotation fixes https://github.com/openservicemesh/osm/issues/4447
**Testing done**: yes
| CLI Tool                   | [x ] |
| Security …
=> cli: Remove metrics annotation from namespaces removed from the mesh

charts/osm/templates/osm-bootstrap-deployment.yaml, charts/osm/templates/osm-deployment.yaml, charts/osm/templates/osm-injector-deployment.yaml
* Adds pod anti-affinities to osm-controller, osm-bootstrap,
osm-injector to ensure better resilience for pod distribution
across nodes
* Replaces NodeSelectors with NodeAffinities for consistency
Pod anti-affinities:
- without anti-affinities: >= 2 replicas may or may not schedule on different nodes
- with anti-affinities: >= 2 replicas schedule on different nodes if possible
NodeAffinities:
- verified that a pod whose label values do not match node's label values fails to schedule
- verified that a node that does not have label for a pod's matchExpression causes the pod to fail to schedule …
=> charts(osm-*): add pod and node affinities to control plane pods

pkg/envoy/ads/response.go, pkg/envoy/ads/response_test.go, pkg/envoy/bootstrap/config.go, pkg/envoy/cds/cluster.go, pkg/envoy/cds/response_test.go, pkg/envoy/lds/auth.go, pkg/envoy/lds/egress.go, pkg/envoy/lds/gateway.go, pkg/envoy/lds/healthcheck.go, pkg/envoy/lds/ingress.go, pkg/envoy/lds/inmesh.go, pkg/envoy/lds/inmesh_test.go, pkg/envoy/lds/listener.go, pkg/envoy/lds/rbac.go, pkg/envoy/lds/tracing.go, pkg/envoy/lds/wasm.go, pkg/envoy/rds/route/rbac.go, pkg/envoy/rds/route/rbac_test.go, pkg/envoy/xdsutil.go, pkg/injector/envoy_config_health_probes.go
Replaces `ptypes.MarshalAny`, `ptypes.DurationProto` and `ptypes.UnmarshalAny(src, dst)` 
with `anypb.New`, `durationpb.New`, and `src.UnmarshalTo(dst)` respectively. Specialized
functionality is injected directly into the generated packages for each message
type.
Deprecation Messages:
```
ptypes.MarshalAny on pkg.go.dev
MarshalAny marshals the given message m into an anypb.Any message.
Deprecated: Call the anypb.New function instead.
```
```
ptypes.UnmarshalAny on pkg.go.dev
...
Deprecated: Call the any.UnmarshalTo method instead.
```
```
ptypes.DurationProto on pkg.go.dev
DurationProto converts a time.Duration to a durationpb.Duration.
Deprecated: Call the durationpb.New function instead.
```
- CI and automated demo
| Functional Area …
=> ref(ptypes): update deprecated ptypes functions

.github/workflows/main.yml, .github/workflows/pre-release.yml
This PR bumps the OSM GitHub workflow from using `actions/checkout@v1` to `v2`
=> ci: Use GitHub action checkout@v2

CONTRIBUTOR_LADDER.md
Resolve ambiguity by removing duplicate approvers
section, as both code maintainers and approvers
are the same and listed in the CODEOWNERS file.
Resolves #4559
=> contrib/ladder: remove duplicate approvers section

scripts/test-w-coverage.sh
`readarray` is a bash builtin introduced in 4.0. This change removes
its use so `make go-test-coverage` can be run on Macs which only ship
with bash 3.2 preinstalled.
Fixes #2152
- Tested locally on my Mac with bash 3.2
| …
=> fix(scripts): remove bash 4.0 dependency in coverage script

charts/osm/README.md, charts/osm/values.schema.json, charts/osm/values.yaml, cmd/osm-bootstrap/osm-bootstrap_test.go
Updates Envoy to v1.19.3 which include the latest security
patch.
Note: Update to v1.20+ is blocked due to
https://github.com/envoyproxy/envoy/issues/20113
CI
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? Will be updated after this change is merged.
=> envoy: update to v1.19.3

charts/osm/templates/osm-multicluster-gateway-deployment.yaml, go.mod, go.sum, pkg/envoy/ads/cache_callbacks.go, pkg/envoy/ads/cache_stream.go, pkg/envoy/ads/response.go, pkg/injector/envoy_config_test.go, pkg/injector/envoy_container.go
- Updates go-control-plane module to v0.10.1. This is
required to use latest changes to the XDS API, e.g.
to set HTTP MaxRequestsPerConnection as a part of the
HttpProtocolOptions.
Resolves snapshot cache (experimental) compatibility
with new SDK.
- Removes Envoy cmd line argument for bootstrap version
which is now the only supported version in Envoy. The
cmd line flag has been removed in Envoy.
Demo, CI
=> envoy: update go-control-plane version

pkg/crdconversion/crdconversion.go
Updates the code to only patch CRDs that require
a conversion strategy. This prevents the webhook
from being invoked for resources that do not
require conversion, thereby reducing the load
on the webhook server in large scale environments.
It also removes an additional failure path for
resource CRUDs.
Note: the existing stubs for APIs that do not need
a conversion are still present, in case they need
to be reused later on.
Local run, CI
2. Is …
=> crd/conversion: only patch CRDs needing conversion

OWNERS
Mirrors the CODEOWNERS file which reflects
the current set of code owners accurately.
The existing OWNERS file was a placeholder
for anyone with write access to the repo, not
necessarily a code owner. The OWNERS file
must be preserved since it's a requirement
for CNCF.
=> owners: mirror code owners file

cmd/osm-bootstrap/crds/config_meshconfig.yaml, pkg/apis/config/v1alpha2/mesh_config.go, pkg/apis/config/v1alpha2/zz_generated.deepcopy.go, pkg/crdconversion/config_meshconfig_conversion.go, pkg/crdconversion/config_meshconfig_conversion_test.go, pkg/envoy/bootstrap/config.go, pkg/envoy/bootstrap/config_test.go, pkg/envoy/bootstrap/types.go, pkg/injector/envoy_config.go, pkg/injector/envoy_config_test.go, pkg/injector/patch_test.go, pkg/injector/types.go
meshconfig
Add TLS protocol related sidecar configuration to MeshConfig.
* TLS minimum protocol version
* TLS maximum protocol version
* Cipher suites
* ECDH curves
These configuration details can be found on [Envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto)
Resovles: #4401 
* Unit test
| …
=> feat(sidecar): add tls protocol version and cipher suites config to

cmd/osm-controller/osm-controller.go, pkg/configurator/client.go, pkg/configurator/client_test.go, pkg/metricsstore/metricsstore.go
These changes add the `osm_feature_flag_enabled` metric labeled with
each feature flag name as it appears in the API. The metric is a Gauge
where a value of 0 indicates the flag is disabled and 1 when the flag is
enabled.
Part of #4568
- Added unit tests
- Did some manual smoke testing with the whole control plane running in a cluster
| …
=> feat(metrics): add feature flag metrics

cmd/osm-controller/osm-controller.go, pkg/envoy/ads/stream.go, pkg/metricsstore/metricsstore.go
This change adds a new `osm_proxy_xds_request_count` metric to count XDS
requests made by proxies, labeled with the proxy's certificate CN and
the XDS type.
Example:
osm_proxy_xds_request_count{common_name="369c9347-5b8f-42ff-ab1b-427ced15ee68.sidecar.bookbuyer.bookbuyer.cluster.local",type="type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"} 4
Part of #4568
- This part of the codebase doesn't have unit tests, but I did some manual smoke testing.
| Demo …
=> feat(metrics): add proxy XDS request metric

cmd/cli/uninstall_mesh.go, pkg/apis/policy/v1alpha1/upstreamtrafficsetting.go, pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go, pkg/catalog/fake.go, pkg/catalog/outbound_traffic_policies.go, pkg/catalog/outbound_traffic_policies_test.go, pkg/envoy/cds/cluster.go, pkg/envoy/cds/cluster_test.go, pkg/envoy/cds/response_test.go, pkg/envoy/xdsutil.go, pkg/policy/client.go, pkg/policy/client_test.go, pkg/policy/mock_client_generated.go, pkg/policy/types.go, pkg/trafficpolicy/types.go
Implements the UpstreamTrafficSetting API for
connection related configurations on clients
connecting to an upstream.
Additionally:
- Updates optional field in API to be a pointer
- Refactors cluster related code wrt protocol
options
- Disables circuit breaking for upstream clusters
by default by using max values
Part of #4500
Tested circuit breaking using a load generator
to exceed connection and request thresholds.
-   Did you notify the maintainers and provide …
=> policy: implement UpstreamTrafficSetting API

pkg/configurator/client.go, pkg/configurator/client_test.go
Updates the lister to only watch the required
MeshConfig instead of all MeshConfigs, and
removes unnecessary code pertaining to irrelevant
MeshConfigs.
CI, demo
=> configurator: only watch required MeshConfig

cmd/osm-controller/osm-controller.go, pkg/envoy/ads/stream.go, pkg/metricsstore/metricsstore.go
This change adds the `osm_proxy_max_connections_rejected` metric which
counts the number of proxy connections rejected because of the limit
defined by the MeshConfig's spec.sidecar.maxDataPlaneConnections having
been reached.
Part of #4568 
This part of the codebase isn't covered by unit tests but I did some manual smoke testing with the whole control plane running.
| …
=> feat(metrics): add proxy rejected max connections metric

docs/release_notes.md, pkg/configurator/client_test.go, pkg/envoy/ads/response.go, pkg/envoy/ads/response_test.go, pkg/httpserver/httpserver_test.go, pkg/metricsstore/metricsstore.go
This change adds `common_name` and `type` labels to the existing
`osm_proxy_response_send_success_count` and
`osm_proxy_response_send_error_count` metrics identifying the proxy and
XDS type for the response.
Example:
osm_proxy_response_send_success_count{common_name="32029594-2980-408e-b92a-3e5ce5174609.sidecar.bookthief.bookthief.cluster.local",type="type.googleapis.com/envoy.config.cluster.v3.Cluster"} 4
Part of #4568 
- Updated unit tests
- Did some manual smoke testing in a cluster
| Control Plane              | …
=> feat(metrics): add cn/type labels to xds response metrics

charts/osm/grafana/dashboards/osm-control-plane.json, charts/osm/grafana/dashboards/osm-data-plane-performance.json, charts/osm/grafana/dashboards/osm-mesh-envoy-details.json, charts/osm/grafana/dashboards/osm-pod-to-service.json, charts/osm/grafana/dashboards/osm-service-to-service.json, charts/osm/grafana/dashboards/osm-workload-to-service.json, charts/osm/grafana/dashboards/osm-workload-to-workload.json, charts/osm/templates/grafana-configmap.yaml
Shows the latest osm release version in the description
field of osm's Grafana dashboard manifests. Also shows
a meaningful message describing each Grafana dashboard's
functionality within the same description field.
The description field is used by osm's Grafana.com
dashboard repo at
https://grafana.com/orgs/openservicemesh/dashboards
The description field is displayed prominently as the
sub-header title for each Grafana.com osm dashboard.
It is also the only location (for now) in upstream
Grafana.com to display compatible versions.
Contributes towards #4282.
Resolves #4525.
Please describe how this change was tested. You could include supporting information
such as logs, snippets, and screenshots.
**Testing done**: Ran the bookstore …
=> chore: show release version in Grafana boards

pkg/catalog/egress.go, pkg/catalog/egress_test.go, pkg/envoy/cds/cluster.go, pkg/envoy/cds/cluster_test.go, pkg/envoy/cds/response.go, pkg/trafficpolicy/egress_types.go, pkg/trafficpolicy/trafficpolicy.go, pkg/validator/validators.go, pkg/validator/validators_test.go
- Implements capability to apply UpstreamTrafficSetting
configuration to an Egress destination.
- Refactors CDS to reuse code related to connection
settings.
- Updates validation webhook for Egress API
Part of #4500
Testing circuit breaker for Egress traffic. 
Sample config:
```
kind: UpstreamTrafficSetting
metadata:
name: httpbin-http
namespace: fortio
spec:
host: httpbin.org
connectionSettings:
tcp:
maxConnections: 1
http:
maxPendingRequests: 1
maxRequestsPerConnection: 1
---
kind: Egress
metadata:
name: httpbin-ext
namespace: fortio
spec:
sources:
- kind: ServiceAccount
name: default
namespace: fortio
hosts:
- httpbin.org
ports:
- number: 14001
protocol: http …
```
=> egress: add UpstreamTrafficSetting support

charts/osm/README.md, charts/osm/templates/_helpers.tpl, charts/osm/values.schema.json, charts/osm/values.yaml
Map image name in values.yaml and resolves #4331
| Install                    | [ x] |
=> Allow custom image names for OSM Helm chart

pkg/certificate/providers/certmanager/certificate_manager.go, pkg/crdconversion/framework.go, pkg/debugger/policy.go, pkg/debugger/port_forward.go
Log calls that don't include `.Msg()` or `.Msgf()` never get logged.
This change adds these where I could find they were missing.
Demo: https://go.dev/play/p/zaZ58Teo7y3
- See Go playground link above
| Performance …
=> fix(logs): add missing Msg calls to logs

pkg/envoy/ads/response_test.go, pkg/envoy/cds/cluster.go, pkg/envoy/cds/cluster_test.go, pkg/envoy/cds/response.go, pkg/envoy/cds/response_test.go, pkg/envoy/lds/ingress.go, pkg/envoy/lds/ingress_test.go, pkg/envoy/lds/inmesh.go, pkg/envoy/lds/inmesh_test.go, pkg/envoy/lds/response_test.go, pkg/envoy/xdsutil.go, pkg/envoy/xdsutil_test.go
This is a follow up PR of https://github.com/openservicemesh/osm/pull/4418. 
The original PR only applies TLS config to Envoy bootstrap config file, which means only the static resources are updated.
This PR applies the config to the dynamic resources in xDS response from control plane. SidecarSpec from MeshConfig is passed to the config generation sections.
* Unit test
* Manual test with kind cluster. Cipher suite is manually edited in mesh config. Confirmed that both static and dynamic resources are updated accordingly.
| CLI Tool …
=> feat(ads): xDS response add TLS config

pkg/apis/policy/v1alpha1/upstreamtrafficsetting.go
Corrects the comments for the UpstreamTrafficSetting
API fields.
Part of #4500
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? `yes`
https://github.com/openservicemesh/osm-docs/pull/343
=> apis: correct comments for UpstreamTrafficSetting

CODEOWNERS, OWNERS
Adds @trstringer as a codeowner maintainer.
@trstringer has been contributing to the
day-to-day maintenance of this project,
documentation improvements, package upgrades
to address vulnerabilities, bug-reporting
enhancements, code reviews etc.
**Maintainers**, if you agree with this nomination,
leave a "+1" comment and approve the PR (do not
merge it).
=> owners: add @trstringer as a codeowner maintainer

pkg/crdconversion/config_meshconfig_conversion.go, pkg/crdconversion/config_meshconfig_conversion_test.go, pkg/crdconversion/config_multiclusterservice_conversion.go, pkg/crdconversion/framework.go, pkg/crdconversion/framework_test.go, pkg/crdconversion/policy_egress_conversion.go, pkg/crdconversion/policy_ingressbackends_conversion.go, pkg/crdconversion/policy_retry_conversion.go, pkg/crdconversion/smi_httproutegroup_conversion.go, pkg/crdconversion/smi_tcproutes_conversion.go, pkg/crdconversion/smi_trafficaccess_conversion.go, pkg/crdconversion/smi_trafficsplit_conversion.go
Currently, CRD conversion webhooks only respond with the error returned
by the first failed resource converted, but there may be several. This
change aggregates errors from all resources sent in a request.
In addition, for #4568 I'm planning to add logic to record metrics labeled with the requested resources' `apiVersion` and `kind` from objects parsed out of the conversion request. Those changes (WIP) are shown here: https://github.com/openservicemesh/osm/commit/e5587d6c8a084559701a9c0ff537ebae851e3e19#diff-c4fc6ee6327a461684ba57d2d0cc26326c4cb0a980119d85cf93c730c1a7ec65. Without this change, resources in the request beyond the first one that fails will not have metrics recorded showing they were also failed to be converted.
- Added/updated unit tests …
=> ref(crdconvert): respond with errors from all requested resources

cmd/osm-bootstrap/osm-bootstrap.go, pkg/crdconversion/crdconversion.go, pkg/crdconversion/framework.go, pkg/crdconversion/framework_test.go, pkg/metricsstore/metricsstore.go
This change adds the `osm_conversion_webhook_resource_total` metric to
count custom resource conversions between API versions.
Part of #4568
Example:
osm_conversion_webhook_resource_total{from_version="config.openservicemesh.io/v1alpha1",kind="MeshConfig",success="true",to_version="config.openservicemesh.io/v1alpha2"} 1
- Updated unit tests
- Did some manual smoke testing with the whole control plane running and creating/updating/deleting a v1alpha1 MeshConfig
| Demo …
=> feat(metrics): add conversion webhook metrics

README.md, charts/osm/Chart.yaml, charts/osm/README.md, go.mod, go.sum, tests/e2e/e2e_ingressbackend.go, tests/e2e/e2e_k8s_version_test.go, tests/framework/common_apps.go
Drops support for v1.19 of k8s which is no longer
supported upstream.
Also updates the `kind` pkg version to use the
latest k8s version v1.23 by default. Since v1.22
deprecated the networking.k8s.io/v1beta1 API,
updates the e2e to use the stable v1 API .
Resolves #4610 
CI: `> k8s server version: v1.23.4` …
=> k8s/version: drop v1.19 support and bump CI version

docs/release_notes.md
Updates the release notes corresponding
to the following changes:
- 97c6395b: regarding k8s version v1.19
- fe049570, 7ecd8e9e: circuit breaking
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? `yet to be done`
=> docs: update release notes for v1.1.0

charts/osm/templates/osm-rbac.yaml, pkg/apis/policy/v1alpha1/upstreamtrafficsetting.go, pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go, pkg/gen/client/policy/clientset/versioned/typed/policy/v1alpha1/fake/fake_upstreamtrafficsetting.go, pkg/gen/client/policy/clientset/versioned/typed/policy/v1alpha1/upstreamtrafficsetting.go, pkg/k8s/client.go, pkg/k8s/client_test.go
Allows updating the status of the UpstreamTrafficSetting
resource through the status subresource. Also fixes a bug
where the status field was nested under the spec instead
of the top level resource.
Part of #4500
Unit test
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? `n/a`
=> apis/UpstreamTrafficSetting: allow setting status

charts/osm/templates/cleanup-hook.yaml, cmd/cli/uninstall_mesh.go, cmd/cli/uninstall_mesh_test.go, pkg/constants/constants.go, pkg/crdconversion/crdconversion.go, pkg/crdconversion/crdconversion_test.go, pkg/injector/webhook.go, pkg/injector/webhook_test.go, pkg/validator/patch.go, pkg/validator/server.go
Currently, the `CABundles` in the Validating, Conversion, and Mutating Webhook Configurations are set to the cert chains of the webhook certificates. The cert chains include the root, intermediate, and leaf certificates and the cabundles typically only include the root and intermediate certificates.
As described in #2650, Kubernetes secrets for the webhook certs were used to resolve a race condition on webhook certificate creation. Since the `CABundles` included the leaf certificates and each webhook had its own certificate, the Kubernetes API would only be able to successfully validate one webhook server instance of each type. All other webhook instances would receive no requests.
This change sets the `CABundle` for each Webhook Configuration to be the IssuingCA rather …
=> ref(webhook): remove leaf cert from webhook cabundles

pkg/envoy/lds/listener.go, pkg/envoy/lds/listener_test.go
Add Envoy access log configuration to inbound & outbound listener for TCP traffic.
Resolves #4530 
✅  updated unit tests.
Dev build of OSM is deployed and set up following the egress demo documentation. It is observed that:
* `outbound-listener` has proper `access_log` settings 
* Envoy logs egress HTTPS connection process. Screenshot below shows Envoy logging HTTPS connection to httpbin.org on port 443
| Demo                       | …
=> feat(log): enable Envoy logging on inbound & outbound TCP listeners

pkg/envoy/xdsutil.go
Fixes a misleading comment regarding number
of pods matching the proxy UUID encoded in
the certificate.
=> envoy: fix misleading comment

.github/workflows/main.yml, Makefile, cmd/cli/namespace_add.go, cmd/cli/namespace_test.go, cmd/cli/support_err.go, cmd/cli/version.go, pkg/bugreport/run.go, pkg/certificate/manager.go, pkg/envoy/ads/grpc.go, pkg/envoy/ads/stream.go, pkg/errcode/errcode.go, pkg/trafficpolicy/trafficpolicy.go, tests/framework/common_metrics.go, tests/scale/osm_common_profile_resources.go
This change updates the version of `golangci-lint` used in the Makefile
and CI to the floating `latest` version so we don't have to periodically
update this manually.
Other changes are made based on linter errors thrown by the updated
version of the linter.
- CI
- Did a manual smoke test of `make go-lint`
| Install                    | …
=> fix(ci): fix lint

charts/osm/templates/osm-bootstrap-deployment.yaml
**Description**: OSM bootstrap deployment is failing if the reconcile label has already been added, so adding the overwrite flag to fix this. 
**Testing done**: Edited osm-bootstrap deployment file and ensured that deployment succeeded. 
| …
=> Add --overwrite to kubectl label cmd in osm bootstrap

charts/osm/templates/osm-bootstrap-deployment.yaml
**Description**: Cherry picking af50d175a650e2047b2f59f4604fc88923e1cb60 to add --overwrite label to osm_bootstrap deployment. 
| SMI Policy …
=> Add overwrite label osm bootstrap

cmd/osm-controller/osm-controller.go, pkg/smi/client.go, pkg/smi/client_test.go
This PR removes the unused kubeClient from SMI client in `pkg/smi/client.go`.
Found while navigating the source code.
Existing unit tests in `client_tests.go` should be enough for the changeset.
| Performance                | [ …
=> ref(pkg/smi): remove unused kubeClient from smi client

pkg/cli/verifier/envoy_config_parser.go, pkg/cli/verifier/envoy_config_parser_test.go, pkg/cli/verifier/testdata/sample-envoy-config-dump-bookbuyer.json, pkg/cli/verifier/testdata/sample-envoy-config-dump-bookstore.json
Adds config parser utility. This is borrowed
from [osm-health](https://github.com/openservicemesh/osm-health/blob/main/pkg/envoy/parse.go) with some tweaks.
Part of #4634
Co-authored-by: Delyan Raychev <delyan.raychev@microsoft.com>
Co-authored-by: Jon Huhn <johuhn@microsoft.com>
1. Does this change contain code from or inspired by another project? Yes
-   Did you notify the maintainers and provide attribution? Yes (co-authors) …
=> cli/verifier: add Envoy config dump parser

cmd/cli/verify_connectivity.go, pkg/catalog/inbound_traffic_policies.go, pkg/catalog/outbound_traffic_policies.go, pkg/catalog/outbound_traffic_policies_test.go, pkg/cli/verifier/connectivity_pod_to_pod.go, pkg/cli/verifier/connectivity_pod_to_pod_test.go, pkg/cli/verifier/envoy_config.go, pkg/cli/verifier/fake.go, pkg/cli/verifier/sidecar.go, pkg/cli/verifier/testdata/curl_permissive.json, pkg/cli/verifier/testdata/httpbin1_permissive.json, pkg/cli/verifier/testdata/httpbin2_permissive.json, pkg/cli/verifier/verifier.go, pkg/envoy/lds/inmesh.go, pkg/envoy/lds/inmesh_test.go, pkg/envoy/lds/listener.go, pkg/envoy/lds/response_test.go, pkg/service/types.go
- Adds simple Envoy sidecar checker
- Adds basic source config dump check for
pod->pod connectivity verifier. The checks
are limited to verifying the outbound filter
chain name, match, and filter, which provides
a reasonably high coverage when a misconfiguration
exists.
- Simplifies filter chain naming for the matching
service which enables cleanly deriving the
inbound/outbound filter chain match names.
- Adds a test to verify source config. The test
simulates curl -> httpbin connectivity in
permissive mode.
- Changes the verifier result printer to add a
marker by its depth, so the output allows
identifying the parent verification for nested
verifications.
Part of #4634
- Deploy curl and httpbin (with 2 replicas) as per the …
=> envoy/verifier: add source config checker

tests/e2e/README.md, tests/e2e/constants.go, tests/e2e/e2e_certmanager_test.go, tests/e2e/e2e_grpc_insecure_origination_test.go, tests/e2e/e2e_grpc_secure_origination_test.go, tests/e2e/e2e_ip_exclusion_test.go, tests/e2e/e2e_pod_client_server_test.go, tests/e2e/e2e_port_exclusion_test.go, tests/e2e/e2e_tcp_client_server_test.go, tests/e2e/e2e_tcp_egress_test.go, tests/framework/common.go, tests/framework/common_traffic_fortio.go
Below is a list of services in the e2e tests that are used to test different web request protocols:
* HTTP: curl
* TCP: tcp-echo-server
* gRPC: grpcurl, grpcbin
They are right now testing in single request mode. As our project develops, we need to a more customizable request sending solution to test various scenarios.
Fortio is a load testing tool that comes with both the server (web UI included) and the load generating client. They are packaged in a single Docker image.
In this PR:
* Using Fortio, e2e test framework is improved by supporting simple load test in HTTP, TCP and gRPC(insecure) protocols. It exposes some common load test configurations such as test duration, number of calls and connections etc.
* Migrated some e2e tests to use Fortio for demonstration and …
=> ref(test): Improve e2e test framework using Fortio as load test tool

go.mod, go.sum
Golang crypto library has security issue and fails CI test. This PR
upgrades the crypto library.
Failed CI test: https://github.com/openservicemesh/osm/runs/6101199443
Re-run the failed CI job on local and get is passed:
| …
=> fix: upgrade vulnerable library crypto

cmd/osm-bootstrap/osm-bootstrap.go, cmd/osm-controller/osm-controller.go, cmd/osm-injector/osm-injector.go, pkg/metricsstore/metricsstore.go, pkg/version/version.go
Simply expose the OSM version information as a prometheus metric.
=> expose the version information via prometheus

cmd/osm-controller/osm-controller.go, pkg/policy/client.go, pkg/policy/client_test.go, pkg/policy/conflicts.go, pkg/policy/types.go, pkg/validator/server.go, pkg/validator/server_test.go, pkg/validator/types.go, pkg/validator/validators.go, pkg/validator/validators_test.go
Fixes #4638. Adds stricter validatingWebhook validations for IngressBackend and UpstreamTrafficSetting (duplicate backends and hosts respectively). This PR also changes MeshService -> IngressBackend retrieval process to match on port as well as service name. This appears to have been an accidental omission from the original design since one would expect to be able to create an IngressBackend that allows access to the same service on different ports.
Additional unit tests added in the appropriate Golang packages
1. Does this change contain …
=> IngressBackend UpstreamTrafficSetting validations

pkg/cli/verifier/connectivity_pod_to_pod_test.go, pkg/cli/verifier/envoy_config.go, pkg/k8s/client.go
- Verifies HTTP inbound and outbound route
configs and top level service domain
- Updates code to correctly translate k8s
service to MeshService. Previously this
would break when a named TargetPort is
used for the service port.
- Exports reusable code in k8s pkg
Part of #4634
- curl -> httpbin test in permissive mode
```
$ osm verify connectivity --from-pod curl/curl-7bb5845476-5b7wr --to-pod httpbin/httpbin-69dc7d545c-hbc6d --service httpbin --app-protocol http
W0422 10:12:19.574556   27135 warnings.go:70] config.openservicemesh.io/v1alpha2 MeshConfig is deprecated; use config.openservicemesh.io/v1alpha3 MeshConfig
[+] Context: Verify if pod "curl/curl-7bb5845476-5b7wr" can access pod …
```
=> cli/verifier: verify basic HTTP route configs

pkg/injector/envoy_config.go, pkg/injector/envoy_config_test.go, pkg/injector/patch.go, pkg/injector/patch_test.go, pkg/injector/volumes.go, pkg/injector/volumes_test.go, pkg/injector/webhook.go, pkg/injector/webhook_test.go, pkg/utils/proto.go
We do this by mutating the already injected pod's UUID,
and reinserting the UUID & new certificate in the appropriate
locations. This will result in a new bootstrap config as well.
=> Support pod recreation for the kubectl debug command.

pkg/cli/verifier/connectivity_pod_to_pod.go, pkg/cli/verifier/envoy_config.go
Uses the same mechanism as the controller to derive
the app protocol for a service port. This is required
for a service with multiple ports, both serving
different protocols.
The `AppProtocol` in the `TrafficAttribute` struct
will be used for ingress/egress instead.
Part of #4634
```
$ osm verify connectivity --from-pod curl/curl-7bb5845476-5b7wr --to-pod httpbin/httpbin-69dc7d545c-hbc6d --service httpbin 
[+] Context: Verify if pod "curl/curl-7bb5845476-5b7wr" can access pod "httpbin/httpbin-69dc7d545c-hbc6d" for service "httpbin/httpbin"
```
| CLI Tool …
=> cli/verifier: derive appProtocol from service

pkg/certificate/providers/tresor/certificate_manager.go
Signed-off-by: Sarah Christoff <sarah.christoff13@gmail.com>
Resolves #4469  where tresor would continue to try and
create a certificate even when decoding the PEM
had an error
| Certificate Management     | [x ] |
| SMI Policy                 | …
=> fix(certificates): return when encountering error in tresor cert issuing  

charts/osm/README.md, charts/osm/templates/preset-mesh-config.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, cmd/osm-bootstrap/crds/config_meshconfig.yaml, pkg/apis/config/v1alpha2/mesh_config.go, pkg/apis/config/v1alpha2/zz_generated.deepcopy.go, pkg/injector/init_container.go, pkg/injector/init_container_test.go, pkg/injector/iptables.go, pkg/injector/iptables_test.go, pkg/injector/patch.go
This change adds a new configurable list of ignored network interface
names. Traffic received from and sent to those interfaces is not
forwarded to the sidecar container by iptables. When this list is empty
(the default), osm-injector produces the exact same iptables commands as
it did before.
The list is configured in the chart at `osm.networkInterfaceExclusionList`
and in the MeshConfig at `spec.traffic.networkInterfaceExclusionList`.
Fixes #4546
Updated unit tests
<details>
<summary>Tested manually e2e</summary>
- Installed [Multus CNI](https://github.com/k8snetworkplumbingwg/multus-cni) on an AKS cluster: `kubectl apply -f https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset-thick-plugin.yml`
- Created …
=> feat(injector): add list of ignored network interfaces

CONTRIBUTING.md
This change adds a new recommendation to CONTRIBUTING.md to not rewrite
git history with `git commit --amend` or `git rebase` after PRs have
been opened to make reviewing them easier.
**Testing done**: N/A
| …
=> docs(contrib): recommend not rewriting git history

cmd/osm-bootstrap/crds/config_mesh_root_certificate.yaml
Adds the CRD for MeshRootCertificate API.
Part of #4502
| …
=> crds: add MeshRootCertificate CRD

tests/framework/common.go
**Description**: Fix e2e_client_server_connectivity_test for NoInstall by explictly setting LocalProxyMode in setMeshConfigToDefault Method. 
Resolves https://github.com/openservicemesh/osm/issues/4707
**Testing done**: Tested locally on AKS cluster with OSM already installed. 
| …
=> Fix e2e_client_server_connectivity_test for NoInstall

pkg/cli/verifier/connectivity_pod_to_pod_test.go, pkg/cli/verifier/envoy_config.go, pkg/cli/verifier/envoy_config_parser.go
Verifies the presence of client and server side
secrets required for pod-to-pod connectivity.
Part of #4634
```
$ osm verify connectivity --from-pod curl/curl-7bb5845476-5b7wr --to-pod httpbin/httpbin-69dc7d545c-hbc6d --service httpbin 
[+] Context: Verify if pod "curl/curl-7bb5845476-5b7wr" can access pod "httpbin/httpbin-69dc7d545c-hbc6d" for service "httpbin/httpbin"
```
```
$ osm verify connectivity --from-pod curl/curl-7bb5845476-5b7wr --to-pod httpbin/httpbin-69dc7d545c-hbc6d --service httpbin 
[+] Context: Verify if pod "curl/curl-7bb5845476-5b7wr" can access pod …
```
=> cli/verifier: verify presence of secrets

cmd/cli/verify_connectivity.go, pkg/cli/verifier/connectivity_egress.go, pkg/cli/verifier/envoy_config.go
Adds the stubs necessary to perform egress
config verification on a pod.
A subsequent change will add additional
validations that perform the actual checks.
Part of #4634
```
$ osm verify connectivity --from-pod curl/curl-7bb5845476-5b7wr --to-pod httpbin/httpbin-69dc7d545c-hbc6d --service httpbin 
[+] Context: Verify if pod "curl/curl-7bb5845476-5b7wr" can access pod "httpbin/httpbin-69dc7d545c-hbc6d" for service "httpbin/httpbin"
```
```
$ osm verify connectivity --from-pod curl/curl-7bb5845476-5b7wr --service httpbin 
Error: one of --to-pod|--egress must be set for connectivity verification
```
```
$ osm verify connectivity --from-pod …
```
=> cli/verifier: add stubs for egress checks

pkg/certificate/fake_manager.go, pkg/certificate/manager.go, pkg/certificate/manager_test.go, pkg/certificate/providers/certmanager/certificate_manager.go, pkg/certificate/providers/config.go, pkg/certificate/providers/tresor/certificate_manager.go, pkg/certificate/providers/tresor/fake/fake.go, pkg/certificate/providers/vault/certificate_manager.go, pkg/certificate/providers/vault/certificate_manager_test.go, pkg/certificate/providers/vault/types.go, pkg/certificate/types.go, pkg/utils/grpc_test.go, pkg/utils/mtls_test.go
Supports multiple clients in Manager struct. Refactoring
as a part of the root cert rotation work. During root cert
rotation, there will be 2 CertManagers - the CertManager
being rotated in and the CertManager being rotated out as
specified in the MeshRootCertificates.
The ca is moved from the Manager to the CertManagers
for each cert provider.
Part of #4502
- CI
3. Has documentation corresponding to this change …
=> ref(cert): update Manager to support mult clients

cmd/cli/uninstall_mesh.go, cmd/cli/uninstall_mesh_test.go
Updates `uninstall mesh` command so that user is prompted on whether they want to uninstall an existing mesh. Also, adds a warning for `delete-cluster-wide-resources` if there are remaining meshes in the cluster, before deleting cluster resources. Resolves #4613
Uninstall mesh now prompts with existing mesh:
Can also uninstall specific mesh with `mesh-name` flag:
Informs when mesh doesn't exist (including when trying to force uninstall):
`delete-namespace` flag:
`delete-cluster-wide-resources` flag:
warning when deleting cluster resources and there are still meshes in the cluster (updated):
`force` flag uninstalls existing mesh [only one mesh in cluster]:
`force` flag uninstalls the default …
=> refactor(cmd/cli): update uninstall cmd

charts/osm/templates/osm-rbac.yaml, cmd/osm-bootstrap/osm-bootstrap.go, cmd/osm-controller/osm-controller.go, cmd/osm-injector/osm-injector.go, pkg/announcements/types.go, pkg/apis/config/v1alpha2/register.go, pkg/catalog/fake/fake.go, pkg/configurator/client.go, pkg/configurator/client_test.go, pkg/configurator/methods_test.go, pkg/configurator/types.go, pkg/envoy/sds/response_test.go, pkg/errcode/errcode.go
Adds the MeshRootCertificate informer client. Refactors the
configurator client to watch the MeshRootCertificate and
MeshConfig resources. Attempts to group informer clients for
resources in the same API group, config.openservicemesh.io.
Resolves #4710 
Part of #4502 
Signed-off-by: jaellio <jaellio@microsoft.com>
- CI
- Demo …
=> feat(api/MeshRootCertificate): add informer client

cmd/cli/verify.go, cmd/cli/verify_control_plane.go, pkg/cli/verifier/connectivity_egress_test.go, pkg/cli/verifier/control_plane.go, pkg/cli/verifier/control_plane_test.go, pkg/cli/verifier/pod.go
Adds a `verify control-plane-health` command.
Currently this check is limited to verifying
that the control plane pods are running.
This will be extended to perform additional
checks pertaining to the health of the
control plane, such as looking for fatal/error
events reported, probe failures, etc.
Part of #4634
When all control plane pods are running
```
$ osm verify control-plane-health
[+] Context: Verify the health of OSM control plane
```
When the pod is not found
```
$ osm verify control-plane-health
checking pods
[+] Context: Verify the health of OSM control plane
Status: Failure
Reason: A …
```
=> cli/verifier: add control-plane-health command

pkg/envoy/lds/http_connection.go, pkg/envoy/lds/http_connection_test.go
Allows to set allowed http upgrade type so that envoy will pass the requested upgrade request upstream.
Implements #4725 by allowing to set the `websocket` upgrade type.
Closes #4725 
**Testing done**:  tested end-to-end on a test cluster
| Egress                     | [x] |
| Ingress                    | [x] |
| Networking                 | [x] |
| …
=> Allow websocket upgrade for all http connections

charts/osm/README.md, charts/osm/templates/osm-bootstrap-deployment.yaml, charts/osm/templates/osm-deployment.yaml, charts/osm/templates/osm-injector-deployment.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, cmd/osm-bootstrap/crds/config_mesh_root_certificate.yaml, cmd/osm-bootstrap/osm-bootstrap.go, cmd/osm-bootstrap/osm-bootstrap_test.go, cmd/osm-controller/osm-controller.go, cmd/osm-controller/validate.go, cmd/osm-controller/validate_test.go, cmd/osm-injector/osm-injector.go, pkg/apis/config/v1alpha2/meshrootcertificate.go, pkg/certificate/fake_manager.go, pkg/certificate/manager.go, pkg/certificate/manager_test.go, pkg/certificate/providers/compat.go, pkg/certificate/providers/config.go, pkg/certificate/providers/config_test.go, pkg/certificate/providers/options.go, pkg/certificate/providers/options_test.go, pkg/certificate/providers/tresor/fake/fake.go, pkg/certificate/providers/types.go, pkg/certificate/providers/vault/certificate_manager.go, pkg/certificate/types.go, pkg/constants/constants.go
The compat layer is used to convert from the old style options
to the new style MRC. This is useful so that we don't have to manage
two implementations of the certificate.Manager.
part of #4713
=> feat(certificate): create a compat layer for provider generation

scripts/port-forward-all.sh
Since the port-forward-all.sh script is no longer referred to on the
docs site for the demo there, it no longer needs to port-forward the
`bookstore` deployment which is not expected to exist in the automated
demo here.
Fixes #3521
- Ran the script against the automated demo and saw no errors.
| Demo                       | [X] |
| …
=> fix(demo): remove unneeded port-forward for bookstore

pkg/workerpool/workerpool.go, pkg/workerpool/workerpool_test.go
This PR accomplishes the following:
1. Remove head of line blocking, by switching from N workers and N queues, to N workers on 1 queue.
Head of line blocking can occur in the current implementation if a single worker is busy, the jobs queued on that worker's queue can get backed up. While the overall system can make progress, none of the jobs in that queue do. Using a single queue maintains the exact same throughput of the system, but reduces the amount of time that any single job may take due to a blockage in the queue. This is taken from queueing theory, and is the most efficient way to process items in a queue. In layman's terms, think of a line at a grocery store where each register has a unique line vs. one line that feeds all registers.
2. Simplifies the code by removing additional …
=> remove head of line blocking from workerpool

pkg/certificate/certificate.go, pkg/certificate/fake_manager.go, pkg/certificate/manager.go, pkg/certificate/manager_test.go, pkg/certificate/providers/compat.go, pkg/certificate/providers/config.go, pkg/certificate/providers/tresor/fake/fake.go, pkg/certificate/types.go
State management for certificate rotation
This PR implements certificate state management for rotation, by maintaining 2 `certificate.Issuer`'s (previously `certificate.Provider`). It adds an ID to each issuer, to be extracted from the MRC, to delineate between a prior issued cert, and the current intended issuer.
We then add a combine method on a certificate, which will add in a `pem.RootCertificate`, such that `GetIssuingCA` will now return the combined set of certificates for validation.
=> Certificate issuance state management

go.mod, go.sum
Resolves CVE-2022-29162 by upgrading runc to v1.1.2.
| …
=> Patch runc security issue by upgrading to v1.1.2

tests/e2e/e2e_ingressbackend.go
**Description**: This PR addresses an issue where an ingress without a root path does not work for some non-kind distributions like AKS: https://github.com/kubernetes/ingress-nginx/issues/8518. Adding a wildcard path in addition to the status/200 path resolved the issue. 
The ingress error happens intermittently. 
**Testing done**: Tested locally on AKS cluster. 
| Egress                     | …
=> Add root path to ingress in ingress_backend_e2e

charts/osm/README.md, charts/osm/templates/cleanup-hook.yaml, charts/osm/templates/preset-mesh-root-certificate.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, cmd/cli/uninstall_mesh.go, cmd/osm-bootstrap/crds/config_mesh_root_certificate.yaml, cmd/osm-bootstrap/osm-bootstrap.go, cmd/osm-bootstrap/osm-bootstrap_test.go, pkg/apis/config/v1alpha2/meshrootcertificate.go, pkg/certificate/providers/config.go, pkg/constants/constants.go, tests/framework/common.go, tests/framework/types.go
Updates the osm-bootstrap to create a default MeshRootCertificate
on osm install. Adds a preset-mesh-root-certificate ConfigMap to
the Helm templates. The osm-bootstrap will obtain the MRC spec
from the ConfigMap and attempt to create a default MRC. If an MRC
already exists with a complete state and issuing rotation stage then
the osm-bootstrap will not create the default MRC.
Additional changes:
- adds MeshRootCertificate CRD to uninstall list
- adds the tokenSecretName and tokenSecretKey values to the
osm.vault values
- removes SecretName from the certManager provider in the mesh
root certificate
- cleans up MeshConfig tests
Part of #4712 
Note: This change does not include creating the Vault token
secret. The MRC created is not used at this point by the OSM
control …
=> feat(certs): create MRC on install

tests/e2e/e2e_ingressbackend.go
Addresses an issue where an ingress without a root path does
not work for some non-kind distributions like AKS:
kubernetes/ingress-nginx#8518.
Adding a wildcard path in addition to the status/200 path resolves
the issue.
**Description**: Cherry pick commit to add wildcard path to ingress in ingress backend e2e. 
| Ingress …
=> Backport: Add root path ingress e2e test (#4756)

go.mod, go.sum
This PR fixes CVE-2022-28948, which causes an issue when attemping to
deserialize invalid input.
| Security                   | [X] |
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? Not applicable.
=> Fix CVE-2022-28948 by patching gopkg.in/yaml.v3

charts/osm/README.md, charts/osm/templates/preset-mesh-root-certificate.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, cmd/osm-bootstrap/crds/config_mesh_root_certificate.yaml, pkg/apis/config/v1alpha2/meshrootcertificate.go
Add the trust domain field to the MRC
=> add trust domain to mesh root certificate

tests/e2e/e2e_statefulsets_test.go, tests/framework/common.go, tests/framework/common_apps.go
**Description**: Add SecuityContextConstraint for zookeeper SA in e2e_statefulsets_test for OpenShift. 
Resolves https://github.com/openservicemesh/osm/issues/4784
**Testing done**: Tested locally on OpenShift cluster.  …
=> Add openshift SCC zookeeper

cmd/osm-bootstrap/osm-bootstrap.go, cmd/osm-controller/osm-controller.go, cmd/osm-injector/osm-injector.go, pkg/metricsstore/metricsstore.go, pkg/reconciler/crd_handler.go, pkg/reconciler/crd_handler_test.go, pkg/reconciler/mutating_webhook_handler.go, pkg/reconciler/mutating_webhook_handler_test.go, pkg/reconciler/validating_webhook_handler.go, pkg/reconciler/validating_webhook_handler_test.go
This change adds an `osm_reconciliation_total` metric counting how many
times the reconciler has been triggered for each kind.
Fixes #4568
Example:
osm_reconciliation_total{kind="ValidatingWebhookConfiguration"} 9
- Updated unit tests
- Did some manual smoke testing with the whole control plane running while changing/deleting reconciled resources
| Ingress …
=> feat(metrics): add osm_reconciliation_total metric

SECURITY.md
Signed-off-by: Sarah Christoff <sarah.christoff13@gmail.com>
Fixes #2402 
yes
no
4. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)?
n/a
=> docs(contrib): add security.md

cmd/osm-controller/osm-controller.go, cmd/osm-injector/osm-injector.go, pkg/k8s/client.go, pkg/k8s/client_test.go, pkg/k8s/errors.go, pkg/k8s/informers/informers.go, pkg/k8s/informers/init.go, pkg/k8s/informers/types.go, pkg/k8s/types.go, pkg/smi/client_test.go
Instead of creating different objects (from 5 different packages) that
each manage their own informer collections, create a single object that
runs a set of informers. A pointer to this object is then shared with
all objects that need it.
Addresses #4551
This PR only modifies the k8s client; once this is merged, the other 4 clients (SMI, config, configurator, and policy) will be modified to use `InformerCollection` as well
-   Did you notify the maintainers and provide attribution? N/A
2. Is this a …
=> k8s/informers: centralize informers to simplify code

cmd/osm-bootstrap/crds/policy_upstream_traffic_setting.yaml
Adds the local rate limiting spec to the UpstreamTrafficSetting
CRD.
The spec is based on the [design doc](https://docs.google.com/document/d/1VTdte9v0JpX7odMtXlGsLlGwDlnXBAEZAf8PMJ_EyY4/edit?usp=sharing).
Part of #2018
Applied the CRD and verified all the fields can be set using the sample:
```
kind: UpstreamTrafficSetting
metadata:
name: local-rate-limit-foo
namespace: test
spec:
host: foo.test.svc.cluster.local
rateLimit:
local:
tcp:
connections: 100
unit: second
burst: 20
http:
requests: 1000
unit: hour
burst: 100
responseStatusCode: 429
responseHeadersToAdd:
- name: x-osm-rate-limited
value: "true"
httpRoutes:
- path: /foo
rateLimit:
local:
requests: 10
unit: second
responseStatusCode: 429 …
```
=> rate-limiting: add spec to UpstreamTrafficSetting CRD

pkg/certificate/manager.go, pkg/certificate/types.go, pkg/envoy/lds/inmesh_test.go, pkg/envoy/lds/listener_test.go, pkg/envoy/lds/rbac.go, pkg/envoy/lds/rbac_test.go, pkg/envoy/lds/response.go, pkg/envoy/lds/types.go, pkg/envoy/rbac/policy.go, pkg/envoy/rbac/policy_test.go, pkg/envoy/rds/route/rbac.go
This PR has 2 main changes:
1. I set the policy builder's AddPrincipal method to AddIdentity. Following my own advice, the builders should accept inputs in terms of OSM concepts, and return envoy configs. A principal is an envoy concept, and so should be constructed internally, and not leak into its parameters.
2. I set the trust domain (currently an empty string) on the listenerbuilder so that it is used on the policy builder.
The final PR will be to simultaneously remove the trustDomain from service.Identity, while populating the trust domain within the cert manager.
=> Set (empty) trust domain on listener builder

pkg/catalog/inbound_traffic_policies.go, pkg/catalog/inbound_traffic_policies_test.go, pkg/trafficpolicy/trafficpolicy.go, pkg/trafficpolicy/trafficpolicy_test.go, pkg/trafficpolicy/types.go
Plumbs the tcp, virtual_host and per route rate limiting
configs into the inbound traffic policy objects.
Next, they will be mapped to Envoy listener and route
configs.
Part of #2018
Unit tests
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? `n/a`
=> rate-limiting: plumb config into inbound policies

pkg/catalog/inbound_traffic_policies.go, pkg/catalog/inbound_traffic_policies_test.go, pkg/envoy/lds/inmesh.go, pkg/envoy/lds/inmesh_test.go, pkg/envoy/lds/response.go
Similar to how outbound filter config is built, this change
relies on the TrafficMatch type to build inbound filter
configs. The TrafficMatch has a 1-1 mapping to an Envoy
filter_chain config. This is necessary to be able to
cleanly apply TrafficMatch based policies (e.g. rate
limiting) without needing to rely on multiple catalog
APIs.
Part of #2018
Unit tests, CI
3. Has documentation corresponding to this …
=> envoy|catalog: use TrafficMatch to build inbound filter config

CONTRIBUTOR_LADDER.md
Clarifies role requirements
Defines the process for adding codeowner permissions per directory
Resolves https://github.com/openservicemesh/osm/issues/4774
| Other                      | [x ] |
1. Does this change contain code from or inspired by another project? yes
- kubernetes
- https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md
- https://github.com/kubernetes/community/blob/master/community-membership.md
- CNCF
- https://github.com/cncf/project-template/blob/main/CONTRIBUTOR_LADDER.md …
=> ref(contributors): update contributor roles and requirements

pkg/envoy/cds/cluster.go, pkg/envoy/cds/cluster_test.go
With the addition of rate limiting to the
UpstreamTrafficSetting spec, it is possible
for the UpstreamTrafficSetting object to be non
nil while having its ConnectionSettings as nil.
Add nil check so the code doesn't panic when
ConnectionSettings is nil and RateLimit is configured.
Unit test …
=> envoy/cds: add nil check for ConnectionSettings

pkg/envoy/lds/inmesh.go, pkg/envoy/lds/inmesh_test.go
Adds support for rate limiting L4 TCP connections.
Part of #2018
1. Unit tests
2. [Demo](https://deploy-preview-389--osm-docs.netlify.app/docs/demos/local_rate_limit_connections/)
3. Is this a breaking change? `no`
4. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? `yes`: …
=> rate-limit: implement connection level local rate limiting

cmd/osm-bootstrap/crds/config_mesh_root_certificate.yaml, cmd/osm-bootstrap/osm-bootstrap.go, cmd/osm-bootstrap/osm-bootstrap_test.go, pkg/apis/config/v1alpha2/meshrootcertificate.go, pkg/certificate/providers/config.go, pkg/constants/constants.go
Signed-off-by: Sarah Christoff <sarah.christoff13@gmail.com>
- update MeshRootStatus to ProviderState 
- remove rotation stage
- add consts for all defined states
- CI
3. Has documentation corresponding to this change been updated in the [osm-docs] (https://github.com/openservicemesh/osm-docs) repo (if applicable)? No
=> (feat: certs) MeshRootStatus -> ProviderState 

.github/workflows/main.yml, README.md, charts/osm/Chart.yaml, charts/osm/README.md, cmd/cli/install_test.go, cmd/cli/mesh_upgrade_test.go, cmd/cli/uninstall_mesh_test.go, docs/release_notes.md, go.mod, go.sum
Update Kerbernetes matrix testing by removing Kubernetes v1.21 and
adding v1.23 and v1.24. Also update the README to include the oldest
supported Kubernetes version.
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? Updates soon by @zr-msft
=> Update Kubernetes version testing

.env.example, .github/workflows/main.yml, charts/osm/README.md, charts/osm/values.yaml, demo/run-osm-demo.sh, tests/e2e/e2e_helm_install_test.go
Set enableEgress and permissive mode to default to true in values.yaml
=> use friendlier defaults for egress and permissive mode

pkg/apis/policy/v1alpha1/upstreamtrafficsetting.go, pkg/envoy/rds/route/rbac.go, pkg/envoy/rds/route/rbac_test.go, pkg/envoy/rds/route/route_config.go, pkg/envoy/rds/route/route_config_test.go, pkg/envoy/types.go, tests/e2e/e2e_local_ratelimit_test.go
- Adds capability to locally (per sidecar) rate limit
HTTP traffic
- Adds HTTP rate limit e2e test
- Clarifies allowed HTTP status codes for rate limited
responses
Part of #2018
Unit tests, e2e tests
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? `will be updated post merge`
=> rate-limiting: add HTTP local rate limiting capability

charts/osm/README.md, charts/osm/values.yaml, pkg/certificate/providers/config.go, pkg/certificate/providers/config_test.go, pkg/certificate/providers/options.go, pkg/certificate/providers/options_test.go, pkg/certificate/providers/types.go
If the Vault token option is not set, the token will be obtained
from the secret referenced in the SecretKeyRef. Currently, the
Vault token must still be set as an option if Vault is the cert
provider. In a subsequent change, all cert provider flags will be
removed from the osm-bootstrap, osm-controller, and osm-injector.
These values will instead be obtained from the MRC created by the
osm-bootstrap and populated using the preset-mesh-root-certificate.
- CI
-   Did …
=> feat(certs): get Vault token from Secret

pkg/validator/validators.go, pkg/validator/validators_test.go
Adds logic to validate the HTTP status code is
among a list of status codes supported by Envoy.
Part of #2018
Unit tests
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? yes
=> validator: validate HTTP rate limiting status code

CODEOWNERS, OWNERS
@keithmattix has been contributing to the project at the level that is
expected of a maintainer to include: Designs and implementations of
feature work, complex bug triaging and fixing, and indepth and sustained
code reviews raising the quality of the product.
**Maintainers**, if you agree with this nomination, leave a "+1" comment
and approve the PR (do not merge it). …
=> Add @keithmattix as a codeowner maintainer

.github/workflows/main.yml
Currently when CODEOWNERS and OWNERS files are modified this will cause
the CI pipeline to be triggered. There is no reason for CI to run when
these two files are modified, so this change ignores them.
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? N/A
=> Ignore CODEOWNERS and OWNERS for CI

pkg/certificate/certificate.go, pkg/certificate/manager.go, pkg/crdconversion/crdconversion.go, pkg/envoy/lds/response_test.go, pkg/envoy/rds/response_test.go, pkg/ingress/gateway.go, pkg/utils/grpc_test.go, pkg/utils/mtls_test.go, pkg/validator/patch.go, tests/scenarios/traffic_split_with_apex_service_test.go, tests/scenarios/traffic_split_with_zero_weight_test.go
1. align imports on casing for tresorFake
2. use GetTrustedCAs where appropriate
3. use a logger component in certificate package
=> cert changes: Fix GetTrustedCAs; align import names; use component logger

.gitignore, Makefile, pkg/certificate/providers/tresor/ca_test.go, pkg/certificate/providers/tresor/certificate_manager_benchmark_test.go, pkg/certificate/providers/tresor/certificate_manager_test.go, pkg/certificate/providers/tresor/types.go, pkg/envoy/ads/response_benchmark_test.go, pkg/envoy/bootstrap/envoy_config_benchmark_test.go, pkg/injector/webhook_benchmark_test.go, pkg/tests/fixtures.go, pkg/validator/server_benchmark_test.go, scripts/go-benchmark.sh
Offline performance profiling is part of issue #4622. This PR adds benchmark test cases that profiles CPU usage, memory usage and program timeline.
* Added `make go-benchmark` make task. It runs all registered packages to be profiled.
* Each `go-benchmark` execution generates profile results which are saved in the `bm_profiles/<execution-timestamp>` folder, which is Git ignored. 
* For the ease of access the results, a symbol link to the latest results is created as `bm_profiles/latest`
TODO after this PR:
* Create a CI job to run benchmark before and after changes and output the performance change. This can be done with [`benchstat` ](https://pkg.go.dev/golang.org/x/perf/cmd/benchstat)
Partially resolve #4622 
| Functional Area …
=> test((benchmark): add Golang benchmark test cases

.github/workflows/require-labels.yml
Currently there is no enforcement of adding `size/*` or `kind/*` labels
to issues. This will help the project and collaborators understand the
type of issue, as well as a rough estimate of how long it is projected
to take to resolve.
This PR adds the workflow to mark issues with `size/needed` in the
absence of `size/*` labels, and `kind/needed` in the absence of `kind/*`
labels. This will only consider issues that are part of a milestone.
1. Does this change contain code from or inspired by another project? Yes, this change uses a custom GitHub action, …
=> Add GitHub Action to require size and kind labels

charts/osm/templates/osm-bootstrap-deployment.yaml, charts/osm/templates/osm-deployment.yaml, charts/osm/templates/osm-injector-deployment.yaml, cmd/osm-bootstrap/osm-bootstrap.go, cmd/osm-controller/osm-controller.go, cmd/osm-injector/osm-injector.go, pkg/certificate/fake_manager.go, pkg/certificate/manager.go, pkg/certificate/manager_test.go, pkg/certificate/providers/config.go, pkg/certificate/providers/config_test.go
Since we're not releasing full MRC support in v1.2, this PR allows users to set a custom trust domain by plumbing it through the helm chart as a command line flag to the 3 binaries (controller, bootstrap, and injector).
Add test to make sure trust domain is set on the issuers
| Certificate Management     | [X] |
-   Did you notify the maintainers and provide attribution? no …
=> Plumb trust domain through to helm chart

Makefile, demo/deploy-bookbuyer.sh, demo/deploy-bookstore-with-same-sa.sh, demo/deploy-bookstore.sh, demo/deploy-bookthief.sh, demo/deploy-bookwarehouse.sh, demo/deploy-tcp-client.sh, demo/deploy-tcp-echo-service.sh, demo/deploy-vault.sh
Signed-off-by: Whitney Griffith whitney.griffith16@gmail.com
**Description**: The demo has been explicitly set to run on nodes with Linux OS and and AMD64 Architecture. These changes unblock running the demo on clusters with exclusively linux/arm64 nodes. The node selectors were removed for the demo apps and [node affinity](ttps://kubernetes.io/docs/concepts/configuration/assign-pod-node/) added where necessary. 
**Testing done**: The demo was run locally with these changes. 
| Demo                       |  [x] |
No
No
=> update demo to allow multi-arch/multi-os 

cmd/cli/uninstall_mesh.go, cmd/cli/uninstall_mesh_test.go
Separate code into functions to reduce the cyclomatic complexity
Helps unblock #4555
Reduces cyclomatic complexity 30->19
| CLI Tool                   | [x ] |
| Other                      | [ ] |
=> chore(cmd/cli): Reduce cyclomatic complexity of uninstall command

demo/deploy-bookstore.sh, demo/tail-bookstore-envoy.sh, demo/tail-bookstore.sh, docs/release_notes.md, scripts/port-forward-bookstore-ui-v1.sh, scripts/port-forward-bookstore-ui-v2.sh, scripts/port-forward-bookstore-ui.sh, scripts/port-forward-bookstore.sh
Updates the scripts to be in sync with the manifests
used in the manual demo documented on the website and
to be compatible with changes made to the bookstore app
labels in 5f54056b.
Also fixes #4906 and updates the release notes for
v1.2.
Ran the demo and scripts
| Demo                       | [X] | …
=> demo/scripts: fix bookstore app label and container name

demo/deploy-bookstore.sh, demo/tail-bookstore-envoy.sh, demo/tail-bookstore.sh, scripts/port-forward-bookstore-ui-v1.sh, scripts/port-forward-bookstore-ui-v2.sh, scripts/port-forward-bookstore-ui.sh, scripts/port-forward-bookstore.sh
Backports e94c48b5 to release-v1.2
---
Updates the scripts to be in sync with the manifests
used in the manual demo documented on the website and
to be compatible with changes made to the bookstore app
labels in 5f54056b.
Also fixes #4906 and updates the release notes for
v1.2.
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? `yes`
=> [backport] demo/scripts: fix bookstore app label and container name (#4910)

cmd/osm-bootstrap/osm-bootstrap_test.go, pkg/catalog/fake/fake.go, pkg/certificate/providers/config.go, pkg/tests/fixtures.go, tests/framework/common.go
Remove unnecessary var types during instantiation to fix lints
=> Fix lints by removing superfluous var type from var instantiation

docs/release_notes.md
Backports #4916
Adds suggestion from #4865 and removes root certificate
rotation.
- CI
=> [backport] fix: update v1.2 release notes (#4916)

cmd/osm-bootstrap/crds/policy_upstream_traffic_setting.yaml
Adds the global rate limiting schema to the existing
rate limiting spec for per VirtualHost and Route
level rate limiting. The schema is based on the
Go types for [UpstreamTrafficSetting](https://github.com/openservicemesh/osm/blob/main/pkg/apis/policy/v1alpha1/upstreamtrafficsetting.go).
Part of #2018
Applied sample configs such as:
```
kind: UpstreamTrafficSetting
metadata:
name: http-rate-limit
namespace: demo
spec:
host: test.demo.svc.cluster.local
rateLimit:
global:
http:
rateLimitService:
host: rls.default.svc.cluster.local
port: 80
domain: osm
failOpen: true
timeout: 20ms
enableXRateLimitHeaders: true
descriptors:
- entries:
- remoteAddress: {}
- entries:
- genericKey:
key: foo
value: bar
- …
```
=> rate-limiting: add global rate limiting schema

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml
Is this a release candidate? No
=> chore(release): cut v1.2.0

scripts/port-forward-bookstore-ui.sh
When going through the walk through at I wasn't able to view the `bookstore-ui` application.  The doc at https://release-v1-2.docs.openservicemesh.io/docs/getting_started/install_apps/#view-the-application-uis shows to do:
```
cp .env.example .env
bash <<EOF
./scripts/port-forward-bookbuyer-ui.sh &
./scripts/port-forward-bookstore-ui.sh &
./scripts/port-forward-bookthief-ui.sh &
wait
EOF
```
but I get the following (nothing fails have to run it manually)  so the UI isn't visible.  
```
❯ ./scripts/port-forward-bookstore-ui.sh
Usage: ./scripts/port-forward-bookstore-ui.sh <selector>
```
this just sets a default.  I thought about  changing the docs but it was mentioned in multiple ways and this seemed easier.
**Testing …
=> The docs walkthrough wants a default when starting port forwarding the UI

charts/osm/templates/cleanup-hook.yaml, docs/api_reference/README.md, docs/release_guide.md
This change updates links to `/content/docs/` on the docs site to
`/content/en/docs/`.
- Manually checked links
| …
=> fix(*): update broken docs links

cmd/cli/uninstall_mesh.go, cmd/cli/uninstall_mesh_test.go
osm uninstall was not removing meshRootCertificate CRD when -a flag was used, fixes letter casing
and adds meshRootCertificate to TestUninstallClusterWideResources()
Resolves #4943 
Previously: 
Fixed:
| CLI Tool                   | [ x] | …
=> bug(cmd/cli): Fixes letter casing for meshRootCertificate CRD

pkg/catalog/inbound_traffic_policies.go, pkg/catalog/inbound_traffic_policies_test.go, pkg/constants/constants.go, pkg/envoy/cds/cluster.go, pkg/envoy/cds/cluster_test.go, pkg/envoy/cds/response_test.go, pkg/envoy/lds/inmesh.go, pkg/envoy/lds/inmesh_test.go, pkg/envoy/types.go, pkg/service/types.go, pkg/trafficpolicy/types.go
Adds the capability to enable global L4 rate limiting
for traffic to upstream services. The rate limiting
config is applied via the L4 network global rate
limit filter on the upstream listener.
Part of #2018
Tested rate limiting using an external rate limit service.  …
=> rate-limiting: add global L4 rate limiting capability

pkg/certificate/manager_test.go
Separate the goroutines, 1 per cert so we don't get a deadlock due to the non-deterministic order of iterating maps in go, within the cm.checkAndRotate() call.
This is due to the internals of pubsub requiring that new ops have cleared channels
=> remove deadlock from cert manager test

cmd/cli/env.go, cmd/cli/install.go, cmd/osm-bootstrap/osm-bootstrap.go, pkg/catalog/inbound_traffic_policies.go, pkg/catalog/outbound_traffic_policies.go, pkg/cli/environment.go, pkg/crdconversion/crdconversion.go, pkg/crdconversion/crdconversion_test.go, pkg/envoy/rds/route/route_config.go, pkg/tests/stream.go, pkg/trafficpolicy/trafficpolicy.go, tests/framework/common_apps.go, tests/framework/types.go
The PRs started to fail when CI `golangci-lint` was bumped to 1.48.0: https://github.com/golangci/golangci-lint/releases
This fixes the linter issues and also cleans up an unused parameter 
| CI System                  | [x] | …
=> Fix linter issues and clean up unused param

charts/osm/README.md, charts/osm/templates/preset-mesh-config.yaml, charts/osm/values.schema.json, charts/osm/values.yaml, cmd/osm-bootstrap/crds/config_meshconfig.yaml, cmd/osm-bootstrap/osm-bootstrap_test.go, pkg/apis/config/v1alpha2/mesh_config.go, pkg/catalog/egress.go, pkg/catalog/egress_test.go, pkg/envoy/ads/response_benchmark_test.go, pkg/messaging/broker_test.go
After 87fd049d, EgressPolicy API is implicitly
enabled when global mesh-wide egress is disabled
by setting `traffic.enableEgress=false` in MeshConfig.
This change updates the remaining changes pertaining
to the now deprecated EgressPolicy feature flag.
CI
| Egress                     | [X] |
2. Is this a breaking change? `yes, release noted for v1.3` …
=> egress: deprecate EgressPolicy feature flag

pkg/envoy/eds/builder.go, pkg/envoy/eds/response.go
Apply builder pattern on EDS resource generation. 
The purpose of the refactoring is to decouple the external resource fetching, core business logic and intermediate result generation.
Resolves issue #4923 
No feature changes.  …
=> ref: use builder pattern in EDS resources generation

pkg/certificate/manager.go, pkg/debugger/certificate.go
Presumed fix for https://github.com/openservicemesh/osm/issues/5000. More details in the comment https://github.com/openservicemesh/osm/issues/5000#issuecomment-1218539412
(even if this is not the issue, this would still be the correct way to check the x509 expiration)
=> cert rotation now ignores monotonic clock readings when checking expiration

cmd/cli/proxy.go, cmd/cli/proxy_set.go, pkg/cli/proxy_get.go, pkg/cli/verifier/envoy_config_parser.go
Extends the `osm proxy` cmd by making it
able to execute `set`(POST) requests as well.
With this change, similar to `osm proxy get`,
`osm proxy set` allows updating the proxy
configuration via the Envoy admin interface.
This is extremely useful for troubleshooting,
when we may want to reset stats counters and
logging levels.
```
$ osm proxy get stats "$fortio_server" -n demo | grep over_limit
cluster.demo/fortio|8080|local.ratelimit.over_limit: 0
$ osm proxy set reset_counters fortio-c4bd7857f-8kxq5 -n demo
OK
```
1. Does this change contain code from or inspired by another …
=> cli: extend proxy cmd to set proxy config

pkg/envoy/sds/response.go, pkg/envoy/sds/response_test.go
Replaces `match_subject_alt_names` with `match_typed_subject_alt_names`.  
The match_subject_alt_names is depreciated in favor of `match_typed_subject_alt_names`: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto.html#envoy-v3-api-field-extensions-transport-sockets-tls-v3-certificatevalidationcontext-match-typed-subject-alt-names
This enables using URI SAN for SPIFFE ID eventually (https://github.com/openservicemesh/osm/issues/4750)
manual, unit
| …
=> Replace depreciated MatchSubjectAltNames with MatchTypedSubjectAltNames

CONTRIBUTOR_LADDER.md
Signed-off-by: Wen Lin <linwen1991@gmail.com>
**Description**: Add links for Github, Slack and Zoom meetings in CONTRIBUTOR_LADDER to help new community members get information easier and quicker. 
**Testing done**: Testing by manually clicking the links.
| Documentation              | [X ] |
| …
=> docs(CONTRIBUTOR_LADDER): add links for Github Slack and meetings

pkg/envoy/ads/cache_callbacks.go, pkg/envoy/ads/cache_stream.go, pkg/envoy/ads/jobs.go, pkg/envoy/ads/server.go, pkg/workerpool/workerpool.go, pkg/workerpool/workerpool_test.go
This completes the ADS snapshot cache implementation, but does not flip the flag to enable it. This is accomplished by:
1. Switch the AddJob method to return a writable channel, so that it can be closed. This removes a channel resource leak.
2. Move the WatchUpdate logic into the OnStreamOpen, so that there is one routine running per connected proxy. This maintains current status quo, and makes it simpler to implement with the current message broker setup.
3. Add in the missing metrics tracking
Part of #2683
=> Complete ADS snapshot cache implementation

cmd/osm-bootstrap/crds/policy_upstream_traffic_setting.yaml, pkg/apis/policy/v1alpha1/upstreamtrafficsetting.go, pkg/envoy/lds/inmesh.go, tests/e2e/e2e_global_ratelimit_test.go, tests/e2e/e2e_local_ratelimit_test.go, tests/framework/common_metrics.go, tests/framework/common_traffic.go
- Fixes a bug in the CRD schema where an optional
field was marked as required
- Adds an e2e test to test the behavior of all the
different descriptor entries that can be used for
rate limiting HTTP traffic
- Adds generic utility functions to retrieve and
reset metric counters for a sidecar
- Moves global rate limit filter right after the external
authz filter to be consistent with having filters that
deny traffic before filters that act on allowed traffic
- Updates e2e framework to allow setting HTTP headers
Part of #5032
e2e test
| Rate limiting          | [X] |
1. Does this …
=> rate-limit/global: add e2e test and fix a bug in CRD

scripts/multicluster/crd/multicluster.x-k8s.io_serviceexports.yaml, scripts/multicluster/crd/multicluster.x-k8s.io_serviceimports.yaml, scripts/multicluster/rbac/role.yaml, scripts/multicluster/setup.sh, scripts/multicluster/uninstall.sh
Add a script to set up a demo multicluster environment for OSM development.
It deploys the sample bookstore application on cluster c1 and c2. C2 exports its bookstore service via `ServiceExport` and c1 imports it via `ServiceImport`. A new `EndpointSlice` resource on c1 is created to store accessible endpoint from c2.
The steps listed in the script are:
1. Setup CRDs
2. Deploy applications
3. Create `ServiceExport` in c2
4. Create `ServiceImport` in c1. It will have a ClusterSetIP
5. Expose bookstore on c2 and get service public IP
6. On c1, create `EndpointSlice` containing the remote service IP 
7. (optional) update coreDNS entries of domain `bookstore.bookstore.svc.clusterset.local`
Partially resolves #4974 
Script is tested by executing with 2 …
=> demo: script to set up vanilla multicluster env

pkg/cli/verifier/envoy_config.go
Right now the CLI fails on the demo, because it  can't verify the mysql pod which uses tcp server first
=> add more protocols to CLI

.github/workflows/release-chart.yml
Steps:
1. Manually release helm chart v1.2.0 
2. Revert this PR
3. Re-release v1.2.1
=> temporarily switch to a manual workflow for helm chart

pkg/cli/verifier/testdata/curl_egress.json, pkg/cli/verifier/testdata/curl_permissive.json, pkg/cli/verifier/testdata/httpbin1_permissive.json, pkg/cli/verifier/testdata/httpbin2_permissive.json, pkg/cli/verifier/testdata/sample-envoy-config-dump-bookbuyer.json, pkg/cli/verifier/testdata/sample-envoy-config-dump-bookstore.json, pkg/envoy/bootstrap/config_test.go, pkg/envoy/types.go
This is purely to make this PR smaller https://github.com/openservicemesh/osm/pull/5056. Once this is in, I can rebase into the other to reduce the diff size and make review a bit easier
Necessary because of https://github.com/envoyproxy/go-control-plane/pull/589
=> switch back to wellknown http_connection_manager name

.github/workflows/release-chart.yml
Revert prior commit that enabled manually pushing helm chart instead of pushing automatically based on tag.
=> Revert "temporarily switch to a manual workflow for helm chart (#5076)"

charts/osm/Chart.yaml, charts/osm/README.md, charts/osm/values.yaml, docs/release_notes.md
=> bump Chart.yaml to v1.1.2

cmd/osm-controller/osm-controller.go, pkg/envoy/ads/grpc.go, pkg/envoy/ads/server.go, pkg/webhook/server.go
This PR:
-  removes the pre-provisioning of the ADS cert that is provisioned.  When it was pre-provisioned it ended up with the `ads.cluster.local` trust domain appended.  When rotating it would end up using this even though it was requested that the provisioned cert already included the `FullCNProvided` which would have given a cert with CN `ads`.  It was an implementation detail that the cert that was pre-provisioned ended up being re-used because our cache mechanism looks up the certs by "prefix" which was `ads`.
- ~Sets up all the internal certificates to have the trust domain as part of the CN.  Prior ADS ended up with trust domain (due to issue explained above) but webhooks didn't. I've chosen to include the …
=> Remove pre-povisioned ADS certificate 

Tiltfile
After moving the CRDs install and dropping the bootstrap init container tilt broke. This fixes that by copy the files to the tilt image. …
=> Fix crds for tilt after CRDS moved in #5065

pkg/debugger/proxy.go
Fixes incorrect nil check logic on proxy, preventing access to the envoy config dump via the debug server.
Resolves #5102 
- verified access to config dump via debug server by running demo with debug server enabled and port forwarding the server …
=> fix(debug): update nil check for proxy

charts/osm/README.md, charts/osm/values.schema.json, charts/osm/values.yaml
**Description**: Update envoy version to v1.23.1. To make this compatible with contour, we will also need to bump contour to v1.22.1 
Checked the release notes of envoy v1.23.1, nothing here seems to impact OSM. https://www.envoyproxy.io/docs/envoy/v1.23.1/version_history/v1.23/v1.23.1
Contour v1.22.1 changelog also does not impact OSM: https://github.com/projectcontour/contour/releases/v1.22.1
**Testing done**: Tested OSM installation and sidecar injection on ARM64 machine and ran through contour ingress demo successfully. 
| Certificate …
=> Update envoy version to v1.23, and contour to v1.22

cmd/cli/namespace_test.go
Corrected namespace spec for enabling metrics from label to annotation of yaml. fixes https://github.com/openservicemesh/osm/issues/5096
**Testing done**: yes, unit testing and e2e testing
| …
=> tests: Corrected namespace spec

pkg/certificate/fake_manager.go, pkg/certificate/manager.go, pkg/certificate/manager_test.go, pkg/certificate/options.go, pkg/certificate/options_test.go, pkg/certificate/providers/certmanager/certificate_manager.go, pkg/certificate/providers/config.go, pkg/certificate/providers/tresor/certificate_manager.go, pkg/certificate/providers/tresor/certificate_manager_benchmark_test.go, pkg/certificate/providers/tresor/certificate_manager_test.go, pkg/certificate/providers/vault/certificate_manager.go, pkg/certificate/providers/vault/certificate_manager_test.go, pkg/certificate/types.go, pkg/debugger/certificate_test.go, pkg/envoy/ads/grpc.go, pkg/envoy/ads/response_benchmark_test.go, pkg/envoy/sds/response.go, pkg/ingress/gateway.go, pkg/injector/patch.go, pkg/utils/mtls_test.go, pkg/webhook/server.go, pkg/webhook/server_test.go
This refactors the IssueCertificate API to use the Options pattern throughout the code base. This does a few things:
- make it possible to add additional information in the Providers IssueCertificate. For instance, we re-use the information to generate a SpiffeID, where as prior we needed guess the trust domain and deconstruct the CN to figure it out
- Simplifies the calls to the Managers IssueCertificate API.  
- In the case of `prefix` it was sometimes the prefix, sometimes not. In all cases it was the cache key and we can hide that detial further.
- The `certtype` is internal to manager and will be removed in future when the information is stored on the MRC so this is a step in that direction by only using it in cert package and unexporting it.
fixes: #5095, …
=> Update IssueCertificate Provider Interface to be more easily extended

cmd/osm-controller/osm-controller.go, cmd/osm-injector/osm-injector.go, pkg/catalog/mock_catalog_generated.go, pkg/compute/kube/client_test.go, pkg/compute/mock_compute_client_generated.go, pkg/envoy/ads/response_benchmark_test.go, pkg/injector/webhook_benchmark_test.go, pkg/k8s/client.go, pkg/k8s/client_test.go, pkg/k8s/mock_controller_generated.go, pkg/k8s/types.go, pkg/smi/client_test.go, pkg/validator/server_benchmark_test.go, pkg/validator/server_test.go, pkg/validator/validators_test.go
Adds the configClient to the k8s client definition and adds methods to support getting, updating, and listing the MRC resource. These methods will be used to update the MRC during root certificate rotation.
Part of #5046 
- CI
| Other                      | [x] |
=> feat(certs): add MRC methods to k8s client

pkg/injector/bootstrap_test.go, pkg/injector/envoy_container.go, pkg/injector/patch.go
Resolved missing namespace component of ClusterID
Part of #5048
Signed-off-by: Whitney Griffith <whitney.griffith16@gmail.com>
[Envoy Sidecar Container Spec](https://github.com/openservicemesh/osm/blob/main/pkg/injector/envoy_container.go#L43) sets the [--service-cluster](https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-service-cluster) parameter based on ServiceAccount and pod.Namespace. Namespace component is always missing, even in [example tracing documentation](https://release-v1-2.docs.openservicemesh.io/docs/guides/observability/tracing/).
**Additional Work**:
| …
=> fix(): Missing name in tracing

charts/osm/templates/preset-mesh-config.yaml
With the introduction of Custom Trust domains the helm chart should use the trust domain when creating contour SAN configuration.
after the this patch:
```
❯ helm template osm charts/osm --set osm.trustDomain=something.com --set contour.enabled=true | grep something.com
"subjectAltNames": ["osm-contour-envoy.osm-system.something.com"],
"--trust-domain", "something.com",
"--trust-domain", "something.com",
"--trust-domain", "something.com",
```
before:
```
❯ helm template osm charts/osm --set osm.trustDomain=something.com --set contour.enabled=true | grep subjectAltNames
"subjectAltNames": ["osm-contour-envoy.osm-system.cluster.local"],
```
| …
=> Use custom trust domain with contour in helm chart

pkg/envoy/bootstrap/config.go, pkg/envoy/bootstrap/config_test.go, pkg/envoy/bootstrap/envoy_config_benchmark_test.go, pkg/envoy/bootstrap/envoy_config_health_probes.go, pkg/envoy/bootstrap/envoy_config_health_probes_test.go, pkg/envoy/bootstrap/types.go, pkg/injector/bootstrap.go, pkg/injector/bootstrap_test.go, pkg/injector/envoy_container.go, pkg/injector/health_probes.go, pkg/injector/health_probes_test.go, pkg/injector/patch.go, pkg/injector/test_fixtures/expected_envoy_bootstrap_config.yaml, pkg/models/healthprobe.go, tests/e2e/e2e_health_probe_test.go, tests/envoy_xds_expectations/expected_output_getLivenessCluster.yaml, tests/envoy_xds_expectations/expected_output_getLivenessListener.yaml, tests/envoy_xds_expectations/expected_output_getLivenessListenerNonHTTP.yaml, tests/envoy_xds_expectations/expected_output_getReadinessCluster.yaml, tests/envoy_xds_expectations/expected_output_getReadinessListener.yaml, tests/envoy_xds_expectations/expected_output_getStartupCluster.yaml, tests/envoy_xds_expectations/expected_output_getStartupListener.yaml, tests/envoy_xds_expectations/expected_output_getVirtualHostsMultiple.yaml
Create an Envoy cluster per (container, health probe) tuple and inject the container name into the path prefix so that OSM supports health probes from multiple containers
Fixes #4948
Instead of having a single Envoy cluster for each type of probe (liveness, startup, readiness), we now create an Envoy cluster per container probe. The probe rewrite results in the following containerSpec:
```yaml
- name: nginx
image: nginx:1.19-alpine
livenessProbe:
httpGet:
path: /osm-liveness-probe/nginx
port: 15901
scheme: HTTP
- name: httpbin
image: kennethreitz/httpbin
livenessProbe:
httpGet:
path: /osm-liveness-probe/httpbin
port: 15901
scheme: HTTP
```
The generated Envoy config looks like this:
```json
{
"clusters":[
{
"name":"httpbin_liveness_cluster",
"type":"STATIC", …
```
=> feat(healthprobes): Allow multiple containers to use health probes

tests/e2e/e2e_certmanager_test.go, tests/e2e/e2e_hashivault_test.go, tests/e2e/e2e_metrics_test.go, tests/e2e/e2e_osm_reinstall_test.go, tests/e2e/e2e_permissive_smi_switching_test.go, tests/e2e/e2e_retry_policy_test.go, tests/e2e/e2e_upgrade_test.go, tests/framework/common.go, tests/framework/common_metrics.go, tests/framework/namespace.go
This is a small PR to refactor tests to:
-  add helper function for running OSM cli which centralizes the call and makes it easier to discover when writing tests.
- move the tests to a function which enables retesting similar functionality (see #5131 for example)
This separate PR to make it easier to review and make #5131 smaller diff. …
=> Move e2e tests to separate function and add OSM CLI helper function

cmd/cli/version_latest.go, cmd/cli/version_latest_test.go
Signed-off-by: Wen Lin <linwen1991@gmail.com>
Fix `osm version` command to make it compatible with local compiled version. Fixing is for [this issue](https://github.com/openservicemesh/osm/issues/5007#issuecomment-1242172429). The issue occurs while compare the `dev` version with latest available version. However, the regex only parses numbered version. When we try to parse `dev` version, we will see error: `Failed to output latest release information: could not parse `dev` as version` . The fix here disabled the comparison of `dev` and latest available version. 
- Test by running the commands `./bin/osm version` and `osm version` locally. 
- Manually deployed the fixed version to an Azure K8s Service cluster and run the commands `./bin/osm version` and …
=> fix(cmd/cli/version.go): fix 'osm version' command to make it compatible with local compiled version

cmd/osm-bootstrap/crds/config_mesh_root_certificate.yaml, pkg/apis/config/v1alpha2/meshrootcertificate.go, pkg/certificate/providers/config.go, pkg/certificate/providers/config_test.go, pkg/k8s/client_test.go, pkg/validator/patch.go, pkg/validator/patch_test.go, pkg/validator/server.go, pkg/validator/server_benchmark_test.go, pkg/validator/server_test.go, pkg/validator/validators.go, pkg/validator/validators_test.go
- adds BASIC validation of the MRC on add and update to the validating webhook
- on add, checks for valid trust domain
- on update, verifies trust domain and provider were not updated
- moves `Intent` field to MRC spec
- adds enum on the `Intent` field to limit possible values to `active` and `passive`
Part of #4723 
| Install …
=> feat(certs): add basic MRC validation

.github/auto_assign.yml, .github/workflows/auto-assign.yml, docs/design_docs/README.md, docs/design_docs/index.md
Add new process for reviewing design docs. Here are the high level changes:
- Design docs are now submitted and tracked as PRs
- Design doc reviewers are automatically assigned: 2 maintainers and 2 contributors
- Auto-assigned reviewers should aim for a turnaround time for ~1 week max on reviews (same as code PRs)
=> Create new design doc submission process

pkg/certificate/README.md
Signed-off-by: Wen Lin <linwen1991@gmail.com>
Link to the [Certificate Management](https://github.com/openservicemesh/osm/blob/main/docs/certificate_management.md) is broken. Fixed by using the correct link.
Test manually in local. 
| Documentation              | [ X] |
| Observability              | …
=> docs(pkg/certificate/README.md): fix broken document link

tests/framework/common.go
**Description**: Skip e2e spiff test for NoInstall. This should unblock the NoInstall nightly job. 
| Security …
=> Skip e2e_spiff_test for NoInstall

pkg/certificate/certificate.go, pkg/certificate/manager.go, pkg/certificate/manager_test.go, pkg/injector/bootstrap_test.go, pkg/utils/mesh_config.go
change renewBefore to use a third of the certificate's validity duration plus some noise
and resolves #5150 
| Certificate Management     | [x ] |
=> Changes renewBefore to use cert validity duration

charts/osm/templates/osm-rbac.yaml, cmd/osm-bootstrap/crds/config_extensionservice.yaml, cmd/osm-bootstrap/crds/policy_telemetry.yaml, pkg/apis/policy/v1alpha1/telemetry.go, pkg/catalog/mock_catalog_generated.go, pkg/compute/mock_compute_client_generated.go, pkg/k8s/client.go, pkg/k8s/client_test.go, pkg/k8s/informers/informers.go, pkg/k8s/informers/types.go, pkg/k8s/mock_controller_generated.go, pkg/k8s/types.go
- Adds CRD for Telemetry and ExtensionService APIs
- Adds informer clients
- Adds an API to lookup the Telemetry config for a proxy
- Minor changes to the API definition
Part of #5136
Unit tests, e2e suite
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? `not yet`
=> apis: add CRD + informer for Telemetry & ExtensionService

cmd/osm-injector/osm-injector.go, pkg/compute/kube/client_test.go, pkg/k8s/client.go, pkg/k8s/client_test.go, pkg/k8s/informers/informers.go, pkg/k8s/informers/types.go, pkg/k8s/types.go, pkg/reconciler/client.go, pkg/reconciler/types.go
**Description**: Removes duplicate definition of InformerKey names. Fixes #5152 
| Security                   | [ …
=> ref(informers): Remove duplicate InformerKey definitions

pkg/envoy/bootstrap/config.go
**Description**: Defines a 60s keep-alive time after which probes will start being sent to check if a sidecar is still connected to the control plane. Previously this defaulted to 2 hours
Resolves #5149
-   Did you notify the maintainers and provide attribution? no
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? n/a
=> fix(envoy): add keep-alive time to detect sidecar disconnections

.github/workflows/main.yml, demo/deploy-vault.sh, tests/e2e/e2e_certmanager_test.go, tests/e2e/e2e_hashivault_test.go, tests/e2e/e2e_meshrootcertificate_test.go, tests/framework/common.go, tests/framework/constants.go, tests/framework/types.go
Add the start of basic tests for MRC rotation:
- runs some basic tests with MRC turned on
- Starts testing the Rotation of Certificates for Tressor, CertManager, and Vault
~- Fixes a bug in the validator selection logic (see https://github.com/kubernetes/kubernetes/issues/92157#issuecomment-825160958)~ (fixed in https://github.com/openservicemesh/osm/pull/5191)
- upgrades vault version to 1.11 which has new Root Cert Rotation APIs (https://learn.hashicorp.com/tutorials/vault/pki-engine#step-7-rotate-root-ca)
e2e
| CLI Tool …
=> Add the start of basic tests for MRC rotation

pkg/certificate/manager.go, pkg/debugger/certificate.go
Remove debugging related to #5000
=> certificate/manager: remove redundant debug info

pkg/k8s/events/types.go
Secret events were ignored, leading
to error logs when Secret events
are received. This allows the
controller to correctly process the event.
Without this change, the follow error logs are observed:
```
{"level":"error","component":"kube-events","time":"2022-10-12T18:36:13Z","file":"types.go:196","message":"Unknown kind: &Secret{ObjectMeta:{envoy-bootstrap-config-e18ceb59-6184-4215-9097-1e32ce86bfc6  httpbin  11b77a82-9cad-40e3-9903-c5b25e01f0f6 49248 0 2022-10-12 18:36:13 +0000 UTC <nil> <nil> map[app.kubernetes.io/instance:osm app.kubernetes.io/name:openservicemesh.io app.kubernetes.io/version:dev] map[] [] []  [{osm-injector Update v1 2022-10-12 18:36:13 +0000 UTC FieldsV1 {\"f:data\":{\".\":{},\"f:bootstrap.yaml\":{},\"f:cacert.pem\":{},\"f:sds_cert.p …
```
=> k8s/events: detect Secret kind

pkg/envoy/generator/cds.go, pkg/envoy/generator/cds/builder.go, pkg/envoy/generator/cds/builder_test.go, pkg/envoy/generator/cds_test.go
This change allows exporting Envoy access logs to an OpenTelemetry collector using the OpenTelemetry
access log config.
The access log config has already been implemented. This change creates the cluster configuration for
the OpenTelemetry collector's ExtensionService.
Resolves #4999
Part of #5136
Tested access logs being exported to an OpenTelemety collector using
config such as:
```
kind: Telemetry
metadata:
name: httpbin-log
namespace: httpbin
spec:
selector:
app: httpbin
accessLog:
format: '{"authority":"%REQ(:AUTHORITY)%","bytes_received":"%BYTES_RECEIVED%","bytes_sent":"%BYTES_SENT%"}'
#format: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% …
```
=> telemetry: allow exporting access log to OTEL collector

pkg/compute/kube/client.go, pkg/compute/kube/client_test.go
This change updates the app protocol detection for a service port to eliminate a misleading error scenario that results from using the same port for multiple protocols.
It does the following:
1. Only uses http implicitly for TCP based ports that do not have appProtocol or a valid protocol prefix in the port name.
2. Adds a warn log when implicitly using http as the app protocol for TCP based ports.
The result is that duplicate filter chain matches
are eliminated with the same port is used for different protocols, eg. port 8080 being used for TCP and UDP.
Resolves #5223
Unit tests …
=> k8s: update app protocol detection for k8s service port

pkg/catalog/mock_catalog_generated.go, pkg/certificate/manager.go, pkg/certificate/mrc_reconciler.go, pkg/certificate/providers/mrc.go, pkg/compute/mock_compute_client_generated.go, pkg/k8s/client.go, pkg/k8s/informers.go, pkg/k8s/mock_controller_generated.go, pkg/k8s/types.go
This reverts commit 6fc993bec81dc172f0c34763882f19780e8a4744.
Reverts: https://github.com/openservicemesh/osm/pull/5195 based on https://github.com/openservicemesh/osm/pull/5195#discussion_r999775665 
This change ends up resulting in the log message `the specified resyncPeriod 2m30s is invalid because this shared informer doesn't support resyncing.`
I tested it out and the base informer needs to have a resync enabled (aka a value > 1s) otherwise it resync is disabled. https://github.com/kubernetes/client-go/blob/c81636cd4415f0858a99c2cc18023740df7aa15f/tools/cache/shared_informer.go#L516-L524
We've been running without resyncs in https://github.com/openservicemesh/osm/pull/5201 without resync and this was initially needed for time based changes, which is a different …
=> Revert "feat(cerst): Adds MRCResyncInterval (#5195)"

charts/osm/README.md, charts/osm/values.yaml
This pins the jaeger deployment to the latest version. We do this we all the other tools we include in the helm chart and this ensures we know what version of jaeger we are supporting.
| Other                      | [x] |
no
no
no
=> Pins the JaegerTracing image to latest version

README.md, SUPPORT
Signed-off-by: Zach Rhoads <zachary.rhoads@microsoft.com>
**Description**: Provide details on which versions of OSM are supported on which versions of Kubernetes in support file.
**Testing done**: Verified file displays correctly.
| Documentation              | [ x ] |
| Performance …
=> docs: update SUPPORT with OSM and K8s version support

cmd/osm-bootstrap/crds/config_mesh_root_certificate.yaml, cmd/osm-bootstrap/osm-bootstrap.go, cmd/osm-bootstrap/osm-bootstrap_test.go, pkg/apis/config/v1alpha2/meshrootcertificate.go, pkg/catalog/inbound_traffic_policies_test.go, pkg/certificate/errors.go, pkg/certificate/fake_manager.go, pkg/certificate/manager.go, pkg/certificate/manager_test.go, pkg/certificate/mrc_reconciler.go, pkg/certificate/mrc_reconciler_test.go, pkg/certificate/providers/compat.go, pkg/certificate/providers/config.go, pkg/certificate/providers/config_test.go, pkg/certificate/providers/mrc.go, pkg/certificate/providers/tresor/fake/fake.go, pkg/certificate/providers/vault/certificate_manager.go, pkg/certificate/providers/vault/certificate_manager_test.go, pkg/certificate/types.go, pkg/constants/constants.go, pkg/errcode/errcode.go, pkg/k8s/client_test.go, pkg/validator/validators.go, pkg/validator/validators_test.go, pkg/webhook/server.go, pkg/webhook/server_test.go, tests/e2e/e2e_meshrootcertificate_test.go, tests/framework/common.go
The PR includes the changes required to support an MVP of manual root certificate rotation. With these changes, a user will be able to manually create and update the `intent` of the MRCs and rotate the root certificate without downtime. OSM utilizes a level-triggered approach to bring the state of the mesh to match the MRC intent.
There are 3 possible values for intent. Each describes the desired role of the provider and certificate settings specified in the MRC:
- **active**: the certificate provider issues and signs certificates and the ca_bundle for that provider is included in the validation context
- **passive**: the certificate provider is not used to issue or sign certificates and the ca_bundle for the provider is included in the validation context
- **inactive**: …
=> feat(cert): use intent to set issuers during root cert rotation

pkg/envoy/generator/lds/accesslog.go, pkg/envoy/generator/lds/accesslog_test.go
Allows specifying the removal of HTTP query strings from access logs as they may contain sensitive
info. If the %REQ_WITHOUT_QUERY command operator
is specified instead of the regular %REQ operator, then a query string formatter is used such that
the HTTP path without the query string is rendered in the access logs.
Resolves #5241
Tested query string masking using the `%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%` 
for both JSON and text based access log formats.
E.g. for the query `http://httpbin.httpbin:14001/status/200?foo=bar`, the `foo=bar` query string is stripped off when using the `%REQ_WITHOUT_QUERY` instead of the `%REQ` operator. 
TEXT
```
kind: Telemetry
metadata:
name: httpbin-log
namespace: httpbin
spec: …
```
=> envoy/access-logs: allow removing HTTP query string

cmd/osm-bootstrap/osm-bootstrap.go, cmd/osm-bootstrap/osm-bootstrap_test.go
Checks if an active MRC exists before attempting to create the default MRC. Previously, if an active MRC existed that did not have the default MRC name, osm-mesh-root-certificate, the osm-bootstrap would error.
Resolves #5237
- unit tests
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if …
=> fix(certs): check for active MRCs on bootstrap startup

pkg/certificate/mrc_reconciler.go, pkg/validator/validators.go, pkg/validator/validators_test.go, tests/e2e/e2e_meshrootcertificate_test.go
This builds on #5201 and validates creation of the MeshRootCertificates as well as updates to the MeshRootCertificates.  It only allows the valid combinations of Active and Passive certificates.
Fixes #5205
unit/e2e/manual
no
no …
=> feat(certs): MeshRootCertificate validation

Makefile, cmd/cli/alpha.go, cmd/cli/certificate.go, cmd/cli/certificate_rotate.go, cmd/cli/certificate_rotate_test.go, cmd/cli/osm.go, pkg/certificate/providers/config.go, tests/e2e/e2e_meshrootcertificate_test.go, tests/framework/common.go, tests/framework/common_traffic_fortio.go, tests/framework/constants.go
This build on #5201 (required before this) to provide alpha support for rotation in the CLI. This is a proposal for adding a command to ease the burden of managing the MRCs and adds several tests for trust domain and switching between providers.
example usage would be:
```
./bin/osm alpha certificate rotate -d -y
```
Resolves #4835 
| …
=> Support for root certificate rotation via CLI

.github/workflows/openshift-nightly.yml
Increase e2e test timeout as 3h might be insufficient
This is just the first step in debugging. If this timeout is also insufficient, I'll continue debugging
Potentially closes #5242  …
=> ci(openshift): Increase test timeout

pkg/certificate/certificate.go, pkg/certificate/manager.go, pkg/debugger/certificate.go
Move truncation into GetExpiration so GetExpiration correctly returns the time with monotonic clock truncated
=> Move the required truncation of certificate expiration time to the GetExpiration method

.github/workflows/main.yml, tests/e2e/e2e_meshrootcertificate_test.go
Split e2es into more buckets so overall time for test completion is faster.
fixes: #5257
| Security …
=> Split e2es into more buckets

CODEOWNERS, OWNERS
Due to the project guidelines on [inactivity](https://github.com/openservicemesh/osm/blob/main/CONTRIBUTOR_LADDER.md#inactivity), this PR proposes moving @snehachhabria and @draychev to emeritus status. Thank you for your contributions to this project!
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? N/A
=> Move snehachhabria and draychev to emeritus status

CODEOWNERS, OWNERS
@shalier has been contributing to the project at the level that is expected of a maintainer.
**Maintainers**, if you agree with this nomination, leave a "+1" comment and approve the PR (do not merge it).
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? N/A
=> Add @shalier as a codeowner maintainer

CODEOWNERS
The last PR (#5261) added @shalier in the OWNERS file but not the CODEOWNERS file which is why she is not being requested on reviews.
=> Add @shalier as CODEOWNERS

README.md
Replaced SMI GitHub links with OSM doc website links for traffic shifting and traffic management
| …
=> Replaced links to OSM doc

cmd/cli/version.go
Now OSM CLI version check will happen regardless of any K8s cluster
**Description**: Earlier the OSM CLI version check only happened when there is K8s cluster present as below
If no K8s cluster is present below is the output
**Testing done**: Yes Manual testing done below are the screenshots
With K8s cluster
Without K8s cluster
| CLI Tool                   | [ X] |
| Ingress …
=> Appended version check

pkg/cli/verifier/pod.go, pkg/health/health.go, pkg/utils/mtls.go, tests/e2e/e2e_envoy_max_mtls_version_test.go
Backport the following fix for #5282 into release-v1.2
Confirmed demo, health check and verifier worked as expected when OSM control plane has the following configuration:
```
Tls Max Protocol Version:  TLSv1_2 
Tls Min Protocol Version:  TLSv1_2
```
| …
=> fix(): reduce minimum tls version for osm controller, verifier, health

.github/workflows/main.yml, cmd/osm-bootstrap/osm-bootstrap.go, dockerfiles/Dockerfile.init, pkg/reconciler/client.go, tests/e2e/e2e_reconciler_test.go
Change the reoncile label to refer to the version of OSM that is in charge of reconciling the CRDs. This ensures that on upgrade, the new version is the only version managing the CRDs
Fixes the upgrade bug from pre-v1.x.3 patches
E2E tests
| Install                    | [x] |
| Upgrade                    | [x] |
-   Did you notify the maintainers and provide attribution? N/A …
=> Add more robust CRD conversion patching

.github/workflows/main.yml, cmd/osm-bootstrap/crds/config_meshconfig.yaml, dockerfiles/Dockerfile.init, pkg/apis/config/v1alpha2/mesh_config.go, pkg/compute/kube/envoy.go, pkg/constants/tls.go, tests/e2e/e2e_envoy_max_mtls_version_test.go
**Description**: Envoy proxy fails if tlsMaxProtocolVersion is set to TLSv1_2 because the minimum tls version for control plane was set to TLSv1_3
| Security …
=> fix(): reduce minimum tls version for control plane

cmd/osm-bootstrap/crds/config_meshconfig.yaml, dockerfiles/Dockerfile.init, pkg/apis/config/v1alpha2/mesh_config.go, tests/e2e/e2e_envoy_max_mtls_version_test.go
**Description**: Part of #5282. This removes support for TLSv1_0 and TLSv1_1 from the envoy TLSMaxProtocolVersion options. 
| Networking                 | [x] |
| Sidecar …
=> fix(): remove support for incompatible tls versions for envoy TLSMaxProtocolVersion

.mergify.yml, docs/automerge.md
Removes the Automatic rebase mergify rule due to mergify's [deprecation](https://changelog.mergify.com/changelog/rebasing-pull-requests-with-a-random-user-is-deprecated) of using a random org user as the [`bot_account`](https://docs.mergify.com/actions/rebase/#options). Mergify instead uses the author of the PR. The action will fail if the user has not logged into the mergify dashboard. If a github application such a dependabot creates a PR and triggers the rebase mergify action, the action will fail.
Related mergify GH issue: https://github.com/Mergifyio/mergify/issues/5074
Example OSM failure:
-   Did you notify the maintainers and provide …
=> fix: remove Automatic rebase mergify rule

tests/framework/common.go
Removed Go 1.16 functionality of io/ioutil that is deprecated now.
**Testing done**: Yes
| Security …
=> Removed deprecated functionality

go.mod, go.sum
Cherry picks 6b3646a from #5286 onto release-v1.2
=> [backport] build(deps): bump containerd from 1.6.6 to 1.6.18 (#5286)

pkg/certificate/providers/mrc.go, pkg/compute/mock_compute_client_generated.go, pkg/k8s/client.go, pkg/k8s/mock_controller_generated.go, pkg/k8s/types.go, pkg/reconciler/client.go
Fixes lint error introduced in #5283
When upgrading helm to 3.11.1, the k8.io client-go package was also updated to v0.26.3. In v0.26 the API for [`AddEventHandler`](https://pkg.go.dev/k8s.io/client-go@v0.26.3/tools/cache#SharedInformer) was updated to return an error and registration handle to enable individual handler cancelation. 
=> fix(): resolve lint error from unchecked AddEventHandler return values
